### ISSUE TITLE
BUG: Sidebar hides ecoverses

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1004]
**Describe the bug**
Sidebar hides ecoverses

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Authenticate with user and create application to Private Ecoverse (https://acc.alkem.io/private-eco/)
3. Using the URL  navigate to the challenge/apply for that Ecoverse (https://acc.alkem.io/private-eco/challenges/ch-private-eco/apply)
4. Click on home button and scroll down - the list of ecoverses on the sidebar disappears
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/05a52215-8ee6-490f-a4f9-4e4a28aa0980)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8019a692-bc5b-4e57-940d-78f73d71171b)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/be753b21-1285-45c9-ad63-0f2feb946dcb)

**Expected behavior**
User can see all ecoverses on sidabar and main container.

## NOTE
Using only these steps, can hardly reproduce the issue, but have seen it and with some other flows, which cannot concretely define in repro steps.

**Comment by techsmyth** [comment]
In this case there is a single provider that provides the global data for both the sidebar + the home page card?

**Comment by hero101** [comment]
This could be caused by the cache not being merged correctly. I have issued a [potential fix](https://github.com/alkem-io/client-web/pull/1022).

**Comment by Comoque1** [comment]
Wasn't able to reproduce the rendering issue, but refreshing the page, returns response with errors.![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c0c9c048-bef9-479b-b1a9-ee0c63fb291b)

On acceptance, refreshing the page, returns, 2 responses containing this error, which mean, that potential fix, may be addressing the issue partially.

**Comment by Comoque1** [comment]
Great, no more errors in the initial requests!
Closing.
