### ISSUE TITLE
Use global admin / global community admin mutations

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1018]
## Description

As a developer I want a single way of assigning / removing credentials

## Acceptance criteria

- [ ] On the admin interface, update the mutations used to manage "global admin" to be "assignUserAsGlobalAdmin", "removeUserAsGlobalAdmin"
- [ ] On the admin interface, update the mutations used to manage "global community admin" to be "assignUserAsGlobalCommunityAdmin", "removeUserAsGlobalCommunityAdmin"
- [ ] Tidy up client code so that there are no mutations for directly assigning credentials used / called

**Comment by Comoque1** [comment]
Tested OK on Dev Env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/99578852-13ad-47f0-8cb8-8ac330fab78f)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/acf4ee0e-fba5-4853-8b78-9a09639bd3d6)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/10653c7e-37ed-41ce-93a6-e9647bf32fd8)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4cfe4961-b89a-43fb-aac5-b36c9e74c083)
