### ISSUE TITLE
Expand text that "filter" operates on, expand to challenges on ecoverse

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1019]
## Description

As a user I want to be able to quickly find the opportunities / challenges that match key words

## Acceptance criteria

- [ ] Expand the text that is searched from the "filter" box to also include the following fields: displayName, context.tagline, context.background, context.vision, context.who, context.impact
- [ ] Apply the same filter option to challenges within an ecoverse

**Comment by Comoque1** [comment]
Tested on ACC env.

For Opportunity search, all requirements stated in AC are working as expected.

Search by entity.context attributes, doesn't seem to return results, except for "tagline"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1d7c3f25-dff3-44ff-9944-614a9cadc319)

Moving the issue back to Backlog.

**Comment by Comoque1** [comment]
Looks OK now on Test env with dev branch.
 - [x] All Challenge context entities are considered to be part of the search
 - [x] When there is no Challenge/Opportunity - search is not visible

Closing the issue.
