### ISSUE TITLE
Organisation Page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1020]
## Description

As an organisation I want to have a profile page on the platform

## Acceptance criteria

- [x] Each organisation has a page with the following route: /organisation/<org.nameid>
- [x] The page is showing basic information about the organisation, albeit with less fields
- [x] Tags are visible
- [x] The page is showing the Ecoverses that the organisation is a host of, as well as any challenges that they are leading
- [x] The page is showing an overview of the key roles within the organisation: owners, admins, members
- [x] Only registered users are allowed to see org members
- [x] The set of fields shown on the profile page should be updated as per the server card related to expanding the organisation fields
- [x] The page is linked from challenge lead logo on challenges; search results popup to have a link.

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/98d13a04-09b8-4262-a059-6d675b103a57)

**Comment by Comoque1** [comment]
Tested on DEV env:

- [x] Each organisation has a page with the following route: /organisation/<org.nameid> - **NOT OK**
Redirect is against "organiSation" and the page is available on organization/experiment
- [x] The page is showing basic information about the organisation, albeit with less fields - **OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/598aa0ec-e396-460a-9334-bbc8a046dcc0)
- [x] Tags are visible - **OK**
- [x] The page is showing the Ecoverses that the organisation is a host of, as well as any challenges that they are leading - **NOT OK**
Redirect to Challenge is not working
- [x] The page is showing an overview of the key roles within the organisation: owners, admins, members - **OK**
- [x] Only registered users are allowed to see org members - **OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0d6ec977-0246-4771-ab3a-5993b7a691ac)
- [x] The set of fields shown on the profile page should be updated as per the server card related to expanding the organisation fields - **OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b56ef6da-c525-4a5e-ab9b-ef9d958c90dc)
- [x] The page is linked from challenge lead logo on challenges; search results popup to have a link. - **NOT OK**
Redirect link is incorrect

Closing, as there is a separate issue to be addressed the redirects.
