### ISSUE TITLE
Use sentry configutation from the server 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1033]
## Description

As a client developer I want configuration to be centrally managed

## Acceptance criteria

- [ ] Use the sentry configuration from the server
- [ ] Remove the Sentry related environment variables from all client env files

## Additional Context
https://github.com/alkem-io/server/pull/1331

**Comment by Comoque1** [comment]
Looks OK on Acc.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/513a5662-f7b0-42c5-95ec-8aec3394208a)
