### ISSUE TITLE
Migrate TagsInput to Material's `Autocomplete`

### ISSUE THREAD

**Issue by atstojanov** [alkem-io/client-web#1037]
## Description

The `TagsInput` component is using custom made input component part of which is copy pasted from the material's `Autocomplete` component. The `Autocomplete` component support our case out of the box. Migrate the TagsInput to use `Autocomplete`.

## Acceptance criteria

- [ ] The TagsInput component uses `Autocomplete`
- [ ] Adding tag OnBlur is available

**Comment by Comoque1** [comment]
All looks good, except user is able to create a tag with space. It would be great, if we could add additional validation
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8e0f3011-3adf-4ec0-a418-fe5e4e26c081)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/db53f06c-ff33-4d15-b6ee-ccbcdb1e3ce3)

Moving the issue in backlog.

**Comment by techsmyth** [comment]
Re tags content, indeed no empty strings but also a minimum lenght of 2.

**Comment by Comoque1** [comment]
Tested on Dev env.
Looks good now. 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0864c11c-4dc3-4f04-baea-cf55549d0abe)
