### ISSUE TITLE
Limit Sidebar ecoverses to those you are member of

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/client-web#1039]
## Description

Current sidebar is showing every ecoverses on the platform. Soon this will become overwhelming. 
The ideal form will be for the user to be able to choose which ecoverse to be visible or not. As first step ecoverses shown in the sidebar should be only those the user is member of.

Global Administrators can edit and see all the ecoverses, but they can be member of a few of them. Even for global admins the visible sidebar ecoverses should be limited.

## Acceptance criteria

- [ ] The sidebar shows only ecoverses which the user is member of.
- [ ] If user is not logged in ecoverses are not shown in the sidebar.
- [ ] If the user is global admin, only ecoverses that the user is member of are visible. 

## TBD
- What member of includes? Is the EcoverseAdmin member of an ecoverse or it should be explicitly added as member?

**Comment by techsmyth** [comment]
No side bar any more
