### ISSUE TITLE
Refine the ecoverse card: Display the number of opportunities in an ecoverse; do not crop tags

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1049]
## Description

As a user I want to be able to quickly see the level of activity within an ecoverse, and opportunity count is an important indicator

## Acceptance criteria

- [x] Between the challenge + user count lines, add in a third one for opportunity count on the cards for the ecoverses.
- [x] Tags should be displayed without cropping.

**Comment by Comoque1** [comment]
Tested on Dev env.
The `opportunity` is available and is getting updated with correct number.
Vertical cropping of tag still remains in particular browser width. Tooltip on not fully displayed tags should be available.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c422d3be-3cfa-495d-81e2-f929b256dfe7)

Moving back to backlog. If you decide - separate issue could be open regarding the comments and this one closed afterward.

**Comment by techsmyth** [comment]
Nice catch. This one can be closed as there is another one now #1085 that is looking at tooltips on the card fields - so suggest we pick this up there.
