### ISSUE TITLE
BUG: Filtering should not be shown if no challenges / opportunities (or if private)

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1054]
**Describe the bug**
The filter box does not make sense to be shown if there are no opportunities in a challenge, or if no challenges in an ecoverse.
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/5e048d39-ade1-41aa-aa72-2d98f0eb2399)

**Expected behavior**
Do not show the filter box if no challenges are visible (none or private ecoverse), or if no opportunities

**Comment by Comoque1** [comment]
Verified as part of [this issue](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1019)
