### ISSUE TITLE
Admin: allow direct link to relevant admin page from ecoverse / challenge / opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1055]
## Description

As an admin, I would like to be able to directly navigate to the admin page for an ecoverse / challenge / opportunity

## Acceptance criteria
- [x] Edit button on ecoverse / challenge / opportunity banner to link directly to the relevant admin settings page 
- [x] Change the icon from "edit" to "cogwheel", and move to top right
- [x] Cogwheel is shown to any user that has the challenge / ecoverse admin credential (or global admin)
- [x] Add a mechanism to each ecoverse / challenge / opportunity admin page to directly link to the display page (i.e. not the admin page but the actual ecoverse / challenge / opportunity)

**Comment by Comoque1** [comment]
Awesome enhancement.
Tested on Dev env. and looks according to AC.

Closing
