### ISSUE TITLE
BUG: Tags not showing on ecoverses

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1056]
**Describe the bug**
The home page is not showing tags on ecoverses:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c0ddc24f-9bec-49fb-b0a5-104e86e402cb)

Sometimes upon going to another area + then back the tags do show, partially:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c52c97dd-fb77-4369-88d0-166c40557ee4)

**To Reproduce**
Reload home page.

To show partial display: navigate to admin - ecoverses - select Alkemio ecoverse - edit info. Then click on Home. That worked a few times for me. 

Looks like a race condition?

**Expected behavior**
Tags always shown. And ideally without cropping!

**Comment by Comoque1** [comment]
The issue with not displaying tags is not reproducible anymore (on Chromium and FF)
Tags are still vertically cropped and when text is longer, tooltip is missing.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2f5efd55-f3cc-4c94-bc83-4680590132f1)

**Comment by Comoque1** [comment]
The comment to be addressed as part of [this issue](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1049)
