### ISSUE TITLE
BUG: No opacity on challenge banner, links display too small

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1057]
**Describe the bug**
It seems like the opacity filter on banners has been lost, meaning that the links are not visible. 

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4b41953b-65eb-4541-9d5f-abb887a54813)

**Expected behavior**
The links should be much more visible, and not "drowned out" by the background image
Fix alignment of the text / buttons
Ideally also make the banner less high

**Comment by Comoque1** [comment]
Looks much better (Checked on Chromium and FF)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fe1ee387-9e42-4b9b-a13f-9103405c47d6)

When the browser width is decreased `Activity` panel overlaps with Challenge title and links
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e3654a32-bece-40dc-82f2-2147d993db4d)

Could potentially move `activity` panel below title after width is decrease.

**Comment by Comoque1** [comment]
After discussing with @hero101, created a [new bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1064).
