### ISSUE TITLE
Help icon + instructions for key context fields on ecoverse / challenge / opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1065]
## Description

As an admin I want to understand what the fields I am filling in are for

## Acceptance criteria

- [ ] Add a little "info" icon next to the key context fields (background, vision, impact, who) that when hovered over shows some help text
- [ ] Help text ready for internationalisation (i.e. so not hard coded) 
- [ ] Help as simple text for now

## Additional Context

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c5b30c53-9e94-4bae-8228-960219e1353b)

**Comment by Comoque1** [comment]
Tested OK on Test env.
