### ISSUE TITLE
Tooltips on card fields

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1085]
## Description

As a user I want to be easily able to see the information for an ecoverse / challenge / opportunity

## Acceptance criteria

- [ ] There should be tooltips on title, tagline + tags so that hovering over them shows the full set of values
- [ ] Available for ecoverse, challenge + opportunity cards

**Comment by Comoque1** [comment]
Looks OK as per requirements.

Added a separate[bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1162) for tooltip translations
