### ISSUE TITLE
BUG: Invalid cookies blocking client login

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1091]
**Describe the bug**
On occasion the client has a stale cookie that is blocking the login to the server. The only way to work around this is to either login with a private session or to clear out the existing cookies. 

**To Reproduce**
Seems to be related to not being connected for quite a while and/or using the same URL for a different instance of kratos?

**Expected behavior**
Invalid cookies are detected and removed so that the user can always login.

Hypothesis: cookie has not expired, but it is not valid according to kratos

## To reproduce
- restart the service with a different secret?
investigate what's going on - timebox to 2 hours
desired behaviour - no hanging, when your cookie is invalid the system treats you as you are not logged in

**Comment by valentinyanakiev** [comment]
https://www.ory.sh/kratos/docs/debug/csrf/
