### ISSUE TITLE
BUG: Admin loading for ecoverse is very slow

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1092]
**Describe the bug**
On switching to the admin page the page takes a long time to load. 

**To Reproduce**
Go to digicampus page. Click on cogwheel - admin page is loading for 8 seconds. 

A quick network analysis shows:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c9d2fc22-68f5-498f-b943-ea41b44e2216)

It seems that this page is twice loading all users (why?), as well as a lot of data about the ecoverse (could this initial load not be much lighter?)

**Expected behavior**
Admin page loads within 1-2 seconds.

**Comment by Comoque1** [comment]
Tested on DEV env.
The performance, when loading "admin" page increased significantly. Almost all requests are passing within a second.
