### ISSUE TITLE
Admin organisation page url to use the nameID, not the UUID

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1096]
## Description

As a user/admin
I want to see the nameID of my organisation which I assigned.
So that I benefit from that field

## Acceptance criteria

- [ ] The URL pattern is admin/organizations/:organisationNameID
- [ ] Rework the dependencies on that structure

## Additional Context
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/3865d364-e543-450c-a4c0-0216d10399e8)

**Comment by Comoque1** [comment]
Tested OK on Dev env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bd5de9dd-dba1-4d2f-a437-a564a5b110f1)
