### ISSUE TITLE
User profile page refresh

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1098]
## Description
As a user I want a clear User profile page, that can be found by others
As a host, I want a place where Users can create new Organizations

## Acceptance criteria
- [x] User profiles to be available at /user/<nameID>, replacing current "/profile" route
- [x] User profile page to be aware when it is the current User
- [x] Profile page to have a bar under the User name with: (a) county (if specified) (b) current role (as is, to be refined more later) (c) verification status for the email (verified / not verified), shown in green / orange respectively
- [x] Edit icon shown at the top right at level of name similar to challenge / ecoverse etc. 
- [ ] Update UI tests
- [ ] Update selectors of the controls to aid the UI tests

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/56e4a34a-bd1f-48da-be38-6b0728d87dc6)

## Additional Context
Full UX design of the User profile page is pending. This is getting the routing / page in place for it. 

RED - error
ORANGE - warning
GREEN - OK

**Comment by Comoque1** [comment]
"Profile" link on [verify success page](https://dev.alkem.io/identity/verify/success) is pointing to `/profile`, instead to the new URL
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/187eb048-5e7a-4374-94f4-d42cebdc4e3f)

**Comment by Comoque1** [comment]
Pressing "submit" button on password reset page, should redirect to user profile. Currently it redirects to the old link.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fa995a01-11a8-4c64-add6-a090fc28b2e0)

**Comment by Comoque1** [comment]
Created separate bugs regarding the comments:
 - [BUG: Clicking on "profile" link from "./verify/success" page, points to old URL](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1131)
 - [BUG: Pressing "submit" button on password reset page, redirects to old profile page](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1132)

The automated tests are addressed as part of this [PR](https://github.com/alkem-io/test-suites/pull/45)
 -
