### ISSUE TITLE
Spike: analysis for redesign v2

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1101]
## Description

As a product owner I want to understand if there are items from the client redesign that should be prioritised near term

## Acceptance criteria

- [ ] Updating of the analysis as done previously, marking 
- [ ] Updating of developer guides / readme
- [ ] Identify key refactorings to be done near term
- [ ] Time boxed to half a day

## Additional Context
https://hackmd.io/PV9XOX5XSRi6JH4wDmfAfw

https://hackmd.io/hx4VSJv-TZOr220bsb6yfQ

**Comment by atstoyanov** [comment]
[Client redesign v2](https://hackmd.io/pLWUfhZTRmW2MEInO7gVig)
