### ISSUE TITLE
BUG: Community UI layout issue

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1111]
**Describe the bug**
Community UI layout issue.

**To Reproduce**

1. Go to https://dev.alkem.io/experiment
2. Scroll down to "Community" area
3. "Discussions" tab is not fully displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/af37ed5e-a9c8-40d1-99dc-02b15eb80d47)

**Expected behavior**
As discussed with @techsmyth - the tab should be removed for the moment.

**Comment by techsmyth** [comment]
This has since been fixed. Closing.
