### ISSUE TITLE
BUG: Home button on the welcome screen does not bring the user to the home page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1121]
**Describe the bug**

**To Reproduce**
Sign up with a new account.

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/8affc550-8d8e-4643-94f6-88b5b10a589e)

Clicking on the button has no effect.

**Comment by Comoque1** [comment]
Tested OK on TEST env.
