### ISSUE TITLE
Updated text / admin / links to use Hub (was Ecoverse)

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1129]
## Description

As a user I expect to see Challenges on a Challenge centric platform

## Acceptance criteria

- [ ] Admin: rename section name to be "Hubs"
- [ ] Front page: update text to be about Challenge Hubs 
- [ ] Membership Org: talk about "challenge hubs that are hosting"
- [ ] Membership User: member of challenge hubs
- ...

**Comment by Comoque1** [comment]
Looks as per AC.
