### ISSUE TITLE
Admin: Opportunity Admins

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1130]
## Description

As a challenge / ecoverse admin I want to be able to assign opportunity admins

## Acceptance criteria

- [x] Admin section on the Admin page for Opportunity updated to allow assigning of opportunity admins
- [x] Admin route is open for users with the OpportunityAdmin credential
- [x] Include the new role in the translation
- [x] Add the settings wheel on the opportunity page for the authorized users (below)
- [x] The list of available users should be derived from the parent challenge

## Additional Context

- Can be accessed by Global Admin, Ecoverse Admin, Challenge Admin, Opportunity Admin
- Global community admin can control the members / groups

**Comment by Comoque1** [comment]
Looks OK on DEV env.

Regarding this point: Global community admin can control the members / groups - works exactly as described  - Global community admin, can add/remove users from community members and group members for the community.
`Cannot add/remove opportunity admins!`
