### ISSUE TITLE
BUG: User with rejected Ecoverse application, can have its Challenge application approved

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1148]
**Describe the bug**
User with rejected Ecoverse application, can have its Challenge application approved.

**To Reproduce**

1. Go to https://acc.alkem.io/application-eco/
2. Create application to the Ecoverse
3. Create application to the Challenge under the Ecoverse
4. Admin `rejects` and `archives` the user application on Ecoverse
5. Admin `approves` the user application on Challenge level - this must be forbidden

**Expected behavior**
When user application is rejected from Eceoverse, Challenge application approval must be forbidden.

**Comment by techsmyth** [comment]
Issue is more fundamental: it seems that the parent community is not being retrieved. Have put a branch up that illustrates this. Check out the branch and then run the following query:
query {

  ecoverses {
    nameID 
    challenges {
      nameID
      community {
        id
        parent {
          id
        }
      }
    }
  
  }
}

All parents are null. Think it is to do with this being a ManyToOne relationship anchored on the child.

**Comment by Comoque1** [comment]
The issue is still reproducible on both Dev and Acc env.

**Comment by Comoque1** [comment]
After adding API tests, the following scenarios are failing:
- [ ] should throw error for creating challenge application without having ecoverse application
- [ ] should throw error for APPROVING challenge application, when ecoverse application is REJECTED
- [ ] should throw error for approving challenge application, when ecoverse application is removed

Currently the tests are disable, and will be enabled, after the issue is addressed.

**Comment by techsmyth** [comment]
Hi Evgeni,

A couple of  updates:
- should throw error for creating challenge application without having ecoverse application: this is not true. It is possible to create the application regardless of there being a membership / application on the parent Hub.
- should throw error for APPROVING challenge application, when ecoverse application is REJECTED: logic is different. This should throw an error when APPROVING a challenge when the user is not a member of the parent ecoverse. 
 should throw error for approving challenge application, when ecoverse application is removed: ditto, not relevant

Essentially the challenge application approval only takes into account whether the user is a member of the Hub community. Any applications at the Hub are not relevant.

**Comment by Comoque1** [comment]
The Bug cannot be reproduce after the latest changes.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a243ce3f-00da-40d4-be96-0b549c0c33d9)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d75f9c13-1ff8-4e23-9c74-f6e23a8a1be1)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d7b99d18-bded-4108-a728-05cec279cb48)

Closing the issue.
