### ISSUE TITLE
BUG: Ecoverse members "Available users" search, doesn't return correct results

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1153]
**Describe the bug**
Ecoverse members "Available users" search, doesn't return correct results.

**To Reproduce**

1. Go tohttps://acc.alkem.io/admin/ecoverses/un_sdgs/community/members
2. In "Available users" search, type "evgeni"
3. Returned results contain many rows of name not containing "evgeni"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5d244e51-08d1-403e-98de-1c7ffec4f157)

**Expected behavior**
Returns the specified search criteria.

**Comment by hero101** [comment]
can't reproduce on local

**Comment by Comoque1** [comment]
The issue was experienced on ACC env. 
Some time ago the same user was created n number of times.
After cleaning it up, the isue is not reproducible.
