### ISSUE TITLE
BUG: Global Admin cannot access Ecoverse/Community page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1154]
**Describe the bug**
Global Admin cannot access Ecoverse/Community page.

**To Reproduce**

1. Go to https://acc.alkem.io/ and authenticate with Global Admin
2. Using the url navigate to: https://acc.alkem.io/alkemio/community
3. See error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/07055be8-fed2-49d3-95c1-f0ef248d16ee)

**Expected behavior**
Global and Community Admin should have access to all community pages

**Comment by techsmyth** [comment]
Note that this seems to be specific to this ecoverse?

**Comment by Comoque1** [comment]
Tested OK on Dev env.
