### ISSUE TITLE
BUG: User navigating from its profile to an ecoverse, throws console error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1171]
**Describe the bug**
User navigating from its profile to an ecoverse, throws console error

**To Reproduce**

1. Go to SUT authenticate and navigate to user profile (i.e. https://dev.alkem.io/user/77-77-6625)
2. Click on any non private Ecoverse (in my case, there was  also private Ecoveres)
3. See error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/16b61fa6-6e98-4d80-9d17-113e3c5f295d)

**Expected behavior**
None console errors are thrown.

**Comment by techsmyth** [comment]
Options:
- authorization policy not propagated correctly on domain model.
- client requesting too much data

**Comment by atstoyanov** [comment]
Is it still relevant?

**Comment by techsmyth** [comment]
Indeed this one is no longer relevant.
