### ISSUE TITLE
Display a message if a User is not entitiled to see the challenges inside a private ecoverse

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1187]
## Description

As a User I want to be informed, that I cannot see community data of a private Ecoverse.

## Acceptance criteria

- [ ] User is informed, that he is forbidden from accessing private Ecoverse community data

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/100434ab-0a10-43d3-9aaa-93d5e595a16a)

## Additional Context

**Needs to be re-verified**

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/43cd7097-daec-4e40-9c66-6d060bf70864)

Currently if a User goes to the home page of a private ecoverse it looks like there are no Challenges.

**Comment by techsmyth** [comment]
Can you please give some more details on this? Is it in the client or at the api level?

**Comment by hero101** [comment]
Tested with client v0.10.6 and server v0.15.1
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/a978ee4b-5f59-4139-be12-d86615df5c10)

**Comment by Comoque1** [comment]
Agree, not reproducible.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/09d081a7-b8c3-4a52-af6f-4c1c40a06656)
