### ISSUE TITLE
Community area is available on Opportunity page.

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1188]
## Description

As a User I want to see community area on Opportunity page.

## Acceptance criteria

- [ ] Community area (similar to Ecoverse/Challenge) is available on Opportunity page.

## Additional Context
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/397be7bf-655a-4174-8474-dab1268f6968)

**Comment by techsmyth** [comment]
This is there now...

**Comment by Comoque1** [comment]
Looks OK now on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/45bccd05-8a33-4fde-b417-0caa3872c208)
