### ISSUE TITLE
BUG: Removing user from Ecoverse community, doesn't remove it from Challenge community

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1192]
**Describe the bug**
Removing user from Ecoverse community, doesn't remove it from Challenge community

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Add user to Ecoverse community
3. Add user to Challenge community
4. Remove the user from the Ecoverse community
5. The user is not removed from Challenge community

**Expected behavior**
When user is removed from parent community, its removal must be propagated down, to the child entities communities/groups.

**Comment by techsmyth** [comment]
This is not a bug but the way it currently works. We would need to see if it makes sense to cascade removal from lower level  communities. Certainly at the moment I am not getting any pull for this.
