### ISSUE TITLE
Remove usage of top level "community()" query

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1200]
## Description

As an architect I want all information related to Hubs to be held inside of the Hub entity so that these could later be isolated. 

## Acceptance criteria
- [ ] Server api is extended to have a "community()" query on the ecoverse level
- [ ] Client should be updated to use the "ecoverse.community()" query
- [ ] Server then has the top level community() query removed

## Additional Context
It is important that the ecoverse data is fully self contained from an access point of view. This may need to be secured / stored separately in the future - even potentially federated as we start looking at decentralization, so important to not build in these cross hub queries now.

**Comment by Comoque1** [comment]
Works OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1e626d52-75d2-41e2-8229-cac8095eeb8b)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6370ce38-82c7-417e-a72a-3b5e1aff653d)

The third point of AC, doesn't seem to be implemented: Server then has the top level community() query removed

**Comment by techsmyth** [comment]
Yes we will need another PR later to address the last AC. Will update + raise a separate card.
