### ISSUE TITLE
BUG: Unable to edit user profiles

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1208]
**Describe the bug**
Edit the profile of an existing user.
Click on save:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/fd2188b7-76b2-4838-8fb6-d8bb5d6d904d)

Seems that editing a user profile is submitting the request to **create** a user, not update.

**Comment by Comoque1** [comment]
Tested on DEV env.
The issue is still reproducible:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5dc127dc-1507-4750-8fff-c7f058b254b8)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d0c0b24e-f030-4f23-ad21-fe820e04a671)

**Comment by Comoque1** [comment]
Not reproducible anymore on DEV env.
