### ISSUE TITLE
BUG: Community on Challenge not rendering using Markdown

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1210]
**Describe the bug**
The Community section Challenges uses the Context.who field. This should be displayed as Markdown, but that is not happening:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2cd8a210-5257-41c0-948c-a858ca5b5a1f)

Note that the text has *But ... 100% safe* - that should be italic.

**Comment by Comoque1** [comment]
Looks OK now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1ca2ff13-1d1e-4c95-91aa-e05f64fc4b18)
