### ISSUE TITLE
BUG(PROD): IPFS request are failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1212]
**Describe the bug**
IPFS request are failing.

**To Reproduce**

1. Go to https://hub.alkem.io/user/evgeni-dimitrov-913
2. IPFS erquests are failing and user avatar is not loading
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a1851ea4-a1ef-4a80-adde-c76c691ab2db)

**Expected behavior**
User can see its avatar.

**Comment by techsmyth** [comment]
Fixed manually...
