### ISSUE TITLE
User card colors: needs theme support

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1247]
## Description

As a User I want to have the country displayed with its full name on user card, so that it is consistent with the rest of the places where user information is displayed

## Acceptance criteria

- [ ] Update the styling as follows:
1. the color of the name should be #068293 and be bold
2. Tag text should also be #068293
3. Tag border-color: #00A88F

**Comment by techsmyth** [comment]
to be picked up as part of applying the new theme
