### ISSUE TITLE
UX: User settings management

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1275]
## Description

As a user I want to be able to manage my preferences

## Acceptance criteria
- [x] Profile
- [x] Community Memberships: including Applications pending / management
- [x] Organizations: including creating new organizations
- [ ] Notifications - Application approved, Receive update notifications, Receive discussion notifications, etc.
- [ ] Add tab control on the user settings management (similar to the general tab navigation of the site)

## Additional Context
Left hand tabbed set of setting types:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/74f951eb-2bec-45da-bb35-10badf9876f4)

Notifications:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/30bb03b9-12a4-47ff-81c0-01ceee476edc)

**Comment by KayleeS96** [comment]
Here's the link to the updated user settings management mock-up (https://xd.adobe.com/view/88438054-bf02-45f5-b978-874a8ab0e11d-dd10/)

**Comment by KayleeS96** [comment]
Here's the new and updated version of the user settings management. We have played around with the new navigation, it isn't pixel perfect yet, but it gives an idea of the possibility. Most content has been resized to fit the new 1280px width.(https://xd.adobe.com/view/50215bf8-00d9-4bec-80e5-81fcd31d1c50-0572/)
