### ISSUE TITLE
Community Tab: Refinements

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1277]
## Description

As a user I quickly want to see what is happening in a community

## Acceptance criteria

- [x] UI as per UX defined in context below.
- [x] Header bar added
- [x] For Challenges, a section at the top to display the Leading organizations 
- [x] Label at top that can be used for an explanation
- [x] Refined header on the Members section (renamed from Users)
- [x] Ignore the "Latest updates" section

## Additional Context
https://xd.adobe.com/view/e0aa155d-63ef-4b01-8603-0ce36fc88072-b5f9/screen/6d0c6f4b-51b9-4e56-9316-4adc6e8e1d40/

**Comment by hero101** [comment]
What is "the activity page" at the bottom?
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/fa4a3e70-1046-4f81-bf2d-32d3f7c81a62)

**Comment by techsmyth** [comment]
Please ignore / remove the activity page section, it is not relevant at the moment

**Comment by hero101** [comment]
What about "Contributing organizations" at the bottom on page 1?
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/e4a02565-c976-4d8e-803b-3a209d2577fa)

**Comment by techsmyth** [comment]
Probably best if we talk this one through...

**Comment by Comoque1** [comment]
The page looks OK on DEV when browser is expanded.
When width is decreased, specifically on Challenge/Community page when there are more leading organizations, the cards are not aligned. Same happens with members.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a55ab619-b594-418b-b08e-5dbe55f34a76)

@techsmyth Please, share how do you like the font size under the header (to me it looks a bit too small).
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/79c4ead3-650b-4cb2-9aac-fb9a1d0b29c1)

**Comment by Comoque1** [comment]
Looks better now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ce6e4c79-bcc0-403d-a3a1-b981e33aae6e)

**Comment by Comoque1** [comment]
Reopening, as on expanded browser, the [organizations](https://dev.alkem.io/un-sdgs/challenges/food/community) cards are not aligned.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1d77da67-84c7-484a-9ecc-49ea081b4a57)
