### ISSUE TITLE
Admin: able to search on organizations when managing lead orgs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1298]
## Description

As a challenge admin I want to be easily able to filter the set of organizations that I can select from when adding / remove lead organizations

## Acceptance criteria

- [ ] Search box above the organizations list on both left and right similar to what is there for managing users that are members
- [ ] Search box filters based on Organization displayName
- [ ] Disabling grid direct filtering on "name" column

## Additional Context

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3e2d920b-22a6-44b9-ac59-b5e362c102bb)

**Comment by Comoque1** [comment]
Tested OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4803e702-dddf-4922-b73b-83d96b4bb7d1)
