### ISSUE TITLE
BUG: List of users for membership is flickering and very slow

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1299]
**Describe the bug**
When I go to add a user to a community or organization the list of available users takes a long time to come up, and is also flickering

**To Reproduce**
Enter admin area
Go to a hub
Click on members
The list of users on the right hand column takes a long time to come up, and is also repeatedly flickering

**Expected behavior**
There should not be any flickering, with a loading indicator shown. 
The "available users" list should be returned with only the following data per user: firstName, lastName, displayName

**Screenshots**
The query to the server is massively too heavy for this control:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/dc96c6fd-f1b0-4afb-90a6-db469a804ec8)

Currently the query is taking 6seconds to return on hub, which will only get much longer as the number of users increases.

- target users on organizations; users on hubs; global admin; global community admin

**Comment by Comoque1** [comment]
With around 90 users the loading takes ~1,5 seconds, which is significant improvement.
The requested data much less:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e0d2943c-e890-4d69-abd5-1348a599df5b)
Flickering is not reproducible.

Closing the bug.
