### ISSUE TITLE
Integrate discussions front end with server api

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1302]
## Description

As a user I want to be able to interact with the discussions api

## Acceptance criteria

- [x] Discussions screen using the Discussions entity from the api
- [x] Create discussion screen using the api to create discussions
- [ ] See detail of discussion screen to show the details of a discussion using the api

**Comment by Comoque1** [comment]
Clicking on "Replay to this comment ", doesn't change any state
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/29f56e6c-12fe-4303-be26-88cb9345ec1c)

**Comment by Comoque1** [comment]
Missing validation for "Title" input filed, when is empty.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5552d1c1-19b5-438b-b97f-9021765c5af0)

**Comment by Comoque1** [comment]
When on "./discussions/new" page, the title seem to be hardcoded and is always: "Digital Twinning "
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1c99b062-5a7f-403e-9858-981a5cbf09ef)

**Comment by Comoque1** [comment]
The title on "./discussions" page always shows the hub name instead the name of the corresponding level entity (in the case below, the opportunity name)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f166788f-ce89-4cdc-bffb-91320962de0a)

**Comment by Comoque1** [comment]
There is no option to set the type of discussion (i.e. "General",  "Questions", etc..)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7296f810-e9b3-4ace-8a56-735b81012c5d)

**Comment by Comoque1** [comment]
There is no way to delete message or discussion.

**Comment by Comoque1** [comment]
"Show all" component is missing.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f105ae17-232f-4f4c-bb1e-6aec00b152d8)

**Comment by Comoque1** [comment]
Created separate [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1326) for `discussions` titles.
The rest of the comments are going to be addressed as part of finalization of the `discussions` functionallity.

Closing this issue.
