### ISSUE TITLE
Spike: update client / server to use Kratos v0.8.0alpha3 / Oathkeeper v0.38.9-beta.1

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1304]
## Description

As a dev I want to know what the implicatiosn are for migrating to the new kratos / oathkeeper versions

## Acceptance criteria

- [ ] Evaluate updating to Kratos / Oathkeeper versions

Timebox to a day

**Comment by valentinyanakiev** [comment]
It is a spike, the spike has finished, there are separate stories for implementation.
