### ISSUE TITLE
BUG: Activity on private hubs is showing up with zeros

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1309]
**Describe the bug**
Look at Hub. On the home page the activity for the private hubs is properly displayed.

However if you click into a private hub then you see all zeros:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ae591aa5-96f4-4cf1-a3da-e6d673399f69)

**Expected behavior**
The activity metrics for a private hub are properly displayed on the hub home page. 

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/23ce21b3-983e-48b1-946e-da1a4c2caafb)

**Comment by Comoque1** [comment]
Looks OK on DEV.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3075549c-3b8f-49f7-978a-621b7d539ea8)
