### ISSUE TITLE
BUG: User cannot create entity when nameId contains underscore (_)

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1313]
**Describe the bug**
User cannot create entity when nameId contains underscore (_)

**To Reproduce**

1. Go to https://dev.alkem.io/
2. Create Ecoverse with nameId containing underscore (_) - error is thrown: `message: "Variable \"$input\" got invalid value \"UN_SDGS\" at \"input.nameID\"; Expected type \"NameID\". NameID value not valid: UN_SDGS"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cfc73433-3748-4ff5-8a1f-33964b260eb3)

**Expected behavior**
Entities can be created with underscore(_) in their nameId.

## Note
The side effects of this is also, that user with nameId containing underscore(_) cannot access its profile.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/292bbf6e-30f0-4b5a-86b0-025f721271c4)

**Comment by Comoque1** [comment]
NameID validation is not displayed on the the following areas on the client.

Organization:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4772239a-3e94-4894-b78a-1663b3ef42b6)

Project:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/95fa7211-292c-4062-8379-4056e1f8536d)

**Comment by hero101** [comment]
@Comoque1 The project issue is addressed in [a separate user story](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1327) since it needs extra attention.

**Comment by Comoque1** [comment]
Looks OK  on DEV now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/057f2494-d6b8-4f83-9e27-e5cc6cba7f1e)
