### ISSUE TITLE
Discussions Overview page 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1318]
## Description

As a user I want to be able to see a clean overview of discussions

## Acceptance criteria

- [x] UI adjusted as per updated design
- [x] Category panel is available on the page, and users can filter discussions by category type. 
- [x] Discussion entry: add category icon, do not display the description. Note no avatars.
- [x] Discussions can be sorted: newest, oldest. Use standard material select. 
- [x] Discussion search: title
- [x] Discussions overview
- [x] Discussions that are displayed are per entity i.e. hub, challenge, opportunity
- [x] Discussions page: enable the button to initiate a discussion by checking if the user has the CREATE privilege on the Community. If the user does not have the CREATE privilege then disable the button and show a tooltip if the user hovers over the button stating that the current user does not have privileges to crate a new discussion.

## Additional Context
[Design](https://xd.adobe.com/view/9f5df785-4222-400e-9db0-3ab785964328-ca0e/screen/b0738518-2ef3-4e45-9c2d-ee03ad0758e2/)

The category chosen does not need to be stored in the URL state. 
Avatars display for later.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
