### ISSUE TITLE
Spike: Investigate support for how to display the Markdown component 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1322]
## Description
As a user I want to see the same markdown component in all places 

## Acceptance criteria
- [x] Toolbar to be at the bottom
- [x] Remove shadows/borders
- [x] Offer two tabs 
- [ ] Outlined styling, including line at the top with the label
- [ ] Initial option for the help icon.

Later
- [ ] Move tabs at the bottom for editing / preview

Timebox to 2 hours

## Additional Context
This investigation provides input for [this story](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1369).

**Comment by hero101** [comment]
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/aa905fa4-434a-4039-9eaa-f39e139f541f)
