### ISSUE TITLE
Community Panel: Implement Discussions tab 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1323]
## Description

As a user I want to be able to navigate to the discussions in a community

## Acceptance criteria

- [ ] Provide preview content in the discussions tab on the community section (panel) in a hub / challenge / opportunity
- [ ] Preview to show the latest 3 discussions plus a label with how many additional discussions there are.
- [ ] Allow user to link to the discussions page

## Important
This story won't follow the design but rather apply the component for visualization of the latest created 3 discussions. 
The latest design for this control will be applied with [Discussions Overview page #1318](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1318)

## Additional Context
[Design - what to use](https://xd.adobe.com/view/9f5df785-4222-400e-9db0-3ab785964328-ca0e/screen/b0738518-2ef3-4e45-9c2d-ee03ad0758e2/)
[Design - where to apply](https://xd.adobe.com/view/665fce90-f549-4cef-a24f-6754f0a2ed28-330c/)

**Comment by Comoque1** [comment]
Looks OK on Dev env
