### ISSUE TITLE
Discussion detail and initiation pages

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1325]
## Description

As a user I want to be able to see the details of the discussions and contribute

## Acceptance criteria

- [x] Discussions details page: update the comment item to display as per new design
- [x] Discussions details page: first comment should display the same as other comments, but before the search
- [x] Discussion details page: do not display "reply to this" page; show the delete icon if (a) the current user is the sender (b) the user has the DELETE privilege
- [x] Discussion details page: add the summary, without the avatars
- [x] Initiation page: add the category
- [x] Discussions details page: only show the post comment control if the user has the CREATE privilege on the Discussion. If the user does not have the CREATE privilege then display a message the current user does not have privileges to post to this discussion.

## Additional Context

[Details design](https://xd.adobe.com/view/c4333267-959e-44b2-a6dc-98462394f4f2-9160/screen/22daf864-df47-418a-891e-f68caf31713f)
[Initiation design](https://xd.adobe.com/view/4651e821-07ba-4ae0-9163-99fa2b0e9cde-1302/)

Re authorization:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/cca21190-f5b3-4718-b36e-923b2664bfe2)

**Comment by Comoque1** [comment]
Tested OK on DEV.
