### ISSUE TITLE
UI: User navigation for community panel, search

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1330]
## Description

As a user I want a nice way to interact with users in a community via the community panel

## Acceptance criteria
Community Panel:
- [x] Implement the hover popup like is there in the organization page now (hovering over associate cards)
- [x] Clicking on the icon to navigate to the user profile page.

Search card for Users:
- [x] Add a 'view profile' button to replace the 'send message' button that allows navigating to the user profile page

## Additional Context
Currently clicking on one of the users shows the old user card which is really poor UX.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
