### ISSUE TITLE
UX: Dashboard tab for Hub / Challenge / Opportunity 

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1339]
## Description

As a user I want to quickly understand what a hub / challenge / opportunity is about.

## Acceptance criteria

Common
- [x] The name of the entity + banner
- [x] The tagline + start of the vision (3 lines) of the entity.
- [x] Add ability to apply.
- [x] Key metrics - see screenshot attached
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/73a91fd1-b9b4-4eb3-8947-796b2e41c34f)
- [x] Show the latest update (as seen in the community panel)
- [x] Show the latest 3 discussions (as seen in the community panel)
- [x] Community preview (as seen in the community panel)
- [x] Status / Lifecycle state - Approved, In progress, Refined

Hub
- [x] Display facilitating organization
- [x] Challenges

Challenge
- [x] Display leading organizations
- [x] Opportunities

Opportunity
- [x] Projects

## Additional Context

[Tabbed View ](https://xd.adobe.com/view/9ca30f8c-48ab-4877-bc2a-6c19f538dc32-c9f0/screen/c050949d-50ee-4d50-8d6c-7d2ff943e4e7/?fullscreen)

**Comment by Roseghost** [comment]
Link: https://xd.adobe.com/view/6445028e-0721-46ed-b7eb-d1e53afff91c-3116/

**Comment by Roseghost** [comment]
Link to Hub, Challenge and Opportunity versions: https://xd.adobe.com/view/9e3e5911-170e-43f3-92ad-8809ddb4020c-cb6d/
