### ISSUE TITLE
UX: Context tab for Hub / Challenge / Opportunity 

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1340]
## Description

As a user I want to understand in detail what a hub / challenge / opportunity is about.

## Acceptance criteria

Common
- [ ] Name and tagline of the entity
- [ ] Banner
- [ ] Tags
- [ ] Vision, Background, Impact, Who of the entity
- [ ] Lifecycle
- [ ] References - (e.g. definition of terms, academic articles)

Opportunity:
- Ecosystem Model
- Solution Aspect

## Additional Context
Add screenshots showcasing where the texts are displayed currently
How to handle quick links? - currently using references for them.

**Comment by KayleeS96** [comment]
We have created a rough version of where the elements will be, not sure on the ecosystem model and solution aspect yet. That we have to get a clearer vision and understanding of.

https://xd.adobe.com/view/b6f9e4f6-a293-4498-80d7-2d51a42e568a-e3aa/
