### ISSUE TITLE
UX: High fidelity navigation design

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1345]
## Description

As a user I want to see an application bar so that I can easily navigate through the application.

## Acceptance criteria

- [x] A search bar is integrated in the navigation bar.
- [x] Information about the user (avatar, name, role are displayed)
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/573815f6-4e1b-440d-bbeb-971a0e096788) - similar format
- [x] Shortcuts to notifications / messages are displayed
- [x] Ability to navigate to the home page, challenges page and contributions page
- [ ] Version with not signed in state
- [ ] Behavior when the users scrolls down the page
- - Could have a variation with drop-shadow, color change, change in density
- - Display only the main navigation bar (do not include the blue one)
- [ ] Need to include the public preview label
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/98662991-8352-4012-89cd-fe1e75e0534c)

## Resulting design

https://xd.adobe.com/view/6581976e-b6c2-46eb-b24c-2440a4769e0c-30d2/

**Comment by Roseghost** [comment]
https://xd.adobe.com/view/6581976e-b6c2-46eb-b24c-2440a4769e0c-30d2/

Navigation designs, has a version with profile picture and version with name+rol.
