### ISSUE TITLE
BUG: Global admin cannot create discussion on particular challenge

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1347]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/digicampus/challenges/digitalediensten/community/discussions/new
2. Authenticate with Global Admin
3. Fill up title and further information - error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a51a4f16-8d4e-4eaa-861b-502ddcfe0585)

**Expected behavior**
Discussion is created successfully.

**Additional context**
The user is able to create discussions to other challenges, opportunities and ecoverses

**Comment by techsmyth** [comment]
I think you will find that the discussion was actually created. The issue is that the membership of the discussion matrix room has not in some cases been accepted for whatever reason before the first message is sent.

**Comment by Comoque1** [comment]
This one will be retested on ACC env.
