### ISSUE TITLE
BUG: User verification status is not visible on the user profile page

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#1348]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io
2. Navigate to https://dev.alkem.io/user/admin-alkemio
3. The user profile doesn't show the verification status

**Expected behavior**
1. Verification status is visible.
2. Verification status is showing the correct status.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The following locations:
- user profile
- user profile popup

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1bb77811-0c93-438f-97c4-4f87896e8294)

**Comment by valentinyanakiev** [comment]
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/2ba76ba8-f088-46ec-b15b-47ae49189b95)

**Comment by Comoque1** [comment]
To look like on Organization profile:
![image](https://user-images.githubusercontent.com/23620658/141785469-063b7a73-bcae-4ac3-b96f-c27e43e5142f.png)

**Comment by valentinyanakiev** [comment]
Linked to https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1186

**Comment by atstoyanov** [comment]
@Comoque1 @techsmyth @linux4e The verified status is not present in the design: 
https://camo.githubusercontent.com/79053bb779ffa11d86ab5d54aff9d1c1273bfc4c0cc34d042a78d7cbb41f3eb9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565636239383137616562353839363130313334626434332f37386537366332612d343933322d343437632d626537352d356234303437356166333062

**Comment by techsmyth** [comment]
@Enderedne @atstoyanov that is a miss, it should be visible. For now please put this to blocked and we can pick this up as part after the tabbed UI switch.

**Comment by techsmyth** [comment]
Moved to be part of #523
