### ISSUE TITLE
UX: Refine current designs to accommodate new navigation

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1351]
## Description

We currently don't have a max width for any page. What we want to set is a responsive container behavior with max width of 1280px.

## Acceptance criteria

- [ ] All problematic designs are adjusted.
- [ ] We have a list of all the components that need to be adjusted.

**Comment by Roseghost** [comment]
https://xd.adobe.com/view/50215bf8-00d9-4bec-80e5-81fcd31d1c50-0572/ 
Current designs for these redesigns. 

Note 22-11: The navigation is still going through a small refinement. This hasn't been applied to designs yet.
