### ISSUE TITLE
UX: Redesign Home page

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1353]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Alkemio introduction
- - [ ] Display tagline, welcome message
- - [ ] Capture that Alkemio is a foundation (sustainable public good)
- - [ ] Have a play around the word alchemy (alkemio), general theming
- - [ ] Make easy to contact
- - [ ] Make easy for the user to understand the activity
- - [ ] Visual placeholder for information - links to discussions, FAQ, concepts, etc.
- [ ] Hub Overview/Explorer
- - [ ] Consistent hub cards with the rest of the design
- - [ ] My hubs / challenges
- - [ ] Have featured hubs section
- - [ ] Explore hubs
- [ ] Top contributors - both organizations and users
- [ ] Dashboard style

**Comment by Roseghost** [comment]
Wireframe/LoFi version 

link: https://xd.adobe.com/view/6e445f77-c155-4bdb-a394-be7b1d20a9bf-3b17/ 

The dashboard layout is barely (actually not) possible if something contains mainly out of cards. First page is just full width and 2nd page is an attempt of dashboard. Probably best to rediscuss this. 

For the rest is the contact us and tutorial buttons are the best outcome for alkemio without giving the user a boat of information at once specially if its a regular user that has to scroll through first section to get to the main use of the page. Alkemio section would get a white but with alchemy like connections as background to give the reference. 

Conclusion: maybe rediscuss soon tm? probably at daily tomorrow?

**Comment by Enderedne** [comment]
Can we think in the direction of [this](https://zone-ui.vercel.app/marketing/blog/) or [this](https://zone-ui.vercel.app/marketing/case-studies/). Generally take some inspiration from https://material-ui.com/store/previews/zone-landing-page/
