### ISSUE TITLE
UX: Challenges explorer page

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1354]
## Description

As a user
I want to see all challenges from hubs that I participate in
So that I can navigate to them

## Acceptance criteria

- [ ] Display the challenges that the user is taking part in.
- [ ] Display the challenges from every hub that the user participates in.
- - [ ] The description for challenges
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/83da886a-5d97-4e04-afe1-6e640ddad1fa)
- [ ] Search needs to be integrated and applied across the hub challenges.
- - [ ] Search over tags, challenge title

**Comment by Roseghost** [comment]
Adobe XD Link : https://xd.adobe.com/view/60573b6e-37e2-4357-9402-d50397dac56d-3504/
