### ISSUE TITLE
User cannot reach its profile

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1358]
**Describe the bug**
User cannot reach its profile.

**To Reproduce**
1. Go to https://test.alkem.io/user/admin_alkemio
2. Authenticate with global admin
3. User is redirected to 404 page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a6cba5f0-6da3-42b9-b074-17857405c4ab)

**Expected behavior**
User can navigate to its profile.

**Comment by techsmyth** [comment]
This looks like a legacy account. The underscore is no longer supported in nameIDs. How did this profile get created?

**Comment by Comoque1** [comment]
Also fixed the users on DEV env.
Closing.
