### ISSUE TITLE
User preferences: notifications management 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1365]
## Description
As a user I want to be able to manage my notifications

## Acceptance criteria

- [x] Notifications tab with a single section holding the toggle for the following user preferences: community application received.
- [x] The title would be "Email notifications" with the description: "Receive email notifications for the following events:"
- [x] Display the following notifications: NOTIFICATION_APPLICATION_SUBMITTED, NOTIFICATION_COMMUNICATION_UPDATES, NOTIFICATION_COMMUNICATION_DISCUSSION_CREATED, NOTIFICATION_APPLICATION_RECEIVED, NOTIFICATION_USER_SIGN_UP
- [ ] Sort based on the display name, in whatever order puts the [Admin] at the bottom

## Additional Context
https://xd.adobe.com/view/88438054-bf02-45f5-b978-874a8ab0e11d-dd10/

**Comment by Comoque1** [comment]
Functionally seems OK.
The sorting is missing and for different users looks differently.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f8165ef-e566-4630-be93-a1b71ae769bb)

**Comment by Comoque1** [comment]
Sorting is similar everywhere now
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cd97d8c3-864d-456a-8733-6f7c2ad6c0b9)
