### ISSUE TITLE
allow removing orphaned rooms on synapse server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1377]
## Description

As an admin I want to be able to remove all orphaned rooms on a synapse server

## Acceptance criteria

- [ ] Mutation for global admins to remove orphaned room

## Additional Context
Note: removing a room means removing all members, which makes the room then ignored.

**Comment by Comoque1** [comment]
Removing orphaned rooms seems to be performing correct.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d63df436-3912-485e-b7c2-83e55fd976cc)

After querying it using `adminCommunicationOrphanedUsage`, it is not returned
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/383cda16-c646-481e-9abf-117351c4410c)

In reality, the room remains available on synapse server
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/47b00734-ce20-4401-90b7-dd9223eb3348)

**Comment by techsmyth** [comment]
As discussed, it is expected that the room is still there on synapse.
