### ISSUE TITLE
BUG: messageCount is not being updated

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1387]
**Describe the bug**
Create a new discussion and send a message to it. The message count is not being updated. Refreshing the page shows the correct value.

Also, please update the label on the button...

**Comment by Comoque1** [comment]
Tested OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/69d1f14e-a85d-4e79-a7ba-1e0e8656b1bf)
