### ISSUE TITLE
BUG: (HIGH severity) Client is failing to load the users

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1397]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/users
2. Confirm the user are loaded - No one user is loaded
3. See error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a6540e2e-b326-4598-aa66-4504a6d585dc)

**Expected behavior**
All user are loaded on "/admin/user" endpoint

**Comment by techsmyth** [comment]
This is corrupted data. Likely on one of the server crashes that you encountered a user was left in a partially created state, so the user does not have its data fully created. This is the reason that agent pool fix is key. Please recreate the database on dev...

**Comment by Comoque1** [comment]
Tested OK on ACC.
