### ISSUE TITLE
BUG: Discussions overview takes too long to load

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#1403]
**Describe the bug**
Discussion overview page takes too long to load

**To Reproduce**

1. Log in.
2. Go to https://test.alkem.io/un-sdgs/community/discussions
3. Navigations take 10-15 seconds to load initially. All discussions make a call to get all authorization policies, which is heavy (see screenshot) and that takes too long.

**Expected behavior**
1. Discussion overview is loaded in 1-2 seconds max

**Screenshots**!
[image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/90f229de-524f-4859-b4cf-6bccb02e3e6f)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu
- Browser: Chrome

**Additional context**

**Comment by Comoque1** [comment]
The discussions list is loaded in much less time ~ 179ms
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/50573c54-8e22-434b-a3ba-b4242b66b378)
