### ISSUE TITLE
Display of known social media icons dependent on them having a value

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1405]
## Description

As a user, I want to see only icons that are set

## Acceptance criteria

- [ ] The display of the social media icons (github, linkedin, twitter) should only be if the reference is present AND if it has a value AND if that value is a valid URL (partial URLs are not valid)
- [x] Testing for valid URL to check if starts with "http"
- [x] Input URL is validated when a user profile is edited

## Additional Context
Note: this is updating the existing UI

**Comment by Comoque1** [comment]
Looks OK, but there are another bugs around the references, which are going to be addressed separately.
