### ISSUE TITLE
BUG: User name is overlapping search field when have narrow layout

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1411]
**Describe the bug**

**To Reproduce**

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0ebb9cbc-eac7-4fc0-8172-e4fdbd42d7ca)

**Expected behavior**
Name to be hidden below a certain width

**Comment by atstoyanov** [comment]
CNR

**Comment by Comoque1** [comment]
Looks OK with the branch Bugfixes on Test env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6f7a2d03-6de3-42f4-9f39-fe25c5bf971e)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b78f9f6e-587e-4add-848d-a0c022b090c4)

When the browser width is decreased a lot, the `search` input hides.
