### ISSUE TITLE
User Profile Settings: refresh profile tab 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1422]
## Description
As a user I want to be able to manage my profile settings

## Acceptance criteria
- [x] Profile tab layout as per design
- [x] Addition of social section to understand "known" references by name:  LinkedIn, Twitter, Github. If links are not there then the entry would not be shown.
- [x] Social section to also have the email
- [x] References section is otherwise the same as the existing one. It should not show the "known" references used in the social section. 
- [x] Admin view to use the profile tab contents

## Additional Context
https://xd.adobe.com/view/88438054-bf02-45f5-b978-874a8ab0e11d-dd10/

Note: references section as they currently are as require a more structural update.

**Comment by Comoque1** [comment]
Overall the layout requirements are covered.

Issues are experienced around the predefined references (twiter, github, linkedin)
https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1452
https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1453

Closing this issue and the bugs will be addressed separately.
