### ISSUE TITLE
UX: Challenge Explorer - add ability to find challenges that are not related to current user

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1424]
## Description

As a user I want to be able to explore challenges, not related to the user memberhip

## Acceptance criteria

- [ ] New component to allow users to search just within Challenges.
- [ ] Component should have descriptive text as follows: "There are currently {activity.challenges} challenges active on Alkemio. Some are public, some are private and hence depend on being a member of the hosting community. 

Please feel free to search through the Challenges that you have access to:
<search box>
- [ ] The current search box component can be re-used
- [ ] The results to be displayed using the normal challenge cards

## Additional Context
The existing search query on the api can be used to return the results, and then only take the Challenge results back.

**Comment by techsmyth** [comment]
@hero101 - as discussed. And please disable the challenges overview tab for now until we have this one. 
@Enderedne - Svetoslav raised the good point about what to show if the user is not logged in...and in general giving the user the ability to search available challenges would be a good addition to this tab.

**Comment by KayleeS96** [comment]
https://xd.adobe.com/view/60573b6e-37e2-4357-9402-d50397dac56d-3504/

**Comment by KayleeS96** [comment]
Updated version
https://xd.adobe.com/view/8969ac32-6302-45ca-996d-55a48628e846-dc3a/
