### ISSUE TITLE
Breadcrumb and entity (i.e. Challenge ) tabs are fixed 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1426]
## Description

As a User I want Breadcrumb and entity (i.e. Hub / Challenge / Opportunity ) tabs to be fixed on top, so that when scroll down, to always have the visibility of where I am.

## Acceptance criteria

- [ ] Breadcrumb and entity (i.e. Hub / Challenge / Opportunity ) tabs to be fixed on top
  - [ ] Current behavior:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ecacd75b-0e08-4837-8ef4-94730efbe7ac)
   - [ ] Expected behavior:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ce66ad41-d3af-4cd3-9d96-c6fc49be4dd4)

**Comment by Comoque1** [comment]
Still reproducible.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ee107ac4-9871-4db0-951b-89328d25dc00)

**Comment by atstoyanov** [comment]
@Comoque1 Unclear images. The acceptance criteria and images contradict the title.
