### ISSUE TITLE
BUG: "Save" button on Opportunity new/edit pages doesn't display its label

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1427]
**Describe the bug**
"Save" button on Opportunity new/edit pages doesn't display its label

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/un-sdgs/challenges/ch1/opportunities/new
2. Authenticate with global admin - save button doesn't have label
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d3784607-11b7-437f-af75-3526f0162083)
3. Same issue is experienced, when creating group on Opportunity
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cf924531-628c-4f2b-a05c-3ca8e10b0099)

**Expected behavior**
"Save" button on opportunity new/edit page has label.

**Additional context**
On Hub and Challenge page looks OK.

**Comment by techsmyth** [comment]
showing up fine for me:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3d291f71-87aa-496b-8b28-1189a168cdbc)
