### ISSUE TITLE
BUG: Discussions overview category filter icons are not centered when screen width is decreased

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1431]
**Describe the bug**
Discussions overview category filter icons are not centered when screen width is decreased

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/community/discussions
2. Authenticate with global admin
3. Decrease the window width
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/790c59ac-5903-4f4c-8e07-8e2433043797)

**Expected behavior**
Discussions overview category filter icons are centered when screen width is decreased

**Comment by atstoyanov** [comment]
It has been fixed

**Comment by Comoque1** [comment]
> It has been fixed

You are right!
![image](https://user-images.githubusercontent.com/23620658/145591847-45e37781-2ea6-4482-94d0-aa3f8a3202cf.png)

Can we address as part of this one "initiate new discussion" button alignment, or you would prefer another issue?

**Comment by Comoque1** [comment]
Opened [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1534) with regards to my previous comment.
