### ISSUE TITLE
BUG: Clicking anywhere on the user name should show the drop down

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1444]
**Describe the bug**
Clicking anywhere on the user name should show the drop down

**To Reproduce**
Login using latest client build. Click on the user name, nothing happens. The drop down is only shown when clicking on the icon. 

**Expected behavior**
Clickng on the user name to also show the drop down.

**Comment by Comoque1** [comment]
Tested OK on Test env.
