### ISSUE TITLE
UX: Contributors Overview page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1449]
## Description

As a user I want to be able to navigate the Users and Organizations that are contributing

## Acceptance criteria

- [ ] Search box for Users
- [ ] Search box for Organizations
- [ ] Activity panel showing the number of Users / Organizations
- [ ] To cover the situation where a user is (a) not logged in (b) logged in

**Comment by Roseghost** [comment]
Link to Adobe XD Design: https://xd.adobe.com/view/81700575-ef74-42e6-94a4-e4c96b39c2a9-d423/

Notes: Search bar filters on both but give their results seperated by blocks.
