### ISSUE TITLE
BUG: Alkemio logo is not used correctly

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1463]
**Describe the bug**
Alkemio logo should be using the brand colors, and be capitalized

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/23c408d7-5aa1-4a58-bf8b-09fe5b030e74)

vs

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6027093c-f790-4347-86ca-33e77d6dc781)

**Expected behavior**
Alkemio logo should not be modified.

**Comment by atstoyanov** [comment]
@KayleeS96 the letter "O" at the end looks different.
![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/7479f252-b62a-483d-aaf1-2a63b6649e36)

![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/4d81968d-576b-4edc-81b2-fc5ac6e634fa)

**Comment by KayleeS96** [comment]
Hopefully this fixes that issue
![Component 78 – 1.svg](https://images.zenhubusercontent.com/612cb1848a783db262f19451/acac58d1-143b-48db-aff4-6615b785690f)
![Component 79 – 1.svg](https://images.zenhubusercontent.com/612cb1848a783db262f19451/28607271-fefc-4ea7-8c4b-7de46fdf1625)

**Comment by Comoque1** [comment]
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/15e5f31d-139e-4627-bff6-45d700d2766d)
