### ISSUE TITLE
BUG:  Links are not displayed with reference names but with the URLs

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1476]
**Describe the bug**
On user profile Links are not displayed with reference names but with the URLs

**To Reproduce**

1. Go to https://dev.alkem.io/user/qa-user
2. Authenticate with the user qa.user@alkem.io
3. Under `links` reference URL is displayed instead of its name/description
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/38eeaec9-4028-445a-890f-c124c65ed116)

**Expected behavior**
All usages of references (excluding "social" references on profiles) should have the same behavior: Display using the name, destination for the link is the URI, text after the link is the description. The description should truncate to 30 (?) characters and the tooltip should show the full URL and description.

## Additional information
References on context page should be a bulleted list with the name and description visible, with the name linking to the URI
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5cf2a965-7770-49bf-97c3-3a1c1bf3952d)

**Comment by valentinyanakiev** [comment]
https://xd.adobe.com/view/09c046c3-47a0-47e0-9a79-655c75030b45-5c93/

**Comment by Comoque1** [comment]
On [Aspect settings ](https://dev.alkem.io/opp-auth-eco-nameid498584/aspects/111-9611/settings)page is still not queried the desciption:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8a7f6c4e-588a-4432-ab12-46b2d1cd3938)

**Comment by Comoque1** [comment]
The first comment is addressed, the last, regarding the hub is not.
