### ISSUE TITLE
UX (UFT) Add emotions to discussion comments 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1482]
## Description

As a User I want to be able to react to discussions, comments and updates with emotions

## Acceptance criteria

- [ ] User is able to set emotions on Discussions, Comments, Updates
- [ ] TBD

## Additional Context
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e189c705-4aaf-4598-8f32-de8e72cf1424)

**Comment by SimoneZaza** [comment]
It took us a few years, but they're here now! ^_^
