### ISSUE TITLE
BUG: (UFT) There is no signup button anywhere on pages (only on login page)

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1486]
**Describe the bug**
There is no signup button anywhere on pages (only on login page)

**To Reproduce**

1. Go to https://dev.alkem.io/
2. Make sure you are not authenticated - There is no signup button anywhere on pages (only on login page)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0232bf3d-8afe-453b-8fb9-071088afe755)

**Expected behavior**
Add "Sign up" button
TBD - where?

**Comment by atstoyanov** [comment]
Inconsistent ![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/f5cd5c34-175c-4121-b7cd-89057804d57c)

**Comment by Comoque1** [comment]
Agree, inconsistent and missing "Sign up" button.
