### ISSUE TITLE
Combine the users + orgs into one "contributors panel"

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1488]
## Description

As a user I want a home page with more focus on the hubs

## Acceptance criteria

- [x] Rename current users card to be "Contributors"
- [x] Label above user section: "Users"
- [x] Show 12 user avatars (as it is now)
- [x] Show text "...plus XX more"
- [x] Label above organization section: "Organizations"
- [x] Show 6 organization avatars without popup (for now)
- [x] Show text  "...plus XX more"

## Additional Context
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d0acd978-55c8-42eb-82f7-c2473c2af711)

**Comment by Comoque1** [comment]
Looks nice on Test env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7300a13f-4305-4a61-a4cd-3d01bf5a41be)

There must be taken in to consideration, that the `...plus 30more` organizations is the total organization and we are already displaying 6 of them. Same applies for the Users.

@techsmyth do you prefer to address this as part of this issue or to open another one?

**Comment by techsmyth** [comment]
Lets take it through as is and create another one for the maths :) Also we need to have a descriptive label under Contributors.
