### ISSUE TITLE
BUG: (UFT) Inconsistent activity size Home dashboard and rest adashboards

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1491]
**Describe the bug**

**To Reproduce**

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fb029347-40e5-4bb0-b856-6dba37d17551)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techsmyth** [comment]
They represent different activity.
