### ISSUE TITLE
BUG: counter on org card is mis-aligned

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1498]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ca5b3ca0-2ea6-4e51-8fd1-b469bd23d3c0)
The alignment of the number of members is not correct. 

Limit the text to 4 lines *if this is supported by the card*

**Comment by Comoque1** [comment]
Looks OK on Test env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d920d4e6-1b26-4a90-9262-e6ba54af8d49)
