### ISSUE TITLE
User count on organization card shows 0

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1501]
## Description
As a user
I want to see number of users in the organization

## Acceptance criteria

- [ ] Members on organization cards to show the appropriate number of **associates**
- [ ] Use the new activity field on organization to retrieve this information
- [ ] Do **not** query all members for the organization unless required

## Additional Context
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/077aad06-4e87-4e2c-8a7a-f008191029cf)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/25c5b5f3-76dd-4daa-a044-51f75bbbb0a5)

**Comment by techsmyth** [comment]
There should probably be an activity query on the organization entity to get the number of users that are in the org.

Plus it should NOT be members, even if the api still says members.
