### ISSUE TITLE
BUG: (High Severity) Only opportunity member can see opportunity community, discussions and canvases

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1513]
**Describe the bug**
Only opportunity member can see opportunity community, discussions and canvases

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/challenges/food/opportunities/food-sec/dashboard
2. Authenticate with global admin - user cannot see community, discussions and canvases (the same applies for challenge admin)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5275a954-baa3-4c77-8b95-87bf1405d6cd)

**Expected behavior**
Global admin, Hub admin, Challenge admin, must be able to see opportunity  community, discussions and canvases.

**Comment by atstoyanov** [comment]
This is a server issue. The permission is determined by `opportunity.community.authorization.myPrivileges.READ`. If it is missing for a user then they don't have access to these tabs.

**Comment by Comoque1** [comment]
This is a client issue. If you navigate to the parent entity dashboard and back to the opportunity, all tabs are enabled as expected.
