### ISSUE TITLE
BUG: The organization avatars are inconsistent

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1524]
**Describe the bug**
The organization avatars do not share the same layout
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/3d82d735-7431-4108-90e8-0cb8e1417b56)

**To Reproduce**

1. Go to the home page

**Expected behavior**
The organization cards are displayed in a format similar to the user avatars
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/aefa38c6-3af9-4ad2-9a21-ed33daea6b63)

**Comment by atstoyanov** [comment]
the fix for resizing the avatars based on the width of the container has an issue when the avatars are oriented portrait (height is bigger than width). The solution is to upload square avatars or landscaped avatars.
