### ISSUE TITLE
Layout refinement

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1525]
## Description

As a user
I want to have consistent UX across the application
So that the application is easier to use

## Acceptance criteria

- [x] Fix the navigation color for disabled - [ ] don't change the background color, change only the opacity
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/eba54371-ab47-4e69-95cd-2b56b2300a14)
- [x] Disable the paper elevation and make the paper color darker or border at the bottom - [ ] need to experiment
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/4627d448-b163-41e5-ad56-429d59705dd8)
- [x] Organization Profile content should be split in 50/50 sections
- [x] All primary actions need to be primary filled buttons
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/61b0a0e0-7320-4d1f-9e5a-7235e8dee29a)
- [x] Rename HUBS to HOME in breadcrumbs
- [x] Increase spacing between hub cards on home page from 8 to 16px

**Comment by atstoyanov** [comment]
In this one can be included unification of 'Sign in' and 'Login' buttons.
