### ISSUE TITLE
BUG: "Initiate new discussion" button gets out of Title card, when browser width is decreased

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1534]
**Describe the bug**
 "Initiate new discussion" button  gets out of Title card, when browser width is decreased.

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Authenticate with account that have access to SDGS hub discussions
3. Navigate to https://acc.alkem.io/un-sdgs/community/discussions
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/94bd3cec-2565-4774-88fd-c85c874098c6)

**Expected behavior**
 "Initiate new discussion" button doesn't  get out of Title card with the Title card, when browser width is decreased.
Rename the button to be "New Discussion"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by atstoyanov** [comment]
It is aligned. It is in the center of his parent element. It is the same as the title.

**Comment by valentinyanakiev** [comment]
Check with the UX team

**Comment by atstoyanov** [comment]
![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/36f47c7b-78b8-469b-9deb-1b9a158991e0)
@linux4e @Enderedne on the discussions page we have repetitive information do we need it? From the breadcrumbs is visible on what entity the user is. From the tabs is visible that we are on the 'discussions' page.
