### ISSUE TITLE
BUG: Discussion category icons wrong color and when browser width decreased label overlaps with expanding arrow

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1535]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/challenges/ch1/community/discussions/new
2. Authenticate a global admin
3. Decrease browser width
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bd9d84f7-4325-4499-83ab-2862db301b90)

**Expected behavior**
 Discussion category icons have blue color and when browser the label and the arrow doesn't overlap.
- The color of the 'Questions' text is black
- The question mark icon is blue (like in the discussions page)

**Comment by valentinyanakiev** [comment]
To be discussed with the UX team

**Comment by Comoque1** [comment]
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a2119890-a7bd-4520-a1a4-e3f1fe863bed)
