### ISSUE TITLE
Consistent usage on hover over profile images

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1544]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by techsmyth** [comment]
@Comoque1 can you please refine this one?

**Comment by Comoque1** [comment]
Closing, as wasn't able to identify inconsistency on different pages, when hover on users profile image.
