### ISSUE TITLE
BUG: Web Sockets requests are failing on acceptance environment

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1545]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/admin/hubs/ole1/challenges/ole11/community/updates
2. Authenticate with global admin
3. Open browser dev tool on "Network"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/be16585f-b93e-479d-af86-e6055da2bfc1)

**Expected behavior**
Web socket requests are not failing.

## Additional information
To be checked: 
`const wsUrl = `${wsProtocol}//${window.location.hostname}:${window.location.port}/${graphQLEndpoint}`;`
row: 68 in `useGraphQLClient.ts`
may need to be: `const wsUrl = `${wsProtocol}//${window.location.hostname}:${window.location.port}/graphql`;`

**Comment by valentinyanakiev** [comment]
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/9dbc42c0-ab44-4c11-9dd4-123cb5f49882)

**Comment by Comoque1** [comment]
Cannot reproduce on DEV env. I'll check on ACC, once deployed.
