### ISSUE TITLE
BUG: "Edit photo" button overlaps avatar

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1550]
**Describe the bug**
"Edit photo" button overlaps avatar.

**To Reproduce**

1. Go to https://acc.alkem.io/user/--3395/settings/profile
2. Authenticate with the user to which profile you are going to edit - "Edit photo" button overlaps avatar
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3d98e98e-6c9d-4b49-994c-7d9a4ec508e8)

**Expected behavior**
"Edit photo" button doesn't overlap avatar.

**Comment by techsmyth** [comment]
I think this is related to the format of the avatar that you uploaded; with the new avatar selector this should not happen anymore.
