### ISSUE TITLE
Make the User card consistent with the design

### ISSUE THREAD

**Issue by Enderedne** [alkem-io/client-web#1552]
## Description

As a User
I want to have the user card as per design
So that I visually pleasing experience

## Acceptance criteria

- [ ] The card currently looks like 
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/5fd0c9c5-ac35-4c9d-b2d3-afc817a05d3f)
and needs to look like 
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/f06a6f1b-a3d3-4069-9505-44111d06f9fa)
- Fix cards whitespace and add only the black details text
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/8b64c130-7aa5-4ca7-8ddb-20718dddc573)
to 
![image.png](https://images.zenhubusercontent.com/5f9fc280178438084d6cdd61/75dd1d64-f6b2-46fe-8362-96af36327423)
- User cards need padding + ellipsis
- The dot in the tag needs to be pacific blue

## Additional Context
Check the proportions

**Comment by Comoque1** [comment]
Opened a separate [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1598) for the tags.
