### ISSUE TITLE
BUG: Community panel users display on Hub/Challenge/Opportunity, inconsistent with Home Contributors panel for users

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1566]
**Describe the bug**
Community panel users display on Hub/Challenge/Opportunity, inconsistent with Home Contributors panel for users.

**To Reproduce**

1. Go to https://dev.alkem.io/
2. Home Contributors panel for users - shows 2 rows by 6 users per row
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/19e1bb97-e536-4238-9d12-09cffe2a1c85)
3. Go to https://dev.alkem.io/un-sdgs/dashboard
4. Hub Community panel for users - shows 3 rows by 4 users per row (same is experienced on Challenge and Opportunity dashboard pages)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/496517d2-d33b-495d-b85a-7ab417afffad)

**Expected behavior**
The Community users panel on Hub, Challenge and Opportunity dashboard pages, must be same as for home page.

**Comment by techsmyth** [comment]
Moving sprint as will be impacted by orgs as memebers

**Comment by Comoque1** [comment]
Previously, there was requirement for "Contributors" card to have 2 rows by 6 items per row. Now the maximum displayed is 3 rows by 4 items per row. @techsmyth if you accept it like this, we can close the issue.
[Link to Challenge](https://dev.alkem.io/un-sdgs/challenges/food/dashboard) with that amount of users / organizations.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/65c0a9ee-a273-4dd1-892c-7866dc42c227)

**Comment by techsmyth** [comment]
Yes this is fine and the issue can be closed
