### ISSUE TITLE
Spike: Options for client side selection of images with cropping

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1575]
## Description

As a user I want to be easily able to upload my avatar. 

## Acceptance criteria

- [ ] Markdown file with analysis of options for allowing users to easily upload images.
To cover:
- [ ] Try out one or two of components supporting this functionality

## Additional Context
Requirements:
- Restrict to supported file types
- Make it easy for users to select image files locally, and then to resize / crop with selection to the size needed by the server

Separate is the exact format / sizes to be supported. 

Timebox to half a day.

**Comment by atstoyanov** [comment]
Using react-image-crop I was able to crop an image and upload it as an avatar with our current API. 
The Example code is can be found here #1626
![CropAvatar.gif](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/5ecef345-fb32-460a-8b4c-5f6cde4654b4)

**Comment by atstoyanov** [comment]
https://hackmd.io/qn_rlWa7RvKfMniX1qC8eQ
