### ISSUE TITLE
Canvases: Clicking on a template to show the contents scaled to the available space and centered

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1584]
## Description

As a user I want to be able to see the full contents of the template to decide if I want to use it

## Acceptance criteria

- [ ] Contents of the template Canvas to be scaled automatically to fit into the available space for the template preview
- [ ] No box for saving as an image (may not be possible to remove)

Timebox to half a day

## Additional Context
At the moment it is displaying an actual canvas, it could be that an image is created in the background in real time and that is displayed?

**Comment by hero101** [comment]
Blocked due to inability to use Excalidraw's API. A workaround would be copying their code from the codebase.
Also, I have found several issues opened related to this.
excalidraw/excalidraw#3831
excalidraw/excalidraw#3959
excalidraw/excalidraw#3007

**Comment by techsmyth** [comment]
Fixed with zoom + scale extension added in forked version of Excalidraw

**Comment by JainamJhaveri** [comment]
@techsmyth could you provide link to the fork please?

**Comment by hero101** [comment]
@JainamJhaveri 

https://github.com/alkem-io/excalidraw-fork
