### ISSUE TITLE
BUG: (UFT) Links missing on "getting started" card

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1588]
**Describe the bug**
Links missing on "getting started" card.

**To Reproduce**

1. Go to https://acc.alkem.io/ - links are missing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ed1ad003-e81e-4343-b463-6eeb3367b9c3)

**Expected behavior**
There are links on getting started panel.

**Comment by techsmyth** [comment]
Fixed in build for 0.12.2
