### ISSUE TITLE
BUG:(UFT) Settings tab is missing on all entities (Hub/ Challenge, etc..) for Global community admin

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1595]
**Describe the bug**
Settings tab is missing on all entities (Hub/ Challenge, etc..) for Global community admin

**To Reproduce**

1. Authenticate with Global community admin
2. https://acc.alkem.io/valio-hub-test/dashboard
3. Make sure the GCA is not member of the hub community - the user doesn't see the settings tab (this applies for all: Hub/ Challenge / Opportunity)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/184c5d05-0ddf-4d91-a0b6-55359abf5c8f)

**Expected behavior**
Global community admin, can see settings tab for all entities (Hub, Challenge, Opportunity).

**Comment by techsmyth** [comment]
GCA should not see content of a space
