### ISSUE TITLE
UX: Help page explaining the key concepts

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1602]
## Description

As a user I want explanations about the key terms used in Alkemio

## Acceptance criteria

- [ ] A dedicated help page explaining the following key terms that are used: Challenge, Opportunity, Hub, Contributors etc
- [ ] UX design for how this is accessible from the client

https://hackmd.io/pzrSEy5DTmmgD6FToVEpwA
![Schermafbeelding 2022-03-31 om 09.37.01.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/afec157b-bb7e-4edb-9eb5-89804d1c713e)
![Schermafbeelding 2022-03-31 om 09.37.11.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/e88c0264-8896-43c0-85f9-224ab05d95f0)

## Additional Context
Both the question mark top right and the help page link under 'getting started' should lead to this page

**Comment by larssondenise** [comment]
https://hackmd.io/mJOHF3BfSzOdec-9MEfT2Q?both

To review Terminology, Section 6

**Comment by larssondenise** [comment]
![Schermafbeelding 2022-03-17 om 13.52.50.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/edd4bc15-9829-41f1-a7c6-97ca050b2709)
![Schermafbeelding 2022-03-17 om 13.53.59.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/578fcc5b-544b-42b5-8f7a-a27dfb62982b)
