### ISSUE TITLE
BUG: (PROD) Avatar is not displayed on Dashboard updates card

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1609]
**Describe the bug**
Avatar is not displayed on Hub Dashboard updates card

**To Reproduce**

1. Go to https://hub.alkem.io/open-innovation/dashboard - Neil's avatar is not displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e35b3f86-7d4a-407f-9af5-f314c9aedce7)

**Expected behavior**
Avatar is displayed.

**Comment by Comoque1** [comment]
After the latest changes Global admin cannot send an community update
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/841ee508-34ca-4bac-ad11-5feeab9afe6a)

**Comment by atstoyanov** [comment]
@Comoque1 this one is not related to this bug.

**Comment by Comoque1** [comment]
Agree, and the issue from my previous comment is not reproducible. I'll need to follow up on it.
Closing this one.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5c0a8efe-0552-444e-9541-60a7432ff422)
