### ISSUE TITLE
Allow usage of client side image selection for banners, background images

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1628]
## Description

As an challenge / org admin I want to be easily able to select the image portion that I want to use

## Acceptance criteria

- [ ] Allow client side selection of image contents with resizing for banner + bannerNarrow
- [ ] Client to have select + preview after selection
- [ ] Client to have information icon with info on ratio, resolution, where used
- [ ] Refactor into a shared component with parameters?

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b59418a7-c8db-4b4b-b792-c21680910412)

For now create a new link ("Visuals")  at the top level Info section that then allows the selection of visuals similar to the above

**Comment by Comoque1** [comment]
Looks OK on all entities.
Opened a [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1713) for a specific case which is rare,
