### ISSUE TITLE
Lazy loading of data on some tabs

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1649]
## Description

As a user
I want minimal loading times and small bandwidth used
So that the application is more responsive and fast

## Acceptance criteria

- [x] tabs to load its own (full) data only when they are clicked 
 - [x] Community
 - [x] Challenges 
- [x] Challenges query supports two parameters - shuffle and limit
- [x] Dashboard to load only challenges and opportunities that are visualized in the preview box
- [x] Keep it reusable (all the three entities have similar tabs with similar/identical data) 

## Additional Context
At the moment, after the redesign using tabs, every entity page with its tabs (dashboard, context, etc.) is loading all the data for all the tabs at once.

**Comment by techsmyth** [comment]
I just added the opportunities limit/shuffle option under a Challenge so I presume that the loading of the opportunities is still returning all of them...

**Comment by Comoque1** [comment]
Pressing "Create discussion" button, doesn't trigger request, hence discussion cannot be created vie the client.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f1ba553-2f0d-4d2b-9558-7dbaabda757e)

**Comment by Comoque1** [comment]
The following is observed on DEV env.

- [ ] **Hub**
  - [ ] Dashboard page: `hubCommunity` and `userAvatars` are **performed twice**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/be704b4f-a73a-4cc5-b19c-d6f29aa6998a)
  - [x] Context: **OK**
  - [x] Community: **OK**
  - [x] Challenges: **OK**
  - [ ] Discussions: when selecting the tab **no** requests are sent??
  - [x] Canvases: **OK**

- [ ] **Challenge**
  - [x] Dashboard page: **OK**
  - [x] Context: **OK**
  - [x] Community: **OK**
  - [ ] Opportunity: when selecting the tab **no** requests are sent??
  - [x] Discussions: **OK**
  - [ ] Canvases: hubCanvases and challengeCanvases are requested??

- [ ] **Opportunity**
  - [ ] Dashboard page: `opportunityCommunity` and `userAvatars` are **performed twice**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a9b56cc2-a1e3-46d7-b83e-f98b42bd5415)
  - [ ] Context: when selecting the tab **no** requests are sent??
  - [x] Community: **OK**
  - [ ] Projects: when selecting the tab **no** requests are sent??
  - [ ] Canvases: hubCanvases, challengeCanvases and opportunityCanvases are requested??

**Comment by techsmyth** [comment]
Re canvases, templates are inherited - hence the parent canvas requests...
