### ISSUE TITLE
Cookie consent to use the new theme

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1651]
## Description

As a user
I want a consistent theme across the application
So that everything is consistent

## Acceptance criteria

- [ ] Cookie consent component to inherit the application theme

## Additional Context
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/0df3ffed-7eea-493d-abb0-c9125f812b68)

**Comment by Comoque1** [comment]
Looks OK on DEV env.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/419dea5c-e296-452e-a6f7-a42d19af2d37)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2f47f198-232c-41bb-be99-11307d9ffc4e)
