### ISSUE TITLE
Excalidraw: icons not appearing; libraries not working

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#1698]
## Description

As a user I want to be able to use the Excalidraw libraries + latest functionality

## Acceptance criteria

- [ ] Use Excalidraw release that has the fixes required.

## Additional Context
Raised at https://github.com/excalidraw/excalidraw/issues/4578 - we need to upgrade to a later release to fix. Issue is that they have not released in a while.

**Comment by hero101** [comment]
Fixe with #1778.
