### ISSUE TITLE
BUG: Breadcrumbs not updating correctly after router v6

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1701]
**Describe the bug**
Breadcrumbs are not being updated correctly after the migration to router v6

**To Reproduce**

1. Go to several pages
2. The breadcrumbs are not updated correctly

**Expected behavior**
The breadcrumbs are updated to display correctly but do not yet have to be clickable.

**Comment by Comoque1** [comment]
Opportunities are missing on the breadcrumb
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b5bf8750-6417-4ae2-a007-2c296b2c7c1c)
