### ISSUE TITLE
BUG: Lack of visible differentiation on hub / challenge / Opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1703]
**Describe the bug**
Users are confused about where they are when they navigate from hub to a challenge as the visual layout is not sufficiently different

**To Reproduce**
1. Navigate to a hub
2. Navigate to a Challenge by clicking on a card in the hub
The only thing that visibly changes is the breadcrumb, whilst other items (such as Dashboard, Home) that are visually grabbing do not change.

**Expected behavior**
The Dashboard tab on a Challenge to have the  type name i.e. "Challenge"

The Dashboard tab on a Opportunity to have the  type name i.e. "Opportunity"

Note: this was **very** strong feedback from UWV.

Design: https://xd.adobe.com/view/b6f9e4f6-a293-4498-80d7-2d51a42e568a-e3aa/

**Comment by me-andre** [comment]
Do we need to update the icons to match the design?

**Comment by techsmyth** [comment]
No, enough for now ro simple update the text labels

**Comment by Comoque1** [comment]
Looks OK, based on AC on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/833e8ce5-f9c9-4f27-aacb-b8cdf765a7b1)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/28eed1d9-f481-4e00-8cab-c1a5d2289f67)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4b9f74d-34f0-40e7-980b-a2f7a67a3da8)
