### ISSUE TITLE
BUG: (PROD) Image on dashboard/updates area is not wrapped

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1705]
**Describe the bug**
(PROD) Image on dashboard/updates area is not wrapped.

**To Reproduce**

1. Go to https://hub.alkem.io/source2gather/challenges/floods/opportunities/mural/dashboard
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/62c22ea1-182c-447d-b618-d5749b10b33f)

**Expected behavior**
Image is wrapped within "updates" container.

**Comment by techsmyth** [comment]
@hoyterutteman I recall you encountered this one. Can you please re-check it?

**Comment by Comoque1** [comment]
The issue on production is resolved (suspect by image resize).
The issue still exists with large images (tested on dev env: https://dev.alkem.io/un-sdgs/challenges/food/dashboard) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b051eefd-095b-41fc-810b-a0c2922fa3da)
https://ichef.bbci.co.uk/news/976/cpsprodpb/13541/production/_124296197_3_chen-ying_traditional-skill_hi-res_credited.jpg
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dedf335f-f92d-4780-a64b-334a297f08f1)

On `entity / community` page the same image the user must scroll to see different parts of it.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3ed47cb4-c337-4780-af07-6951362586f5)
