### ISSUE TITLE
UX: Design for admin on hubs / challenges / opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1710]
## Description

As an admin I want the settings of a hub / challenge / opportunity to have a similar layout to user / org settings

## Acceptance criteria
- [ ] Brainstorm session to bring everyone onto the same page
- [ ] Move to a set of tabs for the settings
- [ ] Tabs to include: context, visuals, community (users list + applications + groups), challenges (on hub, opportunities on challenge etc), updates,  authorization

## Additional Context
TBD - where to put applications?
TBD - what happens with groups + editing?

Current design on hub.alkem.io
![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/e772170f-12b3-489e-901d-7a1f090a5390)

Current design with initial tabs as mentioned in Miro board below
https://xd.adobe.com/view/450cbff7-db30-4605-82ba-b1a206944fd4-105f/

New design for the admin "landingpage" as mentioned in Neil's comment
https://xd.adobe.com/view/4619358f-3203-401a-a44f-0ed50c6c47f8-134a/

Brainstorm session: 
https://miro.com/app/board/o9J_lD_WKG4=/

**Comment by techsmyth** [comment]
@KayleeS96 thanks for the update, looks really nice in this form! 

I have put comments into the XD file directly and will bring it back as there are some updates based on my comments.

**Comment by techsmyth** [comment]
@KayleeS96 @Roseghost realized that we also need to take the admin landing page into this design: 

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/64eacee2-b44a-4838-ba6a-65378fe7f97c)

I would suggest just having 4 tabs: hubs, users, organizations, authorization - and then simply as a first pass moving the existing UI over.

**Comment by KayleeS96** [comment]
@techsmyth I have updated the design and added a new design for the admin "landingpage" as you mentioned above
