### ISSUE TITLE
BUG: Users editing via the admin panel is not showing the option to update the avatar (for other users)

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1713]
**Describe the bug**

**To Reproduce**

1. Go to https://test.alkem.io/admin/users/405f6f8b-fb5a-4ef3-b695-e010037d9ec1/edit
2. Authenticate with GA
3. Navigate to other user profile on admin page - "edit avatar" button and box are missing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/26ad2e77-26ad-4a08-914b-e79b708633fd)

**Expected behavior**
GA and GCA can see and are able to update other users avatars.

**Comment by Comoque1** [comment]
Functionally works OK on test env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a1843c84-27e9-4f7a-89c4-d73a767ca0a5)

The "EDIT" button, is with layout.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1963d10f-893a-4515-8c29-542a973a7c9a)

@techsmyth, if you accept it like that, we can close the issue.

**Comment by techsmyth** [comment]
Yes the new edit option is fine. We will probably later need to do a bit of a cleanup across the application for consistency.
