### ISSUE TITLE
Aspects: Creation of aspects

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1717]
## Description
As a user I want to be able to share information relevant to a particular Hub / Challenge / Opportunity

## Acceptance criteria
- [x] If a user has the "CREATE_ASPECT" privilege from the Context.authorization.myPrivileges, then show the user the "Create Aspect" button
- [x] The set of allowed Aspect types to be picked up from the current template data. This template is shared across all Aspects creation for now. Query: configuration { templates { opportunities { aspects } } } } 
- [x] User is able enter a title, nameID, provide a description, enter a set of tags
- [x] Add text to explain to users when after creation they will be able to add visuals, references after Aspect is created. Placeholder label above the buttons for now. 
- [x] Provide а button: "Create" which creates the aspect and closes the dialog

Note: the following are out of scope for this card: references, canvases. 

## Additional Context
https://xd.adobe.com/view/7c98070c-f9d6-425a-8e0d-aa54f4fc3758-29cb/

**Comment by Comoque1** [comment]
User without privileges to create aspect on opportunity has the "create" button visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d5449545-b670-4266-9dab-317b3fe1e1a3)

The following 2 points are not implemented/visible
- [ ] Add text to explain to users when after creation they will be able to add visuals, references after Aspect is created. Placeholder label above the buttons for now. 
- [ ] Provide two buttons: "Create" (brings the user back to the Aspects control), "Create and edit further" (brings the user to the settings tab)
