### ISSUE TITLE
Address package dependency warnings

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1724]
## Description

As a service manager I want a secure application

## Acceptance criteria

- [ ] Address the high priority package warnings that are being given by npm. 
- [ ] Identify what packages we explicitly depend on generate the high priority warnings.

## Additional Context

Timebox to 2 hours

neil@linux-laptop ~/Documents/Dev_Alkemio/client-web (client-1712)$ npm audit fix
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: postcss-loader@4.3.0
npm WARN Found: postcss@7.0.39
npm WARN node_modules/postcss
npm WARN   postcss@"^7.0.35" from resolve-url-loader@4.0.0
npm WARN   node_modules/resolve-url-loader
npm WARN     resolve-url-loader@"^4.0.0" from react-scripts@5.0.0
npm WARN     node_modules/react-scripts
npm WARN   11 more (@storybook/builder-webpack4, autoprefixer, css-loader, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer postcss@"^7.0.0 || ^8.0.1" from postcss-loader@4.3.0
npm WARN node_modules/@storybook/builder-webpack4/node_modules/postcss-loader
npm WARN   postcss-loader@"^4.2.0" from @storybook/builder-webpack4@6.4.17
npm WARN   node_modules/@storybook/builder-webpack4
npm WARN 
npm WARN Conflicting peer dependency: postcss@8.4.5
npm WARN node_modules/postcss
npm WARN   peer postcss@"^7.0.0 || ^8.0.1" from postcss-loader@4.3.0
npm WARN   node_modules/@storybook/builder-webpack4/node_modules/postcss-loader
npm WARN     postcss-loader@"^4.2.0" from @storybook/builder-webpack4@6.4.17
npm WARN     node_modules/@storybook/builder-webpack4
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
npm WARN Found: webpack@4.46.0
npm WARN node_modules/@storybook/react/node_modules/webpack
npm WARN   webpack@"4" from @storybook/react@6.4.17
npm WARN   node_modules/@storybook/react
npm WARN     dev @storybook/react@"^6.4.12" from the root project
npm WARN     2 more (@storybook/preset-create-react-app, @storybook/addon-docs)
npm WARN   2 more (@storybook/react-docgen-typescript-plugin, terser-webpack-plugin)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@">= 4" from @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
npm WARN node_modules/@storybook/react/node_modules/@storybook/react-docgen-typescript-plugin
npm WARN   @storybook/react-docgen-typescript-plugin@"1.0.2-canary.253f8c1.0" from @storybook/react@6.4.17
npm WARN   node_modules/@storybook/react
npm WARN 
npm WARN Conflicting peer dependency: webpack@5.68.0
npm WARN node_modules/webpack
npm WARN   peer webpack@">= 4" from @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
npm WARN   node_modules/@storybook/react/node_modules/@storybook/react-docgen-typescript-plugin
npm WARN     @storybook/react-docgen-typescript-plugin@"1.0.2-canary.253f8c1.0" from @storybook/react@6.4.17
npm WARN     node_modules/@storybook/react

added 333 packages, removed 84 packages, changed 56 packages, and audited 4002 packages in 33s

483 packages are looking for funding
  run `npm fund` for details

# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install node-sass@7.0.1, which is a breaking change
node_modules/libnpx/node_modules/ansi-regex
node_modules/libnpx/node_modules/cliui/node_modules/ansi-regex
node_modules/libnpx/node_modules/wrap-ansi/node_modules/ansi-regex
node_modules/libnpx/node_modules/yargs/node_modules/ansi-regex
node_modules/log-update/node_modules/ansi-regex
node_modules/sass-graph/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/libnpx/node_modules/cliui/node_modules/strip-ansi
  node_modules/libnpx/node_modules/strip-ansi
  node_modules/libnpx/node_modules/wrap-ansi/node_modules/strip-ansi
  node_modules/libnpx/node_modules/yargs/node_modules/strip-ansi
  node_modules/log-update/node_modules/strip-ansi
  node_modules/sass-graph/node_modules/strip-ansi
    cliui  4.0.0 - 5.0.0
    Depends on vulnerable versions of strip-ansi
    Depends on vulnerable versions of wrap-ansi
    node_modules/libnpx/node_modules/cliui
    node_modules/sass-graph/node_modules/cliui
      yargs  10.1.0 - 15.0.0
      Depends on vulnerable versions of cliui
      Depends on vulnerable versions of string-width
      node_modules/libnpx/node_modules/yargs
      node_modules/sass-graph/node_modules/yargs
        libnpx  10.2.4
        Depends on vulnerable versions of yargs
        node_modules/libnpx
          mrm  >=3.0.0
          Depends on vulnerable versions of libnpx
          node_modules/mrm
            @mapbox/rehype-prism  >=0.8.0
            Depends on vulnerable versions of mrm
            node_modules/@mapbox/rehype-prism
              @uiw/react-markdown-preview  >=3.3.4
              Depends on vulnerable versions of @mapbox/rehype-prism
              node_modules/@uiw/react-markdown-preview
                @uiw/react-md-editor  >=3.6.5
                Depends on vulnerable versions of @uiw/react-markdown-preview
                node_modules/@uiw/react-md-editor
        sass-graph  2.2.5 || 3.0.5
        Depends on vulnerable versions of yargs
        node_modules/sass-graph
          node-sass  4.14.1 - 7.0.0
          Depends on vulnerable versions of sass-graph
          node_modules/node-sass
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/libnpx/node_modules/cliui/node_modules/string-width
    node_modules/libnpx/node_modules/string-width
    node_modules/libnpx/node_modules/wrap-ansi/node_modules/string-width
    node_modules/libnpx/node_modules/yargs/node_modules/string-width
    node_modules/log-update/node_modules/string-width
    node_modules/sass-graph/node_modules/string-width
      widest-line  2.0.0 - 2.0.1
      Depends on vulnerable versions of string-width
      node_modules/libnpx/node_modules/widest-line
        boxen  1.3.0 - 3.2.0
        Depends on vulnerable versions of widest-line
        node_modules/libnpx/node_modules/boxen
      wrap-ansi  3.0.0 - 6.1.0
      Depends on vulnerable versions of string-width
      Depends on vulnerable versions of strip-ansi
      node_modules/libnpx/node_modules/wrap-ansi
      node_modules/log-update/node_modules/wrap-ansi
      node_modules/sass-graph/node_modules/wrap-ansi
        log-update  2.1.0 - 3.4.0
        Depends on vulnerable versions of wrap-ansi
        node_modules/log-update
          listr-update-renderer  >=0.5.0
          Depends on vulnerable versions of log-update
          node_modules/listr-update-renderer
            @graphql-codegen/cli  <=1.8.4-alpha-ff40af04.41 || >=1.9.1-alpha-01fa8c2d.10
            Depends on vulnerable versions of listr-update-renderer
            node_modules/@graphql-codegen/cli
            listr  >=0.14.3
            Depends on vulnerable versions of listr-update-renderer
            node_modules/listr

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install gulp@3.9.1, which is a breaking change
node_modules/cpy/node_modules/glob-parent
node_modules/glob-stream/node_modules/glob-parent
node_modules/glob-watcher/node_modules/glob-parent
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/glob-watcher/node_modules/chokidar
  node_modules/watchpack-chokidar2/node_modules/chokidar
    glob-watcher  >=3.0.0
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/@storybook/react/node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/@storybook/react/node_modules/webpack
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/cpy/node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/cpy/node_modules/globby
      cpy  >=7.0.0
      Depends on vulnerable versions of globby
      node_modules/cpy
  glob-stream  5.3.0 - 6.1.0
  Depends on vulnerable versions of glob-parent
  node_modules/glob-stream
    vinyl-fs  >=2.4.2
    Depends on vulnerable versions of glob-stream
    node_modules/vinyl-fs
      gulp  >=4.0.0
      Depends on vulnerable versions of vinyl-fs
      node_modules/gulp

nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          Depends on vulnerable versions of resolve-url-loader
          node_modules/react-scripts

postcss  <8.2.13
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/postcss
  @storybook/builder-webpack4  *
  Depends on vulnerable versions of postcss
  node_modules/@storybook/builder-webpack4
    @storybook/addon-docs  *
    Depends on vulnerable versions of @mdx-js/mdx
    Depends on vulnerable versions of @storybook/builder-webpack4
    Depends on vulnerable versions of @storybook/csf-tools
    Depends on vulnerable versions of @storybook/react
    node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs
      @storybook/addon-essentials  >=6.2.0-alpha.0
      Depends on vulnerable versions of @storybook/addon-docs
      node_modules/@storybook/addon-essentials
    @storybook/core-server  *
    Depends on vulnerable versions of @storybook/builder-webpack4
    Depends on vulnerable versions of @storybook/manager-webpack4
    node_modules/@storybook/core-server
      @storybook/core  >=6.2.0-alpha.0
      Depends on vulnerable versions of @storybook/core-server
      node_modules/@storybook/core
        @storybook/react  >=6.2.0-alpha.0
        Depends on vulnerable versions of @storybook/core
        node_modules/@storybook/react
  autoprefixer  1.0.20131222 - 9.8.8
  Depends on vulnerable versions of postcss
  node_modules/autoprefixer
  css-loader  0.15.0 - 4.3.0
  Depends on vulnerable versions of icss-utils
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of postcss-modules-values
  node_modules/@storybook/builder-webpack4/node_modules/css-loader
  node_modules/@storybook/manager-webpack4/node_modules/css-loader
    @storybook/manager-webpack4  *
    Depends on vulnerable versions of css-loader
    node_modules/@storybook/manager-webpack4
  icss-utils  <=4.1.1
  Depends on vulnerable versions of postcss
  node_modules/icss-utils
    postcss-modules-local-by-default  <=4.0.0-rc.4
    Depends on vulnerable versions of icss-utils
    Depends on vulnerable versions of postcss
    node_modules/postcss-modules-local-by-default
    postcss-modules-values  <=4.0.0-rc.5
    Depends on vulnerable versions of icss-utils
    Depends on vulnerable versions of postcss
    node_modules/postcss-modules-values
  postcss-flexbugs-fixes  <=4.2.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-flexbugs-fixes
  postcss-modules-extract-imports  <=2.0.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-extract-imports
  postcss-modules-scope  <=2.2.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-scope
  resolve-url-loader  0.0.1-experiment-postcss || 3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader
    react-scripts  >=2.1.4
    Depends on vulnerable versions of @svgr/webpack
    Depends on vulnerable versions of resolve-url-loader
    node_modules/react-scripts

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
fix available via `npm audit fix --force`
Will install @storybook/addon-essentials@6.1.21, which is a breaking change
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/remark-parse
    @mdx-js/mdx  <=2.0.0-next.8
    Depends on vulnerable versions of remark-mdx
    Depends on vulnerable versions of remark-parse
    node_modules/@mdx-js/mdx
      @mdx-js/loader  0.15.5 - 1.6.22
      Depends on vulnerable versions of @mdx-js/mdx
      node_modules/@mdx-js/loader
      @storybook/addon-docs  *
      Depends on vulnerable versions of @mdx-js/mdx
      Depends on vulnerable versions of @storybook/builder-webpack4
      Depends on vulnerable versions of @storybook/csf-tools
      Depends on vulnerable versions of @storybook/react
      node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs
        @storybook/addon-essentials  >=6.2.0-alpha.0
        Depends on vulnerable versions of @storybook/addon-docs
        node_modules/@storybook/addon-essentials
      @storybook/csf-tools  *
      Depends on vulnerable versions of @mdx-js/mdx
      node_modules/@storybook/csf-tools
    remark-mdx  <=1.6.22
    Depends on vulnerable versions of remark-parse
    node_modules/remark-mdx

60 vulnerabilities (41 moderate, 19 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
neil@linux-laptop ~/Documents/Dev_Alkemio/client-web (client-1712)$ npm install

up to date, audited 4002 packages in 16s

483 packages are looking for funding
  run `npm fund` for details

60 vulnerabilities (41 moderate, 19 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by valentinyanakiev** [comment]
After running `npm audit fix -force`:

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/680fd902-9aea-4592-b75c-02677415c8dc)

**Comment by valentinyanakiev** [comment]
More issues than before... Dropping this story.

**Comment by techsmyth** [comment]
The story was to address the warnings, not to run npm audit fix. Please re-open.
