### ISSUE TITLE
Email verification Page: Additional explainer e.g. token expired page message to be clearer

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1734]
## Description

As a user I want to know what is expected of me when the email verification token is expired

## Acceptance criteria

- [ ] Verification page to provide additional feedback for users and give "friendly" error message
- [ ] Message to be "Token has expired. Please enter your email again"

## Additional Context
- This scenario is actually quite likely to happen in the UWV environment due to the usage of Citrix there. 
- You can access the page via http://localhost:3000/identity/verify
- In the red box below an error of kind "token has expired 20000 seconds ago" is reported, which is not very user friendly

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/49fdc372-a9e6-4ab6-b79b-89733cfe42b9)

**Comment by me-andre** [comment]
Hey! Does anyone have ideas how to trigger token expiration programmatically? Thanks!

**Comment by me-andre** [comment]
I wanted to do that just to be able to find where the message comes from. But @Comoque1  has already explained me how to trigger it.

**Comment by me-andre** [comment]
Please have a look at the PR
https://github.com/alkem-io/client-web/pull/1808

I introduced a special map between Kratos message codes and corresponding i18n labels. But we may consider putting Kratos codes in translations directly and using t.exists() to check if the mapping exists.

**Comment by Comoque1** [comment]
There is typo in the message:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/52487f42-1584-4c17-88ea-691da03e88c2)
Also the recovery flow message is the old one.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9733f72f-e48b-4bca-9943-824b666f5783)

We discussed it with me-andre, and he is going to address it.
Moving this item back to backlog.
