### ISSUE TITLE
Aspects: help to guide the user

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1736]
## Description

As a user I want to know what the fields I am being asked to enter are used for

## Acceptance criteria

- [ ] Add help icon to the fields on the create flow (type, nameID, description, ...)
- [ ] Display the tags section with the label "Tags" and not the name of the tagset

**Comment by Comoque1** [comment]
All looks good on DEV env. The only adjustment that is needed is the text from the help icons to be updated.
