### ISSUE TITLE
Aspects: UI tidy up

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1742]
## Description

As a user I want the experience to be clean

## Acceptance criteria

- [x] No longer ask the user to supply the nameID: remove the form field and do not specify this parameter in the mutation call or on summary panel.
- [x] Make the create button filled (so similar to the "Apply" button)
- [x] Allow members to add comments (check the "CREATE_COMMENTS" privilege)
- [ ] The aspect type should be visible on the aspect dashboard

**Comment by valentinyanakiev** [comment]
There is an issue with the nameID validation on CreateAspectOnContextInput, the nameID on CreateNameableInput is mandatory field and has a min length of 3. It is not provided by the mutation now.

**Comment by techsmyth** [comment]
This field is overridden I thought by having the same field name on the derived class?
