### ISSUE TITLE
BUG: "Interested in collaborating" button is confusing if you are already a member

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1743]
**Describe the bug**
User was suprised to still see this button after he was already a member of the Opportunity.

**Expected behavior**
- [ ] Do not show this button if the user is a member of the Opportunity

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f40992a1-fe8e-4455-bd90-bfdd79a37ec2)

**Comment by Comoque1** [comment]
The story is addressed and verified on DEV env.
Added another story, to add label "Member", when the user is a member: Add label on opportunity, when a user is Member #2203
