### ISSUE TITLE
Aspect details: display the user, created date

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1745]
## Description
As a user I want to see the type of the aspect, and to see who created it

## Acceptance criteria
- [x] The avatar of the user that created the aspect should be visible
- [x] The created date should be visible 

## Additional Context

Preference is the first one below:

![image](https://user-images.githubusercontent.com/5598831/153423878-ff6ed384-7883-4170-9a47-4c2bab0edeb4.png)

Link: https://xd.adobe.com/view/906d23e9-8d7b-4e0a-88ca-2a2156296596-c53e/ 

Update (21-02-2022):

On the aspect cards:
![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/2f330092-9ea9-4870-b942-a8acef501110)

On the aspects context page:
![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/f49cf44b-50c2-4096-9a44-9d2ecca3f044)

**Comment by Roseghost** [comment]
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/98bb80fc-26a1-45ef-ae5a-efc495c2f7c6)

Takes less space in in top right and still gives the needed data

**Comment by techsmyth** [comment]
Captured on dev backlog as #1792
