### ISSUE TITLE
BUG: Authentication form is failing to load on the client on DEV env.

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1760]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/identity/login
2. The authentication / Sign-up forms are not loading
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c557435d-7d44-4de1-acc6-48d193cbd2f0)

The issue is reproducible only on DEV environment!

**Expected behavior**
Authentication form is loading. and user can sign in/up successfully.

**Comment by valentinyanakiev** [comment]
Can not reproduce - tried with multiple accounts and seems fine
