### ISSUE TITLE
Bug: Unable to remove an aspect using the client

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1768]
## Description

As a User I want to be able to remove aspects.

## Acceptance criteria

- [x] "Remove aspect" button is available on the client.
- [x] The following users are able to see and click on "remove aspect" button: 
  - [x] GA can remove all aspects
  - [x] Community admin: can remove all aspects from its level and levels below (i.e. Challenge admin can remove challenge and opportunity aspects)
  - [x] Community member: can remove only its aspects and doesn't see "remove aspect" button for the rest of the aspects
  - [x] Anonymous user doesn't see "remove aspect" button anywhere

**Comment by Comoque1** [comment]
Following to our discussion from the daily, it seems that the authorization on api level is correctly applied.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b3effe2e-e7bf-4f8e-911c-b14e64ef726b)

**Comment by hero101** [comment]
Bear in mind that when you create an aspect you no longer have the Aspect card immediately.
This will be addressed in [1944](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1944)
