### ISSUE TITLE
BUG: subscription for all updates being triggered repeatedly

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1774]
**Describe the bug**
As one navigates around the client the subscription for updates is repeatedly triggered. 

**To Reproduce**
Ensure subscriptions logging to file is enabled on the server, and that subscriptions are enabled
Navigate into multiple hubs on the client
Each time a hub is entered the updates subscription is re-establised.

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/bc5faff2-8e4a-4d03-8683-5fc25f4ae727)

**Expected behavior**
The updates subscription should trigger once and remain active.

**Comment by hero101** [comment]
I have navigated to multiple hubs and:
- no such logs are produced
- breakpoints (on the server) break just once per application init
- client network tab shows a subscription just once

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/e163095d-cd1a-4d8f-ac19-0c78bd61ef74)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/f905950c-95d6-445c-9a0b-a18a06ed7701)

**Comment by techsmyth** [comment]
Also just tried it out, and this issue has been resolved. Am no longer seeing multiple updates subscriptions being triggered :)
