### ISSUE TITLE
BUG: When two users work simultaneously on canvas it becomes in invalid state

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1779]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs2/canvases
2. On 2 browsers authenticate with 2 users and navigate to the page above
3. One of the user creates a canvas
4. Both user must have the canvas open
5. I.e. User1 makes an update
6. User1 saves the change and stops editing, very fast the User2 clicks on Edit button - error is thrown and the canvas becomes locked for both users.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a17b7c43-ee4f-4f81-90b0-56a00ecd9cc8)

**Expected behavior**
Canvas doesn't reach state, where none is unable to update it and to check it in.

**Comment by Comoque1** [comment]
> Hi Evgeni, good to hear it happens much less now. What would be very useful is when you do hit the problem that you capture the exact state of the canvas i.e. the current state, who it is checked out by etc.
> 
> Also after it has happened, does the refresh page fix the issue or does it persist?

The state is : 
```
status: "CHECKED_OUT"
lockedBy: ""
```
Refreshing, doesn't fix the issue.
![image](https://user-images.githubusercontent.com/23620658/175310177-d1f2e665-4eba-4fb6-b662-598588a93fc8.png)

**Comment by techsmyth** [comment]
@Comoque1 can you please do one more test: are you able to via the graphql api submit in a request to checkin the canvas?

**Comment by Comoque1** [comment]
Tested checking in a canvas with locked state (using GA account) and worked successfully.
As mentioned above, with latest changes, locking canvas, happens much less and will close the existing issue.

Raised [another issue](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2243) as a placeholder to investigate further
