### ISSUE TITLE
[Spike] Remove nested routes where not neccessery

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1781]
## Description

As a user
I want less bandwidth and loading times
So that the application consumes less data and loads faster

## Acceptance criteria

- [ ] Remove nested routes where not necessary

## Additional Context
Right now at least the tabs are using a lot of nestings on the three entity levels, which means all the data needed for that entity level is loaded without use. 

The query list going directly to the opportunity dashboard
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/84de78c2-2e15-44c4-8660-b3bf8b974d19)

Timebox to half a day

**Comment by hero101** [comment]
The number of requests and amount of data will be further reduced in #1780.

**Comment by Comoque1** [comment]
Bringing back to backlog with initial set of issues:
1. Created challenges discussions are not displayed on Challenge Dashboard page.
2. Creating discussion and navigating back to entity dashboard page throws error in browser console
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e2202468-d0cd-4616-98a2-9a1a2f5d15fa)
