### ISSUE TITLE
Extend user sessions

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1785]
As a user I want that my tokens are refreshed so that I do not have to login daily.

## Acceptance criteria
- [ ] The kratos session is extended silently

## Additional information

Implemented in our Kratos version:
https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions

**Comment by hero101** [comment]
The session is correctly extended.
The cookie is not refreshed and/or the old cookie is taken with higher priority.
