### ISSUE TITLE
BUG: When user navigate to `./organizations/new` organizationProfileInfo query is performed and fails

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1799]
**Describe the bug**

**To Reproduce**

1. Authenticate with GA and navigate to http://localhost:3000/admin/organizations/new 
2. Error is thrown on browser dev tools: `"message": "Variable \"$id\" got invalid value \"\"; Expected type \"UUID_NAMEID\". ID not a valid UUID or NameID: ",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/367c912a-3d02-4c70-8f7f-9862d97fa156)

**Expected behavior**
No queries are submitted that return an error.

**Comment by ccanos** [comment]
@Comoque1 I think this is not happening anymore
