### ISSUE TITLE
UX: Design for how the interaction goes for users that can directly join a community

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1817]
## Description

As a user I want to be able to directly join a community

## Acceptance criteria

- [ ] UX design for how users join a community

## Additional Context
https://hackmd.io/8AhEJtZiRlG_wiVFFu8WRw

Design for joining a hub: https://xd.adobe.com/view/fed146e0-57f9-4380-9b65-c288c53032a5-ab82/

Design for joining a challenge: https://xd.adobe.com/view/17585701-b59f-44ce-8102-2c71d1957912-420b/

**Comment by KayleeS96** [comment]
@techsmyth have uploaded a first version for the interaction with a popup/overlay

**Comment by techsmyth** [comment]
Thanks @KayleeS96  - popup looks good. However the Join actually should be basically replacing the current Apply button that is there on a Hub or Challenge. It for now should **not** be on an organization. Can you update the design (and Monday is fine!) to have the design based on the Hub / Challenge pages?

**Comment by KayleeS96** [comment]
@techsmyth I have updated the design to now have a hub and challenge version. The text in the popup can obviously be changed to fit the hub.
