### ISSUE TITLE
UX: Design for Contribute Tab

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1843]
## Description

As a user I want to know how I can contribute
As a developer, I want to understand the design

## Acceptance criteria

- [ ] Contribute Tab next to Community

## Additional Context
Link to design: https://xd.adobe.com/view/e22b9ea9-c3d2-4de8-bd0e-890c886472ca-b778/

**Comment by KayleeS96** [comment]
@techsmyth have made a first design, link to the design will be posted later (Rose has to create the link)

**Comment by techsmyth** [comment]
@KayleeS96 Great, thanks! Only comment on it is that there needs to be some text before the aspects section to explain the purpose of the tab, but this is already sufficient!

**Comment by KayleeS96** [comment]
@techsmyth Have updated the design to have the text, which obviously can be altered to have the right text

**Comment by techsmyth** [comment]
Thanks @KayleeS96  - great to have this ready to go into the development
