### ISSUE TITLE
Aspect creation flow to also allow adding of card banner visual

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1850]
## Description

As a user when creating an aspect I want to also be able to add the card banner visual as a 4th step in the flow

## Acceptance criteria

- [x] Aspect creation flow extended to allow the user to also add card banner visual

## Additional Context
- New sentence at the bottom of step 3 (as partly moved to 4)
https://xd.adobe.com/view/80e10380-d82b-427b-93ff-84bcf3480d06-d5b2/

**Comment by Comoque1** [comment]
Tested OK on Test env with the related client-web branch.
