### ISSUE TITLE
direct community joining actions

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1855]
## Description

As a user I want the option to be able to directly join a community
As a Hub admin I want to ensure that people that join the community agree to the terms of that community

## Acceptance criteria
- [ ] Button text: Check for the privileges held by a user for a community. 

**Join:** 
- [ ] If the "COMMUNITY_JOIN" privilege is present then display "Join" as the text on the button
- [ ] If the user clicks Join then they should be presented with a popup, similar to the current "Apply" popup without the questions, whereby they see following text: "You are able to directly join this community. By clicking Submit you become a member of this community and are able to contribute to it." 
- [ ] On clicking submit the "joinCommunity" mutation is sent

**Apply:**
- [ ] If the "COMMUNITY_APPLY" privilege is present then the logic re the text and screens shown the user is as before

**No privilege:**
- [ ] If the user is logged in but does not have the "COMMUNITY_APPLY" privilege, then the text displayed should state "Applications not enabled"

## Additional Context
Design for joining a hub: https://xd.adobe.com/view/fed146e0-57f9-4380-9b65-c288c53032a5-ab82/
Design for joining a challenge: https://xd.adobe.com/view/17585701-b59f-44ce-8102-2c71d1957912-420b/
[Client logic for membership](https://github.com/alkem-io/alkemio/blob/develop/docs/community-membership.md#client-logic)

**Comment by hero101** [comment]
- The checkbox for accepting the terms and the text about the terms before it are not included, because we currently can't provide terms and conditions for the specific community.

**Comment by hero101** [comment]
https://hackmd.io/ZTfUQHTUT72oydUcedFhYw
https://github.com/alkem-io/alkemio/blob/develop/docs/community-membership.md#client-logic
