### ISSUE TITLE
Migrate to tabbed interface for admin back end

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1858]
## Description

As a user I want a consistent interface

## Acceptance criteria

- [ ] Migrate the main admin landing page to be tabbed, with four tabs: hubs, users, organizations, authorization
- [ ] Data per tab should only be loaded when the tab is chosen. Default tab is Hubs.
- [ ] Breadcrumb to reflect the chosen tab
- [ ] Structure the code around the admin top level tabs

**Comment by me-andre** [comment]
I intentionally did not optimize the structure of AdminAuthorizationPage cause the page consists of just 2 buttons and looks like a very temporary solution that would likely be replaced with a properly designed one.
