### ISSUE TITLE
Improve NL translations on home page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1861]
## Description

As a User, I want to have all NL translation on home page.

## Acceptance criteria

- [ ] ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/45b8660a-eb31-4187-99c8-d1c591d78ffc)

- [ ] ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3743f28b-b69e-4064-9f2e-b73dcfa0b971)

- [ ] Challenge and opportunity in English
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/83f58d24-1f1e-440e-a700-827afbd97462)

- [ ] ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/33db4500-3c4d-47b8-b5de-cb52c5667ffe)

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by hoyterutteman** [comment]
Regarding the first one, I will change the text such that it will fit nicer. This should be:

Drijft u innovatie binnen uw gemeenschap of organisatie?
Neem contact op zodat we een 1-op-1 sessie kunnen plannen!

**Comment by hoyterutteman** [comment]
Some of the Dutch translations are not coming through. See bug named: "BUG: Translation to Dutch not fully working"

**Comment by techsmyth** [comment]
@larssondenise this looks like a duplicate?

**Comment by larssondenise** [comment]
@techsmyth checked
