### ISSUE TITLE
BUG: Account not positioned correctly in top bar

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#1867]
**Describe the bug**
The user account component in the topmost bar on the right side is not properly aligned with the rest of the content.
This may be due to shorter names or something in the layout that has changed recently.

**To Reproduce**

1. Log in to the application
2. Observe the account component alignment

**Expected behavior**
The component is aligned correctly with the rest of the content.![image.png]
If not enough space then the search bar should shrink. 
Display name should be truncated to available width of the container: a % of the screen width. (approx 25 characters).

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/48c5a90c-be9c-4f68-a8ea-1cb658c602ec)

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/bd6233da-7399-4ef4-a222-5410ed27c2bb)

**Comment by techsmyth** [comment]
It is related to the length of the name:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/33515afb-6afd-4f65-9282-44f6e310c66e)

A longer name pushes it beyond the edge, this is a bug...

**Comment by Comoque1** [comment]
Looks OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a43d4a36-9d01-4447-b2c3-24946899d4d7)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a92d4063-19a3-46ff-8d9b-c132d3c11928)
