### ISSUE TITLE
BUG: User, "My membership" page, doesn't display the cards correctly

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1884]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/user/evgeni-company-9105/settings/membership
2. Authenticate with user that is member from many communities (or create such) - 2 cards instead of 4 are displayed on each row.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/12cb44b1-f47f-4c7b-9eca-670a875cf3e0)

**Expected behavior**
4 cards are displayed on each row.

**Comment by me-andre** [comment]
Fixed by #1823

**Comment by Comoque1** [comment]
The last row cards are displayed with distance
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4536e07-19f9-4ed5-a550-ca5a27318754)

@techsmyth if you accept it, we can close the issue

**Comment by valentinyanakiev** [comment]
if there is a row with less than 4 cards, make them left anchored
