### ISSUE TITLE
BUG: Users cannot be searched by email on "Available users" search field on i.e. "Hub / Members" page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1895]
**Describe the bug**

**To Reproduce**

1. Go to https://test.alkem.io/admin/hubs/hub12/community/members
2. Authenticate with GA
3. Type "fuser101@" - no results are displayed, but must be displayed: "fuser101 luser101"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bcb6ea9a-c3de-4158-8aa0-eb3be1b6b8db)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5f01c6a9-4de8-4560-aa22-7f684b9be9a8)

**Expected behavior**
Available users for assignment must be searchable via email on all pages, if the user who does the search has the privileges to see the emails.

**Comment by techsmyth** [comment]
To be tested after the other work regarding the usage of pagination with filtering is done.

**Comment by Comoque1** [comment]
Tested OK with Spike: Design "filter" parameter on the users query#1931.
Note, as pagination is applied only to / Authorixation / GA page on the client, it was verified only there.
