### ISSUE TITLE
Management of preferences on Org + Challenge

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1904]
## Description

As a challenge admin I want to be able to set the preferences
As an organization admin I want to be able to set the preferences

## Acceptance criteria

- [x] Organization admin interface to have a new Preferences page + display the preference for adding users matching the domain directly (1x)
- [x] Challenge admin interface to display the preferences related to community membership (3x) on the Community tab similar to the design for the Hub tabbed admin interface

**Comment by hero101** [comment]
- Preference page for Organization added in the Admin panel under Authorization
- Preference page for Challenge added in the Admin panel under Community
