### ISSUE TITLE
BUG: Aspect description set from user is not shown on aspect settings page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1914]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/feedback/contribute and open GraphQL Network browser tool
2. Authenticate with GA
3. Follow the process of an Aspect creation 
4. Choose an Aspect type
5. Press "Next" button
6. Fill "Title" field
7. Fill up "Please share the details *" field (the description)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/160acc8b-d04c-4d6d-88ec-9ae5132be458)
8. Press "Next" button
9. On Aspect "Final check" page all looks correct
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/12e26e5b-b4e4-4c34-b57d-7962e0107c07)
10. Create the Aspect
11. Open the Aspect
12. Open the Aspect settings page - Description input field is empty
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6bb841a6-4af1-43df-bfa9-41c9f5e583bd)

**Expected behavior**
 "Please share the details *" field (the description) on Aspect's settings page is displaying the latest value the user has set.

**Comment by me-andre** [comment]
There's another issue that may be related:
When creating an aspect, after adding a tag, the details field gets cleared (if it had content). May occur because of the description field not keeping state. If not the case - makes sense to file another issue.
