### ISSUE TITLE
Spike: Design "filter" parameter on the users query

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1931]
## Description
As an admin I want to be able to quickly filter users

## Acceptance criteria
- [x] Add a "filter" parameter on the users query 
- [x] Using the new filter parameter for searching on users in the following places: users list global admin
- [x] Filter parameter to filter on the following data from the user: first name, last name, email

Design for the filter. Timeboxed to half a day.

**Comment by hero101** [comment]
The example is implemented on `admin/authorization` Global admin authorization page.
