### ISSUE TITLE
Aspects preview section on Dashboard tab Hub + Challenge

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1940]
## Description
As a user I want to be able to see what Aspects are available

## Acceptance criteria

- [x] A aspects preview box under the Hub Dashboard tab 
- [x] A aspects preview box under the Challenge Dashboard tab 
- [x] A aspects preview box under the Opportunities Dashboard tab 
- [x] Aspects preview box has activity statistics 
- [x] Extend API -> activity to have aspects count on hub, challenge, opportunity level
- [x] We show 2 cards
- [x] the aspects preview is below challenges / opportunities / projects

## Additional Context

https://xd.adobe.com/view/e2d9a902-8f26-44bc-bdc8-58d1ca9cfa1e-b78a/

**Comment by techsmyth** [comment]
@me-andre we got some additional feedback on Friday that this preview section needs to be on the dashboard. Hopefully well enough encapsulated that moving it from one tab to another is not too impactful?

**Comment by me-andre** [comment]
@techsmyth , nope. I just altered the queries and moved the logic to another containers.

**Comment by Comoque1** [comment]
All works fine on DEV, except the Aspects(number) not getting updated.
Created a [separate bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1974)
