### ISSUE TITLE
Tabbed Admin / Hub profile - improve controls

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1949]
## Description

As a User I want the Hub profile to correspond to the [mockups](https://xd.adobe.com/view/450cbff7-db30-4605-82ba-b1a206944fd4-105f/)

## Acceptance criteria

- [ ] Update bradcrumb (the current implementation seems correct)TBD
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7643bb91-5639-4075-99ef-c0612c2860cd)

- [ ] Remove the host from Hub / Profile
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3c5d08ea-5943-45aa-811a-0c19ed981b23)

- [ ] "Save" button - move to the bottom of the page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f12b41d1-d02f-4479-825e-b1650ade1081)

- [ ] Fix banners visualization
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9ba92b76-0df2-4f21-9032-c276bceacd8d)

**Comment by techsmyth** [comment]
The URL shown above is the XD URL, so how the URL is showing is fine.
The avatar is I suspect showing up wrong as it is from the populator so the actual backing image has the wrong dimensions. 
The save button needs to be where it is as the visuals are a different section and are edited separately. 
The host should remain as part of the Hub profile as it is critical to the set of the Hub.
