### ISSUE TITLE
Tabbed Admin / Hub challenges - improve controls

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1952]
## Description

As a User I want the Hub challenges to correspond to the [mockups](https://xd.adobe.com/view/450cbff7-db30-4605-82ba-b1a206944fd4-105f/screen/6a3cc406-ed90-4447-b398-75fdd5278ffb)

## Acceptance criteria

- [ ] When on Hub / Challenges , add heading above the grid : Challenges
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/51e6f527-99c0-4f5d-b39d-26b590a0de8e)

**Comment by techsmyth** [comment]
I would not see value in such a header, the user is already on the Challenges tab. However we do need to have explainations on all tabs.
