### ISSUE TITLE
Tabbed Admin / Unify fields on new entities creation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1953]
## Description

As a Community Admin, I want to have similar behavior, when I create entities (Hub / Challenge / Opportunity).
Currently, when Admin creates a hub, 5 fields are displayed on create page, whether on challenge and opportunity create pages, all profile and context fields are displayed.

## Acceptance criteria

- [ ] Hub, Challenge and Opportunity, have the same fields available on create page ("host" is available for hub only)

**Comment by techsmyth** [comment]
Yes this needs addressing, but prefer to take this as a UX phase 2 across the admin move to tabs.
