### ISSUE TITLE
BUG: Hyperlinks wrong color

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1957]
*![image](https://user-images.githubusercontent.com/64191883/154964860-084ca172-11a2-4af8-bd8f-7ad43fc18f59.png)

The hyperlinks colours does not match up to the house style. 

Normal : 
![image](https://user-images.githubusercontent.com/64191883/154964981-29dc7f49-c01e-4538-819b-94ccf8a0d8d0.png)

Clicked [Option, we've not determined a secondary color according to guidelines page and the green is too close to normal so i strongly suggest this blue [Information blue from guidelines and MUI(#1976D2)] for time of being]: 
![image](https://user-images.githubusercontent.com/64191883/154965763-855e779c-37ab-45ba-8149-26b9d4df19b4.png)

**Comment by Roseghost** [comment]
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/e77ab336-88b3-418e-ac22-ace09eb9a129)

Homepage uses ahref instead of link component. Unsure what right solutions is.
