### ISSUE TITLE
Tab panels: intro text on all panels 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1958]
## Description

As a user I want some guidance as to what each tab is about

## Acceptance criteria

- [ ] All tabs on hubs, challenges + opportunities to have a "description" text that is displayed at the top. 
- [ ] Consistent usage of the translation file for retrieving this label

## Additional Context
Note that the places where the i8n text is pulled from is not consistent I think, this may also need attention.

Intro text at the top ("Here you can...":
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6f11bbef-9eaf-4f79-ba5a-45a0b8fbcb02)

No intro text:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1cdd9254-bf8d-44ba-8375-9159f7d5355e)

**Comment by Comoque1** [comment]
On [Opportunity page](https://dev.alkem.io/un-sdgs/challenges/food/opportunities/food-sec/projects) some descriptions are incorrect:
- [ ] Community tab there is no organization
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0ca9315d-1099-412d-b05f-de67fe141e7b)
- [ ] Projects tab missing translation
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8557414f-6ad7-43b7-901b-269a9cb3f339)
