### ISSUE TITLE
UX: Consistency in display of activity metrics

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1961]
## Description

As a user I want a consistent UX

## Acceptance criteria

- [ ] Circle design on hub / challenge dashboard pages etc matches the one on our current homepage

## Additional Context

**Comment by Roseghost** [comment]
Logo Preview text scaling - Shouldn't be? or not this heavy

![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/1b71d9fc-3a99-4b07-8289-b92d9711922e)
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/33a87a7f-11f2-4041-b8ce-7d7766569768)

**Comment by Roseghost** [comment]
Blocks their styling are different
Dropshadow and outline - unsure which we are carrying at this point but I'm guessing outline? 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/11b876b2-a1f7-4cfb-a282-7e03dd0a4438)

**Comment by Roseghost** [comment]
Outline cards - having a max width might fix this? 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/1c40627c-b84e-42da-ae3e-4ed03abea270)

**Comment by Roseghost** [comment]
Searchbar at contributors page wrong background color - Should be white so its visibile thats its a interact-able 

![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/d46771fd-d589-4a70-8c46-016ddf9a7d42)

**Comment by Roseghost** [comment]
Weird alignment at admin page - Navigation bar is too much to the left and content to far to the right. 

![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/52c758e1-0d48-4b34-b57a-381d104dbfbb)

**Comment by Roseghost** [comment]
fontsize of placeholder bigger than regular fontsize 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/86b68ff6-83e7-4449-be80-d3265c304ebf)

**Comment by Roseghost** [comment]
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/58d0607f-d425-4f80-af55-27d64a73b9d0)

Outline color should be same colour as the dot - we use this colour to indicate clickability (this a word?)

**Comment by Roseghost** [comment]
Irregular spacing - Keywords spacing too small and links spacing too big
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/a6d27273-5510-495e-ac8a-8b5445365cbe)

**Comment by Roseghost** [comment]
Number circle doesn't match design - Should be bigger to easily fit the numbers 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/82ef964f-837d-4797-9805-f8edf6633d01)

**Comment by Roseghost** [comment]
Word "Member" has bad readability in dashboard
 ![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/4c05d9c1-e2ac-492f-98a2-594b9fd765ee)

**Comment by Roseghost** [comment]
Spacing of labels on card and aspect page should be connected to the side

![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/24b9cfe3-348c-4591-a23d-fd552af0b8a6)
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/1162e989-c2bd-4b64-a9f8-f3f33990df79)

**Comment by Roseghost** [comment]
Breadcrumb coloring confusing - Aspect shouldnt be greyed out only the last item is your location. 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/1d64a31c-c190-4945-aede-0cc1735ea219)

**Comment by Roseghost** [comment]
Navigation does not match design, selected page should be bold and line underneath should be closer to the text. 

Website:
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/ca7a1de8-6e89-46cd-ac48-c9c0d9a2fb66)

Design: 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/f4c35503-efa2-4bad-8199-66a17318b7fc)

**Comment by Roseghost** [comment]
Update : Deleted comments that aren't relevant to the developers and am picking that up in a seperate issues. as agreed upon last week
