### ISSUE TITLE
Spike: Evaluate tooling for translation management

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1964]
## Description

As a community I want an easy way to manage the platform translations

## Acceptance criteria

- [ ] Evaluate tooling for keeping translations current
- [ ] Evaluate how we manage our translation files as compared to best practices

Key requirements for the tool chosen:
- master of the translation files to remain in version control (so the master copy should not be on a hosted platform service)
- able to highlight where there are discrepancies between the default language (en) and other languages. Discrepancies include: where fields are missing, where the translations do not align (some kind of AI link?)
- able to integrate into our development flows?

Note: the ideal scenario is that we can more or less isolate translation from actual release flow, so that translations do not hold up the finalizing of releases etc. 

Key requirements for how we setup our translations mgmt:
- able to work with multiple translation files (what are the logical splits?)

## Additional Context
Excalidraw uses CrowdIn

timebox to a day

**Comment by hero101** [comment]
## [Locize](https://locize.com/?lng=en)
- [Showcase](https://www.youtube.com/watch?v=ds-yEEYP1Ks)
- [Locize for open source](https://locize.com/open-source.html)
- sync new or removed translation strings (compared with the master language - EN) with a single cli command
- translations are fetched from Locize CDN
- translations can be downloaded
- automatic machine translation is available
- manual machine translation is available
- review workflow - to review translations for a language
- metrics - translated by version, users, health, project metrics, translations used by OS
- auto-generated namespace backups
-  (via plugin) in context editing - the app is opened in an IFRAME in Locize, and by clicking on translatable strings they can be translated on the spot and updated in the translation, and viewed live immediately
- additional descriptions can be attached to strings to improve the translator's experience and accuracy
- (via plugin) find unused translations
- versioning
- attach up to 8 tags to stringsа
- localistars https://www.youtube.com/watch?v=WobsZ_er0I4
- invite translators to the branched project with only the missing keys (crowdbased) - https://www.youtube.com/watch?v=pueV2YSLRfs
- send files through email
- invite new translators 
#### Conclusion
More CDN based without obvious integration to Github, files can be downloaded and used in a build, but additional effort on the infrastructure and scripts is required

## [CrowdIn](https://crowdin.com/)
- [Showcase](https://www.youtube.com/watch?v=7QoHN_qE-OU)
- [Crowdin is completely free of charge for open-source projects](https://crowdin.com/page/open-source-project-setup-request)
- open source license
- file paths need to be configured
- different branches can be configured for sync
- pulls from GitHub on a schedule
- creates PR to GitHub on a schedule (can be manual) with a commit per file on a specific crowdin branch (configurable)
- can scan Figma and xd files for strings and transforms them to translatable keys - files can be updated with a new translated screen
- in context translation - overlay over your live website, where you can click on the text and translate it right away
 #### Conclusion
More file based with integration Github and with all if not more features than Locize
