### ISSUE TITLE
Improved option to delete aspects

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1967]
## Description

As a user I want a clean UX for removing aspects

## Acceptance criteria

- [ ] Remove the ability to delete an aspect from the aspect card
- [ ] Add a new button to delete an aspect onto the aspect settings page. 

## Additional Context
https://xd.adobe.com/view/8b74f059-2ac5-44a6-a230-a9b3038c3717-de27/

Delete button similar to the "Delete the reference" button on other pages, such as Hub profile settings. 
**Delete button is next to the Save button at the bottom.**
https://hub.alkem.io/admin/hubs/uwv/profile 

Old UI:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/da2e83b2-aad8-4b9a-b176-7b8641a9d077)

**Comment by Comoque1** [comment]
Tested OK on Test with PR related to that issue.
