### ISSUE TITLE
BUG: Authorization Load more doesn't work

### ISSUE THREAD

**Issue by Roseghost** [alkem-io/client-web#2015]
**Describe the bug**
Load more text on authorization page doesn't function as desired. 

**To Reproduce**
Went to authorization and doesn't work

**Expected behavior**
Should be clickable and load more.

**Screenshots**
![image](https://user-images.githubusercontent.com/64191883/165052107-c25d6d82-b367-4ed9-a33c-0e36ef0b84e6.png)

**Comment by techsmyth** [comment]
@Roseghost are there more to be loaded? And I assume you mean the Authorization Tab? ON which entity? If still an issue please re-raise.

**Comment by Roseghost** [comment]
I suspect this was the available users list. It loads on scroll now and there for fixed as far as I know :)
