### ISSUE TITLE
UX: Platform template management and usage of platform templates on a Hub

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2018]
## Description

As a developer I want to have a clear design for managing templates on a Hub

## Acceptance criteria

- [ ] XD design for managing templates at the platform level
- [ ] XD design for using platform templates on a Hub settings tab

## Additional Context

https://hackmd.io/zQ5lKDbfSqmW_RhY-4gDYg

Hub template management:
https://xd.adobe.com/view/39240558-394d-42a4-a227-229d1105578e-6c77/

Platform template management:
https://xd.adobe.com/view/d4b6bc7f-ea02-4473-9c52-8ce59e60651c-81e5/

**Comment by KayleeS96** [comment]
@techsmyth I have split the designs in hub and platform template management, you can hover over the remove/add options to get a little overlay mentioning adding or removing the template to/from a hub. Please let me know if additional changes need to be made before tomorrow's meeting

**Comment by techsmyth** [comment]
Thanks, good to have these split - much cleaner.

Two additional comments: I do not see any option to add / remove templates on the Hub. And it would be good to get some kind of consistent display of the "meta-information" about a template, be it aspect or canvas.

**Comment by KayleeS96** [comment]
I have added the add/remove options to the hub template design. I have to think some more on the display of the meta-information though.

**Comment by KayleeS96** [comment]
@techsmyth is this what you mean with regards to the meta-information?

![meta-information ZenHub issue.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/84b93815-0a98-445b-bb78-55d10f140eaf)

**Comment by techsmyth** [comment]
Actually the set of meta-information is not going to fit on the cards. It may be that the experience is that the user sees a list of cards per template type, and that when it is clicked on they get the additional information plus the option to add etc. 

Each card will have to be limited to maybe the title, an image and some tags - and then all the meta-information is shown when the user clicks on it.

Looking at google play store:
![image](https://user-images.githubusercontent.com/30729240/170280246-f35e2131-4983-4974-868b-bc11e871fddc.png)
and then clicking on the first entry:
![image](https://user-images.githubusercontent.com/30729240/170280335-9df1be99-70fe-4e98-950d-5e6aa61e66ff.png)
