### ISSUE TITLE
UX: Design for display of Challenge / opportunity member orgs + leads

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2027]
## Description

As a community manager I want to be able to have the organizations that are involved with my community
As a stakeholder I want to have Leading Organizations for Opportunities

## Acceptance criteria
- [ ] Dashboard Challenge/Opportunity: Display of the Contributors (Users and Organizations). Similar to the Contributors page on the main home page. See all button goes to Community tab.
- [ ] Community tab of Challenge/Opportunity: Display of the contributing members. (1) the Leading Organization, (2) Member Organizations, (3) Leading Users and (4) Member Users. Member organizations similar display as Leading Organizations same as Contributors page (https://hub.alkem.io/contributors)
- [ ] Updates gets the option to be collapsed
- [ ] Dashboard Opportunity: include Leading Organizations
- [ ] Admin: Challenge and Opportunity level, ability to manage the 4 categories

## Additional Context
https://xd.adobe.com/view/eceaddf4-f080-477f-9b06-cd7d58efe11c-b9b9/

https://hackmd.io/xGINTWN4TlqDhRNph3c4IA

**Comment by hoyterutteman** [comment]
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/b1b36f45-6627-45b9-9fc7-80dc17f724b6)

Maybe like this for in the dashboard view?
