### ISSUE TITLE
Community Tab: Display of leads / members on Hubs, Challenges, Opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2028]
## Description

As a user I want to see what organizations are visible on a Community

## Acceptance criteria

- [ ] Add the following sections on community tab for challenges + opportunities: org leads, user leads, user members, org members
- [ ] Add the following sections on community tab for hubs: user members, user leads, org members (host is displayed separtely)
- [ ] Management of the users / orgs in the roles on the settings community tab. Note Hub Host is set separately for the Hub admin. 
- [ ] Lead users should be subset of parent community **members** (based on Denise's suggestions).
- [ ] The material grid is used (example is the Leading organization section - use the same columns/fields)

## Additional Context
https://xd.adobe.com/view/eceaddf4-f080-477f-9b06-cd7d58efe11c-b9b9/

**Comment by Comoque1** [comment]
Fix search on Admin page: hub / community search - searching doesn't filter any data
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c2002a1b-0aaf-4b27-8266-b9c2e0202889)

**Comment by Comoque1** [comment]
## Bugs

The same below notes are experienced for all entities: Hub / Challenge / Opportunity
- [ ] updatePreferenceOnHub takes 6 seconds
https://dev.alkem.io/admin/hubs/un-sdgs/community
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a77f555a-4f65-470b-82d9-45c20b5fac5d)
- [ ] Rename from "Users" to "Member Users" on Admin / Hub / Community
https://dev.alkem.io/admin/hubs/un-sdgs/community
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d8095902-1c0f-4dff-bee9-9a3a1b990c37)
- [ ] **AC** not met: Lead users should be subset of parent community members (based on Denise's suggestions).
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/067f076a-911b-42dd-8d03-1a3fca7c9602)
- [ ] Missing server validation: to assign user as lead, it must be member of the community

## Improvements / Suggestions
- [ ] There is no point of having search just above "User Leads" as the limit is 2
https://dev.alkem.io/un-sdgs/challenges/food/community
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f47f1799-d9b8-46ae-a3dc-c735cda2b369)

**Comment by Comoque1** [comment]
Initial implementation is in place and deployed to Prod.
Moving the item back to backlog, as some of the AC are not or partially met (Described in the above comment).

**Comment by techsmyth** [comment]
@Comoque1 I am struggling to see what work is still left in this. Can you please raise a new issue with the list of items that you see as still outstanding? Not least so we can estimate what is left for planning.

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f28553a9-3277-4dbe-8989-a57834583a2c)

text is also the wrong text.

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ceb1f9cf-1b70-421f-9da4-80f6db2651f4)

On a Hub this does not make sense. The leading org is displayed separately, so please have this section simply be "Lead users" and not have two levels of heading.

**Comment by Comoque1** [comment]
> * Lead users should be subset of parent community **members** (based on Denise's suggestions).

The remaining pieces are, text updates, search to be applied for all contributors instead to have it Lead / Member specific and community headers colors.
Regarding the **AC** point being incomplete, I interpreted incorrectly - and it is working fine.
Regarding multiple requests being sent for `associateOrganizations` - raised a [separate bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2140)
