### ISSUE TITLE
Add location to new org creation

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2034]
## Description

As an Alkemio user I want to have location metadata on Organizations.

## Acceptance criteria

- [ ] Creating an organization should have selectors for Country and City (Country above City)

## Additional Context

- The logic is identical to edit user profile:
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/9f548602-dde1-4e50-83f4-3c5966ac0be3)
- Use server-1899 as base branch on client & server
- run migrations on the server before starting it
- User has Profile and Profile has Location, similar to Organization --> Profile --> Location. Logically the references are the same
- Look at EditUserProfilePage as reference

**Comment by Comoque1** [comment]
After the changes, the following behavior is experienced:

1. On create organization page, the input fields are side by side, instead one over another
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/28bf44be-35e1-496d-a3b1-23df14516592)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0631a2d6-ee5d-408e-8da6-6e527483636a)
2. `Country` and `City` input fields are with different positions, compared to `User profile` page - it would good to be consistent (Keep Country on left and City on the right)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1d2e1942-235d-4605-92f5-1d4f5c865719)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/304cafd4-5943-42de-84b6-b6ea1585a6a9)
3. When updating the location parameters correct data is send and returned, but not displayed on the client (the data is store correctly in the DB)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ab045f21-a411-443c-b16c-8742156c61d0)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0e91e3e4-28de-4e2b-803a-cd790d7a6f06)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cca01bb5-fb31-44a0-8ae2-05f507605758)

Moving back to backlog, for the feedback to be addressed.
