### ISSUE TITLE
UX: Visibility of community lead users

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2041]
## Description

As a user I want to know who I can interact with in a community 

## Acceptance criteria

- [ ] UX design for how users in the Lead role are shown to a community 

## Additional Context
![Option 4 - Shuffle.svg](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1f5da53f-cc03-49ae-a3e9-138e1d0163a0)
Link: https://www.figma.com/file/F46Dbe4JxNlUAGz5eDgr4s/Lead-users?node-id=42%3A166

**Comment by SimoneZaza** [comment]
https://www.figma.com/file/F46Dbe4JxNlUAGz5eDgr4s/Lead-users?node-id=0%3A1 still in progress

**Comment by techsmyth** [comment]
@larssondenise we also should talk our key current users through this update as it moves the host / leading org visibility.
