### ISSUE TITLE
Switch from membership queries to roles queries

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2091]
## Description
As a user I want to be able to see all the roles held by a User or Organization

## Acceptance criteria

- [x] Replace the userMembership query with userRoles
- [x] Replace the organizationMembership query with organizationRoles
- [x] remove the membership service on the server, and remove any usage of it on the client
- [x] update client lib if necessary

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ffd6e095-264f-4404-87dd-9ae5ed32752b)
to
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/42831256-4b41-4ae6-8969-45c3cc878048)
====

Orgs
from

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f72d6903-0619-4acb-9453-7e8c51d79b4a)

to

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/33f0c1f3-9269-4864-ab6e-424185aae7af)

**Comment by valentinyanakiev** [comment]
Is client-lib checked?
