### ISSUE TITLE
Put video's on hub

### ISSUE THREAD

**Issue by hoyterutteman** [alkem-io/client-web#2098]
## Description
As a user
I want to easily access the Alkemio videos
So that I know what Alkemio is and how to use it

## Acceptance criteria

- [ ] English demo video on hub (see image below) 
- [ ] Dutch demo video on hub 

## Demo video 
**Location:** hub.alkem.io

**Video link English language selected**: `https://vimeo.com/708623032?utm_campaign=2022VIDEO&utm_source=VIDEO&utm_medium=VIMEO&utm_term=clicks&utm_content=2022VIDEOHOWTO`

**Video link Dutch language selected:** `https://vimeo.com/709543522?utm_campaign=2022VIDEO&utm_source=VIMEO&utm_medium=VIDEO&utm_term=click&utm_content=2022videohoegebruikikNL `

**Text if Dutch language is selected:** `Wil je het platform gaan gebruiken? Kijk dan eerst deze demonstratie video!`

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/7ba3a110-9269-4e25-8764-cb69b770809a)

**Comment by Comoque1** [comment]
The AC is met, but I think, the video should open in new tab. This is the behavior for external links.
