### ISSUE TITLE
UX: Design for management of Aspect Templates on a Hub

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2110]
## Description

As a hub admin I want to be able to manage my aspect templates

## Acceptance criteria

- [ ] UX design for how a Hub admin manages the set of aspect templates on the Hub

## Additional Context
There is already work on this, but it needs further refinement.

Key points: 

Designs:
https://xd.adobe.com/view/8c8e1b86-c3dd-4ac3-9f12-c7997d752210-d9dd/

Iteration -> https://xd.adobe.com/view/e06dcac1-f20c-4bf4-9b69-12cf76b17a99-b53e/

**Comment by techsmyth** [comment]
Hi Kaylee, I split the previous templates UX design work into two as we need just the management of Aspect templates on Hubs for now. Key points:
- there should not be any notion of inactive
- there probably should be some kind of details display whereby the user can update / delete as well as the option to create a new one

Suggest I try to chat you through this later.

**Comment by techsmyth** [comment]
Thanks Kaylee - I have put some comments into the UX design. Can you please re-iterate?

**Comment by KayleeS96** [comment]
Iteration has been updated with edit and delete pop-ups overlay screens. Create screen will come soon!
