### ISSUE TITLE
Display of Lead user in communities

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2116]
## Description

As a user I want to see the users that are leads of a community

## Acceptance criteria

- [ ] Display of User that is Lead for a community as per UX design

Design below is for Hub, and for Challenges / Opportunities the wording is "Leading Organizations / Leads"

## Additional Context
https://www.figma.com/file/F46Dbe4JxNlUAGz5eDgr4s/Lead-users?node-id=0%3A1

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e444e2d3-a604-491f-8da8-087a1296e30e)

**Comment by Comoque1** [comment]
Works as per AC on Dev env. on all levels (Hub, Challenge and Opportunity)
