### ISSUE TITLE
BUG: Subscription not handled correctly on aspect comments

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2132]
**Describe the bug**
The client is subscribing and unsubscribing on ws next event.

**To Reproduce**

1. Open the network tab of developer options and filter by websockets - choose the active graphql subscription
1. Go to an aspect's dashboard
1. Verify that a subscription event is published by the client
1. Write a comment on the dashboard
1. Observe abnormal ws behavior

**Expected behavior**
The clients subscribes a single time and unsubscribed when the page is closed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/46c064b0-9858-4175-9184-7c42eda936a6)

**Additional context**
The screenshot shows the following abnormal flow:
1. Subscribe event - A
1. Next event - Next of A
1. New subscribe event to the same subscription - B
1. Complete event - Complete of A

Expected:
1. Subscribe event - A
1. Next event - Next of A
1. Next event - Next of A
1. Next event - Next of A
1. Complete event - Complete of A

**Comment by Comoque1** [comment]
Works fine for comments area with [sub-fix](https://github.com/alkem-io/client-web/pull/2178) branch on Test env
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/29555fb7-80db-4012-9bc7-c4ed72de82dd)
