### ISSUE TITLE
Spike: components for managing cookie preferences with multiple levels

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2143]
## Description

As a user I want to be able to choose my cookie preferences

## Acceptance criteria

- [x] Evaluate cookie management components in React and how they are configured
- [x] Demonstrate usage of component to disable e.g. hubspot tracking 

timebox to half a day

**Comment by alstojanovic** [comment]
Suggest we use: https://github.com/porscheofficial/cookie-consent-banner
Looks, nice out of the box, so I assume it will need not too many css tweaking.
Use case on: https://www.cyklaer.de/?

Prototype is on branch `cookie-consent` in the client-web repo.
