### ISSUE TITLE
BUG: URL for user edits via admin uses UUID

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2150]
**Describe the bug**
The URL for a user profile via admin uses the UUID: 
https://hub.alkem.io/admin/users/001df83f-682e-4726-8ae0-a857b19adfc0/edit

**To Reproduce**

1. go to admin + then users
2. select a user, the URL has UUID and not nameID

**Expected behavior**
nameID should be used in the URL

**Comment by Comoque1** [comment]
Works as per AC on DEV env.
