### ISSUE TITLE
Log kratos flow failures to Sentry

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2151]
## Description

As a DevOps engineer, I would like to be able to track Kratos issues in a SaaS environment.

## Acceptance criteria

- [ ] Login / recovery / verification flows throw an error that is then captured + visible in Sentry

**Comment by valentinyanakiev** [comment]
Kratos seems to be logging normal flow like an error:
https://sentry.io/organizations/alkemio/issues/3354157867/events/5d3b025baef84a02ab8f40d3bf67149a/?environment=production&project=5862875
https://sentry.io/organizations/alkemio/issues/3354157867/events/50f0006089414abbbc0d9e862748fc2f/?environment=production&project=5862875
https://sentry.io/organizations/alkemio/issues/3354157867/events/dd551bc30efb4d14b19e484c3580f2e1/?environment=production&project=5862875

Not all messages from the UI are errors.

**Comment by Comoque1** [comment]
Logs are not received, for "login flow expired" 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/52089187-7f61-4ad7-8007-4f212791bcca)

and for "invalid attempt to authenticate"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/02f036f3-bbae-4112-a25b-01b3a5b964f3)

**Comment by Comoque1** [comment]
Moving to blocked,until deployed on PROD.
