### ISSUE TITLE
BUG: Login field is not picked up by password managers

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2163]
**Describe the bug**
Reported by a user: the password manager is not picking up the username field - likely as it is not called username but ID.

**To Reproduce**

1. Save password in password manager
2. Go back to login: it is not picked up

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f6e7886e-674a-4d4e-aefc-6365593cd5b7)

Environment details: LastPass, Chrome plugin, Debian

**Expected behavior**
Password manager picks up the field and fills it out. 

Note: the hypothesis is that it is due to the field not being called username or similar.

**Comment by techsmyth** [comment]
@jgroenen

**Comment by valentinyanakiev** [comment]
Wasn't working for me with Kratos 0.9.0-alpha.2, but is working with 0.10.1 now. Seems to be working just fine.
