### ISSUE TITLE
BUG: Popup cards for users are not displaying tags properly

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2166]
**Describe the bug**
The popup card for users on a Hub page (or elsewhere) has tags that look awful

**To Reproduce**

1. To to the EDI Stelsel hub on demo
2. Hover over the card for Tim Speelman, popup looks like below:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/56a06ed4-4773-41e7-9bd5-6626f0080efc)

**Expected behavior**
The tags should be displayed cleanly

**Comment by Comoque1** [comment]
Added all tags from the users from this hub, to a user on DEV env, and checked its tags display on all pages - there is no cropping.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f3267f38-82ad-4306-9d88-6f7150195856)
