### ISSUE TITLE
Home page top section

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2171]
## Description
As a not logged in user I want to know how to get started

## Acceptance criteria
- [x] Display new top banner section
- [x] Remove the current 4 sections that are displayed
- [x] Detect whether the user is logged in or not + adjust display accordingly
- [x] Not logged in: display new section prompting them to login or not

**Comment by Comoque1** [comment]
Tested on TEST env with the related branch.

Below is the feedback for not authenticated user:
- [ ] Links, the new links show open in new browser tab, as they are outside the scope of the application 
  - [ ] [impact](https://www.alkemio.foundation/) 
  - [ ] [foundation](https://www.alkemio.foundation/)
  - [ ]  [open source](https://github.com/alkem-io)
- [ ] impact and foundation links point to the same page - TBD
- [ ] The link [more about alkemio](https://test.alkem.io/about) points to hub about page, instead to https://www.alkemio.foundation/about/  - Not sure if it is correct

**Comment by techsmyth** [comment]
and also there is no WWW in the URL for the foundation, it is simply https://alkemio.foundation/about. Note that these URLs are also provided as part of the server configuration, so @valentinyanakiev there will also need to be config maps updated as part of the deployment...
