### ISSUE TITLE
My Hubs section

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2174]
## Description

As a logged in user I want to be directly able to go to the Hubs where I am a member

## Acceptance criteria

- [ ] New section for logged in users showing the Hubs where they are a member
- [ ] Label only shown on a card if the user is a Lead

**Comment by Comoque1** [comment]
Tested on DEV env.
Something missing the AC, but available on mockups:
 - Personalized welcome message: Welcome back, <User>
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/418be235-18e4-4e9c-9d38-9b482ec16360)

@techsmyth, would you prefer to address it as part of this issue, or to create a new one?

**Comment by Comoque1** [comment]
After discussion with @techsmyth, we agreed to raise [separate issue related to welcome message](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2241), as we missed to add it in the current story.

Closing this one.
