### ISSUE TITLE
BUG: Organization contributions are not displayed on organizationProfile page, when Organization is member

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2185]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/organization/contributors
2. Make the organization Member to a hub, challenge, opportunity
3. Navigate to the organization profile - contributions panel is empty.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d4951653-2e9e-439f-a615-a94b4cd03d8d)

**Expected behavior**
Organization Contributions are displayed, when the organization is member of the entities communities

**Comment by Comoque1** [comment]
Updated steps to reproduce. Moving to New issues.

**Comment by techsmyth** [comment]
That makes sense, the code before looked for where the org was a **lead** of a hub or challenge, not for Member.

**Comment by techsmyth** [comment]
Taking in as part of #2002
