### ISSUE TITLE
Usage of new cookie component: cookies described, text to display

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2194]
## Description

As a user I want to have clarity about the cookie options that I have
As a steward I want to be compliant

## Acceptance criteria

- [ ] Cookie details added to configuration for cookie component
- [ ] Set of options set on cookie component updated

**Comment by hoyterutteman** [comment]
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/c5df9ebb-1184-4e2a-bdf9-5ac11ab82ec9)
