### ISSUE TITLE
Cookie component extension 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2195]
## Description

As a user I expect the cookie component to have a similar look + feel as the rest of the application

## Acceptance criteria

- [ ] Extend the current Cookie component to have the following text: 
"By clicking “Accept All Cookies”, you agree to the storing of cookies on your device to enhance site navigation and analyze site usage."
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/5a8560ca-62d0-4fb8-bd59-3fc28c6d9a94)
- [ ] Add an extra button for "Settings"
- [ ] On clicking on settings the user sees the following screen without the analysis cookie option:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/93eeb4a9-01d1-4131-9f9d-5363102ef07a)
The first option is always checked. 

Note: we then would not be using the new cookie component that was identified during the spike. 

## Additional Context
Analysis carried out by Hoyte: 
https://hackmd.io/PvpOKT-YQCW6K9tGY9VoGQ?view

**Comment by alstojanovic** [comment]
@techsmyth @hoyterutteman Do I try to create translations to other languages or do we have that somewhere?

**Comment by alstojanovic** [comment]
@techsmyth  One question about the implementation details that @me-andre raised. We are saving this as a cookie but do we want this in local storage instead? We need the information only for the client so there is no need to store it as a cookie.

**Comment by alstojanovic** [comment]
Moved to blocked until the translations are done.

**Comment by hoyterutteman** [comment]
Small banner --> `Door op "Accepteer Alle Cookies" te klikken, gaat u ermee akkoord dat er cookies op uw apparaat worden opgeslagen die bijdragen aan de website navigatie en het anayleren van website gebruik.` 

Settings --> `Instellingen`
Accept All Cookies --> `Accepteer Alle Cookies`

Large banner -->

```
Bij het bezoeken van een website kan informatie worden opgeslagen in uw browser in de vorm van cookies. Deze informatie kan over u, uw voorkeuren en uw apparaat gaan. Meestal wordt deze informatie gebruikt om de website zo goed mogelijk te laten werken. Sommige websites gebruiken de cookies ook voor marketingdoeleinden. Aangezien Alkemio geen advertenties toestaat op de website, maken wij slechts onderscheid tussen twee soorten cookies. Lees meer.

Technisch noodzakelijke cookies: maken het mogelijk op de website te navigeren en uw voorkeuren op te slaan.
Analytische cookies: staan ons toe vast te stellen hoe gebruikers onze dienst gebruiken om de gebruikerservaring te verbeteren.
```

Confirm choice --> `Bevestig keuze`

**Comment by alstojanovic** [comment]
Awesome, thanks @hoyterutteman !
