### ISSUE TITLE
BUG: Large gap from title to tagline

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2196]
**Describe the bug**
On the hub dashboard there is a large gap between the title + the tagline

**To Reproduce**
Visit any hub dashboard:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3fdb421c-dae6-47dd-a0c2-cbc2af691d95)

**Expected behavior**
Tagline should be directly under the title, and then a small gap to the start of the vision

**Comment by SimoneZaza** [comment]
No longer relevant
