### ISSUE TITLE
Add label on opportunity, when a user is Member

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2203]
## Description

As a User, I want to see "Member" label on opportunity card, that contains the opportunity name, similar to Hub and Challenge cards.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4278e00-2e42-412e-bf3e-3fd35232efb2)

## Acceptance criteria

- [ ] Member label is displayed on Opportunity card that contains the title (similar to Hub and Challenge)

**Comment by SimoneZaza** [comment]
no longer relevant
