### ISSUE TITLE
BUG: Aspect template overview doesn't render image from MD

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2231]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/sub-hub/templates/aspect-templates/9fe9c9c5-5e68-4299-ae2c-5ab2a3104ea3/edit
2. Open the aspect template and add an image - the image is visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5ec43043-a4d8-4065-aad3-d92bc9d5127c)inish the Aspect update
3. Finish the Aspect update - the user is redirected to the template overview - the image is not visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6bc0f664-569a-4310-8703-d9d357c39e39)

**Expected behavior**
Images set in MD are visible on aspect template overview.

**Comment by techsmyth** [comment]
Note that both the description and defaultDescription fields are markdown: ![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1a7d9470-1eb3-43d5-8464-f492c3363a74)

**Comment by techsmyth** [comment]
To be verified after refinements are completed
