### ISSUE TITLE
Change verified/not verified visuals of orgs

### ISSUE THREAD

**Issue by hoyterutteman** [alkem-io/client-web#2236]
**Is your feature request related to a problem? Please describe.**
The verified/not verified status of an organisation is too visible at the hub/challenge/opportunity level. Especially not verified looks like something is wrong with the organisation, and it's not directly visible what it means.

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/3f8a5584-c89c-4cee-b95f-a2aaa56c0294)nly 

**Describe the solution you'd like**
Only visible when an organisation is verified, show nothing when organisation is not verified. Also change from 'verified' to a simple symbol, with mouse-over description. 

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/81c0eddd-e997-40bd-bd86-75f1115c3d59)

On the organization page, keep it as is, with addition to the blue checkmark in case an organization is verified.

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/4449317b-bdbd-4fd2-a045-3f0370335729)

**Comment by Comoque1** [comment]
Tested on DEV env.

Regarding AC and actual behavior:
- [x] Only visible when an organisation is verified - **OK**
- [x] show nothing when organisation is not verified - **OK**
- [ ] Change from 'verified' to a simple symbol, with mouse-over description - at the moment it is shown 'Verified' in green on leading organizations and facilitating organizations **without** simple symbol, with mouse-over description 
[link to leading organization](https://dev.alkem.io/un-sdgs/challenges/food/dashboard)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/447895e6-feb8-4add-a7eb-0bd77dd59608)

[link to facilitating organizations](https://dev.alkem.io/un-sdgs/dashboard)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2cf723bd-6b28-4760-a02d-67d805c7c9ec)

- [ ] On the organization page, keep it as is, with addition to the blue checkmark in case an organization is verified. - **[missing](https://dev.alkem.io/organization/united-nations)** blue checkmark
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8b32f7a9-f9e4-49e9-a7f2-eec8232d775e)

Moving back to backlog.
@techsmyth, in case you accept the current behavior, we can close the issue.

**Comment by techsmyth** [comment]
Thanks @Comoque1  - it was an explicit decision not to use a symbol, so how it is now is good.

**Comment by Comoque1** [comment]
OK, closing the issue.
