### ISSUE TITLE
Aspect templates: refinements

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2240]
## Description
As a user I want a user experience that is common across multiple templates

## Acceptance criteria

- [x] Use the banner for the template across the top of the details that popup on hover. Do not use the stock image that is currently displayed top left.
- [x] Only display the "Update" button on the popup window. Delete should move to the the "Update" screen.
- [x] Popup: Group the "info" fields that are common to all templates at the top: title, description, tags
- [x] Description field is Markdown
- [x] Popup: Group the aspect specific fields below: type, defaultDescription
- [x] Use the same grouping on the Update screen.

**Comment by Comoque1** [comment]
Looks much better now!
Couple of notes:
 - tags we display normally on the bottom
 - Can we have the title (Description, Tags, Aspect type, Default aspect description) bold?

**Comment by Comoque1** [comment]
Forgot to attach screenshot in the previous comment.
@techsmyth, do you want to address the above comments or as part of a separate issue?

**Comment by techsmyth** [comment]
Hi @Comoque1 lets just raise those points as a separate issue, they are minor and should not hold up the release...
