### ISSUE TITLE
Add personalized welcome message to user on Home page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2241]
## Description

As a PO, I want users to be presented with welcome message on Home page, when authenticated.

## Acceptance criteria

- [ ] "Welcome back <user first name>!" message is displayed to authenticated users, as defined in the [mockups](https://xd.adobe.com/view/efc89673-a108-4b16-9306-9881714b228e-ba9b/screen/c73bd044-4a9c-49de-9a91-5fa9c24df13c).
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/343dc2ce-fed8-499f-a562-8edaeace471c)

**Comment by valentinyanakiev** [comment]
Duplicate
