### ISSUE TITLE
BUG: Organization avatars to always crop on admin community

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2244]
**Describe the bug**
At the moment the organization avatars sometimes stretch, sometimes crop. It should be one behavior: always crop. 

**To Reproduce**
Visit https://hub.alkem.io/admin/hubs/digileefomgeving/challenges/klimaatadaptatie/community

Settings ==> Community tab + orgs on 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/83f0fb05-b9a3-4ed0-a759-ce49c6a7363d)

**Expected behavior**
Always crop, anchored on the center

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise I noted this issue from our chat last week, but when looking just now I did not see any places where we stretch the avatar beyond in the admin area. What ones were we looking at?

**Comment by SimoneZaza** [comment]
@techsmyth This is on the hub community page:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/7f62cb8a-c8fa-4758-a312-80ef4485e863)
