### ISSUE TITLE
Spike: Allow the user to remain logged in for extended period of time

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2253]
As a user I want that my tokens are refreshed so that I do not have to login daily.

## Acceptance criteria
- [ ] Contact Kratos (raise an issue?) with our findings and ask them what we are missing 
- [ ] User can remain logged in indefinitely if the user is active on the application

## Additional information

Implemented in our Kratos version:
https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions

Note: we have implemented the extension of the server side session, but the cookie duration does not get extended so the user is still logged out after a relatively short period (2-days).

In scope: Raise the issue with Kratos team and follow up discussing with them

Raised in [discussion](https://github.com/ory/kratos/discussions/2559).

**Comment by hero101** [comment]
What does "active on the application" mean? (taken from current AC)

**Comment by hero101** [comment]
Raised a [discussion](https://github.com/ory/kratos/discussions/2559).

**Comment by techsmyth** [comment]
@valentinyanakiev can be closed right?
