### ISSUE TITLE
Images for aspect template cards

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2258]
## Description

As an admin I would like the aspect templates to be visually enticing

## Acceptance criteria

- [ ] Images to use for the aspect template default cards

## Additional Context
The 5 default aspect template types are: Stakeholder, Knowledge, Initiative, Other, Idea

Basically to make the screen shot below look nicer:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1d347723-c49a-4b2d-b17a-1273b74c861c)

**Comment by techsmyth** [comment]
@SimoneZaza suggestions for where to get such images for usage on the aspect template cards?

**Comment by SimoneZaza** [comment]
[https://app.zenhub.com/files/283163879/a24bcd0c-e856-4158-9520-9ba61908f2b8/download](https://app.zenhub.com/files/283163879/a24bcd0c-e856-4158-9520-9ba61908f2b8/download)
@techsmyth visuals for template card, header, and 'normal' card both in color and grayscale. I prefer grayscale.. :)

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/18c9737e-dba9-44d2-8f38-af927dd977f9)
@SimoneZaza agree that grayscale looks nicer!

Is there another image for the stakeholder? Also the related initiative one could have a bit of a "network" flavor to it, the water drops may not be clear. But if I had to update one it would definitely be the stakeholder one!

**Comment by SimoneZaza** [comment]
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/c072af8c-f335-4e77-9118-f704eef4bed8)
@techsmyth Do you like this stakeholder one better? The connectivity is difficult, lots of great paid images there, but the free ones do not really fit. In this printscreen I took a different approach, using hot air balloons... I'm very curious what you think.

**Comment by techsmyth** [comment]
@SimoneZaza yes these two are both better. Hot air balloon works for me, someone attempting to fly somewhere else :) And not seeing a person's face is good for the stakeholder...

**Comment by SimoneZaza** [comment]
@techsmyth [https://app.zenhub.com/files/283163879/17cd7f73-7ef8-402c-beef-e0145b46330a/download](https://app.zenhub.com/files/283163879/17cd7f73-7ef8-402c-beef-e0145b46330a/download)

**Comment by techsmyth** [comment]
Files stored up under contributors/product/visuals
Production environment updated
Demo environment updated
