### ISSUE TITLE
BUG: Translations are not applied on home page top section

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2259]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Change the language - translations are applied only on Login and Signup buttons. All other new components are missing translations
3.See error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9eff2d2b-f73e-4995-84f5-b0a8dd4dfce6)

**Expected behavior**
Translations for all 4 languages are available for the following components:
### When unauthenticated:
- [ ] text under top banner
- [ ] Existing user? Jump back in!
- [ ] New to Alkemio?
### When authenticated:
- [ ] Welcome back admin!

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ccanos** [comment]
https://github.com/alkem-io/client-web/commit/bbefd489354db7bf51f422317b8a4871be157b1e#diff-e5e3a192a07ddbef5beb8ab741253f8c12fb8c187d004f220cd5d8eec539a79b

![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/53ca3a20-94ca-44d6-bae2-ca728e8bf58b)
Do not translate the <impact> <foundation> <opensource> tags, the tag must remain, so the translation would be something like this: <impact>въздействие</impact>
	
the impact-url, foundation-url, opensource-url are taken from the config (it's changed in a later commit), so you can omit those
