### ISSUE TITLE
Prototype of new top level menu

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2274]
## Description

As a user I want to experience the new top level menu

## Acceptance criteria

- [ ] Prototype of the new top level menu structure for feedback

Note: keep as separate branch

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/8907358c-0d3b-464c-955f-3750745b74b9)

to

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/44996f54-5a67-4b6b-afeb-05f04fd253f7)

**Comment by Comoque1** [comment]
When User navigates to Alkemio Home page from mobile, cannot see login button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cdefc6e9-6f81-4b06-88cb-bf177de75db9)

**Comment by Comoque1** [comment]
Raised a separate card for the comment above https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2358.

Closing this one.
