### ISSUE TITLE
Spike: data loading impact of new tabs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2275]
## Description

As a developer I want to know what the impact of the new tabs layout will be on how data is loaded for Hub, Challenge, Opportunity

## Acceptance criteria

- [ ] Analysis of what data loading changes would be required/ advisable for the updated tabs

## Additional Context
Timebox to half a day

**Comment by ccanos** [comment]
https://hackmd.io/dl4ri8UvRcC6bmnySvNrMw
