### ISSUE TITLE
Spike: Design for extending user sessions

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2293]
## Description

As a PO I want to know the path forward to extend user logins

## Acceptance criteria

- [x] Interaction diagram of the roles involved in our implementation
- [ ] Brainstorm session with 4 people to identify path forward, using feedback from Ory
- [ ] Work to implement captured in the backlog

## Additional Context

Timebox to half a day

**Comment by valentinyanakiev** [comment]
There is a diagram what a request does in https://hackmd.io/GrxuDJQPRryEMyatWDgLWQ

**Comment by valentinyanakiev** [comment]
Output story: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/2042
