### ISSUE TITLE
Canvas Templates via settings

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2302]
## Description

As a Hub admin I want to be able to manage the set of Canvas Templates that are being used in my Hub

## Acceptance criteria

- [ ] Templates tab extended with a section for Canvas Templates
- [ ] Canvas Templates card to be displayed similar to the Aspect Template
- [ ] The settings tab allows the admin to select from one of the Templates in the Hub for setting it as a Canvas Template

## Additional Context
https://www.figma.com/proto/QGr6K8F9DKWpuNjdofXfxL/Canvas-Templates?node-id=17%3A369&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=17%3A369&show-proto-sidebar=1

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/321ff01e-840c-4cdc-a5c0-7efab565ae18)

**Comment by Comoque1** [comment]
Looks nice, only a couple of points to be addressed:
1. When browser width is decrease the popup doesn't fit
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0815af8c-e0bc-4ddf-8e33-f97c747e4f84)
2. The dropdown arrow should be right side centered
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f73d1ca5-48da-440e-944e-e0d001586919)
3. Label is missing for the "Canvas template"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4682d8ea-5769-4603-a469-2d29d96ba119)
