### ISSUE TITLE
Design for selection of Canvas for CanvasTemplate

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2312]
## Description

As a hub admin I want to be able to create and update canvas templates

## Acceptance criteria

- [ ] Design for the creation and updating of CanvasTemplates, where the admin can select from existing Canvases in the Hub to be the CanvasTemplate content, including seeing a preview of the Canvas (like when creating a Canvas from a Template) before finalizing the selection.

## Additional Context
https://www.figma.com/proto/QGr6K8F9DKWpuNjdofXfxL/Canvas-Templates?node-id=9%3A51&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=9%3A51&show-proto-sidebar=1

**Comment by larssondenise** [comment]
figma link + comments under additional context @techsmyth
