### ISSUE TITLE
State change buttons not working in opportunity page

### ISSUE THREAD

**Issue by yhunink** [alkem-io/client-web#2317]
**Describe the bug**

**To Reproduce**
1. Go to 'a challenge and click on an opportunity (in the Living Lab Scheveningen  hub).
2. Click on 'settings'
3. Scroll down to 'the state schema'
4. Click the button define, after which refine pops up. Clicking this does not produce any results.

**Expected behavior**
The State is updated successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/29640880/176532675-05c48741-e676-4f1c-86cb-69b18343264b.png)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4a7e3d46-72d5-4492-a773-98d06f3bbb8e)

-

**Comment by Comoque1** [comment]
The issue is resolved and will be on PROD with next release.
