### ISSUE TITLE
BUG: Multiple lead users have no spacing

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2331]
**Describe the bug**
Add multiple lead users to a Hub / Challenge + look at the dashboard page:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/38d2ecdb-3807-499c-af59-36c9eeac4ac3)

**To Reproduce**
Add multiple lead users + look at dashboard page

**Expected behavior**
There should be reasonable spacing between the Lead users, like what is done with avatars in the contributors section

**Comment by Comoque1** [comment]
The issue is not reproducible on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/32250982-5193-4b29-ab24-49cecf1fc835)
