### ISSUE TITLE
Community "see all" to open up a dialog

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2343]
## Description

As a user I want to be able to explore a community, but without it always taking over the screen on About tab

## Acceptance criteria

- [ ] See all on a community to pop up a dialog

## Additional Context

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/f15ea69e-04b2-4c2e-8cce-cadddd3d1971)

**Comment by Comoque1** [comment]
The dialog is working. There are some more details to be added in it and raised a separate story about it: Make community dialog similar to the old community tab #2413
