### ISSUE TITLE
Canvas preview panel

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2345]
## Description

As a user I want to be able to quickly see the canvases in a Hub / Challenge / Opp

## Acceptance criteria

- [ ] Canvases added to dashboard similar to what is done now for Aspects

**Comment by Comoque1** [comment]
Looks good!
The only comment is: when we have only 1 canvas it is centered in the cards container, instead of being positioned to the left , as is for other entities
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fb9eebd1-2fb1-402c-ada4-ff606545faac)

**Comment by Comoque1** [comment]
Now works fine on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e4495cc1-4bc3-4b61-8e19-63f29899db1b)
