### ISSUE TITLE
Switch to new tabs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2347]
## Description

As a user I want a simpler UX

## Acceptance criteria

- [ ] Move to using 4 tabs at each of Hub / Challenge / Opportunity
- [ ] **Hub tabs**
   - [ ] **Dashboard** - Left column
     - [ ] About this hub (context vision)
     - [ ] Facilitating organizations and Host block
     - [ ] Updates
      - [ ] Contributors
   - [ ] **Dashboard** - right column
     - [ ] Challenges
     - [ ] Aspects
     - [ ] Canvases
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/92421db7-7289-42eb-8db5-c9acc71be6d7)
   - [ ] **About** - Left column
     - [ ] All `context` related data
     - [ ] Hub statistics
   - [ ] **About** - right column
     - [ ] Facilitating organizations and Host block
     - [ ] Contributors!
![Schermafbeelding 2022-08-08 om 14.49.11.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b941b41a-28af-41a9-b67a-147a706b6f87)
- [ ] **Challenge tabs**
   - [ ] **Dashboard** - Left column
     - [ ] About this challenge (context vision)
     - [ ] Leading organizations and Lead users block
     - [ ] Updates
      - [ ] Contributors
   - [ ] **Dashboard** - right column
     - [ ] Opportunities
     - [ ] Aspects
     - [ ] Canvases
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/089dfe3e-97f6-4da9-859a-75e355b147ab)
   - [ ] **About** - Left column
     - [ ] All `context` related data
     - [ ] Challenge statistics
   - [ ] **About** - right column
     - [ ] Leading organizations and Lead users block
     - [ ] Contributors
![Schermafbeelding 2022-08-08 om 14.45.48.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/820b66a2-0158-44dd-a795-9b47caa3b8be)
- [ ] **Opportunity tabs**
   - [ ] **Dashboard** - Left column
     - [ ] About this opportunity (context vision)
     - [ ] Leading organizations and Lead users block
     - [ ] Updates
     - [ ] Contributors
   - [ ] **Dashboard** - right column
     - [ ] Projects
     - [ ] Aspects
     - [ ] Canvases
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f9190a3a-5342-45ca-bbac-030994f7fc5f)
   - [ ] **About** - Left column
     - [ ] All `context` related data
     - [ ] Opportunity statistics
   - [ ] **About** - right column
     - [ ] Leading organizations and Lead users block
     - [ ] Contributors
![Schermafbeelding 2022-08-08 om 14.52.05.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/6ad42693-8590-4a0e-9844-cd8a4709de16)

## Additional Context

[LINK TO RESOURCES (MOCKUPS)](https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=0%3A1)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f8e1a892-1425-4303-a56c-6abb8f4066ce)

**Comment by Comoque1** [comment]
@me-andre , I've updated the AC of the story. 
@larssondenise, could you please confirm, it is correct?

**Comment by larssondenise** [comment]
Correct! (only changed Hub stats into challenge/opportunity stats, will check the mock-ups for right positioning)

**Comment by Comoque1** [comment]
Thanks, @larssondenise!

**Comment by Comoque1** [comment]
The [Contributors cards ](https://test.alkem.io/un-sdgs/about) on About page don't look good.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/34b720ab-988b-4a8f-8c0c-60c7b6c24b89)

**Comment by Comoque1** [comment]
On [Hub / About](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2346), the organization card is wrapped and the host is missing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2465be61-36d4-4ff0-a69c-5f0891a55fda)


On [Challenge / About](https://test.alkem.io/un-sdgs/challenges/food/about) tab, link the search container to the Contributors, instead to the Updates
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c929bb34-00b0-4625-9957-332d2234b5ad)

Same comment applies as previous for Opportunity / About tab

**Comment by larssondenise** [comment]
Updates are currently still included in the About pages of Hub/Challenge/Opportunity!
![Schermafbeelding 2022-08-09 om 12.55.13.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/cfa7d328-9847-4e53-a867-109e6273fb0c)

**Comment by larssondenise** [comment]
Updates on the About pages of Hub/Challenge/Opportunity should be under Leading Org/Leads

![Schermafbeelding 2022-08-09 om 12.58.21.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/2ddb07a7-dffb-4719-ab83-fb37be51a015)

Preferably Leading Org/Leads combined in the 'About this Hub section' block
[Schermafbeelding 2022-08-09 om 13.00.26.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/508b8cdd-6f02-49b4-aaa1-b68bf2802094)

Otherwise, remove 'see more' from Facilitating/Leading Org and Lead/Host block
