### ISSUE TITLE
Aspects interaction as dialog

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2362]
## Description
As a user I expect the same interaction style for all cards on the explore tab

## Acceptance criteria

- [ ] Aspects interaction as per UX design
- [ ] In scope: just the dialog, `Explore tab` is out of scope for this story. Will be implemented in https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2375

## Additional Context
The interaction will be a dialog that pops up similar to that of Canvas, with icon tabs in the upper right corner. 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/fd43fd99-e719-4b03-9a01-b76ad680fbd5)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/53742977-514e-400d-afed-b6c6c92d0862)
Specifications of tabs: https://material.io/components/tabs#specs

**Comment by Comoque1** [comment]
I will test the functionality, after story "Callout sections on the explore tab #2375" is implemented.
