### ISSUE TITLE
Callout sections on the explore tab

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2375]
## Description
As a user, I want to see the callouts with all fields

## Acceptance criteria

- [ ] Callout component to display the description (Markdown) plus other information
- [ ] Plus card only visible for admins (with CREATE_CALLOUT privilege on Collaboration entity) 
- [x] No discussion callout for now
- [ ] No Other Canvases / Other Cards sections
- [ ] Use the existing Cards
- [ ] New Callout flow executed from the button at the top right `CREATE NEW CALLOUT`

## Additional Context

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/ee7dcc3e-da3c-4f08-9229-c6c03430c3cc)

**Comment by Comoque1** [comment]
Replace Challenge / Opportunity Explore tabs to be Callout.
