### ISSUE TITLE
Creation of new callout MVP

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2377]
Description
As an admin, I want to be able to create a new call out in the draft state

## Acceptance criteria

- [ ] Button to create a new callout that is displayed for users with the `CREATE_CALLOUT` privilege on `Collaboration`
- [ ] On clicking the button a dialog pops up to allow the admin to enter the information for the new call out and to save it
- [ ] Extend callout domain model - add template id

## Additional Context

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/fabdfad6-ec73-47da-8092-6bb68ef2437e)#

**Comment by larssondenise** [comment]
Design updated:
- Progress bar titles are correct, colour scheme not yet but must implemented as the standard) 
   
TBD 
Preview of the canvas or card template that an admin can see when they select one for the callout
