### ISSUE TITLE
Contributor (user, organization) profile view update

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2399]
## Description

As a user I want to have similar experience for both Organization and User profile pages

## Acceptance criteria
- [x] Banner User + Organization profile same grey colour as containers
- [x] Banner to have the same height as Hub / Challenge / Opportunity banner
- [x] If no avatar is specified then avatar space is still displayed but similar to banners on hub / challenge / opportunity
- [x] Menu bar only settings icon on the right (not visible if not profile owner) 
- [x] User Banner includes: image, name, location, telephone, social (linkedin, github, twitter)
- [x] Organization banner includes: image, name, location, social/contact
- [x] Container left below contains the rest (verified status for orgs, bio, keywords, skills, links etc.)

## Figma link
https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=257%3A1863

## Additional Context
![Schermafbeelding 2022-08-18 om 11.01.00.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b7f99292-51dd-4de6-99df-fed74fcadbbd)
![Schermafbeelding 2022-08-18 om 11.01.28.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/8b7d4e96-6e2f-408a-852b-214ee00aeef3)
![Schermafbeelding 2022-08-18 om 11.05.04.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/d9db1c7f-c49c-46a6-b539-ee3face214df)
![Schermafbeelding 2022-08-18 om 11.06.32.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/0cdc6747-ada8-4e97-bedf-e4255046d5ed)

**Comment by larssondenise** [comment]
To discuss: removing the sentence "here you can see the summary..".? @Comoque1 
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/0c486094-acf1-4227-93d5-612094bf851a)

**Comment by larssondenise** [comment]
For the top banner on both profiles: I think let's keep Alkemio for now, but make an issue on the backlog for adding the settings option to choose your personal banner.

**Comment by larssondenise** [comment]
Option with new banner for Profile/Organization? @techsmyth 

![Schermafbeelding 2022-08-15 om 15.25.17.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/2a25aa36-3c24-41d5-9911-bf60ced3a4bf)
