### ISSUE TITLE
Location + navigation: Banner

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2400]
## Description

As an Admin, I want to have navigation that is consistent across front and back end, and that allows me to see where I am. 

## Acceptance criteria
- [x] Labels on banner, positioned top left, for (a) Hub (b) Challenge. Tags should be clickable + bring the user to the location. Two separate labels, under each other. 
- [x] Hub label shown when in a Challenge or Opportunity
- [x] Challenge label when in an Opportunity
- [x] Limit both labels to have a width of ??? and to show a "..." if truncated
- [x] Labels to have a tooltip showing the full name
- [x] Applies to both front end and to admin

## Figma link
(See page ADMIN)
https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=257%3A1863 

## Additional Context

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/f99dc1be-c7bc-4ddf-a288-127acd71e716)

![Schermafbeelding 2022-08-18 om 13.04.23.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/cd7e60c1-4e3b-4b9f-a63c-25fb790164d1)
![Schermafbeelding 2022-08-18 om 13.07.41.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/ca942b1f-7af1-4d20-964a-f3704f7fc988)
![Schermafbeelding 2022-08-18 om 16.36.26.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/71a58159-c1a0-46e6-b1c8-80e7a347567b)

**Comment by larssondenise** [comment]
@techsmyth designs added + acceptance criteria, let me know if they are correct!

**Comment by SimoneZaza** [comment]
Screenshot added with an icon for hubs and challenges. Hub icon = material icon 'hub', challenges icon should be our mountain icon with the flag on top (sorry, the one in the screenshot is not correct, has to do with importing icons etc.)
