### ISSUE TITLE
BUG: failing to load on Brave browser on iOS

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2401]
**Describe the bug**
alkem.io is failing to load on the brave browser on iOS

**To Reproduce**
Open brave browser on iOS
Go to alkem.io, only a white screen is shown. It does not appear to be related to having a cookie set as the same happens when opening alkem.io in private mode in the browser.

**Expected behavior**
Alkem.io site should load in Brave browser.

Note: dev.alkem.io works ok.
acc works too

**Comment by valentinyanakiev** [comment]
It's working with the new UI and the latest release - verified by me on iOS 15.6.1 & iPhone 13 Pro
