### ISSUE TITLE
BUG: When user set in login endpoint external page URL it redirects to it

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2419]
**Describe the bug**

**To Reproduce**

1. User is unauthenticated
2. Set the following endpoint: https://dev.alkem.io/identity/login?**returnUrl=//google.com**
3. Press enter: user is redirected to google.com

**Expected behavior**
User is redirected to dev.alkem.io

**Comment by techsmyth** [comment]
I do not see an issue that needs to be fixed with this. The returnURL is whatever is passed - and it should be honored.
