### ISSUE TITLE
UX design for contributor role visibility on profile pages

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2432]
## Description

As a user I want to be able to see the roles of other contributors on their profile page

## Acceptance criteria

- [ ] UX design

## Additional Context
Figma link:  https://www.figma.com/file/t3KN1pFopUUNEW7DSC2YOy/Profile-page-User-%2B-Org?node-id=0%3A1

**Comment by SimoneZaza** [comment]
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/23fe5a6f-28c8-4073-accf-4d96397a0379)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/36d3edd3-e80a-4e5b-ba58-1ac89e8d038e)

**Comment by techsmyth** [comment]
@SimoneZaza looks fine. One minor comment is that the labels should also be there on organizations for where lead / member role.

**Comment by SimoneZaza** [comment]
@techsmyth yes, of course. Design is updated. 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/7c542a6d-e986-4bad-b59d-ebb2fb9554e3)
