### ISSUE TITLE
Top level mobile bar: Search

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2440]
## Description

As a user
I want to be able to search directly from the top level menu
in order to be able to search from everywhere in the application

## Acceptance criteria

- [ ] When the search icon is clicked, an input field will appear
- [ ] User is able to type within this field
- [ ] By pressing enter (keyboard done) or the search icon the user is directed to the search page with terms add and search results are shown
- [ ] 'X' or clicking outside closes the input field
- [ ] (Optional) A [collapse animation](https://mui.com/material-ui/transitions/#collapse) is performed from right to left when the icon is clicked. The hamburger menu is hidden, the logo is converted to it's smaller version and the search input field is expanded to the left.

## Additional Context
Menu without search selected
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/98a47ff2-ac04-47da-ad10-91fee3ee2b8b)

Menu with search selected
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/56abe74f-9e9f-4343-bc1e-e5d8c9c56538)

**Comment by techsmyth** [comment]
How to trigger the search on a mobile?
