### ISSUE TITLE
BUG: Creating Aspect / Canvas on explore page, doesn't update the counter on of the activities on Dashboard page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2469]
**Describe the bug**

**To Reproduce**

1. Go to a hub dashboard page
2. Note the number of Aspect and Canvases
3. Navigate to explore page and create 1 Aspect and 1 Canvas
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/52e12003-afb7-4b73-8fcb-69094e616140)
4. Navigate back to Dashboard page - the entities numbers remain the same as from the time, before creating new
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c3da22d3-ff57-4364-b623-0d6933f3aeaf)

**Expected behavior**
Dashboard Canvas / Aspect container activity number updates based on the added/removed Aspect/Canvases from explore page.
The fix must be applied for Hub, Challenge, Opportunity

**Comment by SimoneZaza** [comment]
no longer relevant
