### ISSUE TITLE
BUG: New release bar is shown on login page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2475]
**Describe the bug**

**To Reproduce**

1. Go to https://test.alkem.io/identity/login
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/06e764b6-b420-49e1-8c94-3c506e4b1a07)

**Expected behavior**
Bar should not be displayed on this page, only on the home page

**Comment by techsmyth** [comment]
It may be fixed?
