### ISSUE TITLE
UX: Ordering / Layout of Callouts

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2477]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

## Additional Context
TBD Drafts grouped on top ?

**Comment by larssondenise** [comment]
@valentinyanakiev discussed with Simone: all drafts grouped on top (rest based on date of creation)
