### ISSUE TITLE
Creation of d3 components package: @alkemio/visualizations

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2480]
## Description

As a developer I want to have the code as modular as possible

## Acceptance criteria

- [x] Creation of a new alkemio package: @alkemio/visualizations based on the contents of the analytics-playground repo + "display" package in there
- [x] client-web updated to pick up the lifecycle visualization from this new package

**Comment by ccanos** [comment]
Please, @Comoque1 To test this I'd like you to go through everywhere where you can see a lifecycle diagram and making sure it looks like it should: 
- Hub Admin > Templates
- Challenge settings > Innovation flow
- Opportunity settings > Innovation flow
- Dashboard of a challenge/opportunity > About Tab > click on STATE button
... and maybe more ?

Just seeing them, seeing that their statuses are alright and that the marked current status is the correct. 
Maybe editing the template and seeing that it's updated everywhere...
