### ISSUE TITLE
UX Design for suggested images for Visual

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2497]
## Description
As a user I want to be easily able to find images for the banners on my entities
As a platform I want to have visual images associated with content
As a compliance officer I want to ensure that the images being offered are under a valid license

## Acceptance criteria

- [ ] Design for how the visual dialog would look

## Additional Context
Figma file: https://www.figma.com/file/4yKwyi3yt8N4ov8bX6iwFZ/Visuals-Management?node-id=0%3A1

**Comment by SimoneZaza** [comment]
@techsmyth, first version of the design:  https://www.figma.com/file/4yKwyi3yt8N4ov8bX6iwFZ/Visuals-Management?node-id=0%3A1

**Comment by techsmyth** [comment]
@SimoneZaza nice simple design. I put some comments in as there are a few points we should talk through. Not least should we not move to having users select a single image + then derive both used images from that?

**Comment by techsmyth** [comment]
Looking nice!

Realize that we do have one key flow question to answer. This set of screens is very much for when the user does not already have the images selected. However what if the user does already have banners selected and just wants to edit the alternative text? We cannot offer them the chance to refine how the images are cropped as we do not have the original image stored. So maybe when the user first clicks edit they go to the last screen and from there can popout to select new images?

**Comment by SimoneZaza** [comment]
@techsmyth When making the changes we discussed I actually came up with 2 ways of doing so, so there are now 2 designs for the first dialog.. (:

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b29ecf3f-81c9-4aee-94c1-5568bede96a1)
