### ISSUE TITLE
BUG: text box color Updates

### ISSUE THREAD

**Issue by hoyterutteman** [alkem-io/client-web#2504]
**Describe the bug**
The text box color of an update now is white... 

**Expected behavior**
It should be transparent?

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/4ea3c477-5b91-46b3-838f-5c58d629dbeb)

Chrome

**Comment by techsmyth** [comment]
Does not seem to be happening any more...

**Comment by Comoque1** [comment]
On ACC it seems to be reproducible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/92387621-0d7b-4330-a078-c0e54228f7c9)

**Comment by Comoque1** [comment]
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a6ad79a1-0a70-435e-abb2-721b0c1e9b8a)
