### ISSUE TITLE
BUG: When changing Challenge Innovation flow state, visual discrepancy is displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2506]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/test/challenges/chechch/context
2. Change the state of the lifecycle fast
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3f5c5b94-d0f7-4c46-a356-2d2dcc8590d8)

**Expected behavior**
States are updated correctly and there are no unexpected visual side effects.

**Comment by SimoneZaza** [comment]
no longer relevant
