### ISSUE TITLE
BUG (PROD): Error logged in sentry when navigating to https://alkem.io/open-innovation/dashboard

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2510]
**Describe the bug**

**To Reproduce**

1. Every time a user navigates to https://alkem.io/open-innovation/dashboard error is logged in sentry
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b971a994-a427-41a9-a821-a931787b8c13)

The issue is triggered every time a user navigates to a hub dashboard.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e8929f34-bf48-4d87-8aac-a6fe5094a589)

**Expected behavior**
Understand what is causing this error to be triggered: what, when, where. 
Context: when user navigates to the endpoint: https://alkem.io/open-innovation/dashboard

Timebox: to 2 hours

**Comment by hero101** [comment]
> This error means that ResizeObserver was not able to deliver all observations within a single animation frame. It is benign (your site will not break)

https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/50387233#50387233
