### ISSUE TITLE
UX: Split of challenge page into a separate design file

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2522]
## Description

As a developer I want a clean design just for this epic

## Acceptance criteria

- [ ] UX design specific to the phasing with challenges full page coming later

## Additional Context
Figma file: https://www.figma.com/file/aVIhqlyEgb0DtHv10OfM9O/Challenges-page-redesign?node-id=0%3A1

**Comment by techsmyth** [comment]
Looks nice and more enticing. So you think we should prefill the first search term?

**Comment by SimoneZaza** [comment]
Yes, and refer to it in the description
