### ISSUE TITLE
BUG: Console errors when opening aspect dialog

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2525]
**Describe the bug**
Errors are raised in the console when an Aspect is opened in a dialog in the Explore page.

**To Reproduce**

1. Go to <hub>/explore
1. Open the console
1. Click on an Aspect inside a Callout
1. Observe the errors

**Expected behavior**
Errors are fixed and not shown in the console.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/00e2a94e-dc9b-40c7-86f2-e21eed0e7d87)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/97ddfbbd-6223-49ae-aa5a-3d91782f6310)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/76004477-d4af-4f0b-a748-d18d287e56b4)

timebox to 2 hours, fix whatever can be fixed in the timeframe

**Comment by Comoque1** [comment]
Didn't experience the errors on DEV env.
