### ISSUE TITLE
UX: Design for simple sharing

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2533]
## Description

As a user I want to be able to share information on Alkemio

## Acceptance criteria

- [ ] Design for how we do initial sharing
- [ ] What happens if not available

## Additional Context
Figma: https://www.figma.com/file/dkCUsPmEynd66Ysm1JXyUR/Sharing?node-id=41%3A255

**Comment by SimoneZaza** [comment]
@techsmyth simple version ready on page one

**Comment by techsmyth** [comment]
Nice and simple...
