### ISSUE TITLE
Adjust description on hub dashboard/explore/about depending on whether a user is a member or not

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2536]
**Describe the bug**
When a user is not a member of a private hub, the description of the dashboard/explore/about page should be different.

**Expected behavior**
Show different message based on user having the READ privilege on a Hub:  
- For users with the READ, message is as it is now
- For users without the READ, they see a different message which is initially set to:
"The content of this hub is only visible to members. Interested in reading more? Please join!"

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b77abddb-ea98-4f97-bae7-76323ef21162)

**Comment by ccanos** [comment]
The descriptions are coming from
https://github.com/alkem-io/client-web/blob/develop/src/domain/shared/layout/PageLayout/SimplePageLayout.tsx
