### ISSUE TITLE
Spike: addition of top level queries to retrieve entities

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2548]
## Description
As a client develop I want to have a code base that is easy to maintain

## Acceptance criteria

- [ ] Certain entities to be queryable via top level queries via graphql api: collaboration, community, context
- [ ] Evaluate impact on client code base by having direct access to the entity without context
- [ ] List of where we duplicate queries to deal with hub / challenge / opportunities

Timebox to: half a day

Server queries added in https://github.com/alkem-io/server/pull/2424

## Additional Context
A lot of code on the client is convoluted as additional context is needed to e.g. retrieve an aspect. It is likely the code base can be much simpler if direct graphql retrieval of an entity by UUID is allowed. 

Note: this is allowing direct retrieving of a particular entity, e.g. Canvas, via UUID. It relies on the authorization policy of the target entity being properly set, as it would no longer need the parent entity access to retrieve the child entity. 

The goal of this spike to understand both the impact on the client and the security impact on the server.

**Comment by alstojanovic** [comment]
Full analysis: https://hackmd.io/F4QUg2hESdqz1-GhZSTgIQ?view

**Comment by techsmyth** [comment]
@alstojanovic thanks for the analysis. We certainly could also expose callouts / cards / canvases directly but am not sure that would be the right solution. It might be better to have each journey page one time as part of the top level provider to obtain the id for the relevant collaboration / context / community and then pass that in to the relevant component as a prop? @me-andre  your thoughts? Fundamentally we should not need to be passing around the full journey context.

**Comment by alstojanovic** [comment]
Agree, but we don't need callouts / card / canvases as top level but rather just as a resolved fields with mandatory ID argument. The current `callouts(IDs)` is a bit pointless because we are almost always using it to fetch only one callout and then need to use .find() on the client to retrieve it. We agreed to talk about this tomorrow on the SEE meeting so I think we can come up with a best approach to deal with these issues.

**Comment by techsmyth** [comment]
@alstojanovic that would make sense: another field on collaboration to return a single callout. Ditto on callouts to have a field to return a single aspect / canvas then?

**Comment by alstojanovic** [comment]
Yes, exactly
