### ISSUE TITLE
New Activitylog component on dashboard

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2552]
## Description

As a User I want to see the latest activity related to the Callout of this Hub/Challenge/Opportunity
As a Lead I want to entice Users to contribute to the Callouts

## Acceptance criteria
- [x] New dashboard component for [Activitylog] as per Figma design
- [x] Five latest Activities displayed
- [x] Clicking on User avatar links to User profile + hover over User avatar shows User preview
- [x] First line of text with time and a static description of the activity type:
- Added a new Card
- Published a new Callout
- Joined the Community
- Added a new Canvas
- Commented on a Card
- [x] Second line of text is the description from the log entry

TBD Information displayed per activity is as below
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/276f1623-817d-458e-ac13-5e0451be3b06) 

## Figma link
https://www.figma.com/file/MIjrxdRWOjxJwzfwpc4hlm/Dashboard-page-refresh?node-id=1%3A47

**Comment by Comoque1** [comment]
When registered user navigates to a hub, that is private, the 'Latest activity' panel shows infinite loading for the activities
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0098989b-2f18-4c00-ae0c-b0ec20cda8cf)

**Comment by Comoque1** [comment]
Raised separate issue for above comment: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2600

Closing the story.
