### ISSUE TITLE
Search form refresh

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2557]
## Description

As a User I want a user-friendly/enticing search page

## Acceptance criteria

- [x] New header layout as per figma file
- [x] Search icon to the right
- [x] Search icon is clickable and navigates you to the search page (using search terms if entered)

## Additional Context
![Schermafbeelding 2022-09-07 om 10.59.56.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/5af6de55-2565-42d9-a19b-65a251e5319f)

**Comment by techsmyth** [comment]
https://github.com/alkem-io/client-web/issues/2657 - search being triggered with empty text

**Comment by Comoque1** [comment]
Search is not visible, between 580px and 740px browser width
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bb4e57f3-f961-4558-a889-64be8e222b74)
