### ISSUE TITLE
Associates for organizations?

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2586]
## Description
As a dev team member I want a consistent terminology between client and server. We call them associates on the organization page, members on the organization card, and members in the back-end

## Acceptance criteria

- [ ] TBD change member attached to organization into associate?

## Additional Context
![Schermafbeelding 2022-09-09 om 14.25.27.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/ab8b21d7-1d01-4c67-87bd-1240e8c4b717)
![Schermafbeelding 2022-09-09 om 14.25.41.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/8c7d8d47-110d-422c-a6a9-cef56cd179da)

**Comment by techsmyth** [comment]
Spliting this one into two, one for client and one for server
