### ISSUE TITLE
BUG: Missing validation on comments links

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2588]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/comments-hub/challenges/comments-challenge/explore/callouts/card-default/aspects/3333-7810/dashboard
2. Create a comment with link:  [link without protocol](test.com)
3. Click on the link in the new comment - the link i added to the base URL and user lands on empty page ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/03c9b344-7da1-4d54-a942-ea885f54d006)
4. When user set valid link with external endpoint, he is redirected to the page on same tab

**Expected behavior**
When invalid link is to be sent in the comment, validation is applied.
External links are open in new tab.

**Comment by techsmyth** [comment]
Can you suggest what kind of validation should be applied? I do not think we actually can do sensible validation here.
