### ISSUE TITLE
Share icons added

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2590]
## Description

As a communications lead I want to share the content in an easy way with others

## Acceptance criteria
- [x] Hub Challenge Opportunity
- Button top right with share icon
- Button under the About this Hub on Dashboard
- Both lead to share dialog
- [x] Callout: button with share icon next to settings that opens share dialog
- [x] Cards dialog: 
- Tab with icon top right next to settings 
- Tab displays Card + references left and share options right
- [x] Canvas dialog: button with icon top right
- Click on button opens share dialog

## Design
Figma: https://www.figma.com/file/dkCUsPmEynd66Ysm1JXyUR/Sharing?node-id=41%3A255

**Comment by Comoque1** [comment]
For all authenticated users, 'Share this hub button', must be under 'About this Hub' container (not on the bottom of the page):
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/11e3c8d5-cc77-4f10-a1cd-5506750076a4)
