### ISSUE TITLE
BUG: Header image disappears on mobile device

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2592]
**Describe the bug**
On a mobile device, the header image disappears behind the title of a hub/challenge/opp

**Expected behavior**
As a user I expect to see the header image on top and the title below

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/0b7c1d1a-afca-4192-b67f-29be1abf0a08)

**Additional context**

**Comment by ccanos** [comment]
fixed already
