### ISSUE TITLE
Add visuals description as alt text to images in banners

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#2593]
## Description

As a user with vision impairment I want alternate texts added to Visuals and other images so my screenreader can help me through the website

## Acceptance criteria
Top priority:
- [ ] Platform page
- [ ] Hub/Challenge/Opportunity banners have description as `alt` attribute

Next priority:
- [ ] Cards banners have description as `alt` attribute
- [ ] User/Organization avatar have description as `alt` attribute

Timebox: half a day

**Comment by techsmyth** [comment]
Split out into separate epic
