### ISSUE TITLE
Spanish language translation

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2598]
## Description

As a spanish user I want to see the spanish language on the UX

## Acceptance criteria

- [ ] Translation for spanish added to client

**Comment by ccanos** [comment]
Callout = Aviso ?? 
Canvas = Pizarra ??
hub = hub
discussion": "Debate",

card = Tarjeta

challenge": "Desafío"

dashboard": "Inicio",
    dashboard Panel de control

lifecycle": "Ciclo de vida",

feedback= feedback
banner = banner

parent= contenedor

NameId = Identificador

Flujo de Innovación

**Comment by techsmyth** [comment]
Afraid my spanish is no help in this one :) Only steer I can give is that it may be ok to keep the english terms in places - will depend per language...
