### ISSUE TITLE
BUG: On FF the message of an update is in black background

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2609]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/hub-release-15-09-2022/challenges/chall-release-15-09-2022/dashboard/updates on FF browser
2. The color of the message background is black
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/70ff4239-05d3-46b1-b236-75f76f716933)

**Expected behavior**
The color of the message background is consistent with the one on Chrome

**Comment by techsmyth** [comment]
It looks like it is picking up your theme,this is what I see:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/a76ae26f-89aa-4886-8fc3-2d6ad185d1b5)

**Comment by Comoque1** [comment]
This one is already addressed.
