### ISSUE TITLE
Text for activity entries

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2610]
## Description

As a user I want to see interesting content in the activity log 

## Acceptance criteria

- [ ] Text per activity updated

## Design
https://www.figma.com/file/MIjrxdRWOjxJwzfwpc4hlm/Activity-log?node-id=0%3A1
![Schermafbeelding 2022-09-22 om 13.06.50.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/4703149a-bced-443c-a878-beda805cfc66)

**Comment by larssondenise** [comment]
@techsmyth updated

**Comment by techsmyth** [comment]
Please have a look again with https://github.com/alkem-io/server/pull/2244
