### ISSUE TITLE
Spike: Error handling

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2639]
## Description

As an Alkemio user 
I want to see meaningful error messages
so that I am not confused by excessive information.

## Acceptance criteria

- [ ] A small prototype with a single translated error message and the structure for future extensions created
- [ ] two modes - dev (with stack trace) & prod (without stack trace)
- [ ] full error + stack trace sent to Sentry
- [ ] PII configurable for Sentry

Timebox to half a day

## Additional Context

- [ ] Client-side error handling based on Apollo error codes (the server already wraps them and provides codes)
- [ ] Configurable visibility of error stack trace based on NODE_ENV (stack trace should not be visible with NODE_ENV=production)
- [ ] translation of all error messages to the main languages we use
- [ ] full stack trace sent to Sentry on error
- [ ] PII configurable for Sentry based on a flag

**Comment by Comoque1** [comment]
To be tested on ACC
