### ISSUE TITLE
UX: Admin for Innovation Hub

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2641]
## Description

As an admin I want to know how to manage Innovation Spaces

## Acceptance criteria

- [ ] New tab in global admin settings with list of Innovation Hubs
- [ ] For each innovation hub a profile page with two blocks:
     - [ ] "Profile": 
         - [ ] Title
         - [ ] NameID
         - [ ] Tagline
         - [ ] Host Organization
         - [ ] Description
         - [ ] Visual
     - [ ] List of visible spaces, table showing:
         - [ ] Title
         - [ ] Visibility
         - [ ] Host organization
         - [ ] Remove button

## Design
Figma: https://www.figma.com/file/wZkvw4E1KhRq9Ga6L6HmSL/Innovation-Spaces?node-id=655%3A2489&t=mBk3adJgr9jcJkPE-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/ca0779f9-0210-4f5a-93ca-a43e93da2913)

**Comment by techsmyth** [comment]
@SimoneZaza looks good - a couple of comments added as we need a couple of additional options shown. In particular the subdomain to match is key. Further we basically have two filtering paths: visibility or list of spaces, and the user needs to choose which one to use.
