### ISSUE TITLE
New create dialog for challenge, opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2646]
## Description

As a hub / challenge admin I want to have a nice experience in creating challenges / opportunities

## Acceptance criteria
- Challenge
     - [x] Challenge title
     - [x] Challenge question = tagline
     - [x] Current reality = background
     - [x] Future vision = vision
     - [x] Tags
- Opportunity
     - [x] Opportunity title
     - [x] Opportunity tagline
     - [x] Description = vision
     - [x] Tags
- Both
     - [x] do not specify the nameID on challenge / opportunity (generated on the server)
     - [x] Taglines restricted to 80 characters in length
- Admin 
     - [ ] Admin forms (create Challenge / Opportunity) replaced with the dialogs for creation of Challenge / Opportunity
- [x] CreateOpportunityInput and CreateChallengeInput are updated - the InnovationFlowTemplate should be optional
- [x] InnovationFlowTemplate `default` is the first template (for now)

## Design
https://www.figma.com/file/nyMxnaOQbhGwtIzvJjsQmU/Create-challenge%2Fopportunity-in-context?node-id=0%3A1 

## Additional Context
All old fields (vision, background, impact, who) are used, but only with different labels per Hub / Challenge / Opportunity

**Comment by valentinyanakiev** [comment]
@techsmyth how do we pick defaults?

**Comment by Comoque1** [comment]
New dialog is not available for opportunity creation from admin page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/81c3db7e-5b9b-4956-82df-e49e78ae5228)

**Comment by hero101** [comment]
@Comoque1 This is the desired behavior.

**Comment by Comoque1** [comment]
According to AC:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b70d9da4-b300-4f15-8a15-8d32d69d5c72)

**Comment by Comoque1** [comment]
@techsmyth, is the `tag` required field, when creating, challenge / opportunity?

**Comment by Comoque1** [comment]
Raised a separate card for Opperation creation from Admin area: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2729
