### ISSUE TITLE
New innovation flow admin tab on Challenges + opportunities

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2648]
## Description

As an admin I want to be able to manage the innovation flow

## Acceptance criteria

- [ ] New tab displaying the current innovation flow, and triggering next actions
- [ ] Remove display of innovation flow from the profile tab (in admin)
Note: updating the innovation flow being used is moved to a separate issue.

## Figma
https://www.figma.com/file/4T9jAFgo3QLUaRn0lZZm5Q/Innovation-flow---Admin-tab?node-id=0%3A1

**Comment by valentinyanakiev** [comment]
@techsmyth can you please add a link to the figma file

**Comment by SimoneZaza** [comment]
@valentinyanakiev, @larssondenise , @techsmyth yes, done. https://www.figma.com/file/4T9jAFgo3QLUaRn0lZZm5Q/Innovation-flow---Admin-tab?node-id=0%3A1

**Comment by alstojanovic** [comment]
@larssondenise Can you just point me where to find the correct icon for the tab? I am using some similar one just as a placeholder but I will need the right one to finish the task.
