### ISSUE TITLE
BUG: When browser width is between 580px and 740px , search is not accessible

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2670]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Decrease browser width to be between 580px and 740px - 'Search' bar or settings are not visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d9f36087-2a01-406e-9eae-9772c73b5184)

**Expected behavior**
Search is accessible on all browser width dimensions. Switch to mobile navigation from 740px.

**Comment by SimoneZaza** [comment]
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/30bdddea-57a0-4cae-8c43-b15f9e0f1ff9)
I think a browser width below 740 is very rarely used on desktop, so let's just use the mobile design.
