### ISSUE TITLE
Navigating by clicking on banners or titles

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2675]
## Description

As a user I want to be able to go (back) to the dashboard of a hub/challenge/opportunity easily by clicking on the h/c/o title or banner, etc.
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1b871b64-e4e3-4ea7-b6cd-64f66ad9ccd2)

As a user I would like to go to my profile when I click on my profile picture or my name in the dropdown that opens when I click on my picture in the navigation bar. (Aside from the option to just click on 'My Profile')

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/00f928db-2c68-42d6-8977-c7aa565596c8)

## Acceptance criteria

- [ ] Gap analysis of where links are missing in titles on cards etc. 
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by MayteRagni** [comment]
- a "go back" button should be inserted, to give users the possibility of quickly going back to the desired page
- the banner should be clickable and it should re-direct you to the landing page, while the Alkemio logo should bring you back to the dashboard of the platform 
- ....

**Comment by Roseghost** [comment]
- [ ] Title of "My Hubs" 
     - Should lead to my Hubs overview
     - Found on Homepage
     
- [ ] Title "Explore the Challenge Hubs!" 
     - Should lead tothe hubs overview page
     - Found on Homepage
 - [ ] Title "See who is driving Challenges on Alkemio"
     - Should lead to the Contributors page
     - Found on Homepage
 - [ ] Title of "Challenges" inside a hub
     - Should lead to challenges overview of that hub
     - Found on Hub pages
- [ ] Title of "Events"
     - Should lead to the same page "More Events" buttom or the expand function leads to
     - Found in Hubs
- [ ] Title of "References"
     - Should lead to same place where "More References" below leads to
     - Found in Hub, Challenges and Opportunities 
 - [ ] Title of "News"
     - Should lead to same place where "More News" below leads to
     - Found in Hub, Challenges and Opportunities     
 - [ ] Title of "Contributors"
     - Should lead to same place where "More Contributors" below leads to
     - Found in Hub, Challenges and Opportunities      
  - [ ] Title of "Users"
     - Should lead to same place where "More Contributors" below leads to
     - Found in Hub, Challenges and Opportunities      
  - [ ] Title of "Opportunities"
 
![image](https://github.com/alkem-io/client-web/assets/64191883/dee22f75-9494-4325-98a8-3a472ddf28ab)
 
     - Should lead to same place where "More Opportunities" below leads to
     - Found in Challenges                
  - [ ] Title of all the Context titles within hubs and opportunity
     - Should lead to where the expand option leads the user. 
     - Found in Hub and opportunity context page
  - [ ] Title of all the Context titles within Challenges
     - Should lead to where the expand option leads the user. 
     - Found in Challenges context page
