### ISSUE TITLE
Updating of innovation flow

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2677]
## Description

As an admin I want to be able to update the innovation flow for a challenge / opportunity

## Acceptance criteria

- [ ] Add a new button to the Innovation Flow tab on Challenge / Opportunity to allow the admin to choose a new innovation flow template
- [ ] Innovation flow templates presented to the user to be all those of the appropriate type (challenge / opportunity)

## Figma
https://www.figma.com/file/4T9jAFgo3QLUaRn0lZZm5Q/Innovation-flow---Admin-tab?node-id=0%3A1

**Comment by Comoque1** [comment]
The buttons, for states change are differently located with respect to the mockups.
The Used template (display name) is not shown.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9acafb52-8d00-4a7e-acb2-4ddf2ee4f1a6)

**Comment by alstojanovic** [comment]
This was a known leftover, opened a new PR with updates.

**Comment by alstojanovic** [comment]
@techsmyth We don't have the Dutch and other translations, do we go only with English?

**Comment by techsmyth** [comment]
@alstojanovic yes!
