### ISSUE TITLE
Upload images (public) when editing markdown

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2704]
## Description

As a user I want to be easily able to upload public images
As a user I want to be easily able to upload public documents

## Acceptance criteria
- [ ] Users are able to upload images for usage in Markdown
- [ ] Users are able to upload documents for usage in Markdown / References
- [ ] Users are warned that the content is then accessible via a public URL

tbd:
- [ ] record of content uploaded per hub / challenge / opportunity?
- [ ] Size limitations?

TBD: ability to resize
TBD: ability to copy/paste a screenshot in?

## Design
Figma: https://www.figma.com/file/xvkk0I0bFyOnJVeBeEk4zv/Preferred-language-and-markdown-image-upload?node-id=0%3A1&t=1yoRmN19EY5Qo9Cj-1

**Comment by KayleeS96** [comment]
Design for uploading an image, now has the 'warning' and a paperclip icon. Added an extra option to allow drag and drop if we would want that

![image](https://user-images.githubusercontent.com/79141092/228249902-be48902b-d316-4a64-b70c-312d96f561b2.png)
