### ISSUE TITLE
Update user cards under leading users 

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2713]
**Describe the change**
Leading users on the about page are too big compared to the leading/facilitating organizations cards

**To Reproduce**

1. Go to any About page, such as https://alkem.io/challengecentric/about
2. Scroll down to the Community
3. See cards for leading users
![Schermafbeelding 2022-10-04 om 13.28.49.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/54ef93cc-8419-4cef-bae6-022580a882f3)

**Expected behavior**
For leading users we want similar cards to the organizations such as the one on the dashboard pages
![Schermafbeelding 2022-10-04 om 13.30.39.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/4d492c1d-6edf-4151-bc35-53f8df2999f6)

**Screenshots**

**Additional context**

**Comment by larssondenise** [comment]
@me-andre definitely
1. Yes Hub, Challenge and Opportunity! To align all the lead org cards with lead/host member cards
2. only leads! Contributing members will be the squared small ones, contributing orgs should be squared small ones as well. That change request has been included in #2714 I think!

**Comment by Comoque1** [comment]
On Challenge and Opportunity `About` page, Lead user tags and location are not displayed:
About page: 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/35393d22-7798-4af2-be48-993735b42492)
Dashboard page:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b8f2d7df-a6c6-41e9-8380-a552c2e108a2)
