### ISSUE TITLE
BUG: Creation of Opportunity / Challenge from admin area is not using the new dialog

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2729]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/join/challenges/123-1565/opportunities/new - old form of an opportunity creation is being used
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/edd57745-0122-404f-8b47-db73ea54293d)

**Expected behavior**
When user creates an Challengefrom admin area, the new dialog is used (the one from hub.challenges page)
When user creates an Opportunity from admin area, the new dialog is used (the one from challenge.opportunities page)

The after completion the user is brought to the new entitty.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/334bc5f2-d794-4560-a7fc-6978053d3e22)

**Comment by techsmyth** [comment]
@Comoque1 same for creation of challenges
