### ISSUE TITLE
Explanation for InnovationFlows

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2735]
## Description

As an admin I want to understand what InnovationFlows are + how they are used

## Acceptance criteria

- [ ] Add explanation text at the top of the InnovationFlow tab for challenges / opportunities admins
- [ ] Add similar text for InnovationFlowTemplates

## Design
https://www.figma.com/file/4T9jAFgo3QLUaRn0lZZm5Q/Innovation-flow---Admin-tab?node-id=0%3A1

**Comment by techsmyth** [comment]
Thanks @SimoneZaza - that box works for me

**Comment by SimoneZaza** [comment]
no longer relevant
