### ISSUE TITLE
Allowing closing of Callouts for new cards / canvases

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2740]
## Description

As a callout admin, I want to have callouts where users cannot add new cards / canvases

## Acceptance criteria

- [ ] Update dialog for a Callout to have an additional checkbox to allow the addition of new cards / canvases 
- [ ] Cards callout: display to not show the "+" button if the callout state is CLOSED
- [ ] Canvases callout: display to not show the "+" button if the callout state is CLOSED
- [ ] Discussion callout: to not allow the addition of new comments if state is CLOSED
- [ ] Server logic to not allow new cards / canvases / comments (direct) when in CLOSED state

note: still allow comments on cards for now

![Schermafbeelding 2022-09-19 om 14.32.51.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/c811740c-c896-442c-a5c7-6986c1e0f67a)

**Comment by Comoque1** [comment]
All points from AC are working fine on DEV env.

@techsmyth, I have a couple of questions on which is needed your confirmation:
- community admins and GA cannot cards to closed callouts: 
- community admins and community members can modify existing cards / canvases of closed callouts
- callout state is missing (visually) - I can raise separate card?
