### ISSUE TITLE
BUG: Unauthenticated users see 'Share' button

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2743]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/join/dashboard without getting authenticated - 'Share this Hub' button is available
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/45f074bf-05df-49e4-bc96-34f01c297f92)

**Expected behavior**
Unauthenticated users should not see 'Share' button.

**Comment by techsmyth** [comment]
Why not? the link is still valid...

**Comment by Comoque1** [comment]
Spoke with @SimoneZaza and was suggested that unauthenticated users should not see the button.
