### ISSUE TITLE
UX: Extended functionalities on explore page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2769]
## Description

As a user I want to be able to easily navigate through the explore page to find relevant content

## Acceptance criteria

- [ ] Search
- [ ] Filter
- [ ] "Table of content"
- [ ] Pin ?

## Design
https://www.figma.com/file/ozjif7A9pJiS7YeYY71Dcf/Journey-Pages---Contribute-tab?node-id=0%3A1

**Comment by SimoneZaza** [comment]
@techsmyth I've added the ordering of the callouts in the list and the labels for draft & closed callouts.

**Comment by techsmyth** [comment]
@SimoneZaza looks great! It does trigger some other questions, so suggest we take up a wider review after you are back...key will be how to stage this work as would not want to do all this in one go. Sorting is a clear one that can be split out, cards likely also.
