### ISSUE TITLE
Capture errors on password reset / verification email

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2775]
## Description

As a devops admin I want to know when errors happen on password reset / email verification

## Acceptance criteria

- [ ] Add logging to sentry / equivalent when errors happen on password reset or email verification

**Comment by alstojanovic** [comment]
@valentinyanakiev  the recovery flow error is already being captured in sentry. Is the task to add more information to the logs for this flow?
https://sentry.io/organizations/alkemio/issues/3602221277/events/?project=5862875&query=recovery&statsPeriod=14d

**Comment by techsmyth** [comment]
the password reset errors were not being captured - has something changed?

**Comment by alstojanovic** [comment]
Not that we are aware of.  If you open the logs in sentry, the oldest dates from October 7th.
