### ISSUE TITLE
BUG: Link in comments is opened in the same tab

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2783]
**Describe the bug**
When clicking on a link in a comment on a callout, this link opens in the same tab, leading the user away from the Alkemio platform.

**To Reproduce**

1. Go to https://alkem.io/challengecentric/challenges/enabling/explore/callouts/newcolorscheme-5898
2. Click on 'here' in Svetoslavs comment
3. The mui website opens in the same tab

**Expected behavior**
As a user, I expect a link to open in a new tab (or window) in my browser.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1b843225-1d9d-430d-acb2-4d4974f89104)

**Comment by Comoque1** [comment]
Closing, as this issue is duplicate to `Hyperlinks in cards: no new window/tab opened #858`. Will be addressed for all MD links.
