### ISSUE TITLE
Spike: create a design + approach to deal with create a Social Sign-up Flow - Accepted Terms

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#2784]
## Description

As an Alkemio User 
I want to have uninterrupted social flows with no weird messages in the middle of the flows
so that I can easily use my social accounts.

## Acceptance criteria
- [ ] Client flow where `accepted_terms` property is sent on the initial social sign in / up requests
- [ ] User-friendly error messages if the flow is interrupted and is not complete
Spike to half a day

## Additional Context

This is how our identity schema looks, it has `required` `accepted_terms` property. We don't provide it in the `Sign in` flows, just on the `Sign up` flows. We need to find a way to use it with social sign-ins where `Sign in` and `Sign up` are merged into a single flow.

```json
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "title": "First Name",
              "type": "string"
            },
            "last": {
              "title": "Last Name",
              "type": "string"
            }
          }
        },
        "accepted_terms": {
          "title": "TERMS_MESSAGE",
          "type": "boolean"
        }
      },
      "required": ["email", "accepted_terms"],
      "additionalProperties": false
    }
  }
}

```

**Comment by SimoneZaza** [comment]
Figma: https://www.figma.com/file/Yg0HQX5RXbUCQiaAhwx6n0/Sign-up-page?node-id=0%3A1

**Comment by valentinyanakiev** [comment]
Followed up with Simone, updated the design and created a workflow for social sign ins (workflow chart)
