### ISSUE TITLE
Create activity description using translations

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2792]
## Description

As a user I want the descriptions to be translatable
As a developer I want to have control over the activity description

## Acceptance criteria

- [ ] Activity descriptions should be generated using translations + available data

## Additional Context
The description is currently picked up directly from what is in the log entry on the server, which is fragile. The text to be displayed should be created on the client.

As an intermediate step the existing descriptions can be wrapped:
const updatedDescription =  t('components.activity-log-view.activity-description.callout-published', {description: props.description});

 "activity-log-view": {
      "actions": {
        "callout-published": "published a new $t(common.callout)",
        "canvas-created": "added a $t(common.canvas) to '{{parentDisplayName}}'",
        "card-comment-created": "commented on $t(common.aspect) '{{cardDisplayName}}'",
        "card-created": "added a $t(common.aspect) to '{{calloutDisplayName}}'",
        "discussion-comment-created": "commented on '{{calloutDisplayName}}'",
        "member-joined": "joined",
        "challenge-created": "created a new $t(common.challenge)",
        "opportunity-created": "created a new $t(common.opportunity)"
      },
      "activity-description": {
        "callout-published": "{{description}}2",
        "canvas-created": "{{description}}",
        "card-comment-created": "{{description}}",
        "card-created": "{{description}}",
        "discussion-comment-created": "{{description}}",
        "member-joined": "{{description}}",
        "challenge-created": "{{description}}",
        "opportunity-created": "{{description}}"
      }

**Comment by alstojanovic** [comment]
@techsmyth is this in review by mistake?

**Comment by techsmyth** [comment]
@alstojanovic this was done as part of the PR that was just merged about refactoring the activityLog query + usage

**Comment by alstojanovic** [comment]
ok, so it doesn't need separate review?

**Comment by techsmyth** [comment]
No, it can be part of the other one
