### ISSUE TITLE
BUG: Comments number chars doesn't correspond to the validation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2821]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/activitylog-hub/explore/callouts/card-default/aspects/cardwithmeaningful-4254/dashboard
2. Add a comment:
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
```
3. The used / available counter says 366 / 500, but when the request is performed, it fails:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0ec99024-7d0c-49cc-9bf2-d311c6978868)

**Expected behavior**
Counter of remaining chars for a comment is correct. 
The issue must be fixed on both callout discussion and card comment.

**Additional context**
On ACC env, the the behavior is correct, which means, that in current develop is reduced the number of characters to be written.

**Comment by hero101** [comment]
it seems like the `description` column of the `activity` table has smaller character limitation than the content of the message, which is inserted into activity.description.

**Comment by Comoque1** [comment]
After the changes, the user can send comments with bigger amount of chars, than the displayed limit. As far as I remember, we discussed, to show the rounded char limit to improve the visibility.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/beff6e7d-00e0-4ad4-9bd5-447c56b04fa9)
