### ISSUE TITLE
Optimize how canvases are loaded

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2838]
## Description

As a user
I want a better experience while loading my canvas
So that <some business value>

## Acceptance criteria

- [ ] Optimize the way the canvas dialog is provided with the canvas data

## Additional Context
The query selecting canvas data is outdated, addressing the needs in the older days when Canvas wasn't under Callout.

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/184e2b05-db65-4943-bf20-f0f81ee196de)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/c31712d7-051e-4439-aa1d-5ff9049516a3)

**Comment by techsmyth** [comment]
To be rechecked
