### ISSUE TITLE
Mobile: Journey page

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2840]
## Description
As a visitor, I want to see an attractive platform on my mobile device on which I can navigate through the tabs on the journey pages to see all public content
As a user, I want to see an attractive platform on my mobile device so that I can interact with it
As a team member, I want to show interested parties an attractive platform on their mobile device in which they can navigate through the tabs on the journey pages to see all public content

## Acceptance criteria
For screen sizes XS-LG:

All pages:
- [ ] Show mobile top navigation 

Journey pages: 
- [ ] Full-width header with min. height of 80px (when the screen is smaller than 480 px, start cropping the image from the center)
- [ ] Show the full title and tagline when the user clicks on the title bar (either by expanding the title bar or by opening a dialog if this is much less work)
- [ ] Floating arrow on the bottom right to move to the top of the page 
- [ ] Full-width bottom navigation component for tabs (explore, collaborate, challenges/opportunities/agreements, about, share)
- [ ] For users with admin rights, instead of the 'share' tab show 'more'
- [ ] For users with admin rights, the 'more' tab opens a bottom sheet with 'Share' and 'Settings'

## Additional Context
Design: https://www.figma.com/file/ewjYRfl8IPPCnPlY3F6nuZ/Mobile-Journey-pages?node-id=0%3A1

**Comment by hero101** [comment]
Closing this in favor of #2737, #2883. @SimoneZaza thank you for the insights.
