### ISSUE TITLE
BUG: White space above header image on mobile device 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2841]
**Describe the bug**
On my mobile phone, there is a lot of white space above the header image on the homepage. 

**To Reproduce**
This seems to be happening on XS screen sizes (575px and less)

**Expected behavior**
I expect the header to stick to the navigation bar

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/57391721-205f-4d5d-9fb1-f3270aa5207f)

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS: 15.6.1
- Browser: Safari
- Version: ?

**Comment by techsmyth** [comment]
Fixed
