### ISSUE TITLE
Create & edit single canvas type Callout

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2856]
## Description

As an admin I want to be able to create a single canvas type Callout with selected template for every new Canvas on that Callout. I also want to be able to update the canvasTemplate information on existing callouts. Also, I want an easy way of creating a callout with a clear vision on what the different types are.
_Example: I want users to share personas via the persona template that I have made._

## Acceptance criteria
Callout create/edit:
- [ ] Callout create/edit view to allow choosing a different canvasTemplate from HubTemplates or from the library
- [x] When editing, there is a warning text that it will impact future submissions & preview
- [x] When editing, buttons for comments and cards become disabled and greyed out

Canvas create:
- [ ] Callout canvas submission simplified dialog + directly open in edit mode after creating
- [ ] CanvasTemplate to be picked up directly from the Callout entity when adding a new contribution
- [ ] Visuals for the Canvas template are picked up from the CanvasTemplate

Server:
- [x] Callout entity extended to allow selecting a canvasTemplate
- [x] Update existing dto's
- [x] Migration to add the additional column to the Callout entity

## Additional Context
https://www.figma.com/file/dxSkLrIm1pZidIcDLHfZ8J/Single-Canvas-Type?node-id=0%3A1&t=KpkPumQDY0f0RQdV-1

**Comment by alstojanovic** [comment]
Agreed with @larssondenise that we go with the release without the import from library because the flow when editing a callout with canvas template from library is broken and needs a  domain model revision around template/templatesSet entities.
