### ISSUE TITLE
Default image for when there is no image selected

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2864]
## Description

As a user I want to see something nice when there is no image uploaded in a place where it should be.

## Acceptance criteria

- [ ] Default image for when there is no image selected.

**Comment by techsmyth** [comment]
@SimoneZaza actually in progress or should this be in new?

**Comment by techsmyth** [comment]
Ah hold on, you are working the image to be used - right? This will differ per usage (hub / challenge / opp etc)?

**Comment by SimoneZaza** [comment]
@techsmyth indeed, this is the image itself. I was actually thinking about a very simple standard image for all journey types, cards, etc., to keep it clear that a different image should be uploaded instead.

**Comment by techsmyth** [comment]
@SimoneZaza ok clear 👍
