### ISSUE TITLE
BUG: Deleting a card throws error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2866]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/defaults/explore/callouts/card-default
2. Create 2 cards to the existing callout
3. Delete both of the cards - error is thrown after deleting the second card: `"message": "Banner visual not defined",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e93a270f-608d-4988-bd4f-806de1ffc7ed)

**Expected behavior**
Cards, are deleted successfully and no errors are thrown.

**Comment by techsmyth** [comment]
@Comoque1 I tried this one but was not able to reproduce it locally...

**Comment by alstojanovic** [comment]
It also hard for me to reproduce but the issue is there.
