### ISSUE TITLE
New Comments subscription on Discussion Callouts is not working

### ISSUE THREAD

**Issue by alstojanovic** [alkem-io/client-web#2877]
**Describe the bug**
When a User posts a comment, it doesn't show in the discussion callout. After navigating to some other tab and back to explore page it shows up.

**To Reproduce**
Steps to reproduce:
1. Go to explore page
2. Post a comment on default discussion callout

**Expected behavior**
After posting a comment, the comment should appear in the callout.

**Screenshots**

**Comment by hero101** [comment]
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/18e1c070-5b49-4aa9-a7a3-d730e57f32d8)

**Comment by alstojanovic** [comment]
This is still an issue.

**Comment by alstojanovic** [comment]
The commenting is unusable until then. Do we want to fix this asap or wait?

**Comment by hero101** [comment]
@alstojanovic we want a workaround - I will try to think of something.

**Comment by hero101** [comment]
Closing in favor of alkem-io/server#2252.
