### ISSUE TITLE
Help dialog

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2879]
## Description

As a user
I want easy access to help, faq, and new updates
So that I am quickly onboarded and can see all the updates and help I need

### FAB
- [x] A floating action button (FAB) in the right bottom corner is present on desktop and mobile versions
- [x] The current "Go to the top" button is displayed on the top of the desktop and mobile versions
- [x] Clicking on the FAB opens a dialog
### Dialog
- [x] The text in the dialog is translatable
- [x] Text is shown as Markdown
- [x] Three buttons are present, which opens links in a new tab..
- Help - use the link for support
- Community Forum
- New user? start here (link to onboarding page on website, ask Denise)
- [x] A link is present at the bottom
- [x] Links are read from the server configuration

### Server configuration
- [x] Four links are added to the server configuration
- [x] The value for community and release notes links will be added later 

## Additional Context
[Help dialog Figma design](https://www.figma.com/file/IcZgJtuguDeodanyH0Xy08/Help-dialog)
[React floating action button (FAB)](https://mui.com/material-ui/react-floating-action-button/)

**Comment by Comoque1** [comment]
All links / icons point to support page 
1. Help Center & FAQ: (https://alkemio.foundation/support/)
2. Community Support Forum: (https://alkemio.foundation/support/)
3. New user? Start here!: (https://alkemio.foundation/support/)
4. Looking for tips & tricks? Find them in the blog posts here!: (https://alkemio.foundation/support/)

The link in the text `here` points to help page: https://alkem.io/help and opens in the same tab, instead to new.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c4ea3680-74b1-4e30-a81e-e42fac8415b8)
