### ISSUE TITLE
Templates Import dialog - Restyle dialog

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#2890]
## Description

As an Alkemio admin (Hub admin/platform admin) I want a nicer UI when importing Canvases/Cards/InnovationFlows from innovation packs

#### Hub > Settings > Templates
- [x] Change the **Import** button to 
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/1b55a57d-4ea1-4490-a588-ae6e13137a2a)

#### Dialog restyling - This Issue doesn't include Search/Filter functionality
- [x] Title bar changes per template type to import: Canvases/Cards/Innovation flow
- [x] Cards for Canvases/Cards/Innovation flow show:
    - [x] Visual banner of the TemplateInfo (added to the current query)
    - [x] Title
    - [x] Innovation pack displayName
    - [x] Organization displayName
    - [x] Organization Logo (added to the current query)
- [x] Cards have a preview button that will put the dialog in preview mode - **not included in this task**
- [x] Cards have an Import button - On click on Import button, template is imported into the hub

## Additional Context
https://www.figma.com/file/PwLYdTm1PNEZvPMpZt94up/Platform-Template-Library?node-id=219%3A516

**Comment by ccanos** [comment]
Design changed after estimation

**Comment by techsmyth** [comment]
Very cool to see this working. A couple of pieces of early feedback:

If there are no entries of a given type then the display is not great:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/0c8737d0-c16d-4bf4-a24d-4a6904d755e6)

Clicking on preview on card has a strange jump with a back button visible behind the foreground dialog:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4cf03f37-5d3f-44e8-b272-e8350bd63ade)

**Comment by ccanos** [comment]
Requirements changed a bit after the meeting.
Now there are no buttons Preview and Import in the card, (design needs update),
When clicking on the card the user sees the preview and then they can click Import in the preview.
