### ISSUE TITLE
Markdown: allowed characters visible vs stored

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2891]
## Description

As a user, I want to know how much content I am able to add

## Acceptance criteria
- [ ] Keep current behavior in which character counter aligns to visible characters
- [ ] If the character limit is reached, don't allow the user to enter more characters
- [ ] Increase the limit on the server, put it to be ~10x the client limit
- [ ] Also check for server limit on the client
- [ ] In the edge case that someone exceeds the server limit while staying within the client limit, show validation error (design will follow)
- [ ] Log such cases

## Additional Context
Likely then that the client is carrying out two sets of calculations - and is stopping users from entering new content if either is reached to avoid errors.

The exact UX to be discussed with @SimoneZaza

**Comment by Comoque1** [comment]
@SimoneZaza, the MD limits displayed on the client are different from before - is this expected?
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2b3b06bf-b08b-466f-9d36-45bef9c03ec9)

**Comment by SimoneZaza** [comment]
@Comoque1 Ehm, no? These limits should be the same as they were, so I believe 8000 - 8000 - 2000 - 2000 ?

**Comment by SimoneZaza** [comment]
@Comoque1 and I assume we'll have some trouble with existing content when these are decreased?
