### ISSUE TITLE
BUG: Subscriptions on Updates are are not showing the updates

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2898]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/admin/hubs/hub-release-07-11-2022/communications
2. Authenticate with 2 users (User `A` has rights to create update, User `B` is member of the hub community)
3. User `B` is on dashboard page of the hub, User `А` is sending a community update to the particular hub - the update is created successfully, but it is not visible from User `B`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cb91bfb9-7993-439c-87ec-b4f4ffc22f38)

**Expected behavior**
Subscriptions are working for community updates.
Updates (Admin area) page is refreshed and the correct number of updates is displayed.

**Comment by hero101** [comment]
Closing in favor of alkem-io/server#2252.
