### ISSUE TITLE
BUG: opening a card + then closing it causes data to reload

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2958]
**Describe the bug**
Data is being reloaded which makes the interaction on busy pages painful

**To Reproduce**
Go to https://alkem.io/challengecentric/explore and open a card + then close it - the data is being reloaded. 

**Expected behavior**
The data should not be reloaded if a user pops up a dialog and then closes it.

**Comment by techsmyth** [comment]
@alstojanovic this has to be solvable - am curious what you came up with!

**Comment by alstojanovic** [comment]
@Comoque1 With this issue please check that hubCanvases (challengeCanvases and opportunityCanvases) query isn't triggered on explore page load. This query was loading data that was already being loaded with HubCallouts etc. queries.
