### ISSUE TITLE
Notify admins that they should contact Alkemio support to update innovation flows

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2962]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/admin/hubs/hub-release-07-11-2022/challenges/challenge-release-07-196/innovation-flow
2. Authenticate with CA
3. Try to update innovation flow - authorization error is thrown.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/139ea1b3-5269-461a-b268-ddd226a7181a)

**Expected behavior**
Challenge admin can update the used challenge innovation flow template.

**Comment by larssondenise** [comment]
Issue seems to be solved, so closing!
