### ISSUE TITLE
Proper 'activityCreated' subscription

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#2964]
## Acceptance criteria

- [ ] Server returns `ActivityLogEntry` instead of `Activity`.
- [ ] Client uses `ActivityLogEntry` instead of `Activity` in the subscription's body.
- [ ] Triggering the query on a new entry received is no longer performed
- [ ] Client counts on the full information from the subscription, rather than refetching a query

## Additional Context
This workaround was introduced because the subscription wasn't able to return `ActivityLogEntry` because of missing loaders, which are introduced via the execution context, which at the time wasn't available to the subscription context.

**Comment by Comoque1** [comment]
Latest activity on HUB, doesn't display newly created challenge
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0432d64c-d47f-4230-a653-2bc081caceea)

**Comment by Comoque1** [comment]
Latest activity on HUB, doesn't display newly created cards
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c62cb882-4bc6-4821-9106-e6d4ba0d1dab)

**Comment by hero101** [comment]
@Comoque1, I have updated your comments to a numbered list.

- 1 and 2 are also applicable to opportunities
- 3 and 4 are actually working - you are looking at the top, but they are at the bottom
- all are taken care of
