### ISSUE TITLE
Canvas: ability to center + scale to show content

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2969]
## Description

As a user I want to quickly see the contents of a canvas without having to manually scale / scroll

## Acceptance criteria

- [ ] Button to scale and center the canvas to show all content
- [ ] When a Canvas is used as a template, then this should be always done

Spike: half a day

**Comment by Comoque1** [comment]
When [creating new canvas template](https://dev.alkem.io/admin/hubs/canvases-hub/templates) using existing canvas, the content is not centered
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9adb2d56-dd4d-482c-b943-c2d1ab7b374f)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a23fef0a-a967-4231-8433-cb308f1fde0a)
