### ISSUE TITLE
New Journey Cards membership/organizations tab

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2978]
## Description

As UI champion I want to test the refresh of the cards, following material, first in a safe space 
As a User I want to be able to leave a community

Note: these are part of the bigger UI refresh 

## Acceptance criteria
Journey cards include
- [ ] journey icon
- [ ] journey title
- [ ] tagline
- [ ] Hub title in case of challenges opportunities
- [ ] option to leave
- [ ] member/lead icon (top right corner)
- [ ] lock icon - private icon
- [ ] Ensure it's possible to implement via composition other variations of the card.

Technical:
- [ ] Mark old cards as deprecated through jsdoc

## Design

https://www.figma.com/file/CbYDZUjipUx6dEJR7Dr0H0/Personal-profile-settings?node-id=0%3A1&t=6fYVFk5cGUEYQYTr-0

**Comment by hero101** [comment]
The figma file isn't able to be opened
