### ISSUE TITLE
Visualization refresh for Innovation Flow

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2999]
## Description

As an admin I want a good representation of the InnovationFlow

## Acceptance criteria

- [ ] Design for how we display the states and associated information for an InnovationFlow

## Suggested Design
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/d4629b0d-ccca-4cd3-8b80-9191a0a6f63f)
https://www.figma.com/file/SKe3YDHm3Rs7yzuDohHSPK/Innovation-flow-design?node-id=0%3A1&t=U0T4uQbNSZauPztq-1

**Comment by techsmyth** [comment]
@SimoneZaza looks grat!

**Comment by techsmyth** [comment]
@SimoneZaza looks grat!

**Comment by SimoneZaza** [comment]
no longer relevant
