### ISSUE TITLE
Canvas dialog refresh

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3013]
## Description

As a user I want an easy way of interacting with the canvas

## Acceptance criteria
CANVAS:
- [ ] Creator + published date added on top
- [ ] Edit button bottom right 
- [ ] When checked out by other user: edit button is disabled + text to explain that is checked by user X

CREATE/EDIT CANVAS:
- [ ] Clicking on the plus card in a Canvas Callouts results in opening Canvas directly in edit mode 
- [ ] When creating, Canvas initial value is CanvasTemplate value
- [ ] Title input field 
- [ ] Delete button. Click on delete opens confirmation dialog to ask are you sure
- [ ] Save button (is save & stop editing)
- [ ] Click on close button opens confirmation dialog to ask if you want to save or not 

## Design
https://www.figma.com/file/LNuYfQWbq12zLWNmUPNHHw/Canvas-dialog?node-id=0%3A1&t=6xWw3jPCzM1km2L8-1

**Comment by Comoque1** [comment]
Closing the issue as it is already merged to master.
Raised a separate bug, regarding the 3rd point of AC, is doesn't seem implemented:
BUG: When checked out by other user: edit button is NOT disabled + text to explain that is checked by user X is shown but not the concrete user #3396
