### ISSUE TITLE
BUG: Removing canvas tempate from a hub, throws an error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3023]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/hubs/hub-release-25-11-2022/templates/canvas-templates/
2. Open browser dev tool
3. Remove a Canvas template - error is thrown for the response: `"message": "Cannot return null for non-nullable field CanvasTemplate.id.",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f193d850-1ef1-451c-b5b5-83c1f2a97eaf)

**Expected behavior**
No error is thrown, list of available items is refreshed.

**Additional context**
The impact of the bug is low, as the entity is actually remove. The client is trying to retrieve it after that.

**Comment by Comoque1** [comment]
Still getting an error, when delete canvas template
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8df1b929-d7a7-4145-9390-6db208e4e95d)

In addition, the request triggered from the client, doesn't seem right:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6311829c-eae0-4455-9a37-510ebb1ca92d)

**Comment by techsmyth** [comment]
I just tested it with latest on client + server, it is working find for me.

**Comment by Comoque1** [comment]
The issue is still reproducible on DEV env.
Steps:
1. Create canvas on hub
2. Navigate to hub settings
3. Create a canvas template using the created canvas
4. Delete the created canvas template: error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/17c5f1e2-f31d-4c65-901d-32c27aa3a968)
[Uploading... image.png]

**Comment by techsmyth** [comment]
@Comoque1 please try deploying from develop branch onto test + check it there. The code is working fine locally but not on dev - could something have gone wrong in terms of the code on dev?

**Comment by Comoque1** [comment]
@techsmyth, yes, looks like there is something wrong with DEV env. Yesterday I recreated the db, but this resolved only the issue with the deletion of hub/challenge/opportunity. 
On TEST env., using develop branch, canvas templates are being removed successfully.
