### ISSUE TITLE
Journey Pages MVP - Global Styles + Typography

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#3055]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Typography updated
- [ ] Text / font changes
- [ ] CSS / colors

## Additional Context
https://www.figma.com/file/yTQkqDOwJCPTBSpX9ZS0CS/Version-1---December-2022?node-id=0%3A1&t=qj1prIyLq0yCFCmS-0

## Notes
For the text styling, create a set of components for each style we have in the Library (`Heading`, `Paragraph`, `Caption` etc), so that we never provide any customizations such as fontWeight manually.

Details are in the figma file

**Comment by techsmyth** [comment]
@Comoque1 not sure how much testing you can actually do on this one from a QA perspective, not least as this has been merged to the journey-refresh branch
