### ISSUE TITLE
BUG: HubProvider query is querying templates

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3070]
**Describe the bug**
The impact of having `templates` being queried as part of "hubProvider" query is that there may be many and big templates added to the hub, which would have significant impact on the server load.

**To Reproduce**

1. Go to https://acc.alkem.io/hub-release-27-10-2022/dashboard
2. Open browser dev tools
3. Refresh the page and observe `hubProvider` query: it contains `templates` as part of 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b19ec427-0cf3-47ad-9acd-5b7dee8cc13f)

**Expected behavior**
 `templates` are not part of `hubProvider` query.

**Additional context**

**Comment by techsmyth** [comment]
Templates are no longer part of this query which is good. A separate issue has been raised for the new query for hubTemplates loading too much data, especially for Canvases.
