### ISSUE TITLE
BUG: HubDashboardReferences request is failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3071]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/hub-release-27-10-2022/dashboard
2. Open browser dev tools
3. Refresh the page: HubDashboardReferences is failing randomly
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/53ecefa6-46ee-4772-a461-481aa8e1078a)

**Expected behavior**
HubDashboardReferences succeeds every time a user navigates to hub page.

**Comment by techsmyth** [comment]
To be checked again now that journey pages are refreshed

**Comment by alstojanovic** [comment]
Checked it. it's renamed to HubDashboardReferencesAndRecommendations and wasn't able to reproduce on acceptance env. We could add an additional skip condition to when hubId
