### ISSUE TITLE
Activity should not be visible on dashboards when do not have rights to see it

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3074]
**Describe the bug**
When I am not logged in, I can still see user profiles and information in the Latest activities of a public Hub. However, user profiles should not be visible before you are logged in.

**To Reproduce**
1. Go to 'alkem.io'
2. Click on 'any public hub'
3. Scroll down to 'latest activities'

**Expected behavior**
Activity log query should fail if the user does not have the READ_USERS  privilege (typically is not logged in).
Activity log component should state that the user should be logged in to see activity. Check READ_USERS privilege at platform level. 

Activity log query should fail if the user does not have the READ  privilege (so private hub / challenge)
Activity log component should state that the user should become a member to see activity. Check READ privilege at Collaboration level. 

Note: two different messages are shown depending on the privilege that is missing. 

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/46972269-5e09-4b89-a1d4-9dac779326f1)
Text: To see the recent contributions, please sign in or join if you are not yet a member of this Hub.
Text style: Caption

**Screenshots**
![Schermafbeelding 2022-12-09 om 16.29.54.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/1f59d5b4-4271-4597-b018-e7c78df0043d)

**Comment by SimoneZaza** [comment]
@techsmyth I think this block should just not be visible to people who are not signed in/users who are not a member on a private hub?

**Comment by techsmyth** [comment]
@SimoneZaza is it not useful to show that there is activity of some sort? Easiest indeed to just not show the block. But we also need to address this at the api level to prevent data leakage...

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise just looked at this. the query to activity should fail if the user does not have the READ_USERS privilege at the platform level. The client should check if the user has that privilege before making the query, and if the user does not have that privilege then the box should still be shown but without data (background image?) and with a message to sign in to see latest activity. Can you please make a design for that?

**Comment by SimoneZaza** [comment]
@techsmyth ![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/46972269-5e09-4b89-a1d4-9dac779326f1)
Text: To see the recent contributions, please sign in or join if you are not yet a member of this Hub.
Text style: Caption

**Comment by techsmyth** [comment]
@SimoneZaza  looks good. Simple + clear...

**Comment by alstojanovic** [comment]
@SimoneZaza 
Just to check, the error messages are:
unauthenticated user + public hub/chall = "To see the recent contributions, please sign."
authenticated user + private hub/chall = "To see the recent contributions, please join this Hub/Challenge."
unauthenticated user is accessing public hub
I added a third case when unauthenticated user is trying to access private hub. "To see the recent contributions, please sign in and join if you are not yet a member of this Hub"

**Comment by SimoneZaza** [comment]
@alstojanovic @Comoque1 Perfect!!!
