### ISSUE TITLE
BUG: Error message "Missing property" is shown for populated field

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3107]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/
2. Click on "Sign up" button - user is redirected to https://acc.alkem.io/identity/registration
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d5435cc7-4fdf-4e43-a242-5243f9b4bf58)
3. Click checkbox for T&C
4. Click "Continue to platform" button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/47153dc4-0ed3-4d18-a5e0-0cf82914677c)
5. Fill up email and password fields only and press "Sign up" button - error messages are shown for populated field
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/593c037b-2a49-4331-84f8-15c8ea86946d)

**Expected behavior**
Error message "Missing property" is shown only for not populated field.

**Comment by valentinyanakiev** [comment]
should be resolved by #3103, to be verified
