### ISSUE TITLE
Spike: Challenge page queries to be privilege aware

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3115]
## Description

As a user I want to have a view tailored for private challenges

## Acceptance criteria
Make a challenge private, and then the user is a member of the Hub but not the Challenge. The Challenge page should not generate errors and should restrict the information shown as is done on a private Hub.

- [ ] Challenge page queries to check for privileges + request data accordingly
- [ ] Detail what is remaining

Spike: reserve one day to update queries

**Comment by Comoque1** [comment]
As part of separate bug(BUG: Errors are generated, when user navigate to private hub / challenge #3350) will be addressed errors for private entities.
