### ISSUE TITLE
UX: Design home page dialog/landing page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3120]
## Description

As a not logged in user, I want a clearer view on what the platform offers me

## Acceptance criteria

- [ ] Dialog to pop-up for not logged in user
- [ ] Option to sign in/sign up, some additional info, option to click away and have a look first.

## Design - Iteration 3
Figma presentation: https://www.figma.com/proto/FmRiT6tY4T12mEMKnXitzn/Landing-page?page-id=199%3A3049&node-id=213%3A1474&viewport=-892%2C459%2C0.39&scaling=min-zoom
Figma edit&inspect: https://www.figma.com/file/FmRiT6tY4T12mEMKnXitzn/Landing-page?node-id=199%3A3049&t=XnkYKFMX2gFCJ7Nj-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/c911d9a2-5f7f-4298-b6ea-acad6479382a)

### 2 options: In a dialog or directly on the page
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?node-id=0%3A1&t=7kzwzAUHAUpPbWJF-1

### Iteration 1
Figma: https://www.figma.com/file/FmRiT6tY4T12mEMKnXitzn/Landing-page?node-id=16%3A1198&t=LB0ZcSCNqbY0VWV9-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/89170a7b-3f0c-47fe-9530-60477fb3ee26)

### Iteration 2
Figma: https://www.figma.com/proto/FmRiT6tY4T12mEMKnXitzn/Landing-page?page-id=76%3A2569&node-id=76%3A2683&viewport=455%2C217%2C0.14&scaling=min-zoom (2 pages, use the arrows on your keyboard)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b1204f9e-10ff-48b4-a7b0-11431b8e1e01)

**Comment by SimoneZaza** [comment]
Question: won't we have an issue with browsers blocking pop-ups?
