### ISSUE TITLE
Spike: calendar components

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3161]
## Description

As a user I want to see events in my community

## Acceptance criteria

- [ ] Research the options for React calendar components, and select one to try out
- [ ] Mock up the data that is fed into the component
- [ ] Capture findings: what are the data implications (format used, updating etc), ways to display

Timebox to 0.5 days in a joint session with Product. 

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/a51c5f62-eaab-46d2-afe0-14c363c3596e)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ee09e8c4-233d-4a4d-8453-7fae8d1543a2)

**Comment by alstojanovic** [comment]
@valentinyanakiev  I thinkyou did some research on this, maybe add some notes about what you found?
