### ISSUE TITLE
Sign-up visibility 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3163]
## Description

As a user I want to be able to quickly find out where I can sign in

## Acceptance criteria

- [ ] Sign up button to have higher visibility

Note: this is a first pass, but any other suggestions/improvements of the team member working on this issue are welcome! 

## Additional Context
I was just on a telephone call with a new user, I asked her to sign-up, but she struggled to find the "sign up" button. 

Is it an idea to put this in the action color top right besides "Log in"? It really took her about 30 seconds and some prompts from me to find out how to sign up...

## Design
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/ff4f4dc9-9d59-4661-a5c7-c11344879ae5)
Figma: https://www.figma.com/file/FE4fFgYUUAkUt2BHb4IoLa/UX-Guidelines?node-id=301%3A2305&t=wRj1V6iXWM0M7PJ6-1

## Implementation
Please try to use SwapColors component first

**Comment by SimoneZaza** [comment]
Part of client #3418
