### ISSUE TITLE
Remove logic that was hiding draft callouts from non-admin users

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3187]
## Description

As a client developer I want a clean code base

## Acceptance criteria

- [ ] Remove pseudo authorization code on client that was hiding draft callouts from non-admin users

**Comment by hero101** [comment]
So everyone can see that it's a draft? What value is this bringing?

**Comment by hero101** [comment]
@Comoque1 Is this still needed?

**Comment by Comoque1** [comment]
I don't think so.
