### ISSUE TITLE
BUG: Card description is displayed on activity log description, instead of the card title

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3190]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/challenges/food/dashboard
2. The activity log for cards is displaying the cards description instead of their titles
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6bbe08af-2c0f-41f1-9185-d24f3729dda1)

**Expected behavior**
When callout card is created its title is displayed on activity logs

**Comment by techsmyth** [comment]
@Comoque1 this one can be a lower priority...
