### ISSUE TITLE
Visibility within Journeys for unauthorized users

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3221]
## Description

As a hub lead I want unauthorized users to get a condensed view of non-restricted content while informing them that there is more once they're authorized.

UPDATE: An overlay/dialog without the option to close it might work nicely here. This implicitly gives the user the message that there is more once they're a member + that this overlay will be gone then (instead of a dashboard changing it's content once they're a member)

**Comment by SimoneZaza** [comment]
Also add lock symbol or other message to communicate on the dashboard page of a private hub

**Comment by larssondenise** [comment]
Is this the same as[ #3281 ](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/3281) @SimoneZaza
