### ISSUE TITLE
BUG: Lock missing on cards of private hubs

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3223]
**Describe the bug**
Private hubs no longer have the label with the word 'private', but instead, should have a lock symbol. This is currently missing. 

**To Reproduce**

1. Go to alkem.io
2. Scroll down to Challenge Hubs

**Expected behavior**
A lock symbol on private hubs, next to the title on the right (see screenshot of design below)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/7828008f-3fa3-497b-be49-ced19c3c721f)

**Design**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/ccfdb614-5918-4e85-822a-27b25110ee08)

**Comment by techsmyth** [comment]
Now showing up nicely
