### ISSUE TITLE
BUG: Expand button missing on mobile discussion callout

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3237]
**Describe the bug**
The discussion callout (in dev environment) is missing the expand button (which should have the same behavior as the show all button).

**Expected behavior**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/276a7656-2535-44a2-b110-2fa8a8fed8a0)

Design:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/5e6e1835-ecdd-42f5-a927-a3f97cd5c20b)

**Comment by Comoque1** [comment]
Looks OK on DEV

While testing, discovered 2 other mobile related issues:
- [ ] BUG: Expand button missing on mobile card callout comment #3286
- [ ] BUG: Closing card dialog after it has been open 2 times, move the user on top of the page #3287
