### ISSUE TITLE
BUG: HubTemplates are loading canvas values; revisit when query is executed

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3259]
**Describe the bug**
The HubTemplates query is loading the canvas values, which should not be done as these are very heavy:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c47ea727-0bfa-482f-a655-d33e280c1f2d)

**To Reproduce**
Go to any hub, and look at the HubTemplates query

On a Hub with a log of Canvas Templates this query will take a long time to return.

**Expected behavior**
Canvas values should not be loaded when loading the HubTemplates.

Question: why do we actually load the HubTemplates when showing the dashboard page at all? Surely these are only needed when going to create a new Callout or on the Admin / Templates tab?

**Comment by alstojanovic** [comment]
@techsmyth adjusting the estimate on this as it was not so trivial as it seemed. HubTemplates query is now executed only when we open dialogs and the code has been refactored to only get Card or Canvas templates when needed and added additional query for fetching only the canvas value needed for rendering the canvas template.

**Comment by techsmyth** [comment]
@alstojanovic understood, you basically took in more work. In general we should not update estimates as they are meant to be a proxy for how well we are planning, but in this case we did not properly understand the issue. Nice set of updates.

**Comment by Comoque1** [comment]
Tested on following areas on DEV env.:
- [x] Admin / Hub
  - [x] Creating canvas from existing canvas, gets specific canvas value, only when selected
  - [x] Creating canvas from template, gets specific canvas value, only when selected
  - [x] Only when open existing canvas template, the value is requested
  - [x] In all other scenarios, only info, preview etc.. is requested.
- [x] Contribute for Hub / Challenge / Opportunity
  - [x] Creating canvas from template, gets specific canvas template value, only when selected
  - [x] Only when open existing canvas on callout, the value is requested
  - [x] In all other scenarios, only info, preview etc.. is requested.

Really nice improvement.
