### ISSUE TITLE
Home Page Contributors Section

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#3263]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria
Fix these graphical issues:
- [ ] The gap at the right of the list
- [ ] Variable number of items dependent on resolution??
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/86ebd5bc-71e2-44aa-b80e-c59342ad53b1)
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/9f45583e-d3c6-41c3-9805-ed6f896b9016)
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/82ddff1a-1e2c-44e1-969f-90723d5946c4)

TBD.

**Comment by SimoneZaza** [comment]
this block will be removed entirely soon
