### ISSUE TITLE
BUG: Challenge cards on Challenges page show weird button when expanded

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3264]
**Describe the bug**
Challenge cards on Challenges page show weird button when expanded

**Expected behavior**
Not to show the 'APPLICATIONS NOT ENABLED' button

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/dbdccbca-c89e-4754-b5df-38fff036e9a4)

**Comment by Comoque1** [comment]
The issue seems to be resolved on challenge level.
The same issue is experienced on Hub level, until the user become a member to at least 1 hub
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/32b2c1d5-c38e-48c2-844f-e9729a88adbd)
