### ISSUE TITLE
BUG(PROD): Navigation bar on Admin is incorrect

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3290]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs
2. Navigation bar is not from end to end 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/95ec56f0-fef7-4cb8-913b-607be1521e31)

**Expected behavior**
Admin navigation bar has the same width as to banner

**Comment by techsmyth** [comment]
@me-andre I presume this is fixed with the admin layout work that you have done?
