### ISSUE TITLE
BUG: Canvas cards are not equal size as the "+" button

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3298]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/contribute/callouts/visualcallout-6954: canvas cards are not equal size as the "+" button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b6b7a5bc-f090-467e-9169-c8940a08373b)

**Expected behavior**
Canvas cards are same as "+" button.

**Comment by ccanos** [comment]
@Comoque1 not reproducible anymore, checked in local, dev and acc.
