### ISSUE TITLE
Dashboard Page layout refresh

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3303]
## Description

As a member I want to be able to see the challenges in a Hub

## Acceptance criteria

- [ ] Dashboard page updated as shown below

## Additional Context
Rational is to give the Challenges, which should be the key focus, higher visibility

Also news does also tie into contributions, which does not need to be full width.

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/05f4eb12-7702-4dad-b570-a81327924f7e)

**Comment by SimoneZaza** [comment]
no longer relevant
