### ISSUE TITLE
Contributions visible on Contribute Page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3305]
## Description

As a user I want to be able to see what the recent activity is

## Acceptance criteria

- [ ] Contributions box in left hand column on Contribute page with a longer list of entries (10).

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by larssondenise** [comment]
@techsmyth not sure what was meant by this?

**Comment by techsmyth** [comment]
@larssondenise having a way to see more than just the few contributions that are shown I think; I also have forgotten some of the context.
