### ISSUE TITLE
BUG: banner image resolution too low

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3307]
**Describe the bug**
On a desktop the banner image resolution is way too low

**To Reproduce**
Go to Alkemio on a desktop and download the image. It is 84k. 

It is visibly blurred on a desktop. 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/81a2e2c3-fd1a-4d3f-9455-8f17d557a585)

**Expected behavior**
A lower resolution image is loaded on mobiles. (current image)

At higher resolutions, i.e. above XX breakpoint, a higher resolution image is loaded.

**Comment by SimoneZaza** [comment]
![header_wide.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/6170a220-0de0-45f3-a313-c2a930ba701b)
@techsmyth Here's the image in a better resolution, should I upload it somewhere else as well?

**Comment by techsmyth** [comment]
@SimoneZaza I think it is fine to be attached as above.

@ccanos can you please add this image into the client-web repo besides the current image (so keep that!) and then have a switch regarding which image to load based on the breakpoint?
