### ISSUE TITLE
Refinement of key orientating text

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3308]
## Description

As a user I want to quickly get to the content

## Acceptance criteria

- [ ] Refinement of key wording for guiding users on the platform.

**Comment by techsmyth** [comment]
@larssondenise can you please have a look at the updated wording / layout when this goes to develop?

**Comment by larssondenise** [comment]
@techsmyth updated wording looks okay. But the lay-out changes are not all done, am I right (the better alignment on platform page / bold fonts) ? And the changes with regards to my hubs + username below do not seem to work. Not sure if we still wanted to change them? 
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/3a414dc7-3536-478f-b67b-a462ea6e370d)

**Comment by larssondenise** [comment]
@techsmyth not sure if I understand the 'explore membership options' in the section under explore challenge hubs
