### ISSUE TITLE
Add tagline to user/organization profile

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3313]
## Description
As a user I want one sentence to explain my role or goal on Alkemio
As a user I want to see one line with the key information on a user card to decide if they are relevant. The first sentence of the bio, which is currently displayed on the user card, is not always relevant.

## Acceptance criteria

- [ ] Tagline added to the user and organization profile (limit: 80 characters)
- [ ] New field for tagline added in settings 
- [ ] The word 'Location' above city/country removed in settings
- [ ] About added as a title in the info block
- [ ] Spacing and text style adjustments according to design

## Additional Context
https://www.figma.com/file/t3KN1pFopUUNEW7DSC2YOy/Contributor-memberships?node-id=330%3A856&t=sQotdRssaJ3oFDZr-1

**Comment by SimoneZaza** [comment]
This is done right?
