### ISSUE TITLE
Footer bar layout 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3315]
## 
As a user I want a clean page with a clean footer bar

## Acceptace criteria
- [ ] It should resize properly on mobile. Current behavior
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e6586cd3-1bf0-492d-8a70-29e133da9b96)
- [ ] Design updated to reduce empty space as per design

## Design
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/27eb5cb0-880b-49bd-a3d4-95f4b45522b7)

- [ ] Height 60px (3 rows)
- [ ] Everything on one line
- [ ] Alkemio Foundation left aligned
- [ ] Language is not translated 

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/a1d403bc-8d5b-4052-852e-a71eee7cfab0)
Mobile:
- [ ] Logo on top
- [ ] Group set of 3 links(/language) together
- [ ] Alkemio Foundation bottom left

**Comment by techsmyth** [comment]
@SimoneZaza looks great! I will take the UX label off and move to backlog...

**Comment by alstojanovic** [comment]
@techsmyth There is no Bulgarian translation for the footer. It is falling back to English.

**Comment by techsmyth** [comment]
@alstojanovic yes you are right - my mistake. I have updated the issue to focus on the overall layout part of it and removed the bug label...

**Comment by Comoque1** [comment]
The point 'Language is not translated' is not implemented

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/08ec8301-bd93-4d1d-9397-b26061762fe9)

**Comment by Comoque1** [comment]
Correct, wrongly interpreted.
