### ISSUE TITLE
BUG: Updating the challenge access preference is reverted on the client

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3319]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/private-hub3/challenges/pr-challenge-3137/authorization
2. Authenticate with GA
3. Using the client, set the preference `Allow non-members to read the contents of this Challenge.` to enabled
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/041392d2-eb08-47cc-9436-920c15a31540)
4. Query the `anonymousReadAccess` state for the challenge: it is false
```
query {
  hub(ID: "private-hub3") {
    authorization {
      myPrivileges
      anonymousReadAccess
    }
    challenges {
      nameID
      displayName

      authorization {
        myPrivileges
        anonymousReadAccess
      }
    }
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cf237bdf-cbc7-48d7-9e97-77aeaff6c9a7)

**Expected behavior**
Preference state changed on the client, updates correctly the value store in the DB

**Comment by techsmyth** [comment]
@Comoque1 the anonymous read access is inherited from the hub. Is the hub private in this situation?

**Comment by Comoque1** [comment]
> @Comoque1 the anonymous read access is inherited from the hub. Is the hub private in this situation?

Yes, the hub is private. Creating a hub default `anonymousReadAccess` is `false`, creating challenge to it, the challenge preference has: `anonymousReadAccess` is `false`, but on the client it is shown as true
![image](https://user-images.githubusercontent.com/23620658/211535520-1ccfd474-aecc-4e01-86f1-2e904ab8fb4d.png)

**Comment by techsmyth** [comment]
@Comoque1 please just ignore the flag for anonymous read access. That is only one input into the eventual privileges that are assigned to a given user. So only the resulting privileges is relevant.

**Comment by Comoque1** [comment]
Closing based on the above comment.
