### ISSUE TITLE
BUG: "Application not enabled" button background and text color on Hub / Challenge is not correct

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3345]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/un-sdgs/dashboard with registered user without being member to the community
2."Application not enabled" button background and text color on Hub / Challenge is not correct
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0912d54d-6a85-456e-a143-9e0b9626c830)

**Expected behavior**
"Application not enabled" button background and text color on Hub / Challenge look like:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b7b2b28d-76d5-4123-9462-47dcdcf072e8)

**Comment by alstojanovic** [comment]
@Comoque1 should it be like JOIN or like MEMBER button? Because this is a disabled button.
