### ISSUE TITLE
BUG: Errors are generated, when user navigate to private hub / challenge

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3350]
**Describe the bug**

**To Reproduce**

1. Open browser dev tool
2. Go to https://acc.alkem.io/
3. Create a private hub
4. Navigate with registered user (not admin), to the private hub: Requests are failing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/609efd13-69dc-4021-8212-8abd8b5e968c)
5. Make the user member of the and navigate to the private challenge: Requests are failing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bbab4888-aeb9-455a-9611-47fcd0135dea)

**Expected behavior**
The client should check if it has read access before making the requests, as there should not be standard failing requests, when user try to access private hub/challenge

**Comment by valentinyanakiev** [comment]
@Comoque1 @techsmyth is this really high priority?

**Comment by Comoque1** [comment]
Yes, but not for this release.
