### ISSUE TITLE
BUG: Very hard to apply on mobiles

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3353]
**Describe the bug**
A new user of the Shipping Retrofits community was trying to apply via his mobile but it was very hard to do so.

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/f7bf1207-b13e-4b99-967e-cf1dd92b51ca)
**To Reproduce**
Go to a community with application questions, scroll down. The confirmation button is hidden behind the tabs.

"apply button was only visible if you really drag the screen down with keeping your finger dragging it down but if you’re forcibly doing that it doesn’t let you actually press the apply button"

**Expected behavior**
Application for membership to a community should be a good experience on the mobile

## Suggested fix
Add spacing below apply button

**Comment by SimoneZaza** [comment]
@techsmyth I tried in various ways but I can't recreate this issue, the apply button is always accessible for me. @Comoque1 any thoughts?
