### ISSUE TITLE
WYSIWYG Editor should have the platform styles

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#3356]
## Description

As an admin of e.g. challenge I want to preview my input on challenge settings page right when I enter the text.
I want the WYSIWYG editor to have the same text styles as the rest of the platform.

## Acceptance criteria

- [ ] WYSIWYG text styles put in accordance with the text styles in <WrapperMarkdown>

## Additional Context

**Not to be addressed before we revisit the editor choice.**

**Comment by SimoneZaza** [comment]
no longer relevant?
