### ISSUE TITLE
BUG: Input fields are not centered on create organization page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3358]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/organizations/new
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/35afcb27-92ab-4b88-b9f7-cbcc2d74155b)

**Expected behavior**
Input fields are centered on create organization page

**Comment by SimoneZaza** [comment]
seems fixed
