### ISSUE TITLE
UX: Journey dashboard page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3379]
## Description

As a UX lead I want all the pages copied in the design system so that I can create components and use them easily for designs 

## Acceptance criteria

- [x] Mobile
- [x] 1400
- [x] 1800 

## Additional Context
Screen shots / UX designs / data that are relevant.

**Comment by KayleeS96** [comment]
Designs are done, issue with body 1 fonttype pending. Will adjust when issue with fonttype is resolved.
