### ISSUE TITLE
Visual switch to Space

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3385]
## Description

As a usage champion I don't want to confuse the users of the platform by talking about communities but still only visualizing hubs on the platform

## Acceptance criteria

- [ ] Switch from hub to communities in the translation files

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@larssondenise still relevant?

**Comment by larssondenise** [comment]
I'll check + I see Dutch hasn't gone with it

**Comment by larssondenise** [comment]
all switched!
