### ISSUE TITLE
BUG: After editing and closing a canvas, second failing "checkoutCanvas" request is triggered

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3394]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/release-11-01-23-hub/challenges/challengecreatedby-2810/contribute
2. Open existing canvas
3. Edit and save the changes
4. Close the canvas - second failing `checkoutCanvas` request is triggered 
4. Error: `"message": "Unable to update state: provided event (CHECKIN) not in valid set of next events: CHECKOUT",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/665fe9c5-d0d7-4c75-beea-e5be231b6b7a)

**Expected behavior**
On canvas close, the second canvas checkout request is not triggered.
Mutation to be triggered that is not returning an error.

**Comment by hero101** [comment]
@me-andre This sounds too complicated, is it really required?

**Comment by Comoque1** [comment]
Not sure if it was introduce with this one, but now, when I close canvas different error is thrown
"message": "Variable \"$input\" got invalid value { canvasCheckoutID: \"186e3c1a-62ec-4aaa-813a-6b201049b594\", eventName: \"CHECKIN\", errorOnFailedTransition: false }; Field \"errorOnFailedTransition\" is not defined by type \"CanvasCheckoutEventInput\".",
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fb99b365-dc32-4903-9fdc-35b253010e20)
