### ISSUE TITLE
BUG: top callouts + recent contributions shouldn't display markdown

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3433]
**Describe the bug**
Currently, markdown is not rendered properly in the Top Callouts block on the dashboard page. Instead, the user sees the *-_ etc, which looks a bit weird. In the Recent Contributions block, markdown is properly shown, but with all these different styles in 1 block this looks a bit messy. 

**To Reproduce**

1. Go to 'https://alkem.io/digileefomgeving/dashboard'
2. Scroll down to 'Top Callouts' en Click on Callout
4. See error: markdown is not shown in top callouts, but is shown in callout itself

**Expected behavior**
Top Callouts block and Recent Contributions block should display plain text without any markdown styles, see comment below.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/0352f1a0-f418-4beb-9ea2-cffdb9a7c97b)
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/e30939eb-fecb-4c00-b4fc-672584c0f45b)If applicable, add screenshots to help explain your problem.

**Comment by SimoneZaza** [comment]
The nicest thing to do may actually be to display the text without any markdown here? Having headers in such a block isn't very nice I think.

**Comment by SimoneZaza** [comment]
@ccanos Great! As we just discussed, I would suggest indeed trying to render the two lines without any markdown styles, both in this block and in the Recent Contributions.

**Comment by techsmyth** [comment]
@ccanos please also have a look at the notifications repo, that now uses a package called markdown-to-text which converts markdown to text - so you could then use any text display component...
