### ISSUE TITLE
description events, cards, and profile need way more characters

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3434]
## Description

As a community admin, I want to be able to copy the full event descriptions from my website to my journey page so I don't need to shorten the text.
As a user, I want to be able to copy more text in a card than is currently possible (1800)
As a community admin, I need more characters to properly describe the background and vision of my journey

## Acceptance criteria
Event description:
- [x] Update type to be VERY_LONG_TEXT_LENGTH + 6000 on client
- [x] Server needs a higher limit: 32k

Card description:
- [x] Update type to be VERY_LONG_TEXT_LENGTH + 6000 on client
- [x] Server needs a higher limit: 32k

Hub/Challenge/Opportunity: Background
- [x] Update type to be VERY_LONG_TEXT_LENGTH + 6000 on client
- [x] Server needs a higher limit: 32k

Hub/Challenge/Opportunity: Vision
- [x] Update type to be VERY_LONG_TEXT_LENGTH + 6000 on client
- [x] Server needs a higher limit: 32k

## Additional Context

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1cd98c55-f23f-44ee-842d-c57b10c46b08)
Word/Character count for a typical event description including 2 images.

**Comment by SimoneZaza** [comment]
@SimoneZaza add other fields that need a character limit update

**Comment by SimoneZaza** [comment]
@techsmyth do you agree on also extending the character limit of Cards & Journey background/vision?

**Comment by techsmyth** [comment]
@SimoneZaza yes!
