### ISSUE TITLE
Possibility to lock Whiteboards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3437]
## Description

As a user, I want to be able to lock my whiteboard so other people can see it but not edit it.

## Acceptance criteria

- [ ] Multiple options, and per whiteboard

## Additional Context

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2fb62b40-695b-4791-8631-c46f559fb3b8)

**Comment by techsmyth** [comment]
Overtaken with RT whiteboard UX design
