### ISSUE TITLE
Less intrusive way of visualizing that a callout is closed

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3439]
## Description

As a user, I want a subtle hint that I can't contribute to a Callout anymore, not some banner screaming at me that it is CLOSED

## Acceptance criteria

- [ ] Change background color of the label/banner to white
- [ ] Change "CLOSED" <H3> to "This Callout is closed. You can still comment on the individual cards." <caption, primary color>

## Additional Context
Suggested Design:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/4db58d1a-5e31-409f-96a8-dc4cb20ab38e)

Current Design:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/a580c4da-2447-4f86-b07d-5c6839704dc9)

**Comment by SimoneZaza** [comment]
(without the plus button of course)

**Comment by Comoque1** [comment]
@SimoneZaza, is it expected to have the same message for all callout types, or it would be better to bring it back and have different messages (callout type based) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f24f2022-d4d1-4329-aec2-83cb31b31cf3)

**Comment by SimoneZaza** [comment]
Thanks @Comoque1, for now we think this is fine, only card callouts are currently being closed. I assume the text is in the translation file so we can find something more fitting for all types?

**Comment by Comoque1** [comment]
From what I see, there is translation, but it is not callout type based (correct me if I am wrong @hero101 )

**Comment by hero101** [comment]
> From what I see, there is translation, but it is not callout type based (correct me if I am wrong @hero101 )

@Comoque1 You are correct

**Comment by Comoque1** [comment]
Added a [placeholder story](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/3600) in order not to forget to add translations.
