### ISSUE TITLE
BUG: Private challenge and opportunity of archived hub is visible on search result

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3448]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/search?terms=private+challenge - Challenges and opportunities of an archived hub are visible on search results
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1c9adc68-c458-4255-aeec-9620d302ff67)

**Expected behavior**
Archived data is not displayed on Search results page.

**Comment by techsmyth** [comment]
@Comoque1 please check this again for users without elevated privilege...

**Comment by Comoque1** [comment]
The behavior is the same as for #3449. With Hub Admin role, the archived hub is returned, with member - not. Closing.
