### ISSUE TITLE
BUG: Private challenge of archived hub is visible on search result from Challenge page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3449]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/challenges
2. Type in search input field for 'Explore other Challenges visible to you' 'private challenge' - Private challenge of archived hub is visible on search result from Challenge page
3. clicking on it redirects to 404 page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/61ea1e1e-ffd3-4899-a48d-e9918524508a)

**Expected behavior**
Archived hubs data is not displayed when searched related data.

**Comment by techsmyth** [comment]
@Comoque1 just tried this - and for me it was working as expected. The way the filtering happens is that the search service checks if you have READ privilege, and if you do it returns the result. So when searching as global admin I indeed saw the above behavior, but using a non-elevated account I got no results.

**Comment by Comoque1** [comment]
Thanks @techsmyth ! My fault I haven't added the role that I was using (Hub Admin) to the bug description. It has read privilege, so this is expected. Closing the issue.
