### ISSUE TITLE
Missing padding on Challenges page

### ISSUE THREAD

**Issue by Roseghost** [alkem-io/client-web#3453]
**Describe the bug**
On the challenges page some blocks dont have padding in between

Current situation: 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/c19e2650-ea1e-44a2-b7b7-965832f2e26e)

**Expected behavior**

Correct situation: 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/998a6891-4cef-4aae-9ea9-13816df5275a)

**Desktop (please complete the following information):**
Mobile and desktop version on Chrome

**Additional context**

**Comment by SimoneZaza** [comment]
moving this to the icebox as I think we need to address the entire Challenges page..

**Comment by Comoque1** [comment]
This change seems that introduced regression:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/29289484-6ee6-4e79-8a36-10c1148739ba)
