### ISSUE TITLE
Search tab in Community with results

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3454]
## Description

As a community member I want to see results just in that community

## Acceptance criteria

- [ ] Search icon added to the tabs
- [ ] Clicking on search icon opens a dialog showing only the search bar
- [ ] Entering a search term opens the search page with the results
- [ ] Search tab to have 3 results sections: Challenges + Opportunities, Contributions, Contributors
- [ ] On mobile: blocks with horizontal scroll as in challenges block on dashboard
- [ ] Opportunity cards show parent Challenge
- [ ] Contribution cards show parent Callout and parent Challenge/Opportunity
...

## Additional Context
Figma: https://www.figma.com/file/U7ked8NAbWgBhbEDduXXXO/Search-in-hub?node-id=0%3A1&t=idBGPRpTUJkHzf6h-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/de01ca6f-4757-4a81-b385-fe23b6da708b)

**Comment by Comoque1** [comment]
Tested (not finished) on DEV env, resulted in one major regression:
1. Opening hub settings is failing:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/41ffdf3a-e409-4490-b173-d19911fcc28c)

2. The overlay contains string: "Search suggestions:" 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7bbb5c79-20f4-441a-b994-e2d36aa53a39)
