### ISSUE TITLE
BUG: Calendar events are failing to open

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3458]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/dashboard/calendar/111-8136 - error is thrown: `"message": "Variable \"$eventId\" of type \"UUID!\" used in position expecting type \"UUID_NAMEID!\".",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b88b5871-05ee-4033-8b0e-4d2ad7d89678)

**Expected behavior**
Events are successfully open.

**Comment by ccanos** [comment]
@Comoque1 Fixed together with the ShareDialog #3311 
Shouldn't show that error, but we need to do something with the past events in the V2 @larssondenise
