### ISSUE TITLE
Search for full name

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3461]
## Description
As a user I want to type the full name of someone and find them as a user. The current search only searches for first or last name instead of the full name.

## Acceptance criteria
- [ ] Search function should include full name

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/496270a5-dbdd-4188-b8c9-b88e729cef30)
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/859d2e0e-6fdc-4f48-a2a9-0efa104db379)

**Comment by techsmyth** [comment]
@larssondenise this is already merged :) The search now includes the displayName field.
