### ISSUE TITLE
UX: Management of Application Form

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3471]
## Description

As a community admin I want to be able to edit / update the set of questions applicants to the community need to fill out

## Acceptance criteria

- [ ] Community admins able to edit the questions for applications: add new questions, remove questions, specify sort order
- [ ] specify the language being used in the Application Form
- [ ] Display a markdown box to provide additional context to applicants

## Additional Context
The data model per question is shown below. Also to think through what explanation we would want to provide per question + how that shows up (in the box + then goes when user starts typing?).

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/285efe63-72d7-492c-b063-3f4ab99b03ac)
Screen shots / UX designs / data that are relevant.

**Comment by KayleeS96** [comment]
@techsmyth @SimoneZaza Made a first mockup of what this could look like. Let me know your thoughts

Figma link: https://www.figma.com/file/SaRhJ3fxyErgkUIOuCJmZ5/Admin-application-form-questions?node-id=0%3A1&t=5YDJvf7KILm3m3QP-1

![image](https://user-images.githubusercontent.com/79141092/219391774-818d35e6-a162-43ce-be1e-b94e19353127.png)

**Comment by KayleeS96** [comment]
@techsmyth @SimoneZaza Updated the design according to the feedback. Let me know any further thoughts

![image](https://user-images.githubusercontent.com/79141092/220112480-29e6ca19-bf1e-4bf2-a7da-8845f5ec6480.png)
![image](https://user-images.githubusercontent.com/79141092/220112527-94e1dd62-4290-4372-8031-b1988208643d.png)

**Comment by techsmyth** [comment]
@KayleeS96 looking a lot better! A couple of additional comments:
- There should be a max length on the question, though this should be say 200 characters.
- There is **also** a max length on the answer text provided. That also needs to be shown and be configurable
Re the explanation text, I am not sure how best to bring this in. the dialog as it is now sort of works, but it may be better also make it clear that there is a section related to "answers", where by there is an "explanation of what answers should cover, plus max length of answers"

@SimoneZaza maybe we chat this through briefly tomorrow.
