### ISSUE TITLE
Filtering of Hubs by tags

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3474]
## Description
As a  user I want to be able to group Hubs by theme

## Acceptance criteria

- [x] Allow filtering of the Hubs on the platform based on tags in the tagset on the Hub.
- [x] The set of tags to be used, and associated display text, to be hard coded in the client for now (later configurable via Innovation Spaces)
- [x] Display text to be translatable
- [ ] Selection of which filter to apply to be controllable from the route used to show the landing page (e.g. url parameter)
- [x] Show all is deselected when another button is clicked
- [x] Other buttons can be selected at the same time
- [ ] Selected button: background to be primary color, white text + check icon

### Groups (tags to be case-insensitive)
- Show All 
- Energy Transition: "Energy Transition", "Energietransitie"
- Inclusive Society: "Inclusive Society", "Inclusieve Samenleving" 
- Public Services: "Public Services", "Publieke Diensten"
- Innovation: "Innovation", "Innovatie"
- Supporting Vulnerable Groups: "Supporting Vulnerable Groups", "Kwetsbare Groepen"
- Digitalization of Society: "Digitalization of Society", "Digitalisering"
- Other (With the Other theme to include those that don't fall into one of the defined groups)

## Additional Context
This is a light weight mechanism to give some order to the platform page until such time as we have Innovation Spaces - and even when they are there this may well still be useful.

Screen shots / UX designs / data that are relevant.

Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?node-id=112%3A4&t=o74AVwHFVxFPQWRZ-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/11c97166-7729-40f3-a7ce-d529eecb6739)

**Comment by SimoneZaza** [comment]
@techsmyth Question during refinement: Why can't we use a normal tag again? Hidden tags bring a lot of complexity, and these tags should actually also fit between the normal tags?

**Comment by SimoneZaza** [comment]
@techsmyth just to be sure: the three filters in the design are still dummy filters, is that correct?

**Comment by techsmyth** [comment]
@SimoneZaza yes - to be updated

**Comment by hero101** [comment]
The functional requirements were predefined when it was in Progress.

- the exact functionality wasn't clear (matching the text of the buttons, or a tagset represented by the button)
- the set of tags wasn't defined
- the buttons changed from 4 to 8

**Comment by techsmyth** [comment]
Yes agreed this needed more thought. Lets try to find time this afternoon to talk it through.
