### ISSUE TITLE
Search page: header refresh

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3475]
## Description

As a community champion I want users to have a positive first experience

## Acceptance criteria

- [ ] Search page top section refreshed as per design
- [ ] Search suggested terms to be from the translation file

As part of this task I have fixed a behavior that Simone told me to tweak:
- [ ] When searching on the global search field at the top bar, if multiple words are introduced (separated by spaces obviously), they should be translated into one single search term. 
The way to separate search terms is comma from now on. SearchPage was already putting commas in the url to separate terms. 

## Additional Context

Screen shots / UX designs / data that are relevant.
https://www.figma.com/file/07orFzKe86yopPA1X2G1Gs/Global-Search-page?node-id=0%3A1&t=z5xw17TDV9pho2M6-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/21912052-d787-4db3-97be-4c57f3a129dd)

**Comment by techsmyth** [comment]
@SimoneZaza as discussed, great if you can put a design in place so that this can be taken into the prioritization for the next sprint

**Comment by techsmyth** [comment]
Looks great!

**Comment by techsmyth** [comment]
@SimoneZaza @Fintokyo suggestion from Fintan is to make the text box smaller as will not be lots of words - not sure how this plays out in terms of UX?

**Comment by techsmyth** [comment]
@SimoneZaza plus also update the set of suggested terms:  ‘innovation’, ‘energy’, ‘inclusive’,  etc.?

**Comment by SimoneZaza** [comment]
@techsmyth @Fintokyo I agree that the input field is a bit large, but I'm struggling to find a better alternative:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b00353fe-4017-4ea4-8a2c-2df3383408dc)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/32c22fd8-4bd7-4d32-86e6-7a7acae1fa37)

**Comment by Fintokyo** [comment]
Hi Simone, thanks. I can only see a small version of the screen, but my preference would be the 4th one, where the search box and the suggested words are on the same line.

**Comment by SimoneZaza** [comment]
Hi @Fintokyo , the problem with that one is that on small screens, part of the search terms will be wrapped underneath the search box..

**Comment by Fintokyo** [comment]
Hi @SimoneZaza, is this still an issue if the search box is only the width of 2 or 3 words (I doubt people will every search using more than 1 or 2 words, but please let me know if this isn't the case), and then the number of suggested words is only 4 or 5 words?

**Comment by SimoneZaza** [comment]
Hi Fintan, I’m curious to see whether this works – I’m trying to reply to the notification from Github in my mailbox.

According to Statista, in about 80% of the time people indeed search with 1/2/3 search terms, but that still leaves 20% of the users who use more. And the experience of having too long of a text for the search box to fit is really terrible in my opinion..

Aside from that, I wouldn’t restrict the number of suggested words. Especially in this early stage of the platform, the search can also be used to explore what is happening there. The more suggested terms (up to a certain limit of course), the more diverse groups of people we might enthuse.

To conclude, it’s quite a small change to go from two lines to one, so I’d suggest just to start with the slightly smaller search field on top and the suggested terms below and see how it behaves?

Regards, Simone

Van: Fintokyo ***@***.***>
Verzonden: maandag 13 februari 2023 12:30
Aan: alkem-io/client-web ***@***.***>
CC: Simone Rietmeijer ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [alkem-io/client-web] Search page: header refresh (Issue #3475)


Hi @SimoneZaza<https://github.com/SimoneZaza>, is this still an issue if the search box is only the width of 2 or 3 words (I doubt people will every search using more than 1 or 2 words, but please let me know if this isn't the case), and then the number of suggested words is only 4 or 5 words?

**Comment by Fintokyo** [comment]
Hi Simone, thanks for the feedback, and I'm happy to go as you proposed. For the suggested words, please replace the current words with ‘innovation’, ‘energy’, ‘inclusive’, and some others that you find relevant for the key themes of the challenges currently on the platform

**Comment by SimoneZaza** [comment]
Based on the tags that hubs and public challenges are currently using, I suggest:
- Innovation
- Energy
- Inclusive
- Design 
- 3D
- Community
- Transition
- SSI
- Privacy
- (+ Dutch: dienstverlening, digitale overheid)
The full list can be found in Teams>Product: https://stichtingcherrytwist.sharepoint.com/:x:/s/Contributors/Eez6zo7acC1OpUcjthll-0sB8s9udqSw7TJCMMiWzvWK_g?e=hVeSNn

**Comment by Fintokyo** [comment]
Looks good!
