### ISSUE TITLE
BUG: Error is thrown, when community member save changes on canvas created from someone else

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3486]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/pr-hub-pr-chal/contribute/callouts/collaboratevisually-7107/canvases/mycanvas-hubmemb-1176
2. Make a change
3. Save the change - the changes is save successfully, but error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/491a9d07-d75c-4893-a2e3-e651430fd085)

**Expected behavior**
When community member has the rights to update canvas of created from another user and saves the changes, there are no errors and save button state changes to edit.

**Comment by ccanos** [comment]
It's an authorization issue, but happening when updating the visual, not the canvas.

The GraphQL network tab looks alright, and the canvas gets updated, but there is another mutation in parallel triggered by:
[CanvasActionsContainer:157](https://github.com/alkem-io/client-web/blob/235f19ffce4019aaafd240427a20f5a7f68bdcf3/src/domain/collaboration/canvas/containers/CanvasActionsContainer.tsx#L157) to update the visual preview of the canvas.
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/1346f667-5c5d-4068-ad8b-f2ec21a997d9)

I have debugged the server and looks like the permission is just missing in the visuals, but I'm not sure if they should inherit it or it should be there on creation or what is the problem:

Authorization policy of the visual of my local canvas which was created by GA:
```
[{"grantedPrivileges":["create","read","update","delete"],"criterias":[{"type":"global-admin","resourceID":""},{"type":"global-admin-hubs","resourceID":""}],"inheritable":true,"name":"credentialRuleTypes-platformGlobalAdmins"},{"grantedPrivileges":["read"],"criterias":[{"type":"global-admin-community","resourceID":""}],"inheritable":true,"name":"credentialRuleTypes-hubGlobalAdminCommunityRead"},{"grantedPrivileges":["grant"],"criterias":[{"type":"global-admin","resourceID":""},{"type":"global-admin-hubs","resourceID":""}],"inheritable":true,"name":"credentialRuleTypes-hubAuthorizationGlobalAdminGrant"},{"grantedPrivileges":["create","read","update","delete","grant"],"criterias":[{"type":"hub-admin","resourceID":"307ef219-ed6e-4b53-8b48-564beb932f9f"}],"inheritable":true,"name":"credentialRule-hubAdmins"},{"grantedPrivileges":["read"],"criterias":[{"type":"hub-member","resourceID":"307ef219-ed6e-4b53-8b48-564beb932f9f"}],"inheritable":true,"name":"credentialRule-hubMembersRead"},{"grantedPrivileges":["contribute"],"criterias":[{"type":"hub-member","resourceID":"307ef219-ed6e-4b53-8b48-564beb932f9f"},{"type":"global-admin","resourceID":""},{"type":"global-admin-hubs","resourceID":""}],"inheritable":true,"name":"credentialRule-collaborationContributors"},{"grantedPrivileges":["create","read","update","delete"],"criterias":[{"type":"user-self","resourceID":"5676e8ef-7388-4c47-8ac8-214b034dfef7"}],"inheritable":true,"name":"credentialRule-canvasCreatedBy"}]
```
