### ISSUE TITLE
BUG: I cannot click on the description or date of an event

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3495]
**Describe the bug**
Clicking on the description or date of an event on the dashboard doesn't bring me to the event itself.

**To Reproduce**

1. Go to https://alkem.io/challengecentric/dashboard
2. Scroll down to the events
3. Try clicking on the date or the description of the event that is there

**Expected behavior**
I expect also to be able to click on the date and the description, not just the title.

Note: if possible, made consistent across similar components (e.g. references, ...)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/92ee8930-2a2b-441d-b15b-5a737392862b)

**Comment by Comoque1** [comment]
Fixed on DEV env.
