### ISSUE TITLE
Yes! New functionality! (Release notification on the platform)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3502]
## Description

As a user I want to get a feeling of joy when seeing the release notification

As the Alkemio team, I want to frame the message of a new release as being:
great, fun, cool, new functionality, wow, YEAH! 

Instead of a new release as being: 
new things you have to get used to and maybe in the case that you're actually interested you can read more about it here...

## Acceptance criteria

- [ ] Add celebration icon: import CelebrationIcon from '@mui/icons-material/Celebration';
- [ ] Change the text into:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/10dd29d9-7bf7-4147-8013-44926386b9a6) New release out! Click here to read all about the latest changes. 

## Additional Context
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/9ae1b729-791b-459a-88ff-87f1dfaa6a8a)

**Comment by SimoneZaza** [comment]
Hi @ccanos, I think this is perfect :) thanks!

**Comment by Comoque1** [comment]
@valentinyanakiev, I have no rights to move this card. The implementation works as defined, so could you please close it for me.
