### ISSUE TITLE
UX: Translation gap analysis

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3506]
## Description

As a user, I want to see a consistent approach in the language being used.

## Acceptance criteria

- [ ] Platform gap analysis to see where on the platform we are still using English terms instead of for example Dutch

## Additional Context

Break down the following analysis into bugs / issues to be worked:
===
In the home page of alkem.io, translated in Dutch, there are still the following English words:
- top right > challenges
- then the clickable impact, open source and foundation below the mountain visual are in English
- at the very bottom: repository and then on the line where the help button is there are privacy, Security, support and language are still in English
- contact the host within hubs it is in English 
- events 
- welcome, collaborate visually, contribute and the line below each box
- within the section "over", one of the boxes is called impact
- within a hub: context, community, updates, challenges, templates
- within settings and then "aurhorisatie": Hub admin, group members, available users
- in the share dialog there is: copy link or share on Alkemio in English 
- the pup up contact the host is completely in English
- events pup up
- the contribute tab is in English 
- within the challenges the contrubite tab is in english still : why do you care about this challenge?, contribute ..., collaborate visually.

**Comment by MayteRagni** [comment]
In the home page of alkem.io:

**Comment by larssondenise** [comment]
Closed as I believe all mentioned translations are now fixed/captured
