### ISSUE TITLE
BUG: Not redirecting from sign_up when have a session

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3513]
**Describe the bug**
Going to the sign_up URL, i.e. https://alkem.io/identity/sign_up, when one already has a valid session is showing the following:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f0043673-4530-4e6c-af2e-fa542c4174cc)

**To Reproduce**

1. Go to alkem.io + sign in
2. Enter the following URL in the browser bar: https://alkem.io/identity/sign_up - the client does not handle it properly.

**Expected behavior**
Going to /identity/sign_up when the user already has a session should redirect to the landing page.

**Additional context**
High priority as this URL is used to redirect from the new Homepage.

**Comment by Comoque1** [comment]
This is still reproducible.

**Comment by Comoque1** [comment]
I was useing the prod endpoint on dev env.
With the right endpoint (https://dev.alkem.io/identity/sign_up) it works
