### ISSUE TITLE
BUG: Envelope on Hover-contributor-card in Recent Contributions block (Journey Dashboard) opens profile page instead of message dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3517]
**Describe the bug**
When you hover over a user in the Recent Contributions block (Journey Dashboard), and then click on the envelope icon, instead of opening the message dialog, you go to the profile page of this user.

**To Reproduce**

1. Go to https://alkem.io/challengecentric/dashboard
2. Hover over a user image in the Recent Contributions block
2. Click on the envelope

**Expected behavior**
The message dialog opens, as it does when you click on the envelop elsewhere

**Comment by ccanos** [comment]
Changed estimation to a 5  because the change has been bigger than I thought, and still I am not fully happy with the code in this bugfix
