### ISSUE TITLE
UX Refinements - Round 5

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3525]
## Description
A group of related UX refinements to improve the user experience

## Initiative / goal
User engagement

### Hypothesis
By taking away usability barriers there is more usage

## Acceptance criteria and must have scope
- [ ] Collection of smaller fixes

## Stakeholders
tbd

## Timeline
tbd

**Comment by techsmyth** [comment]
Replaced by new epic + moved issues over
