### ISSUE TITLE
Messaging yourself

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3527]
## Description
As a user, I don’t understand why I don’t have an envelope on my profile where others do have one. I’m afraid no one will be able to send me a message.

## Acceptance criteria
Design for how to deal with this, probably a fun message that appears when you click on the envelope in your own profile
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.
https://www.figma.com/file/sInf95e8CnKva4HIa9411p/Send-yourself-a-message?node-id=0%3A1&t=SQmuNQ1oGF5VZ91z-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/c1fd6f25-bab9-4ea8-b7e9-96d274071c07)

**Comment by alstojanovic** [comment]
Allowed to send the message to yourself. Additional note that the User is sending a message to himself isn't added because it wasn't as straight forward.
This component is reused for the flow where we are sending a message to community and in general to multiple users.
