### ISSUE TITLE
BUG: When refresh dev.alkem.io/home - 404 page is displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3530]
**Describe the bug**

**To Reproduce**

1. Go to dev.alkem.io/ - user is redirected to dev.alkem.io/ home
2. Refresh dev.alkem.io/home - error page is displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d3ee5e54-fa2e-49a1-bce8-0e49fa5a035d)

**Expected behavior**
Home page loads successfully after refresh.

**Comment by techsmyth** [comment]
@Comoque1 @valentinyanakiev this is a routing issue I think...

**Comment by Comoque1** [comment]
This one is fixed already.
