### ISSUE TITLE
Letting users know they can use mentions / tagging / emoticons

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3531]
## Description

As a user I want to know that I can tag other users

## Acceptance criteria

- [ ] Provide some indication / feedback to users that they can mention other usrs
- [ ] Provide some indication / feedback to users that they can use emoticons

## Additional Context
Link to figma file: https://www.figma.com/file/y2jGWLWur88xGtFJmbf1l3/Comments-components?node-id=0%3A1&t=2GIVYW7YM19M6cjc-1

Current situation
![image](https://user-images.githubusercontent.com/79141092/221558179-dacc9460-080e-4506-b3b9-9c6784d5137d.png)

**Comment by KayleeS96** [comment]
Update: multiple options to encorporate the icons for emoticons and mentions into the textbox. Further discussion needed on which option is the most suitable.

![image](https://user-images.githubusercontent.com/79141092/221588434-65d4a271-b14c-492c-939f-3fcf9fcf6658.png)
