### ISSUE TITLE
Landing page and Hubs tags enhancements

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3536]
## Description

As a User I want to have smooth experience on Landing page and filtered Hubs tags.
The issue contains some findings out of the currently implemented stories:

## Acceptance criteria

- [ ] Filtering of Hubs by tags #3474
   - [ ] tags to be translatable
- [ ] Landing page routing support #3518
   - [ ] Alkemio logo to be clickable and to redirect to */home page

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by larssondenise** [comment]
I have taken some of your notes into a separate issue on landing page mobile experience @Comoque1

**Comment by larssondenise** [comment]
I am closing this one, as these points are considered in the other issues! @Comoque1
