### ISSUE TITLE
BUG: Past event is on top  of "Events" list

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3543]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/release-21-02-23-hub/dashboard
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d4798837-f52c-4627-94c5-ae33ee631572)

**Expected behavior**
Past events must be shown on bottom of the list.

**Comment by ccanos** [comment]
@Comoque1 blocked? why? tried tp close it?
