### ISSUE TITLE
Gender options

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3546]
## Description

As a user I want to be able to select a non-male/female gender option

## Acceptance criteria

- [ ] UX design for options to present
- [ ] User.gender field to become an enumeration 
- [ ] Client updated to allow users to select options are per design

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Roseghost** [comment]
@SimoneZaza is asking development where these variables are being used. 

IMO It should be pronouns and not gender.

**Comment by techsmyth** [comment]
@Roseghost actually not being used
