### ISSUE TITLE
Management application questions

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3552]
## Description

As an admin I want to manage the type of questions that I want to ask my community when they apply 

## Acceptance criteria

- [x] Add a section for the application questions to the Community tab of the hub/challenge settings
- [x] Markdown box to provide description for the application form
- [x] Plus button opens new question row
- [x] Option to delete the question + choose whether it is required

## Additional Context
https://www.figma.com/file/xgV87awP3yUM7X0TIeZjlH/Journey-Page-Settings?node-id=0%3A1&t=Nes7N1WNHwepAfTz-1

**Comment by ccanos** [comment]
removed from the AC:
- [ ] Disable the section for application questions if join button is unabled
because it is quite hard to implement. Looks like there is no way to get a specific preference value, creating another task to review this.
