### ISSUE TITLE
BUG: Filter button resize

### ISSUE THREAD

**Issue by Roseghost** [alkem-io/client-web#3562]
**Describe the bug**
The filter button its container oversizes itself. 
![image](https://user-images.githubusercontent.com/64191883/220904490-5af90efd-43d5-49e2-872e-039d013c5a87.png)

**To Reproduce**

1. Go to '[Challenges](https://alkem.io/challenges)' in mobile dimensions
2. Scroll down to "Other Challenges within My Hubs (21)"
3. See error

**Expected behavior**
Only show the word "filter" and it's corresponding icon 
Aswell as the 12 px radius thats present on at the 1440 px dimensions one. 

![image](https://user-images.githubusercontent.com/64191883/220905913-2a367762-47f7-4ae1-93fd-251f8f70f517.png)

**Additional context**
Context of "within My Hubs" is already given by the heading next to it.

**Comment by Roseghost** [comment]
@SimoneZaza I realized this clashes with the fact theres also filter in the bar underneath. 
The bar searches on tags or name. 

Possible suggestions
"Search on tag or name"

**Comment by SimoneZaza** [comment]
Sounds good @Roseghost (sorry I'm just seeing this now). I suggest then adding a Hub icon to the Hub names in the menu that pops up when a user clicks on the filter button.

**Comment by ccanos** [comment]
@SimoneZaza @Comoque1 
not sure if it makes sense anymore. 
We did some changes last week in `PageContentBlockHeader` to stack filters on mobile view, and it looks like this now: 
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/4eb600ad-6711-4cb2-a78b-9771feca9374)
