### ISSUE TITLE
BUG: errors viewing organization profile

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3578]
**Describe the bug**
A non-logged in user is getting errors when opening the profile page for an organization:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/982a96ee-f69b-4c0a-bc72-41930156289f)

The contributor profile pages are key pages, so they have to work without errors - even if the user is not logged in.

**To Reproduce**

1. Log out (if logged in)
2. https://alkem.io/organization/ictu

**Expected behavior**
The organization profile should display without errors, with requests for associates information conditional on the user having the READ_USERS privilege on root level.

**Comment by techsmyth** [comment]
@simonezaza @larssondenise this is likely related to the users associated with the organization, so we will need beyond a stop gap fix a design for how to address this properly.

**Comment by SimoneZaza** [comment]
For unauthorized users, I would suggest a simple note in the associates block saying "Please sign in to see the users that are associated with this organization". Or did I misunderstand the question?

**Comment by techsmyth** [comment]
@SimoneZaza yes that would be ok, as long as the logic is updated to not trigger the query that caused the error.

**Comment by techsmyth** [comment]
@Comoque1 clearly a drop, we should have updated the acceptance behavior. I suggest to add another issue with the updated behavior - can you please do that?

**Comment by Comoque1** [comment]
Card raised: Organization profile information for unauthenticated user #3649.
Closing this one.
