### ISSUE TITLE
Add footer to help dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3585]
## This story originated as a Bug:

**Describe the bug**
When I open a journey page on a mobile device, the tab menu is placed at the bottom of the screen and I don't have a footer

**Solution**
Add footer to help dialog
https://www.figma.com/file/5RfyhykhSETtttX1CFPrHd/Footer-for-mobile?type=design&node-id=0%3A1&t=Vx9YOcCvolARfPgP-1

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1f434a86-a7c1-4fd9-983e-382e36027abf)

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/2a700840-6dcc-48c8-9ba1-bcaa48c388f4)

**Comment by Roseghost** [comment]
![image](https://github.com/alkem-io/client-web/assets/64191883/9dc0c5df-c88a-4b62-8f3d-109b626d0091)


Navigation bar is at the bottom on mobile version. 
Alternatives for footer?

**Comment by SimoneZaza** [comment]
Help dialog is gone
