### ISSUE TITLE
Add a Card for Contributors

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#3594]
## Description

As an Alkemio User
I want to have all the contextual information of the Contributiors I search
so that I can navigate / use the information quicker and easier.

## Acceptance criteria

- [ ] The card should have messaging icon on it for triggering the message dialog
- [ ] Blurred edges are not needed in the initial version - just crop the image

## Additional Context

https://www.figma.com/file/U7ked8NAbWgBhbEDduXXXO/Search-in-hub?node-id=0%3A1

**Comment by Comoque1** [comment]
Tested on ACC and DEV env. These are the observations:
- [ ] The card should have messaging icon on it for triggering the message dialog - there is icon, but when it is clicked, the dialog is opened for a second and after redirection to user profile

- [ ] Missing components from figma file
   - [ ] Square image with blurred version of the same image
   - [ ] Pin icon + Location
   - [ ] Expanded card
     - [ ] Tagline
     - [ ] Tags
