### ISSUE TITLE
UX: Remove / transfer demo hubs

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3595]
## Description
As a product lead, I want to transfer the valuable demo hubs to the production environment and delete old irrelevant hubs from the demo environment. Killing demo + creating an innovation space for the demo hubs is an important steps towards testing **innovation spaces** functionality.

## Acceptance criteria
Based on screenshot below:
- [x] Transfer the green demo hubs from demo.alkem.io to be a demo labelled hub on production (use query to make demo). 
     -  Cityhub010 to become cityhub, an example hub for how cities can use Alkemio
- [x] Check content of red demo hubs, and delete
- [x] Demo hubs with no marking, check with admin whether they can be deleted

## Additional Context
![msedge_5W6jMaHurP.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/656de32f-e760-45bb-bf1b-d2c416c11a00)

**Comment by larssondenise** [comment]
@MayteRagni updated the set of hubs to be transferred/deleted (kvk , IFS and SIDN need to be moved to production). Then check the callouts in the red demo hubs + if there is no important content just remove! As discussed leads / organizations are not transferred. 

@techsmyth sure about organizations? No one will be notified or will the admins?

**Comment by techsmyth** [comment]
@larssondenise organizations might be handy alright, especially if no notifications are generated. Maybe worth doing at least for the host organizations, and lead orgs - if not too much effort.

**Comment by larssondenise** [comment]
@MayteRagni can you add the hosts and leads?
