### ISSUE TITLE
Ordering Callouts / Sorting Callouts

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3613]
## Description

As an innovation facilitator, I want to set the order of the callouts so that they align with the innovation process that I use and it is clear what the order of the questions/exercises is.
As an Admin I want to bring the most important Callout to the top
As a User I want to see most important Callouts first 

## Acceptance criteria

- [ ] Add icons to unpublish / edit options
- [ ] Add 4 items to the Callout settings menu:
  - [ ] Move up (callout switches places with the one above; screen scrolls up a bit as well so the user stays with the moved callout)
  - [ ] Move to top (callout moves to the top, all the callouts that were above it move one place down; screen scrolls up a bit as well so the user stays with the moved callout)
  - [ ] Move down (callout switches places with the one below; screen scrolls down a bit as well so the user stays with the moved callout)
  - [ ] Move to bottom (callout moves to the bottom, all the callouts that were below it move one place up; screen scrolls down a bit as well so the user stays with the moved callout)
- [ ] Menu stays open after clicking one of the buttons (only when easy)

## Additional Context
From previous issue on this topic: 
Moving up: look at the callout above the current one, take its sortOrder and reduce by 1
Moving down: look at the callout below the current one, take its sortOrder and increase by 1

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/0587f8cc-2e6f-4a33-a034-2a274d63b8f8)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/280c3889-bcb1-4336-b40b-c63c543c5122)

**Comment by larssondenise** [comment]
@SimoneZaza here is the other raised issue + design! Only included two items, move up and down + icons?

https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/2629
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/c5c45b0e-0f55-4174-8592-a6bb3ea976c3)

**Comment by SimoneZaza** [comment]
@larssondenise I think we should also include move to top/move to bottom... Maybe up/down is enough for now, but once people have a couple more callouts this will become a bit annoying..
