### ISSUE TITLE
Hub dashboard for unauthorized users

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3629]
## Description
As a unauthorized user, I want an appealing landing page in a Hub I am not a member of that tells me more about the Hub and clarifies what I can do if I want to join. 

## Acceptance criteria
- [ ] Dialog that pops up when an unauthorized user enters one of the journey pages. This means a Hub dialog when entering Hub, Challenge dialog for Challenge, Opportunity dialog for Opportunity. 
- [ ] Dialog to include the context, hosts, statistics and some additional information re whether it is private or not
- [ ] Before permissions are loaded, we don't show the dialog
- [ ] Back button on the top left to let the user go back to where they came from. If there is nowhere to go back, we hide it.
 - [ ] If a block is empty it needs to be hidden Blocks hidden when there is no data.

## Additional Context
https://www.figma.com/file/U49LoKY9DXOdlGJQ6niwLx/Dashboard-Landing-page-for-non-authorized-users?node-id=0%3A1&t=pxwdXBZ6glyoB89k-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/eadbdff5-4355-47e3-8d51-04f0b8704c75)

**Comment by Comoque1** [comment]
I raised a separate bug and will close this issue.
BUG: When unauthenticated user navigate to opportunity of private challenge of private hub, page crash #3803
