### ISSUE TITLE
BUG: Callout settings button not visible for mobile, when title longer

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3630]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/contribute/callouts/contribute-739
2. Make the callout title longer
3. Open the callout on mobile - settings, share (and 'expand') buttons are not visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/46c95c57-27a6-4260-a082-1c60a1541a09)

**Expected behavior**
Truncate title: When open callout on mobile and title is longer - settings, share (and 'expand') buttons are visible and clickable.

**Comment by ccanos** [comment]
@Comoque1 not reproducible anymore
https://dev.alkem.io/un-sdgs/knowledge-base
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/268550f2-5c72-426c-895f-96f7c46438fd)

**Comment by Comoque1** [comment]
Yes, looks OK on Apple:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/eb0af549-0579-4588-a504-7a13e48b55e2)
