### ISSUE TITLE
BUG: search result cards cropping image further

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3654]
**Describe the bug**
A clear card image is set in settings:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/52b67883-9eb7-4e72-8a8f-bda5221ac97c)

but on search results it is showing up further cropped:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/806ffb93-b2b7-4637-bc69-fc2c0d48f44d)

**To Reproduce**

1. Go to search and pick any hub result, image is not correct

**Expected behavior**
The cards image should pick up the image properly from the bannerNarrow visual.

**Comment by Comoque1** [comment]
Tested OK
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6e5e3fb2-35d0-41d1-8eb8-ddae01b8d757)
