### ISSUE TITLE
Contributor cards in search to have square image with blurry background

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3658]
## Description

As a user, I want my profile picture on the search cards to be square, not in landscape orientation. The current card cuts off my picture in a weird way.

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/40e3074f-2b53-41d0-8a05-b7f107555c45)

## Acceptance criteria

- [ ] Picture itself to be square
- [ ] Background to be a strongly blurred version of the picture, as with the header images on the journey pages on large screens.
- [ ] Locations: 
- Cards that appear when hovering over user avatars on Global Contributors page: https://alkem.io/contributors
- Card that appears when hovering over lead user avatar on Journey Dashboard page: https://alkem.io/building-alkemio/dashboard (hover over denise)
- Cards that appear when hovering over user avatars on host/contributors section on Community page of Space: https://alkem.io/building-alkemio/community
- Cards that appear when hovering over user avatars of comments: https://alkem.io/building-alkemio/challenges/aihackathon-inde-9368/collaboration/pleasepresstheco-8124

## Additional Context

Design:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/0a923f4e-d4bd-4805-bcbc-dd176e74bfce)
https://www.figma.com/file/C0CXFtd4UgnJUf1G43UHc0/Cards-Redesign?node-id=108%3A1728&t=K2wHpgNAp87nsCCC-1

**Comment by Comoque1** [comment]
Tested on Sandbox and is as per AC
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5032873bc788a7dafadbb77447d83772b397b569/image.png" alt="image.png" />
