### ISSUE TITLE
BUG: Not able to update the Innovation flow state of an Opportunity

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3659]
**Describe the bug**
When trying to update the innovation flow state of the Journey Structure Opportunity by clicking on the 'Refine' button, I get an error. The same happens at other opportunities where I try to edit the state. For Challenges, I don't have the same issue, there I can update the state. 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/bb04c6a5-f904-4a4c-8672-788f334cca65)

**To Reproduce**

1. Go to an opportunity where you have admin rights
2. Go to settings > innovation flow
3. try to update the state

**Expected behavior**

**Comment by techsmyth** [comment]
@SimoneZaza I just tried this on production, and it was working fine for me. After a bit of digging it appears that the Innovation Pack has an invalid template in it - and your opportunity had picked up the invalid template. 

See details below for what is in the innovation pack template:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f47ff396-cdf3-423a-8b3e-c4ab62487869)
