### ISSUE TITLE
BUG: keep the position on the page when closing a dialog

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3686]
**Describe the bug**
When opening up a card in a callout, then every time the card is closed the user is brought back to the top of the page - which is very irritating if trying to explore a lot of cards in a callout.

**To Reproduce**

1. Go to https://alkem.io/challengecentric/challenges/enabling/opportunities/purposehour-8149/contribute/callouts/mychallenge-9255/aspects/connectingwithothe-5528/dashboard
2. Open a card, and close it
3. Repeat

you are brought to the top of the page

**Expected behavior**
Stay at the location on the page

**Comment by techsmyth** [comment]
@me-andre this is fixed with the callouts work you were doing?

**Comment by Comoque1** [comment]
@techsmyth, I think it was addressed with this story: Avoid reloading of callouts when closing a post / whiteboard #4332.

The behavior from the bug is not reproducible.
