### ISSUE TITLE
Admin: update of Hub visibility for platform admins

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3689]
## Description

As a platform admin I want to be easily able to update Hub visibility

## Acceptance criteria

- [ ] Add a section to Admin > Spaces, where global (space) admins can:
- select a visibility
- apply the new visibility

Suggestion: eye icon behind the delete icon. Clicking on the icon opens a dialog with dropdown that allows you to change the visibility

**Comment by Comoque1** [comment]
Nice to have this feature! Works as defined.
