### ISSUE TITLE
Client routing of callout URLs

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3699]
## Description
As a user I want to be able to share callout links regardless of where they are placed in the community

## Acceptance criteria
- [ ] Callouts are referenced by the following format: <communityNameID>/collaboration/<calloutNameID>
- [ ] Client uses the "group" field on the Callout to find the group for the callout
- [ ] Client uses a fixed mapping table in the client identified the right tab to use. I.e. f(group) ==> tab
- [ ] On closing the callout dialog the user is then on the right tab
- [ ] Client to log an error to sentry if it encounters a group that is not known by the mapping table in the client. 

## Additional Context
Callout urls will point towards a callout dialog, to avoid having to load the correct menu tab. Closing the dialog will direct to the right tab.  

Unauthorized users will see a dialog with text to explain that they are unauthorized

**Comment by Comoque1** [comment]
When try to open card callout on Challenge / Opportunity  (DEV env), fails to load the page.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/21eb34b4-c9fd-4bb1-bfe7-e78a52cc6c46)

**Comment by Comoque1** [comment]
When create canvas or card on callout on Community / Challenge / Knowledge tab and refresh the page - 404 page is display insted of the aspect / canvas
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/72410108-4ef6-4335-957e-31817b8d50d4)

**Comment by Comoque1** [comment]
Opening Cards / Canvases on Knowledge tab are failing to load - redirect to 404 page

Could be used link: https://dev.alkem.io/un-sdgs/contribute/callouts/contribute-5732/aspects/111-735
 ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8305923a-68b9-484f-9ed7-6fba18fa7369)
