### ISSUE TITLE
Moving callout to another group

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3700]
## Description

As a user I want to have the right callouts in the relevant tabs

## Acceptance criteria
- [ ] Callout Edit dialog to allow moving the callout to another group ("section")
- [ ] When user clicks save, dialog closes and user goes to new location (without opening the callout)

## Additional Context
All Callouts are currently part of the contribute tab (which will become the knowledge tab). After implementing callouts in context, we want users / ourself to be able to move callouts to another tab.
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/796431db-19eb-406b-a189-d665affc4e2e)

**Comment by Comoque1** [comment]
Location component to be removed for Challenge / Opportunity callouts.
The rest is working OK on DEV env.
Raised separate card for : Move callouts to knowledge base tab #3875
