### ISSUE TITLE
Update Knowledge and Challenges tab for Hub

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3702]
## Description

As a user I want to be able to use callouts in context on the Challenges + Knowledge base tab

## Acceptance criteria
- [ ] Contribute tab to become knowledge base, no change further
- [ ] List of Callouts to keep old behaviour (scroll to Callout without changing the url)

## Additional Context
Note that for example https://alkem.io/challengecentric/contribute should now go to https://alkem.io/challengecentric/knowledge

**Comment by alstojanovic** [comment]
Synced with @ccanos , waiting some work from the PRs that are in review to be merged. Draft PR is up, putting the issue back to backlog.
