### ISSUE TITLE
BUG: Description placeholder overlaps MARKDOWN / WYSIWYG controls

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3712]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/organizations/test/profile
2. `Description` placeholder overlaps MD controls
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/63fa4e0b-5c1c-497a-a76b-20ea24f9df9e)

**Expected behavior**
Keep the menu bar to be one line with an arrow to show next set of controls.
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/3b132a5a-546e-44c7-b804-eda5f9501752)

**Comment by SimoneZaza** [comment]
Instead of lowering the placeholder, can we keep the menu bar to be one line with an arrow to show next set of controls? Like this?: 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/3b132a5a-546e-44c7-b804-eda5f9501752)

**Comment by techsmyth** [comment]
@ccanos can you please put down an estimate on this?

**Comment by Comoque1** [comment]
The arrow is not centered and is not with 2 arrows as per design.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ccb694fb-3559-4ab7-b03b-7d8b44a58a89)

**Comment by Comoque1** [comment]
After discussed with @me-andre, it seems, that this change will consume some time and @SimoneZaza accepts the current behavior. Another card will be created to be improved the control.
