### ISSUE TITLE
Continue to last known location after verification

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3727]
## Description

As a user I want to be brought to the relevant community after signing in

## Acceptance criteria

- [ ] On the "thanks for verifying" page the button offered should take the user to the location from which they started the sign up flow

TBD: assuming the user lands back in the same browser?

Only store last visited Hub

Timebox: half a day

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
As result of the story testing, some 3 points have been identified for discussion.

- BUG: Private challenge `Sign in to Apply` button redirects to Hub page #3797
- BUG: Sign In / Up buttons on Forum and Contributors page, don't store return URL #3796
- Improve registration flow# 3795
