### ISSUE TITLE
BUG: Whiteboard preview image is not captured when saving 1st time

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3735]
**Describe the bug**
When creating a whiteboard and saving it, no preview image is shown on the card:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/98e1c443-8ce6-475f-8198-15e4ab59d122)
When opening it again, clicking on edit and then save, the preview is shown:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/35f92c99-f5e8-4c04-afbe-e5ce85c01ca6)

**To Reproduce**

1. Go to https://alkem.io/challengecentric/challenges/testingexperiment-4911/contribute/callouts/designs-2316
2. Click on add button
3. Create whiteboard, click Save

**Expected behavior**
To show preview immediately (after saving for the first time)

**Comment by techsmyth** [comment]
@alstojanovic is this the same one as what we talked about with the canvas renaming? did it ever get investigated? It looks like quite some whiteboards on production have blank images so keen to chase this one down...

**Comment by alstojanovic** [comment]
The whiteboard previews are generated fine for me. I think we can close this one. We talked about a problem with whiteboard callouts but I could never reproduce it, it was something about not being able to update a callout once you create a whiteboard. This was an issue but I think we fixed it some time ago.

**Comment by SimoneZaza** [comment]
Works for me :)
