### ISSUE TITLE
BUG: Discussion MD, doesn't allow the specified max limit when used new lines, MD visualizers, etc

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3758]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/forum/new
2. Create a discussion with such MD
```
As a new user, there are a few key steps to jump-start your ‘As a new user, there are a few key steps to jump-start your ‘As a new user, there are a few key steps to jump-start your

‘As a new user, there are a few key steps to jump-start your ‘As a new user, there are a few key steps to jump-😀

your ‘As a new user, re are a few key steps to jump-start your ‘As a new user, there are a few key steps to jump-start your ‘As a new user, there are a few key steps to jump-sta

rt your ‘As a new use
```
3. The displayed used symbols are 498/500, but the button doesn't allow the creation of the discussion.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2f3b7dc5-387f-4e63-9830-96f574c5e930)

**Expected behavior**
The behavior must be similar to the journey context fields

**Comment by valentinyanakiev** [comment]
Increase to LONG_TEXT_LENGTH on the server

**Comment by valentinyanakiev** [comment]
@me-andre I don't believe this would be necessary for this fix as I am changing one constant with another. It's a DTO constant as well, no need to change the DB as the field is text type there. This should solve the current problem. I wouldn't change constants like that as they are used in many places and that will likely lead to regressions (e.g. if the constant is used for a DB field size (and they are)).

**Comment by Comoque1** [comment]
Issue is reproducible, for all fields that have 500 and 2000 characters limit displayed on the client side.
- Callout
- Community updates
- Card / Whiteboard / innovation flow  templates (description)
- User profile (Bio)
- Organization profile (Description)

- Context fields (Impact and Who)

**Comment by SimoneZaza** [comment]
When this is picked up, please also address 'Character limits on forum' #3786

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ce578324-5611-4d53-8d12-c398a6409ac7)

**Comment by techsmyth** [comment]
Being taken up with #4534
