### ISSUE TITLE
Change error message for error signing in with an existing identifier.

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3767]
## Description

As a user, I want to know why I can't sign in with my LinkedIn account when it fails because I apparently already had an account with the same identifier.

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b8869545-2f89-4d8b-9c95-fd4b9ef9155e)

## Acceptance criteria

- [ ] Change the text of this message to: "You're trying to sign in with a LinkedIn/Microsoft account, but the associated email address was already used before. Please sign in with this e-mail address and password or try to reset the password. If that doesn't work, click here to contact the Alkemio team." 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
@larssondenise , any suggestions for the text?

**Comment by larssondenise** [comment]
@SimoneZaza this is sign in, not sign up right? Or do you mean that you can't sign up with a new gmail because it is already connected to the gmail account used via linkedin?

**Comment by hero101** [comment]
@SimoneZaza What is "click here to contact the Alkemio team" supposed to do?

**Comment by Comoque1** [comment]
@larssondenise, @SimoneZaza, this is the  "Sign Up" flow. But as the user tries to sign up with existing Linkedin account he is redirected to "Sign In" flow.  

Regarding the message, probably could be improved:
1. User cannot reset password of his Linkedin account through Alkemio
2. User cannot authenticate to Alkemio using its LinkedIn credentials, but through Linked in form

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/723eebed-73b9-4ea9-a02c-3ecd763ef9ac)

**Comment by Comoque1** [comment]
@larssondenise, @SimoneZaza, @techsmyth, if you accept it as is on the screen shot (in the above comment), we will close the story.

**Comment by techsmyth** [comment]
@Comoque1 yes the message could be improved, but the critical point is that the user knows why they cannot login - so this is ok. I notice there is a click here in the message - is that actually clickable? If not then please raise another issue + close this one. It is anyway now a translation update rather than a code one - so this is fine.

**Comment by Comoque1** [comment]
> @Comoque1 yes the message could be improved, but the critical point is that the user knows why they cannot login - so this is ok. I notice there is a click here in the message - is that actually clickable? If not then please raise another issue + close this one. It is anyway now a translation update rather than a code one - so this is fine.

@techsmyth, no, the message is not clickable.

**Comment by techsmyth** [comment]
ah, so there will be work needed anyway to update this text. For now you can close this one and please raise one to refine the actual translations - also in other languages.

**Comment by Comoque1** [comment]
Raised a story: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4053
