### ISSUE TITLE
Navigation block on the dashboard

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3769]
## Description

As a visitor of the Hub, I want to quickly navigate to or see the Challenges and Opportunities that are part of this Hub. 

## Acceptance criteria

- [ ] Add a navigation block in each Space Dashboard (not Challenges) with Challenges and the option to expand to see Opportunities. Clicking on the journey leads to the journey dashboard
- [ ] All journeys have an avatar with the relevant journey icon (cropped image + filter with primary color + icon. If cropped image is too difficult, use only icon - timebox 2h)
- [ ] Show all expands the list of Challenges / Opportunities if there are more
- [ ] Help icon to explain what the users see ('Here you can find all Challenges and possible Opportunities that are part of this Space. Navigate to one of them to read more')
- [ ] Lock icon for private Challenges behind the title

- [ ] Block is smaller with for example 2 Challenges only
- [ ] Block is empty when there are no Challenges / Opportunities

## Design
Figma: https://www.figma.com/file/zw3ymZPkFkVqtMsVLRuLRR/Structure-refresh-Q1%2FQ2?node-id=468%3A3040&t=cXxuJL5D0ZVjm8rQ-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/29b3e07a-6a15-4f59-a921-747cde872ac2)

**Comment by hero101** [comment]
Please provide the help text.

**Comment by hero101** [comment]
Have you considered components?
Will this work? - https://mui.com/material-ui/react-tree-view/#gmail-clone
