### ISSUE TITLE
Allow for direct publishing of callouts 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3782]
## Description

As a user I want to be able to immediately publish a callout, not having to save it as draft first.

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/c7cc1eca-577d-460f-a3b9-942509f13bf0)

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

## Additional Context

This was taken out of the acceptance criteria for the callouts in context create/edit in April 2023 since it raised too much complexity for it to be quickly implemented when creating the new dialogs for the Hub refresh.

**Comment by alstojanovic** [comment]
We added the publish dialog as part of the original story in the end. We agreed to call 2 mutations one after another.
