### ISSUE TITLE
Forum Character limit

### ISSUE THREAD

**Issue by MayteRagni** [alkem-io/client-web#3784]
**Is your feature request related to a problem? Please describe.**

As a team member I need to populate the forum to set an example for our users and give some helpful insights, guidance, and tips. However, there is a text limit of 500 w. which makes it a bit hard to do so. Especially because emojis/bold writing take up more space.

**Describe the solution you'd like**

I would extend the word limit to be able to successfully describing or giving answers to relevant questions + make it more visually appealing with more emojis or imported images etc. 

**Describe alternatives you've considered**

I think it would be nice to have at least 800 words available :)

**Comment by MayteRagni** [comment]
Example of a quite long, but still possible answer to questions on the forum: 

Are you an impact-driven individual that maybe is already working towards making a difference in your field of interest? Or simply are you a person who wants to contribute to making an impact on Challenges you care about but do not know how to or whom to reach out to? 
Alkemio is the only platform, so far, that you can count on for these types of needs! 😄
We offer you the possibility to create a network of people that are concerned and work towards the same goals even if they might come from completely different environments. What stops them from efficiently tackling common issues is that there is no way for different stakeholders to come together into one place and work out solutions together by sharing their resources and knowledge. 
But imagine if this was possible, it would make a big difference and it would guarantee more efficient and successful outcomes!
Alkemio is the platform that englobes a variety of tools that will help communities to work out their challenges together and reach a solution more efficiently since it is challenge centric and the whole point is to SOLVE your common issue! 🎯🎉
This is not it! If you are a person that is just looking to cooperate with other organizations on a certain topic you can subscribe to Alkemio and find your community to start contributing, everyone's help and expertise are valuable and could help reach the goal faster!
So if you are concerned about the world's biggest challenges and want to contribute to making this a better place to live, Alkemio is what you need!

**Comment by SimoneZaza** [comment]
Thanks @MayteRagni! I copied this over into another issue since I was missing some templates, so I'm closing this one.
