### ISSUE TITLE
Character limits on forum

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3786]
## Description

As a user I want to be able to use more text when asking for help or sharing insights in the forum.

## Acceptance criteria

- [x] Visible Character limit for a discussion to be 2000 
- [ ] Visible Character limit for comments to be 2000

## Additional Context
Original issue:
Is your feature request related to a problem? Please describe.

As a team member I need to populate the forum to set an example for our users and give some helpful insights, guidance, and tips. However, there is a text limit of 500 w. which makes it a bit hard to do so. Especially because emojis/bold writing take up more space.

Describe the solution you'd like

I would extend the word limit to be able to successfully describing or giving answers to relevant questions + make it more visually appealing with more emojis or imported images etc.

Describe alternatives you've considered

I think it would be nice to have at least 800 words available :)

I have tried to make an example of a slightly longer question/answer for the form so that the character limit can be extended more than sufficiently. Considering that bold writing and attachments occupy a lot more than words. Here is a screenshot of the characteristics of a well-written answer in the forum format:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/70273bd1-ce09-4d2c-a470-44d2d44502a8)

**Comment by Comoque1** [comment]
The sizes are extended and I am closing, the issue.
Raised a separate bug (BUG: WYSIWYG editors incorrect behavior #3848)to address correctly, the behavior when MD text is used (not pure text)

**Comment by Comoque1** [comment]
Reopening this story in order to address the issue properly (use proper server side size, apply correct client validation with respect to the server side text length size)
The bug mentioned in the above comment will be expanded with all the findings for the rest of MD fields.
