### ISSUE TITLE
Adding more than 1 reference on a card fails.

### ISSUE THREAD

**Issue by alstojanovic** [alkem-io/client-web#3793]
**Describe the bug**
When User tries to add more than 1 reference on an existing card the second createReferenceOnProfile mutation fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://dev.alkem.io/test/contribute/callouts/contribute-43/aspects/testcard-9732/settings
2. Click on '+' icon to add a reference
3. One reference is created.
4. Click on '+' icon again.
4. See error in GraphQL network tab.

**Expected behavior**
User should be able to create as much references he wants.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6098ca4375c041fa936966af/d09011c0-ba6d-41c9-ad3f-e2b78b72e532)

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/27874e6e-9ddf-4bf9-9c06-af35838f82f2)

The client needs to generate a different displayName - it is using the same one each time now
