### ISSUE TITLE
Management of documents per Hub

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3794]
## Description

As a hub admin I want to be able to see the documents stored and used within my Hub

## Acceptance criteria
- [ ] Hub admin interface extended with tab for managing documents as per design
- [ ] Confirmation dialog when deleting a file
- [ ] Expand server API to get the uploadedDate

NOT included from the designs:
- Deletion
- Quotas

## Additional Context

Figma: https://www.figma.com/file/dgZ2LH2SGpSGosZEjgNO3H/Settings---Document-Storage?node-id=0%3A1&t=odEXTpjNic9kXNlb-1

**Comment by valentinyanakiev** [comment]
@techsmyth do we need this for the initial release?

**Comment by techsmyth** [comment]
This can be after the release that does the migrations of existing links, so it can be later
