### ISSUE TITLE
Input field for alt text

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3800]
## Description

As a user with a visual impairment, I want to know what's in a picture.
As an admin, I want to share the content of the images in my journey also with people who are visually impaired

Acceptance criteria
- [x]  Input field for adding a description to a visual in edit box
- [x]  Display of resulting alternative text for a Visual next to Visual preview on settings page

## Additional Context
Figma: https://www.figma.com/file/EAdTafSSb6VAyQwS92EPEQ/Alt-text-for-visuals?node-id=0%3A1&t=LIPJ8qxfUTPFlecP-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/ac4b0e6d-0e2e-43c9-b2bd-410c375c14dc)

**Comment by alstojanovic** [comment]
@SimoneZaza how long should the alt text be? I assume we will have validation for the limit.

**Comment by SimoneZaza** [comment]
@alstojanovic sorry, didn't specify that indeed. Can you set it to be 100? Total limit should be 140, so then we'll have 40 left for the standardized text (see other issue in this epic).
