### ISSUE TITLE
BUG: When unauthenticated user navigate to opportunity of private challenge of private hub, page crash 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3803]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/hub-release-31-08-2022/challenges/chall-release-31-08-2022/opportunities/opp-release-31-08-2022/dashboard - page crash
2. The above page crash is hit when unauthenticated user try to access opportunity of private challenge of public hub
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4389677a-4fbb-4784-8244-76769e4eb47a)

**Expected behavior**
When unauthenticated user try to access opportunity of private challenge of public hub: TBD

**Additional context**
See all comments below

**Comment by hero101** [comment]
Not reproducible with either of the links.
The [first](https://dev.alkem.io/un-sdgs/challenges/food/opportunities/rural/dashboard) loads correctly everything without any errors.
The [second](https://acc.alkem.io/hub-release-31-08-2022/challenges/chall-release-31-08-2022/opportunities/opp-release-31-08-2022/dashboard) receives redirect requests and is correctly redirected to the Sign In page.

**Comment by Comoque1** [comment]
The issue is still reproducible on ACC env, with the provided example:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVpCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6bfdcb9e15cdc0bf85d87396b429d4c60889e42/image.png)

**Comment by Comoque1** [comment]
The issue is still reproducible, so moving it back to backlog.

**Comment by Comoque1** [comment]
The issue is still reproducible with brand new [Space / Challenge / Opportunity](https://acc-alkem.io/space-05-12-2023/challenges/challenge-05-12-2023-1469/opportunities/123321-2219/dashboard)
<img width="1491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekU1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8476c5cd9e36776d4676525f76ffdf5e548f8726/image.png" alt="image.png" />

**Comment by hero101** [comment]
I confirm it's reproducible with the mentioned setup locally.
I have gone through all the queries that run on that page and I couldn't find an issue.
<img width="302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5045d4e19ae02f53db752f3d3fc8457f9fd32c58/image.png" alt="image.png" />

Here is the error
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5SQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efbc3659250a1c189ffa2a17680f11b09b51053b/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
Not reproducible anymore.
