### ISSUE TITLE
Alternative text for all Visuals

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3806]
## Description

As a visually impaired user I want to have meaningful alternative text for images

## Acceptance criteria

- [ ] Visuals to have a translation string for each usage of the form. Examples:
- "Banner: {{visual.alternativeText}}" ==> Banner: 'Enabling online collaboration' challenge: users working together'
- Cards for journeys, cards on search
- "Avatar for user: {{visual.alternativeText}}" ==> Avatar for user: Neil with red shirt on blue background"
- Cards for Whiteboard => Card banner showing a preview of {{displayName}} whiteboard
- [x] alternativeText field limitied to 120 characters

Note: above translation strings are just examples; key is that they are a combination of both standard text using available information (e.g. journey type, user name) and the alternate text from the Visual entity.

Note: visual readers tend to stop at 140 chars, so allowing 20 for fixed + 120 for alternative text.

Timebox: 3 hours, priority order as above

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
Can we set a character limit to this text? Truncating the display name? The limit for the complete alternative text should be ~140 (see comment in the epic), so I would suggest 40 here, 100 for the manually added description?

**Comment by techsmyth** [comment]
Good point. I can see that total text of approx 140 makes sense. I would also though like to see if we can limit the different set of lengths being used. So maybe we make the user enterable text to have a max the same as tagline (so 120 characters), and then have say 80 characters for the fixed part In terms of fixed vs user editing: we do need to restrict the length entered for this text as part of the server validation. So we need to land this - suggest we chat it through with a couple of examples next week.

**Comment by techsmyth** [comment]
@alstojanovic see updated description, it has been discussed with SImone
