### ISSUE TITLE
Notifications settings

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3810]
## Description

As a user, I want to set my notification settings in a pleasant, structured manner. I want to be able to quickly find the notification setting that I'm looking for.

## Acceptance criteria

- [ ] Create new design based on text in design file

Not in scope: notification texts to be translated by translation file > we need separate issue for this!

## Additional Context

Figma: https://www.figma.com/file/CbYDZUjipUx6dEJR7Dr0H0/Personal-profile-settings?node-id=302%3A209&t=NKC4EYmtQ0XbvIV5-1

**Comment by MayteRagni** [comment]
https://www.figma.com/file/CbYDZUjipUx6dEJR7Dr0H0/Personal-profile-settings?node-id=302-209&t=LYvvu8BV8BXZzIQO-0
