### ISSUE TITLE
UX for InnovationSpace v1

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3813]
## Description

As a user I want to have a simple first innovation space version

## Acceptance criteria

- [ ] UX design

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
I think this is the same as this issue https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/3815

**Comment by SimoneZaza** [comment]
See #3815
