### ISSUE TITLE
BUG: Opportunity shows that I'm a "Member" while I'm actually not

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3814]
**Describe the bug**
When an opportunity is open to hub/challenge(?) members to contribute, it shows the member label on the description block on the dashboard, also to people who are not a member. There is no way for a user to actually become a member (or request to become a member). This is important since the notifications for the actions happening in that opportunity depend on the user being a member.

So, for now, this should remain a Join button, also when members of the hub are allowed to contribute anyway.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/7c012565-30cf-4db7-92f2-e1f5bb2b4841)

**Additional context**
This button should be using the myMembershipStatus field on Community entity:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e9366b9e-976b-4fb5-9942-a450413436e1)

**Comment by techsmyth** [comment]
@me-andre please also have a look at this with the other one re membership status

**Comment by SimoneZaza** [comment]
@techsmyth @larssondenise this seems to be a little more complicated.. What do we want? Currently, there are no application, membership, and authorization blocks in the Opportunity settings. Maybe we should expand the work on membership/visibility settings (#3834) of the space to also include the opportunity?

**Comment by techsmyth** [comment]
This needs a chat through, hard to land by comments. I am reluctant to pick up opportunity membership near term, so we may need a patch @me-andre if you are around the next 20 min somewhere let me know as would like to talk through what the component currently does - as it should regardless be using myMembershipStatus in the logic.
