### ISSUE TITLE
More accessible way to select the time of an event

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3820]
## Description

As a user, I want to be able to select the time of an event in a simple and intuitive way, also on desktop
As a user with a visual impairment, I want to be able to select the time of an event in an accessible way.

## Acceptance criteria

- [ ] Remove the clock thing for a simple dropdown with 30 min time steps, like in Teams (see screenshot below)
- [ ] No support for directly entering the time

## Screenshots 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/97bfe267-f269-45b7-96ef-a4e189d60758)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/26f44b4f-757f-4c56-82f9-00191e9faab8)

**Comment by Comoque1** [comment]
Tested on DEV env.
On mobile device the "End time" box overlaps "Type of events"
The list of hours fit through out the whole height of the screen
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9dc37eb4-5ebc-486f-85c5-a4d7549ba699)

**Comment by Comoque1** [comment]
Looks much nicer on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a24aac33-4513-49e7-aff5-c4124588474c)

Bear in mind that with this control, cannot be applied fine tune of the minutes (i.e. cannot be set 21:17 or 21:22)
