### ISSUE TITLE
BUG: Public Services tag on home page doesn't include public services hub (dutch synonym missing)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3833]
**Describe the bug**
When a user filters on Public Services at the home page, the hub that is all about public services doesn't show up since it is tagged with "publieke dienstverlening" instead of "publieke diensten"

**To Reproduce**

1. Go to https://alkem.io/home/?hub-filter=Public+Services&hub-filter=Publieke+Diensten
2. It doesn't show the hub "Publieke Dienstverlening"

**Additional context**
Of course, as a quick fix, we could add another tag to the hub, but if it's not a lot of work, it would be better to add "dienstverlening" to the filter, since "publieke dienstverlening" is more common in Dutch than "publieke diensten"

**Comment by larssondenise** [comment]
Can we check this together, I think we need to decide on maybe a more general one so that uwv and vng for example are also part of it! @techsmyth
