### ISSUE TITLE
BUG: Subscriptions working incorrectly on whiteboards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3838]
**Describe the bug**
During Purpose hour 17/4, I had a dialog open with our whiteboard in checked in status (Denise was editing it from another device). At one point, the whiteboard in my dialog changed: all of a sudden I saw one of the other whiteboards in the callout. Appearantly, the other group saved their whiteboard and my dialog was updated as well. After a while (~a minute?) it changed back to the correct one. I'm not sure whether this happened automatically or that Denise clicked save.

**To Reproduce**
Edit any whiteboard and save it while someone in the same callout is viewing another whiteboard.

**Expected behavior**
Subscriptions should only operate for whiteboards that are not being edited by you.

_Note: this has the potential for lost work._

**Comment by SimoneZaza** [comment]
@alstojanovic @techsmyth anything to add?

**Comment by techsmyth** [comment]
@SimoneZaza it looked very much like the client was picking up any whiteboard update event that the user could subscribe to. Important to note that the two whiteboards were in the same callout: https://alkem.io/challengecentric/challenges/enabling/opportunities/purposehour-8149/contribute/callouts/startingacommunity-6003

**Comment by techsmyth** [comment]
Some initial analysis on this one:.

Setup: local development environment, with two whiteboards in use in the same callout. Directly on playground setup subscriptions for the two whiteboards, and then edit one and then the other whiteboard. All is working fine. 

Try from the client using latest from develop: am getting the following error:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/130ec636-84bd-46e9-b024-0e543ef13ef1)

In looking at the subscription itself, is it an issue with the usage of the apollo cache as the id of the returned entity is canvasID and not just id? Should this subscription not be returning the actual whiteboard?
