### ISSUE TITLE
Move callouts to knowledge base tab

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3875]
## Description

As a Community Admin, I want to be able to move callouts to hub knowledge base tab

## Acceptance criteria
- [ ] Migration to set callouts with empty group string to have group "knowledge"
- [ ] Community Admin is able to move callouts to hub knowledge base tab from, dashboard, community and challenges tab

## Dev note:
We need to rethink how to put Callouts in the KB tab. Having `group = null` for callouts in the KB tab makes imposible to move a callout there. This happens in many other places too, if we send a string set to null or empty, the server (because of TypeOrm or because of the way we build the queries) ignores it and doesn't set the column.
So the following mutation doesn't do anything:
```graphql
mutation {
  updateCallout(calloutData:{
    ID:"20da3d7c-e8d7-4bee-9891-d91179317c7b",
    group:""
  }){
    id
    group
  }
}
```

----

The combo box items are set in `src/domain/collaboration/callout/CalloutForm.tsx` around line 180

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
it should not be that the empty string maps to the knowledge tab. It should be that if the group is not set that it maps to the group used for the knowledge tab.
