### ISSUE TITLE
Show Demo hubs in My Hubs block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3886]
## Description

As a user trying out Alkemio with a Demo hub, I want an easy way to reach my Hub. 

## Acceptance criteria

- [ ] Show Demo hub in My Hubs block on the home page
- [ ] Demo hubs to be shown after the active hubs (sort order, to be done server)

Note: hubs query likely will need to be updated to also specify the "DEMO" visibility. To check if this causes issues e.g. with the bottom section. 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
Same as #3885

**Comment by techsmyth** [comment]
@SimoneZaza 3885 was closed, so keeping this one open
