### ISSUE TITLE
Keep user on child entity, when he close dialog from parent activity log related to the child entity

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3896]
## Description

As a User I want to remain on activity journey level, which I have opened from parent activity log.

## Acceptance criteria

- [ ] Keep user on child entity, when he close dialog from parent activity log related to the child entity
  - [ ] User who open from HUB activity log -  Card, Comment, Callout, Whiteboard created on child challenge, after closing the dialog, remains on the challenge level
  - [ ] User who open from Challenge activity log -  Card, Comment, Callout, Whiteboard created on child opportunity, after closing the dialog, remains on the opportunity level

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
Seems to be fixed :)
