### ISSUE TITLE
BUG: Recommendations endpoints are pointing to *./contribute

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3906]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/challengecentric/dashboard
2. Click on any link from `Recommended by the Host` - user is redirected to 404 page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8e3da008-d1c6-4768-91f3-592db2e003a0)

**Expected behavior**
Recommendation links point to correct endpoint

**Comment by valentinyanakiev** [comment]
Going to be addressed by updating the entries in the DB by the OPS team
