### ISSUE TITLE
BUG (PROD): Hub member cannot join / apply private challenge

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3909]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/helease-21-04-23-hub/challenges/release-21-04-23-cha-8334/contribute
2. Make sure you are member of the parent hub
3. Click on the link below the banner - it is not clickable. Label 'Member' is displayed wrong (must be join / apply)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/705360cd-318d-4873-8f93-f8b09924ff85)

**Expected behavior**
When user reach dialog for unauthorized user to Hub / Challenge, he must have Join / Apply buttons available, instead of "Member" label.

**Comment by techsmyth** [comment]
This button should be being picked up from myMembershipStatus field on Community

**Comment by Comoque1** [comment]
The issue may be related to #3814
