### ISSUE TITLE
Multiple/all day/Subspace events: Create&Edit dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3912]
## Description

As a user, I want to be able to specify events that span multiple days. 
As a user, I want to quickly create full-day events without the need of time input.

## Acceptance criteria

- Dialog to be updated as per design
- [ ] Multiple/All day event (= already in the database)
- [ ] 15 min time steps instead of 30
- Show in Space (server work #4540)
- Add references (extracted to: #7006)
- [ ] Add location field (profile: city)

_See the comments for clarifications._

## Additional Context
- Select start date
- End date is set to be the same as start date  
- End date can be set to be later
- If start date is then changed, end date remains the same
- Validation error (tooltip) if needed: Start of the event cannot be set to be later than the end date/time

## Server things
From Svetoslav: 

- There is a beginning date
- There is no end date. The end date is the sum of begin date and durationMinutes - a column in the database.
- There is no full-day field. There is a durationDays column though _UPDATE: there is wholeDay field (used for the implementation)._
- There is a timezone but it is hard to rely on. The original date (on the UI) is stored in the database. When read, the date is returned in UTC

## Design
https://www.figma.com/design/rddyv3LBg0sbm1b7Yny9ze/Calendar-V3?node-id=35-221&t=kBz9ml9y23WojMQ7-1

**Comment by bobbykolev** [comment]
Note the following changes and clarifications:
- the requirement of the reference was extracted in: #7006;
- the URL requirement was removed from the story. URL field in the location entity seems redundant as we'll need it only for events. Furthermore, a URL can be easily added to the references or inside the description (like in most other calendars).
- The All-day option will allow only a single day - disabling time and end date.

The above was discussed with @SimoneZaza  

Screenshot of the altered design based on the above:
<img width="1722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEkxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52294ad93cbd5efb4b1c089c6b70333afa92b287/Screenshot%202024-10-08%20181353.png" alt="Screenshot 2024-10-08 181353.png" />
