### ISSUE TITLE
Admin for Innovation Hubs - full

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3914]
## Description
As a platform admin I want to be able to manage innovation hubs

## Acceptance criteria
- [ ] Overview of Spaces included in this Innovation Hub + visibility + host organization
- [ ]  User can add and remove Spaces
- [ ]  User can sort the order of the spaces

Note: the ability to filter by visibility is not possible with this implementation.

## Additional Context
This is needed in a very functional way as otherwise it will be hard to create / manage innovation hubs e.g. upload image for the banner.

For now, the only criteria to filter on is 'visibility' and the types are demo, archived, active. In the future filter criteria can for example also be host organization, tags, etc.

## Design 
https://www.figma.com/file/wZkvw4E1KhRq9Ga6L6HmSL/Innovation-Spaces?type=design&node-id=655%3A2489&t=gaiNzFRM6LKsxzqT-1

**Comment by hero101** [comment]
This design requires more than discussed in the domain model.
alkem-io/server#2752 needs to be updated to fit these requirements.

**Comment by techsmyth** [comment]
@hero101 I see we were looking at the design at the same time :) I just added comments - will need to be another iteration of the design.

**Comment by techsmyth** [comment]
Split this issue into two issues, which both need to be estimated.

**Comment by Comoque1** [comment]
When I add a space to innovationHubs, it is not returned in 'Current selection' list.
Also demo spaces are not displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXVxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e378fe9a9d3af9f025d41e05daf5dc48a198e1a6/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXlxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87c414f7835be89c8c2ace68d25fece195fbd92f/image.png)

**Comment by Comoque1** [comment]
Raised separate issues from the above comments in the epic: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4757
