### ISSUE TITLE
BUG:When Admin try to remove Challenge, that have child journey the error that is thrown is "BAD_INPUT"

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3929]
**Describe the bug**
Admin can't delete a challenge from her demo hub (and Simone can't either). We both get the message 'bad user input'
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/0c3a0b80-7662-4fb9-a8a6-2d8cb8d411e2)

**To Reproduce**

1. Go to https://acc.alkem.io/release-11-01-23-hub/dashboard
2. Try to remove a challenge with an opportunity: error is thrown(correct), but the message is not informative: `"Unable to remove challenge (andrewschallenge-3913) as it contains 1 opportunities"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dd2cd0f5-347a-4e89-90e1-fef98f66675d)

**Expected behavior**
Correct message is shown to the Admin: This Challenge cannot be deleted since there are Opportunities inside. Please delete these Opportunities first.

**Comment by SimoneZaza** [comment]
@techsmyth can you remove the Circulaire Economie Challenge from the DSIH hub in another way?

**Comment by SimoneZaza** [comment]
I think this is actually the same issue as #3459, if this is fixed, that one can probably also be closed.

**Comment by techsmyth** [comment]
@alstojanovic @valentinyanakiev yes this should be a different exception type, as it is not a validation exception.
