### ISSUE TITLE
BUG: Challenges cards inconsistencies on Hub dashboard and Challenges tabs

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3937]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/callouts-hub/dashboard  and expand the challenge card
2. On other browser go to: https://dev.alkem.io/callouts-hub/challenges and expand the challenge card
3. There are difference and the crd used under "Challenges " tab is the correct (Without apply button, with lock icon and without Hub)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ddf4e707-7c12-4620-a661-3ff7732de544)

**Expected behavior**
The challenge card used on Challenges tab must be used on Dashboard tab.

**Comment by SimoneZaza** [comment]
Challenges are no longer displayed on Dashboard. Cards on Challenges tab look fine
