### ISSUE TITLE
BUG: Share button opening something else than our share dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3940]
**Describe the bug**
The share button in the tab menu of a journey doesn't open the regular share dialog but something else instead. This was fine when the share button only showed the url, but now we have the functionality to directly share to other users, I really miss it.
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/dc703d93-2ba2-48f2-86bc-cd47ff629d86)
**To Reproduce**

1. Go to https://alkem.io/challengecentric/challenges/enabling/dashboard
2. Click on share button in the tab menu
4. See error (I hope)

**Expected behavior**
Fully remove the native share functionality for now

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Additional context**

**Comment by Comoque1** [comment]
Tested using BrowserStack on Apple / Safary and works correct now
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1GQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c92b12f12443a330923393de07b7c66aaf847a0e/image.png)
