### ISSUE TITLE
Platform page for innovation library

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3951]
## Description

As a user I want to see the possible templates and innovation packs that can guide me on my innovation journey 
As Alkemio, I want an easy way to demonstrate the innovation library to explain its potential

## Acceptance criteria

- [ ] Innovation library added to the platform menu
- [ ] Section for innovation packs
     - Cards for innovation packs include titel, description, tags, number of templates, provider
     - Search bar
     - Expand button as well as show all button open a dialog with all innovation packs
     - Clicking on innovation pack goes to innovation pack profile
     - Five innovation packs per row
- [ ] On mobile: 
     - horizontal scroll, no need for expand or show more 

## Additional Context
https://www.figma.com/file/EJFZQmkQ6ZxQTLkF0h9UES/Innovation-Library?type=design&node-id=0%3A1&t=b4g8lTFd2oSRdmj2-1

**Comment by Comoque1** [comment]
AC from story is met and tested on DEV env.
Some points and notes from the designs are added in a separate story: Library page improvements (Mobile) #4000
