### ISSUE TITLE
BUG: Collection of links callout + closed message

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3954]
**Describe the bug**
The text at the bottom of a closed collction of links refers to cards:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c4fe34cf-0fd3-4293-aa90-e164bc09de52)

**To Reproduce**

1. Go to any dashboard page with the collection of links recommendations
2. click on the expand button, the dialog has a label at the bottom that is wrong

**Expected behavior**
For a collection of links callout that is closed this label should not be shown.

**Comment by valentinyanakiev** [comment]
@techsmyth how is this related with the related story?

**Comment by techsmyth** [comment]
The related story also has the comment that the bottom label should be removed. But it may be that we want to do this one without waiting for the other.
