### ISSUE TITLE
BUG: Template doesn't allow to select part

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3964]
**Describe the bug**
When you import one of the templates, you are not able to select various blocks of content when selecting a part of the template.

**To Reproduce**

**Expected behavior**
When I hover over the content, I expect to be able to select all like the picture below to be able to move it / make it smaller etc. Instead of having to click on each block separately
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/16f76114-a839-4c25-bbfd-10e0c6759470)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/cb3ae9c5-8f64-4163-be12-159774bb4356)

**Comment by larssondenise** [comment]
@SimoneZaza Still not really.. ctrl A does select it all, but still selecting parts of it does not work...

**Comment by ccanos** [comment]
@larssondenise please, can you put here links of problematic templates when you find them?

**Comment by larssondenise** [comment]
Checked a few, I think they are all fixed!
