### ISSUE TITLE
BUG: Tooltip is not not displayed on mobile

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3966]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/dashboard
2. Hover / click over the question mark on Navigation block - none tooltip is displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c49ca2de-c483-4ad4-b02e-e892b0535eaf)

**Expected behavior**
Tooltips on these question mark icons should be displayed when tapping on them, with a close button at the top right. This can also be implemented on desktop if that's easier, then we have hover (normal) + tap (with close button) on desktop and only tap on mobile. We have to decide what to do with tooltips that don't have a dedicated icon, for example, the tooltips that appear when hovering certain objects on a desktop.

**Comment by Comoque1** [comment]
@SimoneZaza, @larssondenise, could you please define behavior for help icons (with tooltips) on mobile devices?

**Comment by larssondenise** [comment]
I would expect clicking on the help icon, shows the helper text (@SimoneZaza you?). I see that other tooltips on mobile also don't display helper text. So also a bigger gap analysis is needed to check behavior of the other tooltips.

**Comment by SimoneZaza** [comment]
@Comoque1 @larssondenise Tooltips on these question mark icons should be displayed when tapping on them, with a close button at the top right. This can also be implemented on desktop if that's easier, then we have hover (normal) + tap (with close button) on desktop and only tap on mobile. We have to decide what to do with tooltips that don't have a dedicated icon, for example, the tooltips that appear when hovering certain objects on a desktop.
