### ISSUE TITLE
Upload document text + second dialog

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#3979]
## Description

As a user I do not want to have to click through a confirmation dialog every time I upload a document
As an admin I want to ensure that users comply with the t+cs of the platform re content that is uploaded

## Acceptance criteria

- [ ] Text underneath dialog for choosing a file to be: Please make sure that this document complies with Alkemio’s content standards, click here for the terms and conditions
- [x] Remove second popup dialog: 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e0bed06e-8567-4df8-a9b7-f44eefb7b58f)

## Additional Context
Current design:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/7fed339c-f170-43d8-95dd-d7632f42855c)
Text: Keep in mind that all uploaded files become accessible to everyone with the link and can only be deleted by the Alkemio team. Click here for the terms and conditions.
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/dd3fef61-53ae-45fd-85df-93df3ba8c63e)
Text: Please make sure that this document complies with Alkemio’s content standards. Click here to see the Acceptable Usage Policy (section 7). [and then the checkbox]

**Comment by techsmyth** [comment]
@SimoneZaza this dialog can be removed. I checked our usage policy on https://www.alkemio.foundation/legal/hub/#aup 
and the uploading is covered imho.

Also we now have the user that uploaded it, as well as the context where it is uploaded to - so much stronger meta information than before. 

Please have a look and see if any other adjustments are needed around this user experience before we just take away the pop up dialog...

**Comment by SimoneZaza** [comment]
@techsmyth I would suggest changing the helper text underneath the input field to "Please make sure that this document complies with Alkemio’s content standards, click here for the terms and conditions" and removing the confirmation dialog. I don't think we need to state here that the documents are protected?
