### ISSUE TITLE
BUG: When user remove some of its profile data, it remains

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4038]
**Describe the bug**

**To Reproduce**

1. Go to your user profile settings (i.e. https://acc.alkem.io/user/evgeni-dimitrov-8814/settings/profile)
2. Fill up with data all the fields.
3. Save the changes
4. Remove all not required fields - the data remains for the following fields:
 - Phone
 - Tagline
 - Social references
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b96ac347-d95e-447d-9849-0a03cf08bd20)

**Expected behavior**
When user remove some of its data, the new state is saved.

**Comment by hero101** [comment]
The server was not able to handle empty strings, but the client does not send the empty strings either.
Now the server is able to handle empty strings, at least on the profile, but the client also needs some work.
