### ISSUE TITLE
Refinements on InnovationHub display

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4041]
## Description

As a champion I want to see the InnovationHub displayed nicely

## Acceptance criteria

- [ ] Change the title to be H2
- [ ] Banner image to be the correct width, aligned with the items in the navigation bar
- [ ] Footer to be clickable
- [ ] Banners on other pages to state that you're leaving the innovation hub

## Additional Context
Timeboxed to a day
Bucket to reserve capacity in the sprint

**Comment by hero101** [comment]
We need to define the requirements to derisk this one, having in mind the event this week and the 29th is a public holiday I don't believe we would have enough time to release this on the 31th as planned.
