### ISSUE TITLE
Update sign-up pages for FR language

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4050]
## Description

As a User I want to have clear french translations on Sign up page

## Acceptance criteria

- [ ] Page title: Créez un compte et commencez à faire\ \ du bien
- [ ] Sign up button
- [ ] Fields labels
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b1e21ba2-783a-4ae4-86ad-e36b8bef43b7)

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@larssondenise this is one you may need to discuss with Andrew....
