### ISSUE TITLE
Update text for the error "Register with existing identifier"

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4053]
## Description

As a I want to have correct message for the case where I try to register with credentials that are already used (i.e. LinkedIn).

Current message is: `You're trying to sign in with a LinkedIn/Microsoft account, but the associated email address was already used before. Please sign in with this e-mail address and password or try to reset the password. If that doesn't work, click here to contact the Alkemio team.`

## Acceptance criteria

- [ ] TBD

## Additional Context

Screen shots / UX designs / data that are relevant.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a6df5891-b401-4922-8132-b33bfffb973c)

**Comment by larssondenise** [comment]
@techsmyth @Comoque1 not sure if I see what is wrong with the text here? :)

**Comment by Comoque1** [comment]
> @techsmyth @Comoque1 not sure if I see what is wrong with the text here? :)

The text says.....",click here to contact the Alkemio team", but the area is not clickable.

**Comment by hero101** [comment]
@techsmyth @larssondenise  Please, define the AC.

**Comment by hero101** [comment]
Please define the AC.

**Comment by techsmyth** [comment]
@hero101 Denise will pick up the text to go into this

**Comment by hero101** [comment]
@larssondenise I see this issue is moved to review but there isn't any related PR. Is this coordinated with someone?

**Comment by larssondenise** [comment]
sorry yes, already picked up!
