### ISSUE TITLE
BUG: Files uploaded on Opp are shown as Challenge location

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4054]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/doc-hub/storage
2. Create new opportunity
3. Add documents to the opportunity profile and to an aspect of it
4. Go to the hub storage - all docs displayed are shown as they are part of hub / challenge entities
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0737566b-278d-46fb-9deb-c82846fba350)

**Expected behavior**
Correct relations document / entity are shown on storage page

**Comment by valentinyanakiev** [comment]
@Comoque1 that's not a bug, that's per design. There is no storage bucket on Opportunity level, all Opp files are stored on the Challenge storage bucket.
