### ISSUE TITLE
Design for how we work with top level queries

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4055]
## Description

As a client developer I want to have less parameters / context passed around
## Acceptance criteria
- [ ] Look at best practices + how it is done other apis
- [ ] Review of all usage of nested queries on the client 
- [ ] List of entities to make available in top level queries (or as fields one level deep)
- [ ] Prioritized list of client updates to simlify code

Timebox: a day 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
Finding are documented in a hackmd file: https://hackmd.io/fBJs8CgyTbKDJ1o-iO_o4Q

**Comment by valentinyanakiev** [comment]
I have added a Profile story to New Issues.
