### ISSUE TITLE
Visual consistency review 

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#4075]
## Description

As an Alkemio user I want elements in the web application to be consistent.

## Context
During a review with @SimoneZaza we have a identified a few things that may need a visual review but that I estimated that require more effort than the time available for now. Probably many of these things will be addressed when we implement the component library.

## Acceptance criteria
- [ ] Put filters (and the rest of the actions of the blocks) a bit higher:
 ![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/57fbb47a-84ba-4caa-abe6-9fa00e0c5670)
For now this is fixed with a flex alignItems center, but I think the header of those blocks should be reviewed because the dialog expander icon should stay always at the top right, the title on the top left, and the rest of the elements should flow, with the current markup that's not possible and we end up doing quirks and tricks to adapt the view to the phones screen size

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by ccanos** [comment]
@SimoneZaza  I have put this directly in the icebox because I think we can address many things when we start a component library. But for now we can use this as a placeholder or a list of things to have in mind, feel free to change anything in here

**Comment by SimoneZaza** [comment]
part of a more structural approach in a different issue
