### ISSUE TITLE
BUG: Description of links unnecessarily truncated

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4079]
**Describe the bug**
In wide blocks and in dialogs the description of a link (Collection of links callout) is truncated while it's not necessary to do so. 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/baa71084-c3be-471e-b0f7-e513cd769a14)

**To Reproduce**

**Expected behavior**
Wide block: use the space of  1 full line
Dialog: show all

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
Looks OK on DEV, after the fix
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f215c8f8-11a8-48c6-907e-dee1111ba1ad)
