### ISSUE TITLE
BUG: Info text on knowledge base page no longer relevant

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4080]
**Describe the bug**
Since the Contribute tab became the Knowledge base tab, the info block that is shown on the left is showing irrelevant information for this page
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/5d5eab30-b96f-49eb-9995-0336b288a253)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by larssondenise** [comment]
This is hardcoded I think, will check with Dev @SimoneZaza

**Comment by larssondenise** [comment]
Added to translation file
