### ISSUE TITLE
BUG: Whiteboard preview image on cards in All templates block (Innovation library) breaks the card consistency

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4082]
**Describe the bug**
Since the all templates block in the Innovation Library shows different types of cards, these cards should look consistent. The whiteboard card breaks this style on certain resolutions since the image seems to align to the 1.6(?) aspect ratio instead of a set height (consistent with the other cards). 

**To Reproduce**

**Expected behavior**
Fixed height, crop from center

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ccanos** [comment]
The aspect ratio of the images is set in the component, `src/core/ui/card/CardImage.tsx`
In theory we should crop that image to adapt the card to the surrounding cards.
maybe we can pass a property to unset it when the card is surrounded by "not-all-the-same-height" cards?
