### ISSUE TITLE
Opportunity Membership messages

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4102]
## Description
It is currently not possible to 'join' an opportunity, but you can be added manually by the Admin. 

If the settings of the challenge are 'Space members can contribute to Challenge', they can also contribute to the Opportunity. If not, the user can not contribute but also not join. This makes it very confusing

## Acceptance criteria

- [ ] Add application button on top of the page on Opportunity Dashboard
- [ ] Remove 'Applications not enabled' button on About tab
#### opportunity.community.membershipStatus = notMember  && challenge.community.membershipStatus !== member: 
get message
  - [ ] Web (Interested in joining this Opportunity? You'll have to become a member of the Challenge first, click here to go there)
  - [ ] Mobile (To be able to join this Opportunity, you'll have to become a member of the Challenge first)
- [ ] Clicking on the message (button), user is redirected to Challenge level, where he can see how to become a member
#### opportunity.community.membershipStatus = notMember  && challenge.community.membershipStatus === member: 
get message: "Send a message to opportunity leads to become a member" + clicking it pops up the sendMessage dialog to the leads

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/d80ef812-dfc5-4b3e-94ed-af63026682ef)

**Comment by Comoque1** [comment]
After fast discussion with @SimoneZaza and @alstojanovic , the following feedback is being addressed:
- change the message: `Send a message to Challenge leads to become a member` to `Send a message to Opportunity leads to become a member`
- send the message to Opportunity leads
- If fast add the button to Opportunity / Dashboard tab
