### ISSUE TITLE
Activity in recent contributions wrongly displayed

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4104]
## Description

As a user I don't want to be confused by the English terminology + incorrect information in the recent contributions block

## Acceptance criteria

- [ ] Time in recent activity to be translatable
- [ ] When lead adds new member, it shouldn't display their information (change together with invitations and when we remove the option to add members manually?)
- [ ] Opportunity activity is shown in Challenge which results in double text when new member enter (User joined Opportunity X in Opportunity X) 

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/adb92536-f723-40cf-adc9-88b2477a87bf)

**Comment by SimoneZaza** [comment]
needs to be split in 2: time to be translatable (everywhere); update sentences in translation file
