### ISSUE TITLE
BUG: Unauthenticated user cannot see Hubs on Innovation Hubs page and the banner

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4124]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-uwv.alkem.io/home without authenticating
2. The hubs assigned to the visible list or demo hub are not displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7d81b594-003a-4a5b-93a3-290e45ff6cf4)

**Expected behavior**
Unauthenticated user can see Hubs on Innovation Hubs page and the banner of the innovationHub

**Comment by hero101** [comment]
It's when a membership status is requested for unauthenticated users.
The field is described as "The membership status of the currently logged-in user".
There are errors returned but the data is there.
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/f1558043-a957-4e76-be7b-d923392cb19a)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/8c7b3be0-3ef9-4f26-8015-8b9d23bb0c2d)
