### ISSUE TITLE
Update text in recent contributions

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4150]
## Description
As a ux lead I want clean contributions

## Acceptance criteria

- [ ] Remove 'to opportunity X'

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/5c196061-7b64-49ab-aeb4-e431ab4f94a5)

**Comment by larssondenise** [comment]
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/125a4142-3606-42e2-bdaa-4a555b4b71d4)

![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/4fd1c3b5-1fd6-4f91-af01-7552d5bbeacd)

**Comment by larssondenise** [comment]
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/90258089-33c3-413f-8029-1b18e23d3ddf)

**Comment by larssondenise** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm5aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3541613051617234658aa0e7c517759aa6ea21a8/image.png)
The code is: 
 "member-joined": "{{time}} '<userlink>{{user}}</userlink>' joined the {{communityType}} '{{journeyDisplayName}}'",

- The first '{{journeyDisplayName}}' cannot be removed, as it will will result in 
" 4 months ago 'Jet Klaver' joined the opportunity in 'Volwassenheidsmodel' "
- Removing the second journeydisplayname as the parent entity is also not desirable as you will loose the link option.

**Comment by SimoneZaza** [comment]
this got fixed when redesigning the activity blocks for my dashboard
