### ISSUE TITLE
Time to be translatable

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4151]
## Description

As a dutch user I don't want to be confused by the time stamp in English

## Acceptance criteria

- [ ] Make time to be translatable

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/d4a08c04-4ab8-4b6a-b1c7-88e50aad49ce)

**Comment by techsmyth** [comment]
Done as part of the activity text being fully translatable.
