### ISSUE TITLE
Pending invitations user

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4160]
## Description

As a user I want an overview of my pending invitations or applications

## Acceptance criteria

- [ ] Pending memberships, including pending invitations/open applications added to menu under profile avatar
- [ ] Number of invites visible 
- [ ] clicking opens a dialog with open invitations + open applications
- [ ] New cards for pending invitations
- [ ] Clicking on invitation opens the invitation with, if added, the message of the lead and option to decline, join or hide. And the option to go back to overview dialog. 
- [ ] Terms & Conditions visible 
- [ ] If there are more than 5 open applications new row, not horizontal scroll. On mobile, horizontal scroll. 

## Additional Context

https://www.figma.com/file/CAveHHIWJanVVXIWis2p1H?node-id=0:1&locale=en&type=design

**Comment by SimoneZaza** [comment]
13, considering reviews and testing, new containers, new cards, extending dropdown menu of the profile.
