### ISSUE TITLE
Clicking on Alkemio logo (top left corner), should keep user on the same subdomain

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4167]
## Description

As a User I want to remain on same subdomain, when I click on Alkemio logo

## Acceptance criteria

- [ ] When user is on uwv.alkem.io and click alkemio logo, should be redirected to uwv.alkem.io
- [ ] When user is on alkem.io and click alkemio logo, should be redirected to alkem.io
- [ ] When user is on demo.alkem.io and click alkemio logo, should be redirected to demo.alkem.io

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by valentinyanakiev** [comment]
@Comoque1 this is not a priority nor a decision has been made on the business behavior of it, so it is fine to redirect to the main domain.
