### ISSUE TITLE
BUG: 'This is a Demo Space....' label is missing on uwv subdoamin hubs 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4168]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-uwv.alkem.io/hub-17-05-2023-release/dashboard - 'This is a Demo Space....' label is missing on uwv subdoamin hubs 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5ae68c18-3987-4e06-950d-8c79410ba00b)

**Expected behavior**
Label 'This is a Demo Space. Click here to collaborate in active Spaces.' must be available for user opening hubs of subdoamain, while on it.

**Comment by hero101** [comment]
@valentinyanakiev @SimoneZaza 
This isn't an issue with the Hubs, in fact, there isn't an issue at all.
It was understood as "this Space is outside of the active Hub you are in" but it actually is "you are in a Space with demo visibility", which works on the three domain options and is not considered as a part of the Hub feature.
This issue also raises the question that users need a way to know if the content they are viewing is outside of their active Hub.

**Comment by hero101** [comment]
what are we going to do with this story?

**Comment by hero101** [comment]
Closing this issue, because there is no bug. There even is already a label stating you are in a Space outside of your Hub.
