### ISSUE TITLE
BUG: Alkemio logo always opens up new page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4174]
**Describe the bug**
Everytime, even when not in an innovation Hub, clicking on the Alkemio logo opens a new tab

**To Reproduce**

**Expected behavior**
Clicking on Alkemio logo should only open up a new tab with alkem.io/home when you are for example in uwv.alkem.io/home

**Screenshots**

**Comment by Comoque1** [comment]
Duplicate with #4212
