### ISSUE TITLE
Design for multi-user whiteboard

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4178]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] What does it look like when multiple users are editing the same whiteboard?
   - [ ] Their presence
   - [ ] Their cursors?
   - [ ] What they're doing? 
- [ ] Access models: lock? single user/multi-user? only invitees? only members of this space? only alkemio users? everyone?
- [ ] 

How do others do this?
- [ ] Miro
- [ ] Figma
- [ ] Google docs/google whiteboard
- [ ] ...

## Additional Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk5KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d17b470272e441f5d461bb047e3b792b18929704/image.png)

Link to Figma file with research info: https://www.figma.com/file/MzjrE0u8iwQjQ8os56AitR/Multi-user-whiteboards?type=design&node-id=0%3A1&t=HoE5GwvDqF4vThBf-1

**Comment by hero101** [comment]
Who can verify this? It's been in Review for a month now.

**Comment by SimoneZaza** [comment]
@hero101 thanks for the reminder

**Comment by SimoneZaza** [comment]
@techsmyth can you have a look if you agree with this design?

**Comment by hero101** [comment]
Closing in favor of #4765

**Comment by hero101** [comment]
Closing in favor of #4765
