### ISSUE TITLE
Community Settings refresh

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4179]
## Description

As an admin I want a clear admin interface for how to manage my community. Including managing invitations and applications as well as the roles of members of the community. 

## Acceptance criteria
Community settings to include
- [ ] Pending applications on top
- [ ] Roles of members visible and adjustable. Clicking on edit icon opens dialog 
- [x] Adjusted columns for Membership of users and organizations 
- [ ] Only show the Add button if the user has the COMMUNITY_ADD_MEMBER privilege (which will be only assigned to global admins)

## Additional Context

https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp?node-id=3:2&locale=en&type=design

**Comment by Comoque1** [comment]
@SimoneZaza, @techsmyth, the implementation is applied on Space level only. As it is not specified in the AC, I need you confirmation, that it is not expected to be available on Challenge / Opportunity level as well.

**Comment by Comoque1** [comment]
@ccanos, could you please add the space name at the end of the first message?
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6e8ad692-d909-446a-b4e6-eaae6d962c42)

**Comment by techsmyth** [comment]
@Comoque1 yes understood that it is only there for space level at the moment, will discuss with SImone / Denise...this can then be closed.
