### ISSUE TITLE
Display nameID, host + visibility on Space admin settings read only

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4181]
## Description
As a space admin I want to see what settings are controlled by the platform + where I can get support to change them

## Acceptance criteria

- [ ] Display the host, visibility + url for the Space in read only fashion with information on how to get them changed
- [ ] Updated settings page to move visuals and references in separate blocks
- [ ] Two save buttons (one for About, one for References)

## Additional Context
https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?type=design&node-id=170%3A14&t=mS9mYMsbe5QCIMba-1

**Comment by larssondenise** [comment]
Difficulties: splitting save buttons, retrieve fixed information + avatars

**Comment by techsmyth** [comment]
@larssondenise seems that two things now got mixed into this one...

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise putting this back to new issues + product discussion as I think that many of these fields actually may want to be displayed on the settings tab, which might be a much easier update. Then the profile tab simply has removals (of host, nameID).

**Comment by Comoque1** [comment]
Both "Save" buttons trigger the same request:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2U1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0240f2f199caf19e10059e3d57552c50d6bbb805/image.png)

**Comment by techsmyth** [comment]
@me-andre @Comoque1 I think this is fine that the buttons both save the same thing. Lets close this item and @SimoneZaza please take an action to look at what we do with having 2 save buttons.
