### ISSUE TITLE
Hide empty challenges block

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4189]
## Description

As an Alkemio user I want optimal signal:noise ration on my pages.

## Acceptance criteria

- [ ] `Challenges` block hidden when there are 0 `Challenges` in a `Space`

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
We took away the entire block on the Space Dashboard page, and on the Challenges page it is also not shown when there are no Challenges, so I'm closing this issue :)
