### ISSUE TITLE
Improvements contribute page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4199]
## Description

As a user I want an intuitive design for the contribute page that triggers me to contribute

## Acceptance criteria

- [x] List of collaboration tools to show the state, via a lightweight query (so not all data)
- [x] "Add collaboration tool" button to be shown above all the collaboration tools instead of at the bottom

About box: 
- [x] About box: to show the CARD visual coming from the profile on the InnovationFlow
- [x] To show the description of the InnovationFlow, truncated

## Additional Context
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/830a471f-e2a3-4c48-98a0-d108a97ebc9c)

**Comment by ccanos** [comment]
The About box is already implemented in #4200 https://github.com/alkem-io/client-web/pull/4381/
