### ISSUE TITLE
Community search to include tags

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4201]
## Description

As a user I want to see users in my community that have certain tags

## Acceptance criteria

- [ ] Client side filtering that is used on community page (inside a Space) to include also user / org profile tags in the searching / filtering.

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
@techsmyth, is it expected the users / orgs that are displayed to be only members/ leads of the space community or, it should be able to return all of them?

**Comment by techsmyth** [comment]
@Comoque1 yes it should be searching only within the space community. Important is that this is a client side search - so looking through only the community for this space.
