### ISSUE TITLE
BUG: Space community page, doesn't use the 'COMMUNITY_ADD_MEMBER' privilege to determine whether to show the Add button

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4203]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/doc-hub/community
2. Use hub member - the requests to get community data, don't query the user privileges, hence show the "ADD" button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/449d9705-9e02-4848-8a43-673a7af5b863)

**Expected behavior**
Users with no 'COMMUNITY_ADD_MEMBER privilege ', should not see add button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e68c7f1b-96bc-4c57-963c-d23596d78d0d)

**Comment by techsmyth** [comment]
@Comoque1 I just tested this, and the button is not shown if the user does not have the privilege. Closing it. Raised anothrer issue #4490 to update who is assigned the privilege.
