### ISSUE TITLE
BUG: Community search not working properly (UWV)

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4222]
**Describe the bug**
The search on the community pages seems to not show single results 

**To Reproduce**

1. Go to 'https://alkem.io/uwv/community'
2. Search for names where there should be 2 results and a search where there should be 1 result
3. In the case of two results, they are directly shown. In the case of one result not.

**Expected behavior**
Results always to be visible directly

**Screenshots**
When there is more than one search result, the results are shown
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/62f7cd11-c443-411d-a404-3b2b3c8c0b1a)
When there is only one result, it is not shown
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/acaf52e8-2c60-45ca-a5e8-49ddf83a345b)
Only when clicking on expand or show all, it shows the result
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/9de1b4c2-4f3b-42da-88fd-c50db26b5692)

**Comment by techsmyth** [comment]
Duplicate
