### ISSUE TITLE
BUG: unable to login from chrome on mobile

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4223]
**Describe the bug**
Fintan is unable to login to Alkemio from chrome on mobile:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d7bda378-0d80-4abe-b6b2-cf182ee89b73)

It is working to use Microsoft logon for him on Safari

**Expected behavior**
Login should work

Note: potentially a cookie issue?

Aside: I (neil) also had logon issues recently with Brave, which went away with the release yesterday.

**Comment by techsmyth** [comment]
@Fintokyo @valentinyanakiev reported by an external user who was logging into alkemio from a google meet setup. Worthwhile seeing what cookies Fintan has set in his mobile browser.

**Comment by Fintokyo** [comment]
Hi @valentinyanakiev, happy to chat through this when you have time

**Comment by valentinyanakiev** [comment]
@techsmyth chatted through with @Fintokyo - cookies were fine and the flow was respectively fine now. I guess either the cookie expired or the secret change wiped it out if it was from before that. Closing the bug.
