### ISSUE TITLE
Platform templates visible when no Space templates

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4227]
## Description
As a  user I want to directly be triggered with visual content when I open the innovation library

## Acceptance criteria
- [ ] Discuss how to show content quicker. Show platform templates if there are no Space templates? or a few?

## Additional Context
Came from the working sessions with UWV
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/c16cf9dd-2373-43d9-ba80-4317a70b9777)

**Comment by SimoneZaza** [comment]
duplicate #4558
