### ISSUE TITLE
Callouts in Context for Challenge/Opportunity

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4247]
## Description

Callouts in context have been added on the Space level but should also be possible in the Challenges and Opportunities

## Acceptance criteria

- [ ] Callouts in Context for Challenges: Dashboard (Recommendations, left, right), Contribute Tab (left, right), Opportunity tab (left, right)
- [ ] Callouts in Context for Opportunities: Dashboard (Recommendations, left, right), Contribute Tab (left, right), 
- [ ] Edit / create dialogs to be updated by enabling or changing the callout group `canChangeCalloutGroup`
- [ ] Buttons added for callouts in context

Migration for opportunities:
- [ ] Location of the (default) callouts

## Additional Context
To be checked that created callouts are using right position

**Comment by Comoque1** [comment]
the size is 13 because of migration, client, testing
