### ISSUE TITLE
BUG: Links in emails do not work

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4250]
**Describe the bug**
Emails that I get about new callouts, have incorrect links and lead to error pages

**To Reproduce**

1. Click on the link of any new published callout that you get in email
2. It shows identity.alkem.io/.... 

**Expected behavior**

**Screenshots**
![msedge_gfoHDq0D8i.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/e12558f0-92c1-4860-8d69-f1927bcaff24)
![msedge_D31bJOlOKL.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b139cf0c-8ad0-4c28-838e-c801657fecfd)

**Comment by techsmyth** [comment]
@larssondenise @larssondenise actually there is also a deeper issue: the notifications in principle need to be aware of the innovation hub from which the originating action was triggered. Should be doable (server knows which innovation hub for every request) - but needs work.

**Comment by techsmyth** [comment]
This is a pure config issue from infra-ops as far as I can tell. Notifications.yml file uses this field:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b535bb09-63b9-451e-b599-0b7d7c32e9eb)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1950d7c8-0c7e-4747-8820-ab27f295b254)

It is picking up the following env var:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/8a9cec52-3d7d-4ed9-bd51-e70d5dd167ba)
