### ISSUE TITLE
Helper text to be shown on all reference input fields

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4253]
## Description
As Alkemio team I want to make sure everyone is aware of the fact that there are rules for uploading a document

## Acceptance criteria

- [ ] Explainer for text for uploading to be visible on all places where we upload images/files:
- [x] References in a profile (user, innovation pack, space, challenge, opportunity, ..?) (already there?)
- [x] Callout: post, call for posts, call for whiteboards, single whiteboard (already there?)
- [ ] **Collection of links callout**
- [ ] little restyle to align & visually group the related input fields:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/911a2dbf-208a-4f3c-b470-7fec4ee113f6)

## Additional Context
Carlos came across this when doing removing the dialog for uploading confirmation

**Comment by Comoque1** [comment]
There is a minor regression from tags refactoring on organization settings: https://dev.alkem.io/admin/organizations/org-canvases957332/profile

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVpKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e44a1d37a2a8661275d42f7811766c8c374eda07/image.png)
