### ISSUE TITLE
BUG: not able to update global admin roles in community

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4261]
**Describe the bug**
On a local environment, a global admin cannot assign himself roles in a community: 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3bfd4c6c-b14e-4746-8cfc-b027b9a566cd)

**To Reproduce**

1. login to a community as global admin
2. add yourself as a member
3. try  to assign additional roles to yourself, the client does not allow it...

**Expected behavior**
If a user has grant rights on the community then they should be able to update the roles

**Comment by Comoque1** [comment]
This one is fixed on Space level. On Challenge / Opportunity, user still cannot remove himself as admin from the them.

**Comment by Comoque1** [comment]
And the above comment is resolved. Now admin, can add/remove / assign Admin / Lead privileges on all Journeys.
