### ISSUE TITLE
Set headers and footers of dialogs to be fixed so close and save buttons are always visible

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4266]
## Description

As a user I want to see what dialog I'm in, also when I've scrolled down a bit, left my computer for a while, and then come back. Also, I want to be able to close it at any time and last but not least, I want to see the save/other action button at any time, so that I'm aware of the need of pressing this button before I close the dialog.

## Acceptance criteria

- [ ] Headers to be fixed  when scrolling (title, close button)
- [ ] Footers with action buttons to be fixed to the bottom of the dialog, the content to scroll between header and footer
- [ ] We need to use a new component (dialogWithGrid) that allows to specify the width in columns (10col for callout create/edit)
- [ ] All dialog content should be put in a component named DialogContent

## Additional Context

Overview of dialogs in the Spaces, Challenges and Opportunities with adjustments in brackets
Perhaps a discussion needed if a footer needs to be implemented in every dialog to improve the viewing experience.

**Space: Dashboard**
- About this Space (Header needs to be adjusted to H3)
- Events
- Recommended by host

**Space: Community**
- Who's involved
- Contact the host(s) (Header needs to be adjusted to H3)
- Posts, whiteboards, collection of links etc.

**Space: Challenges**
- More Challenges

**Space: Knowledge Base**
- Posts, whiteboards, collection of links etc.

**Challenge: Dashboard**
- Recommended by host
- Share Challenge (Header needs to be adjusted to H3)
- Contact the lead(s) (Header needs to be adjusted to H3)

**Challenge: Contribute**
- Add/create callout
- Posts, whiteboards, collection of links etc.

**Challenge: About**
- Innovation flow (Header needs to be adjusted to H3)
- Context (Header needs to be adjusted to H3)

**Opportunity: Dashboard**
- Recommended by host
- Share Opportunity (Header needs to be adjusted to H3)
- Contact the Lead(s) (Header needs to be adjusted to H3)

**Opportunity: Contribute**
- Add/Create Callout
- Posts, whiteboards, collection of links etc.

**Opportunity: About**
- Context (Header needs to be adjusted to H3)

**Comment by larssondenise** [comment]
Giving priority as users lose work because they missed the publish/create button. Also because they are not prompted with 'are you sure you want to close, because you have content in there'. This is raised as a separate issue

**Comment by Comoque1** [comment]
- [ ] Add link to collection of links dialog, doesn't have "Add another link" button and footer links fixed
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekF5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2288634e8ca6f7ee05717920e893a7f400dd6f73/image.png" alt="image.png" />
<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekl5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d93c1b9a5aab8fd85826746509a2bbe4b6434e5/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@me-andre I've added my findings in the above comment.
@SimoneZaza , could you please review and share your thoughts if we address as part of this one or, raise separate issues?

**Comment by Comoque1** [comment]
`Publish Callout` dialog has the header `H2` and footer is not fixed
<img width="1158" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEU1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4791625926c951240b18648a97733e9f0f12ec9a/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
`Create new Callout template` header is not `H3`
<img width="1985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUU1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55a759554eca397f991fe9e6acf72728b1a29e30/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Expanded view of `Collections` callouts (Post and Whiteboard) when have longer description and user scrolls to bottom, header is invisible
<img width="1029" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK001QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf92927608fcdec2177816a612942de2040bd555/image.png" alt="image.png" />

<img width="1018" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1E1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93a57e70c3656f8c74ff44fec1f7faab8da67ac5/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Expanded opportunity context vies have  the header in `H2`
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0E1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e18e386722eaced955192c0f7621933eb21ce4c/image.png" alt="image.png" />
