### ISSUE TITLE
Info blocks on knowledge base, subspaces, dashboard to be editable from the block itself

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4268]
## Description

As a space admin I want to change this default text that appears on the top left of my Subspaces page and my Knowledge base
As a space admin I want the block on the dashboard to not hold the same text as in my future vision

## Acceptance criteria

- [x] Edit in context? Edit icon on the block?
- [x] Default text for these blocks 
- [x] Dashboard description to be decoupled from the future vision context field

Designs:  https://www.figma.com/design/IOJdWGF5Bxmh69NUWl2Ws4/Info-Blocks-to-be-Editable?node-id=0-1&t=ORs7SPfXjc3aQloj-1 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by jeroentskui** [comment]
![Image](https://github.com/alkem-io/client-web/assets/26659857/314338ae-2ff1-400b-ba6b-703dbcd9ee17)

**Comment by jeroentskui** [comment]
emualte the screenshot above for the ui element for adjusting the text
