### ISSUE TITLE
BUG: Subscribed users don't get reactions visible

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4283]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/doc-hub/collaboration/000-3070/posts/333-8723/dashboard
2. Authenticate with 2 users on different browser
3. User make a reaction
4. User 2 subscription returns the reaction, but the client doesn't display it
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/84fd5ca1-1c37-475c-b97b-8e02ba536dd9)

**Expected behavior**
Reactions are visible on the client.

**Comment by hero101** [comment]
This hasn't been implemented. Will be implemented with https://github.com/alkem-io/client-web/issues/4251

**Comment by Comoque1** [comment]
With latest changes on ACC env, the reactions are visible using subscriptions.
Closing this one.
