### ISSUE TITLE
All text in activity to be translatable

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4291]
## Description

As a product champion, it is very hard to get the activity text correct given there are three distinct sections to it. 
As a user, I want that the activity entries are fully translated to my language and read well in that language

## Acceptance criteria

- [ ] Single translation string for each type of activity, covering all three sections

Note an activity events can have potentially different phrasing and hence order in different languages. 

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b31f0b84-717d-4601-b39e-393cb2a23d24)

There are three sections currently:
- time (which also needs to be translated) + user
- core text about the event
- the sub-entity that it happened in (if any)

Ideally we can get to a single string that has something like: 
"{eventElapsedTime} - {displayName} commented on {postDisplayName} {childEntityIcon} {childEntityDisplayName"

**Comment by Comoque1** [comment]
The implementation, seems fine, but the actual behavior on the client, is that for some activities on different  languages, the time and user are missing. After a discussion with @ccanos, he identified, that when we remove the existing translations for activity logs, the issue will be resolved and we'll have a fallback to English.

Raised for new translations to be added for activity logs: Create new activity log translation #4368
