### ISSUE TITLE
Demo label to be not shown on challenges when space has demo label shown

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4292]
## Description

As a sales person I want to be able to give compelling demonstrations

## Acceptance criteria

- [ ] Demo label removed from challenge + opportunity cards when inside a space

Note: label still shown when doing global search / challenges page / profile pages et.

Feedback is that it distorts the platform visuals too heavily.

**Comment by valentinyanakiev** [comment]
@ccanos this is working fine, it was just not deployed on dev due to the build failing...
