### ISSUE TITLE
Refactor of the Callout expanding mechanism because it causes double subscriptions for certain Callout types:

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#4309]
## Description
As an Alkemio developer I want a performant and well organized code.

Analyzing this bug #4303, we detected that the subscription to RoomEvents `useSubscribeOnRoomEvents` is being called twice when opening a callout dialog:
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/1f3018e5-90cc-4367-b6c9-636da399c322)

We have two subscriptions to the same roomId, one from the page, and another from the dialog.
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/b0c85f91-67f6-4b2f-89eb-f6726ac6d5ec)

That was causing message duplication on the chat window, not on the server, once the page was refreshed the duplicates were gone.
It has been patched in https://github.com/alkem-io/client-web/pull/4308 but it's not a full fix.  With this PR we are only checking if the message is already in the list of cached messages, (also happens with reactions). 
But a proper fix would need a refactor to avoid resubscription, or to avoid subscribing from callouts open in a dialog, or any other alternative.

Callout dialog is shown from `domain/collaboration/CalloutPage/CalloutPage.tsx`, and the subscription to the comments callout is on `collaboration/callout/comments/CommentsCallout.tsx`.

Further investigation is required and see if it's worth it a refactor, for now we have a hacky patch for the messages, but this is also happening with Posts:
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/a8fb789b-f1a8-42ce-ad0a-be7d3a68c907)

## Acceptance criteria

- [ ] Investigate the issue and take a decision about the problem - maybe this Issue should be a spike...

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
From what I see, the subscription is not duplicated. It is open for a specific room, when a callout or post card is open and the subscription is closed wihen the dialog is closed.
The could also be seen in the screenshot of the description.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVlaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5a0cbd55edab17eb3a0792b76590ae7046b33d57/image.png)
