### ISSUE TITLE
Use ClassificationTagset for callout location on Space

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4317]
## Description

As a developer I want a clear way to manage the display location

## Acceptance criteria

- [x] Remove "group" field on Callout entity, mapping the specified value into the displayLocation tagset
- [x] Update logic on client to specify the updating of that tagset directly
- [ ] Remove enum on client CalloutsGroup (pick up server enum)
- [x] Use updated callouts field query

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
When user open callout settings, the location always shows "knowledge", instead of current location:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0c8a81a5-d36a-4057-a15a-5511c9532c4e)
