### ISSUE TITLE
404-page

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4319]
## Description
As a UX lead, I don't want users to be able to see a fake private Hub when they type in a random name

## Acceptance criteria

- [ ] New 404 page, see figma file
- [ ] Search bar that shows results on general search page
- [ ] Client to log an error to sentry / apm whenever this page is shown: link that was used 
- [ ] Mobile version as well!

## Additional Context
Link to Figma file: https://www.figma.com/file/b9MAR2Qj3EijJ0Hd00T59p/Page-not-found?type=design&node-id=0%3A1&mode=design&t=Wp4uZq6GO6p8bjIA-1

## Design
![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/c6b7cceb-f533-404b-a792-949e624136d6)

**Comment by Comoque1** [comment]
The design is implemented, but there are routes that could lead to page crash or invalid visualization.
A [card](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4923) is raised and will be addressed as part of it.
