### ISSUE TITLE
BUG: client deployment script has suffix added

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4321]
**Describe the bug**
Images have an extra suffix

**To Reproduce**
Look at client images from recent builds

**Expected behavior**
Client images are generated without the extra sufix

**Comment by hero101** [comment]
What is this connected with? Can you provide more details and a screenshot or a link?
The images in the docker registry seem fine.

**Comment by techsmyth** [comment]
@hero101 this was one I raised in discussion with @valentinyanakiev - I do not know the details...

**Comment by hero101** [comment]
@valentinyanakiev

**Comment by valentinyanakiev** [comment]
This is outdated and was fixed. Closing.
