### ISSUE TITLE
Remove redundant code 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4346]
## Description

As a developer I want a clean code base

## Acceptance criteria

- [ ] Analyse the code base (using e.g. ts-prune) to identify constants / classes / graphql entries that are not used
- [ ] Remove code / constants identified

Timebox to half a day?

## Additional Context

One option for doing this:
ts-prune --project tsconfig.json | grep -v '(used in module)'

**Comment by ccanos** [comment]
https://hackmd.io/_73Ez9jJRDmp_VG_oUsedA

**Comment by techsmyth** [comment]
Updating estimate as added a day
