### ISSUE TITLE
Journey dashboard refinement Space/Challenge/Opportunity

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4347]
## Description

As a user I want to immediately see custom content/callouts, as an admin I want the locations to make sense (left-right, not "recommendations")

## Acceptance criteria: **Space/Challenge/Opportunity**

- [ ] Remove "Dashboard-recommendations" location for callouts
- [ ] Move the callout currently under "dashboard-recommendations" to be"dashboard-right" sorted to come first 
- [ ] Move recent contributions to be a small block at the old location of the recommendations, showing 3 most recent contributions, truncated, taking into account #4004. Switch in this block switches to 'top callouts' (label not visible), showing the 3 most active callouts.
- [ ] Add dialog to recent contributions/most active block, showing the last 25(? Up to discussion) events
- [ ] Delete Challenges block
- [ ] Move references block to about dialog
- [ ] When there is no leading organization, don't show block / or button to contact the lead
- [ ] Welcome block to be as in #4192

And this means that we should also
- [ ] Remove Dashboard - Recommendations location for callouts in context
- [ ] Standard callout Recommendations should 'move' to Dashboard - right first place

Activity entries
- [ ] Display text to be adjusted to work in both short + long display form (product team to do this)

## Additional Context
https://www.figma.com/file/7DA9iP2BGpDDDsHCTzSSqg/Dashboard?type=design&node-id=501%3A60&mode=design&t=rfkLyutaOIcEXXlS-1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkt3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d9dfc81d42b34ecb69a5279667e0e0b70b9c7b5/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdit3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd2735da308479cee92db213665873de8ae8131c/image.png)

**Comment by Comoque1** [comment]
@SimoneZaza, could you please provide a design for Activity logs when resized in smaller block?

**Comment by MarinaAlkemio** [comment]
VeloKonzept requested this change as well, together with making a post that can have comments
