### ISSUE TITLE
BUG: references button not working when post not yet saved

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4349]
**Describe the bug**
When you add a reference to a callout that's not yet created, it breaks. So, it would be great if this references button is muted and when you hover over it or click it, a helper text states "To add references, you'll have to save this post first"

**To Reproduce**

**Expected behavior**
 this references button is muted and when you hover over it or click it, a helper text states "To add references, you'll have to save this post first"

**Comment by Comoque1** [comment]
The issue is not reproducible anymore.
