### ISSUE TITLE
BUG: Newly created post using "Publish" appear as DRAFT on the UI

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#4360]
**Describe the bug**

**To Reproduce**

1. Create a Post of any kind using the Publish button
2. The Post appears as DRAFT, but was published. This does not happen constantly but it's easily reproducible after a few tries.

**Expected behavior**
The Post appears published after being created with the Publish button every time.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/f1089159-5129-44dc-9d78-3afc59ec4204)

**Additional context**
The correct mutation for publishing the post is executed but the state does not appear to be refreshed consistently.

**Comment by Comoque1** [comment]
Looks like, not all changes are pushed to ACC env, as cannot create callout.
On DEV env, I can.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2MzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--662417aed8cb362d75195cba3a63b18aa293d222/image.png)
