### ISSUE TITLE
BUG: Callouts are not displayed on Challenge / Opportunity contribute tabs

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4373]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/release-11-07-2023-hub/challenges/release-11-07-2023-h-5291/opportunities/release-11-07-2023-o-4862/contribute - no callouts are displayed.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d5dd2669-c773-40e9-b906-b71072c26488)

**Expected behavior**
All related callouts are displayed.

**Comment by hero101** [comment]
Is this still a high priority and is the issue still valid?

**Comment by Comoque1** [comment]
This is not an issue. It is missing functionality, which is going to be addressed in the starting sprint.
