### ISSUE TITLE
Remove pending applications from profile

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4376]
## Description

Since one can now see their pending applications in the pending memberships dialog, there is no need for the block on the user profile anymore. Moreover, it might not be nice that others can see what journeys you've applied to but were not yet let into.

## Acceptance criteria

- [ ] Remove block with pending applications from user profile
- [ ] Also change email notification /workspaces/notifications/service/src/templates/community.user.application.applicant.js (see below).
This should be "Once your application is accepted, you will find this {{journey.type}} on your <a href="{{applicant.profile}}">profile</a> and homepage. As long as your application is pending, you can find it under "Pending Memberships" in your platform menu."

        {% block content %}Hi {{applicant.name}},<br><br>
          We have received your application for the {{journey.type}} <a style="color:#065F6B; text-decoration: none;" href="{{journey.url}}">{{journey.displayName}}</a>.

          Please view the status of your application on your <a href="{{applicant.profile}}">profile</a>.
        <br><br>
        {% endblock %}

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@SimoneZaza can you please clarify the second acceptance criteria?

**Comment by SimoneZaza** [comment]
@techsmyth done, but it isn't very nice... maybe wait until we do the homepage refresh and then include it in there? Or just remove the entire sentence?

**Comment by techsmyth** [comment]
@SimoneZaza lets keep it in for now, good to at least have the guidance. It may be a bit before we have the notifications properly in the new home page...

**Comment by alstojanovic** [comment]
@techsmyth just to make clear. We 1) remove the applications section from user profile and 2) update the second sentence in the email template with suggested text?

**Comment by techsmyth** [comment]
@alstojanovic yes! Unless you see a problem with it? The applications should not really be part of the main user profile, ideally there is somewhere an invitations / applications option in your profile settings - but not here.
