### ISSUE TITLE
BUG: Unable to change my own member rights in a space

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4391]
**Describe the bug**
Why can't I make myself a lead? 

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b4652610-08f6-42d8-8b0c-1a314ce5317e)

**To Reproduce**

**Expected behavior**
To also be able to edit your own rights.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techsmyth** [comment]
Addressed in the me Query PR
