### ISSUE TITLE
BUG: Header Banner  is not as per design for mobile

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4409]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/challengecentric/challenges/testingexperiment-4911/dashboard from a mobile
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0f4bc3b6-9997-4da4-8392-6fe4536d6932)

**Expected behavior**
Header Banner  be as per [design](https://www.figma.com/file/BZR4ozFba6KLI0RvfBstDV/Challenges-refresh?type=design&node-id=218-8872&mode=design) for mobile

**Comment by Comoque1** [comment]
This is still not implemented.

**Comment by ccanos** [comment]
I was going to take this one, but I think it's looking good now in develop @Comoque1

**Comment by Comoque1** [comment]
You are right, @ccanos. This one is correct.
