### ISSUE TITLE
BUG: Challenge/Opportunity banners issues

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4413]
**Describe the bug**
The lovely new banners for Challenges and Opportunities still can use a little bit of refinement:
 
- [ ] Opportunity to also have the Space reference on top, with both the Challenge and the Space being clickable
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/acb04f8f-2f64-49fd-a513-55d120453ab3)

- [ ] Banner to align to the left side of the content, not stick to the left side of the screen **(no priority, can be split into a new issue that we'll pick up later)**

**Comment by Comoque1** [comment]
This is already addressed. To be released.
