### ISSUE TITLE
No tags available on post: don't show on card

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4415]
## Description

As a user, I want to read as much as possible directly from the card of a post. Currently, when there are no tags available this still takes quite some space which I would prefer to be used to let me see more from the description

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/b54a1cab-ece0-4849-a73b-bc56cc9adcfb)

## Acceptance criteria

- [ ] When there are no tags available, use this area for a longer description
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
@SimoneZaza, is it expected the same behavior for the cards on search results? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWxEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--115a8d2778e8ca4d921d00aeea84750b3a2bd400/image.png)

**Comment by SimoneZaza** [comment]
Yes that would be very nice, I'm sorry that it wasn't specified..
