### ISSUE TITLE
BUG: Client using Lead org on space for the host

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4421]
**Describe the bug**
The lead org is being used for the host org information on the client. And only one lead org is allowed. 

**To Reproduce**

1. Go to https://alkem.io/tip
2. Click on the about this space button. 

The lead org is TIP, the host org is Digicampus. 

**Expected behavior**
The client should display the host as the host, and the lead as the lead. 
The client should allow for two lead orgs on the Space.

## Additional information
Please also switch to getting the orgs based on role using the field "organizationsInRole" field rather than "leadOrgs", that should be removed. 
Also in terms of the limits to enforce re number of allowed lead orgs / users etc, consider getting that directly from the community policy.

**Comment by techsmyth** [comment]
Putting this as high priority as this bug effectively blocks any value from the work done on this whole epic.

**Comment by valentinyanakiev** [comment]
@techsmyth we have verified and re-verified with Evgeni. The behavior is as expected and the data returned is exactly the data with the credentials **('SPACE_HOST')**. Digicampus has TIP selected as HOST org in the community settings. If this selection is incorrect, Digicampus / Ops team should pick the right setting.

**Comment by techsmyth** [comment]
@valentinyanakiev the flow I did was to change the LEAD organization on the community settings page to be TIP. Which seems then to have updated the HOST organization. The end state I must be able to reach is that TIP is the lead org and digicampus is the host. 

Note that the Host org should also not be updatable via the community settings, only the settings mutation for the host / visibility. In my using it the Host org somehow got updated via the community settings...

Maybe I did something odd, so please check what happens when you try to change the lead via the org settings tab....
