### ISSUE TITLE
BUG: unable to assign challenge admin

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4445]
**Describe the bug**
In trying to assign Senna as challenge admin it looks like the wrong community id is being sent

https://alkem.io/admin/spaces/building-alkemio-platform/challenges/understandingusage-6722/authorization

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2598fdd5-8365-4743-9351-f3c996c5c92b)

**To Reproduce**

1. Go to above admin link and try to add senna

**Expected behavior**
The user should be added as challenge admin

**Additional context**
The mutation is currently passing in teh challenge ID:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3a4b55cb-d181-4e2c-bc4f-224a6c602189)

**Comment by Comoque1** [comment]
From the client, incorrectid is provided for community.
Aleks is picking it up.
