### ISSUE TITLE
BUG: Release notification is not triggered, when release version is updated

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4456]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/home
2. Open browser dev tools on "Application" tab
3. Open local storage
4. Change the version to 39 `{"prevClientVersion":"0.39.0"}`
5. Refresh the page - release notification must be displayed.

**Expected behavior**
Realease notification is displayed on client version update.

**Comment by ccanos** [comment]
Not sure why, but this was never implemented...
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/7b818786-f04d-484c-846f-4b339d1e2966)

It's an easy one, can be treated as a bug
