### ISSUE TITLE
Events on Challenge / Opportunity

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4459]
## Description

As a User,
I would like to be able to add events on lower-level Journeys
so that I can manage / plan / broadcast what's going on my Journey

## Acceptance criteria

- [ ] Events can be added on Challenge / Opportunity

## Additional Context

I am using the platform and wanted to build the content of a Challenge and there are crucial pieces missing.

**Comment by techsmyth** [comment]
This is done right?

**Comment by Comoque1** [comment]
Yes, quite some time ago. Closing.
