### ISSUE TITLE
BUG: List of callouts on challenge shows all callouts, on all flow states

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4467]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/review-31-07/challenges/challenge2-6988/contribute - on first state  callouts list shows 3 callouts, when there are only 2 visible
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/832aa82c-a1e6-4e9e-bf96-8bb4805abe2f)

**Expected behavior**
List of callouts correspond to displayed callouts for the particular flow state

**Comment by SimoneZaza** [comment]
@Comoque1 This is the expected behaviour I think? The list should show all, independent of the state. The state is being displayed in the list in bold. This way, a user doesn't have to click through all of the states to find a particular tool.
