### ISSUE TITLE
Placeholder: on new challenge all callouts are displayed in innovation flow dialog, including the ones from dashboard page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4468]
## Description

As a User I want to see callouts in innovation flows dialog, only, when I can move them from state to state.
The current behavior is a bit misleading, I can move callouts between the flow states, but they remain on dashboard tab and do not become visible on the state I've put them.

## Acceptance criteria

- [ ] TBD
- [ ] …

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@Comoque1 should be fixed with the callout sort order work that Carlos has done.

**Comment by Comoque1** [comment]
Now only callouts related to the innovation flow are available.
