### ISSUE TITLE
Select innovation flow :  Create dialog Ch/Opp

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4485]
## Description

As a lead, I want to directly choose the innovation flow when I create a new 

## Acceptance criteria

- [x] Create dialog to be updated as per design
- "Default Challenge/Opportunity flow" to be displayed when opening the create Ch/Opp dialog
- [x] Library dialogs to be almost the same as the dialogs used for whiteboard templates and post templates, apart from:
- Add warning text (see design)
- Mute use button for templates that are not part of the Space templates. 
- [x] On both Challenge and Opportunity

## Additional Context
Innovation flows can only be chosen if they're selected in the Space Templates. For now, we're not changing that, so the users need to be aware of this limitation.

https://www.figma.com/file/kbr6P350Xds6IKwoLtC1Vu/Challenge-%26-Opportunity-dialog-with-innovation-flow?type=design&node-id=80%3A240&mode=design&t=0ONqnRDz67aSvIMP-1

**Comment by Comoque1** [comment]
When User select different from the default flow, the default callouts are not displayed on the journey creation
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d169c0574a3f83576a5db3f25a5ac5cddbb45177/image.png)

**Comment by ccanos** [comment]
I've been able to reproduce it in localhost, and have been debugging to see why this is happening and suddenly it has stopped happening. I cannot reproduce it anymore, neither in dev.
I think there may be a race condition in here: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelYyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33109957b1e1ce0753a21ec4614164290fbd32d0/image.png)
trying to get the initial state of the lifecycle machine, but those functions look synchronous to me.

If this is still reproducible tomorrow, I will take another look.
relevant files:
src/domain/collaboration/collaboration/collaboration.service.ts:95
src/domain/challenge/innovation-flow/innovaton.flow.service.ts:302  
src/domain/common/lifecycle/lifecycle.service.ts:210

**Comment by Comoque1** [comment]
Tried, multiple times to reproduce on DEV environment, with no success.
