### ISSUE TITLE
BUG: Innovation flow dialog settings button is shown to user without privileges

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4496]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/release-03-08-23-hub-cont/challenges/release-03-08-23-cha-8670/contribute
2. Authenticate with user with access to the challenge but not admin - he sees Innovation flow dialog settings button is shown to user without privileges
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/58994415-34a1-40fe-bc27-c18db75bdcfc)

**Expected behavior**
User doesn't see the settings button.

**Comment by valentinyanakiev** [comment]
@Comoque1 raised https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4519 and the UX team is working on designs how the UX would look. The InnovationFlow Settings dialog is based on `UPDATED` privilage of `InnovationFlow`.
