### ISSUE TITLE
BUG: Only showing one lead on dashboard

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4500]
**Describe the bug**
As a community lead I want to be able to show two leads on the space dashboard. But while I can now select two, only 1 is showing up: 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c7058e35-675d-4ffd-8c38-18046aed54b1)

**To Reproduce**

1. Go to https://alkem.io/shipping-retrofits/dashboard
Only one lead is showing up

**Expected behavior**
The dashboard should show the space leads, not host, and be able to show two of them

Note: this is the third bug in this series to getting 2 leads showing up on the space.

**Comment by techsmyth** [comment]
@valentinyanakiev this was the parent epic: https://github.com/alkem-io/alkemio/issues/1012 

The acceptance criteria did not explicitly list it for the epic, and clearly the key driver had not been communicated: namely that some spaces required multiple visible orgs, and could not move ahead without it.

**Comment by valentinyanakiev** [comment]
@techsmyth talking strictly about process and expectations on both sides:
- I don't believe developers read the epic definition when working on a story, nor that they should unless the definition of the story is very unclear / there is a reference to the epic. By the time the epic is broken down into stories, the requirements from the epic should be translated into the story and should contain all the information / AC / mockups needed to work on the story, unless explicitly stated (which should be rare and mostly for spikes)
- An arbitrary business requirement that can go either way (e.g. having a host vs leads) can't be implicit and is the product team's responsibility to clarify and state explicitly what is expected. For example, in this fix where we have changed the `Host` to `Leads` on the `Space Dashboard` - the `About` dialog has boxes for both the `Host` and the `Leads`. It is not obvious what is expected, and there isn't really an obvious `correct` implementation in my eyes. There are just `different` implementations.

Happy to discuss ways of working. Also happy to discuss AC and how we can improve on that constructively - it's been a source of frustration, misalignment, and unmet expectations product - dev, highlighted by multiple people during our last 2 retrospectives. Also, I'd like to highlight that implicit requirements not specified in the story can have knock-on effects like rendering the estimate useless.
