### ISSUE TITLE
Expand button on list of Callouts

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4513]
## Description

As a lead and user of the innovation flow, I don't want to see an endless list of callouts that hides my callouts on the left

## Acceptance criteria

- [ ] Max of 5 callouts
- [ ] more than 5, add expand button 
- [ ] when expanded, add collapse button
- [ ] Located: Challenges: contribute page; Space: knowledge base  (should be the same)

## Additional Context

![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/893cfce8-42ac-4596-ad78-a4dd6bdb02f2)
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/e3458903-6d79-473d-a295-eee71cd45437)

**Comment by alstojanovic** [comment]
@SimoneZaza Do we have this expand feature somewhere on the app? Any figma link on how it should look?
