### ISSUE TITLE
Closed collaboration tool of type Post without comments: Don't show closed message

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4552]
## Description

As an admin sharing a post callout that is not meant to get comments, I don't want to see the "This Post is closed"-message. 

## Acceptance criteria

- [ ] When a post callout is closed, check if there are already comments. If so, use the current design. If not, do not show a message stating that you cannot respond, nor the message that the callout is closed. .

## Additional Context
Also requested by VK

**Comment by SimoneZaza** [comment]
@Comoque1 I think this is still the case? <img width="601" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e93338a3db7619a5753f2be881b264fb16b3692a/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@SimoneZaza you are correct, there is another story raised with respect with the different cases: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4895
