### ISSUE TITLE
Handling of replies on deleted comments

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4556]
## Description

As a user I want a clean interaction around messages

## Acceptance criteria

- [ ] Instead of the original message, show a placeholder: _This message has been deleted_ 
- [ ] The message text is translatable
- [ ] Show a grey block instead of the avatar
- [ ] Show all the comments below them as usual

## Design
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnhIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1ccd8fe07b541c17b456704aba6f6dc64251ad91/image.png)

**Comment by hero101** [comment]
From Teams Development channel:
> There is an outstanding issue with the replies when a thread message (the first message in a thread) is deleted. The replies are still in the room but are not displayed and the counter in the client is showing all the messages in the room - displayed or not. I believe we should handle this by displaying a deleted message placeholder to preserve the context of the reply messages. This may require the product's standpoint, but usually, that is the way most messaging clients are handling that situation.

**Comment by alstojanovic** [comment]
Element solves both replies and replies in a thread the same way. When the parent message is deleted they do not delete any other messages and on every place where the deleted message is referenced they put a placeholder [message deleted].

![image](https://github.com/alkem-io/client-web/assets/23555519/84176b99-a7c9-4b58-8691-857a2f473c58)

Teams deals with it similar, for conversations it puts a placeholder for the deleted parent message and it doesn't remove replies. For normal replies it doesn't even remove the deleted message, it removes it only at the original place in the conversation where it was added.
![image](https://github.com/alkem-io/client-web/assets/23555519/b944f0a1-11bd-42bc-a4f2-75411242433a)


![image](https://github.com/alkem-io/client-web/assets/23555519/15c76951-cb8a-49f8-b14c-ca0c121cc351)

**Comment by SimoneZaza** [comment]
Yes, I agree this is how we should do it too. Same text, same formatting:

_This message has been deleted_

**Comment by hero101** [comment]
I suggest something like that. Depending on the information available about the deleted message the design can vary.

![image](https://github.com/alkem-io/client-web/assets/7901834/95a26192-acba-4297-84ff-e1db1d481eca)

**Comment by techsmyth** [comment]
Good point Andrew, can you please raise that as a separate issue. It will not be in time for this issue, but I agree that we need to do this...

**Comment by alstojanovic** [comment]
https://spec.matrix.org/v1.8/client-server-api/#redactions
We can utilise redaction events but I am not sure if we need to adjust our message interface to be able to convert these events to messages.
Do we then continue with the agreed client fix?
