### ISSUE TITLE
Fast loading of my spaces

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4557]
## Description

As a user I want my spaces to be loaded fast

## Acceptance criteria

- [ ] separate query to load my spaces on the home page based on the results a query to the "me" api: mySpaceMemberships
- [ ] show the user spaces before loading the rest of rolesUser query or the all spaces query

## Additional Context
Update spaceMemberships in UserMetadata to pick up this data

**Comment by valentinyanakiev** [comment]
@techsmyth please benchmark before / after. It would be interesting to see the comparison.

**Comment by techsmyth** [comment]
@valentinyanakiev just did a local test with a stopwatch on the phone: 8.2, 6.0 + 7.1 seconds for three page reloads. Lets see what it is like after...

**Comment by techsmyth** [comment]
@valentinyanakiev already a bit faster with this release: 5.8, 6.2, 6.0 - lets see what this one brings when it gets to production. but noticeably better - even if more to go....

**Comment by Comoque1** [comment]
On dev env, using the query, that is currently being used on ACC and the new on DEV, I have the following results: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnNmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d72455110e9dad3cf534e6653cbb417383d98584/image.png)

I will keep the story until deployed on ACC as, overther there have an account wiith big membership:
ACC: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1FmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--71421bbfe33ae8ff42649dd677ca05488d20abfc/image.png)

**Comment by Comoque1** [comment]
After deploying the change and refreshing the home page, the results are as follows:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjhtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e34f8587318a3a21679d0bfbe231494cc8c75247/image.png)
