### ISSUE TITLE
Load innovation library templates when no space templates available

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4558]
## Description

As a user, I want to see templates when I open the library in a whiteboard. If there are selected templates for the Space, these should get more weight, but that is already happening  by putting them separate from the rest, on top of the page. When there are no Space templates, the page now feels very empty. I think we should then immediately load global templates. TBD whether  or not to do the same when there are space templates.

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/44bdc871-202e-4143-bffd-341537cdc5d5)

## Acceptance criteria

- [x] When Space templates section is empty, directly open Platform templates
+ make it look nice :)
- [x] "No templates found in this Space, find further platform templates below" in caption font instead of body
- [ ] Correctly looking spacing on top and below
- [ ] Maybe separator?

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Tested on DEV env.
On web looks the dialog looks nice:
<img width="1189" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXF5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69af4dd6d6693b606f858488324f1fcbc49d2d5b/image.png" alt="image.png" />

On Mobile is another case. @SimoneZaza do we have some expectations for it?
<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJ5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9772d237454baadfedc4d721a372fb309adb53c4/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
In addition, "callout template" on space is not showing text fully
<img width="1047" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3F5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a439e7951d534b5bef1bb91d3ee04976ff319fcb/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
All comments are addresed.

**Comment by SimoneZaza** [comment]
@Comoque1 I've raised a new issue on reducing content in the header of dialogs and blocks/making this more responsive. We'll work with the product team on a visual strategy because these kind of things are happening everywhere on the platform...
