### ISSUE TITLE
Organization profile pages to show orgs in lead roles

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4583]
## Description

As an organization representative I want my contributions to be visible

## Acceptance criteria

- [ ] Lead roles to also be shown on the org profile page

## Additional Context
Look at the shipping retrofits page: https://alkem.io/shipping-retrofits/dashboard

And then click on the Vanesti Vetnures logo, the shipping retrofits contribution is not visible

**Comment by Comoque1** [comment]
With this implementation if the user is not member of a space, but lead of a challenge, the contribution is not displayed.

**Comment by techsmyth** [comment]
@Comoque1 this should not touch anything related to user contributions - it is only affecting the organization contribution page...can you please double check?

**Comment by techsmyth** [comment]
Raised case still outstanding in https://github.com/alkem-io/client-web/issues/4686
