### ISSUE TITLE
BUG: !! Can't access comments on a card

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4587]
**Describe the bug**
Sorry, no time to properly describe this at this moment, but me and Marina can't see all the comments on the 'building the agenda' card (which has 10 entries) in a callout in the offsite challenge, we only see the last comment and can't scroll up

https://alkem.io/building-alkemio-org/challenges/teamoffsiteseptemb-9083/contribute

https://alkem.io/building-alkemio-org/challenges/teamoffsiteseptemb-9083/collaboration/post-collection-default/posts/buildingtheagenda-4729

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3dlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--23280ca0a229fb2b06216ba2785c671ca1eb37b7/image.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
This is duplicate to https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4556. The comments are not lost, but design is needed for the the case, when main comment is deleted how to display replies.

**Comment by SimoneZaza** [comment]
Thanks @Comoque1, I've included a suggestion there and will close this one then

**Comment by SimoneZaza** [comment]
@Comoque1 we had another look with @techsmyth, the data is coming back to the client. @ccanos can you have a look?

**Comment by valentinyanakiev** [comment]
@SimoneZaza @techsmyth which data? We already knew the comments are not deleted, but the thread was. If the thread is still there that would be new to me thou...

**Comment by techsmyth** [comment]
@valentinyanakiev the data is coming back, and the thread is also there - so the client is just not displaying it from what I can see
