### ISSUE TITLE
BUG: User is presented in add member dialog, after it has been added as a member

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4588]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/spaces/vite-space/community
2. Add a user as member
3. Open 'Add member' dialog and type the name of the added user - it is displayed

**Expected behavior**
When a user is added as member, he should not be displayed in "Add member" dialog.
Te be applied for all journeys.

**Comment by alstojanovic** [comment]
@Comoque1  The filtering fix was applied also on usersPaginated and organizationPaginated queries apart from original availableMemberUsers.
