### ISSUE TITLE
BUG: Alkemio is failing to load on iOS, Chrome browser

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4591]
**Describe the bug**

**To Reproduce**

1. Go to alkem.io - the application doesn't load
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2drIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--11728515ec2bb7586add8251861d240f69ed36b8/image.png)

**Expected behavior**
Alkemio loads successfully

**Smartphone (please complete the following information):**

- Device: iPhone13
- Browser: Chrome
- Version: latest 116.0.5845.103

**Additional context**

**Comment by valentinyanakiev** [comment]
The fix is deployed on sandbox and verified on my iOS device (iPhone 13). Not reproducible with the fix.
