### ISSUE TITLE
BUG: Refreshing Organization admin section, throws an error

### ISSUE THREAD

**Issue by MarinaAlkemio** [alkem-io/client-web#4596]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/organizations/vite-org/authorization
2. Refresh the page - errors are thrown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDRtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d41c6b4847a32c119a88914dfe9fde13d38ba92/image.png)

**Expected behavior**
No errors are thrown on organization admin section after refresh.

**Comment by hero101** [comment]
Seems like a code bug.
Queries have to be skipped if the parameters are not defined. Try to avoid passing empty strings.

**Comment by Comoque1** [comment]
This issue is already addressed.
