### ISSUE TITLE
Page doesn't refresh after changed location of callout

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4602]
When I change the location of a collaboration tool in the dialog and then close the dialog, the page isn't refreshed but the block on the left is.

![Image](https://user-images.githubusercontent.com/38861315/262316673-5adec679-2916-4d8e-a36a-ee096c6756d5.png)

**Comment by SimoneZaza** [comment]
@Comoque1 I think I remember staying in the selected tab (Complete), not being redirected to the active tab. So I clicked on the complete tab, there was nothing there, then I opened the settings dialog from there, moved a callout to this complete tab and closed the dialog again. I remained on the complete tab but nothing had changed there. The block on the left did change.

**Comment by SimoneZaza** [comment]
@Comoque1 I think I remember staying in the selected tab (Complete), not being redirected to the active tab. So I clicked on the complete tab, there was nothing there, then I opened the settings dialog from there, moved a callout to this complete tab and closed the dialog again. I remained on the complete tab but nothing had changed there. The block on the left did change.
