### ISSUE TITLE
BUG (AHT): Callouts on Contribute - left should be fixed, not attached to a innoflow state

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4603]
On the Contribute page, the callout on the left part of the page should not be linked to a certain state, they should remain there when a user goes to another state.

![Image](https://user-images.githubusercontent.com/38861315/262319160-3175fc7a-263d-42fa-a8fa-d24b36353070.png)

##Expected behavior
On the contribute page to have two 'locations':
- Contribute left (fixed)
- Contribute right (innovation flow)

Callouts with the location 'Contribute left (fixed)' are behaving just as on the dashboard tab and other tabs and are not part of the innovation flow. So they don't (dis)appear based on a selected state and they are not visible in the innovation flow settings dialog. If easy to implement, it would be great to show them in the list block without a location behind it. If it saves a lot of time to just not show them there, that is also fine. 

Callouts with the location 'Contribute right (innovation flow)' are behaving just as they are now.

**Comment by Comoque1** [comment]
Bug

**Comment by Comoque1** [comment]
@SimoneZaza, could you please clarify in the expected behavior, for which callouts, it is related - default, newly created, are we going to put a pin to fix them?

**Comment by SimoneZaza** [comment]
@Comoque1 is this clear?

**Comment by Comoque1** [comment]
> @Comoque1 is this clear?

The described - yes!
One more question - should the left callouts be displayed on the list of callouts block?

**Comment by SimoneZaza** [comment]
@Comoque1 If easy to implement, it would be great to show them in the list block without a location behind it. If it saves a lot of time to just not show them there, that is also fine. (Added this in the expected behavior as well)

**Comment by SimoneZaza** [comment]
@alstojanovic thanks, clear!

**Comment by Comoque1** [comment]
All works as defined.
@SimoneZaza , just FYI, on "Innovation flow" dialog, the callouts from contribute_left position are still displayed and can be moved among different states, but they actually remain fixed on left position and are displayed on all states.
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77a468caf16b3455039d563df36dd651782dfd01/image.png" alt="image.png" />
