### ISSUE TITLE
Reduce the data in UserContext by utilizing myRoles on Community/Organization

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#4615]
## Description

As a user
I want fast loading time

## Acceptance criteria

- [ ] of<Community> and the other community helpers/fields (such as challenge name ids) should not be a part of UserContext
- [ ] Remove contributions from UserContext
- [ ] Remove usage of userRoles query from populating UserProvider
- [ ] Refactor the components such as Journey cards, Organization cards to use Community.myRoles/Organization.myRoles

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
Added high priority label as this will have a big impact on initial page load for users.
