### ISSUE TITLE
Creation of callout template in Space templates from callout

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4621]
## Description

As a global admin I want to be able to convert my existing work to a template that others can use

## Acceptance criteria
- [ ] New privilege: SAVE_AS_TEMPLATE, assigned to global admins
- [ ] Ad feature flag "Save callouts as template" on Space license
- [ ] Allow on the cogwheel entry on a callout the option to "Save as template", only shown if the user has the SAVE_AS_TEMPLATE privilege 
- [ ] For saving as template, the user enters the title to be used and a brief description + tags. 
- [ ] MUI Icon: DownloadForOfflineOutlined

## Design
Figma: https://www.figma.com/file/evsVpSowMdshDpaPDXP4eb/Callout-templates?type=design&node-id=126%3A3702&mode=design&t=7StRSRX7FUtWTugT-1 (bottom left section)

**Comment by SimoneZaza** [comment]
@techsmyth  Shouldn't you also be an admin of the Space that this callout is in?

**Comment by SimoneZaza** [comment]
Client: 5
Testing: depends on exact privileges
Server:

**Comment by techsmyth** [comment]
@SimoneZaza not about the role but about the privilege you have - so if it is tied to the Create or Update privilege on the place where the template would be created then that is fine. The policy about who gets that update privilege is a separate discussion!

**Comment by SimoneZaza** [comment]
@techsmyth @larssondenise Shouldn't the person who created the callout also get the save-as-template privilege?

**Comment by techsmyth** [comment]
@SimoneZaza agreed - will update criteria

**Comment by techsmyth** [comment]
@SimoneZaza actually on further reflection it will not make a difference, as the person will not be able to create the template in the space template set - so they would need to be admins of an org that is providing an innovation pack

**Comment by SimoneZaza** [comment]
@techsmyth yes, but if they are admins in another Space or org providing innovation pack...?
