### ISSUE TITLE
Cards for CollaborationTool-templates

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4630]
## Description

As a user, I want to see the different collaboration tool templates that are in an innovation pack

## Acceptance criteria

- [ ] Card as per design, showing:
     - [ ] Template title
     - [ ] Template description
     - [ ] Template tags
     - [ ] Template organization
     - [ ] Innovation pack
     - [ ] Response type visual

## Design
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczFIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--829988f351ac6ff2275f0da80900582a49f6ebeb/image.png)

Figma: zoom out first! Designs for multiple issues in this file. https://www.figma.com/file/evsVpSowMdshDpaPDXP4eb/Callout-templates?type=design&node-id=0%3A1&mode=design&t=A9tcHQi6g3fGiBAV-1

**Comment by hero101** [comment]
@techsmyth  #4630 and #4631 are blocked by #4629, which is not in the Sprint 71

**Comment by techsmyth** [comment]
@hero101 could the cards not be developed with mocked up data?

**Comment by hero101** [comment]
@techsmyth They can, but it's best to be actually applied somewhere.
It's not 100% blocked, but it's better to follow some logical order.

**Comment by Comoque1** [comment]
Cannot test the scenarios as there is no way to to import callout templates from platform:
- [ ]  Innovation pack
- [ ] Response type visual
- [ ] Mobile view

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkcvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54946f2ea2fff14e7ec68642ec749337c46a2947/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnkvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fde8e1006196c8ef57087b89d074c8f94c6fa04/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNisvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edb259f976a26bbf47ac5e94926b0a070ca2c8b1/image.png)
