### ISSUE TITLE
Client: Evaluate reducing package size via build config

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4637]
## Description
As a user I want the client to download and work quickly

## Acceptance criteria

- [ ] Evaluate options provided within Vite to reduce the size of the package that is downloaded to users
- [ ] Read up on other options offered by Vite that might be worth spiking
- [ ] Focus: tree shakedown (removing code not needed /used), identifying packages that can be removed from the client
- [ ] Identify what options there are for customizing our build process given our usage of react-scripts
- [ ] Markdown file with findings

Timebox to: a day?

**Comment by hero101** [comment]
1. Links
https://rizkicitra.dev/blog/improving-performance-in-react
https://rizkicitra.dev/blog/improving-performance-in-react#using-vite-js
2. Some code
```typescript
// vite.config.ts
import { chunkSplitPlugin } from 'vite-plugin-chunk-split';
//...
plugins: [
chunkSplitPlugin({
    strategy: 'unbundle',
    customChunk: args => {
      // files into pages directory is export in single files
      let { file, id, moduleId, root } = args;

    },
    customSplitting: {
      'react-vendor': ['react', 'react-dom'],
      'core': [/src\/core/],
      'dev': [/src\/dev/],
      'domain': [/src\/domain/],
      'main': [/src\/main/],
      // 'core-ui': [/src\/core\/ui/],
      // 'core-apollo': [/src\/core\/apollo/],
      // 'core-auth': [/src\/core\/auth/],
      // 'core-routing': [/src\/core\/routing/],
      // 'core-utils': [/src\/core\/utils/],
    }
  })
]
```
3. Found out that the `index.html` adds some `<link rel="modulepreload" crossorigin href="xxx">` and preloads all the resources when the page loads.
