### ISSUE TITLE
BUG: Community panel for challenge member roles edit has space term

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4645]
**Describe the bug**
The text on the dialog displayed to challenge (and opportunity?) admins for editing roles of a community member is talking about spaces:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTlEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--95415b0d20c402db9334f8364ec834bed141d0e3/image.png)

**To Reproduce**

1. Go to a challenge, click on settings + go to community
2. Click on a user edit and look at the dialog that pops up

**Expected behavior**
Text on the panel to be appropriate for the challenge (or opportunity)

**Comment by larssondenise** [comment]
@techsmyth I think this can't be changed as member settings are the same for space and challenge. So we have to split that!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalRZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d03687e6530ca78af90661d4b3e45febe05a043/image.png)
