### ISSUE TITLE
Sentry errors after move to vite to be understandble (not "Bee", "Hee" etc)

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4668]
## Description

As a Developer, I want to get clear understanding of "Bee", "Hee" errors logged in Sentry.

As a engineer I want to know where errors are actually happening

## Acceptance criteria

- [ ] Errors messages in Sentry are understandable
- [ ] Errors are returned with specific stack so, that it can be reproduced / fixed

## Additional Context
https://alkemio.sentry.io/issues/4429435474/?project=5862875&query=is%3Aunresolved&referrer=issue-stream&stream_index=18

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmRkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99787ced03451b1854bff9924a5c486c6dfa83bb/image.png)

**Comment by valentinyanakiev** [comment]
Needs to be verified when we deploy to an environment that reports to Sentry. Build pass now and the source maps are successfully uploaded to Sentry.

**Comment by valentinyanakiev** [comment]
Needs to be revalidated after deployment. _Should_ be working now...
