### ISSUE TITLE
Button for multi-user whiteboards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4690]
## Description

As a (beta testers group) user I need a way to start a multi-user whiteboard

## Acceptance criteria

- [ ] Add button to the choose callout type dialog
- [ ] Icon (this probably needs a custom icon, but for now let's choose between these two: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjFtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4940f51648771c76928517dd0d5a7b6aee417bbd/image.png)

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
@techsmyth preference for one of the icons? I think we have to create a custom icon, but for now, we can choose one of the above? And do you maybe have a better word for "multi-user"? Everything I can come up with also works for a single-user whiteboard...

**Comment by techsmyth** [comment]
I would suggest an image more like the following: 
![image](https://github.com/alkem-io/client-web/assets/30729240/8f24796b-7d49-47f8-b4d2-a9463b5369e6)

**Comment by SimoneZaza** [comment]
@techsmyth , ok, let's go with Real-time whiteboard then, for now.. I think we might want to have some more ideation around this word? :) For me it feels a bit weird: can I not update the other whiteboards in real-time then? I think we really miss the collaboration part, but with that part in it, the word becomes too long. 
Regarding the icon, unfortunately I cannot find anything like that in the MUI set. In the material set I did find the one that I've put in the issue now, but since this is just for the beta testers group, we might want to keep it as simple as possible and choose an MUI one? https://mui.com/material-ui/material-icons/

**Comment by techsmyth** [comment]
Moving forwad there will only be RT whiteboards, so no separate icon is needed
