### ISSUE TITLE
BUG: image lost?

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4694]
**Describe the bug**
In this post: https://inclusive-innovations.alkem.io/visimp/collaboration/eengeslaagdeworksh-7991 I've put an image, but when I checked this morning, it was gone. I'm not sure if there was also text inside the description of the callout, but I guess there wasn't any (btw, I've put the image back in since this is an active space).

I've checked the Storage overview, and I think it was the top one in this list:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3RyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3dac474a9f98fccea237b6b3ccb78049a370df07/image.png)

If I click on it, a 404 page opens:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzVyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66594c1b8ffb6f884bbbd181b5920ba490265d3f/image.png)

I've noticed the image was missing this morning and I think it was still there last week, or at least two weeks ago.

**Comment by SimoneZaza** [comment]
@techsmyth @hero101  here's a summary, hope this is everything you'll need...

**Comment by techsmyth** [comment]
@SimoneZaza am closing this as do not know any concreate action we can take. The new storage setup should help a lot, as it should be clearer what image is associated where - so think we just have to monitor moving forward. Plus any image failings like this should show up in our logs once we have storage deployed in a way that we can see if there is an issue by looking at the logs.
