### ISSUE TITLE
Upload of images propagated

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4720]
## Description

As a user I want to see images uploaded by others in my whiteboard

## Acceptance criteria

- [ ] Images uploaded by others should be propagated to other users

**Comment by Comoque1** [comment]
This seems to work only for RealTime Whiteboards.
Is it expected to work for single / multiple whiteboards as well?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWFxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5057c6370fa117cfec973305360ad68bd4af200c/image.png)

**Comment by Comoque1** [comment]
This seems to work only for RealTime Whiteboards.
Is it expected to work for single / multiple whiteboards as well?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWFxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5057c6370fa117cfec973305360ad68bd4af200c/image.png)

**Comment by Comoque1** [comment]
The above comments are going to be addressed as part of this bug: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/2189
