### ISSUE TITLE
Change info text on knowledge base tab

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4724]
## Description
As a user I want to understand what this page is and what is expected of me. This is already pretty clear from the title of the tab, but the text in the block on the left confuses me:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa054IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c1aa398a58febf9ce0bb7752813a2467032f247/image.png)

## Acceptance criteria

- [ ] Change info text on Knowledge base block
- [ ] Might also be worth checking the others..

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
@larssondenise do you **_maybe_** have time to pick this up? Guess it's just updating the translation file?

**Comment by larssondenise** [comment]
@SimoneZaza suggestions for text?
