### ISSUE TITLE
BUG: Add dialog doesn't display DEMO spaces

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4759]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/innovation-hubs/demo-visibility
2. On current selection block, press "ADD" button - dialog is displaye
3. Type "demo" in search - no results are displayed (only active spaces are available)
4. Even if an admin adds an active space, it is not displayed in the list of "Current Selection"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUd4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd757ec170f4e8ed91c25df2b5ac391c66f98562/image.png)

**Expected behavior**
TBD

**Comment by Comoque1** [comment]
Now the "Current Selection" dialog displays only DEMO spaces

**Comment by techsmyth** [comment]
@me-andre yes that would explain it. Evgeni must have gone to the platform admin from the innovation hub URL. Maybe we need to always to the platform admin from the root alkem.io location...

**Comment by techsmyth** [comment]
@me-andre I would rather not have that - it is cleaner to have the admin always from the root, otherwise more complexity in the api.
