### ISSUE TITLE
Spike: Excalidraw 0.16 (whiteboard)

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4768]
## Description

As a user I want a great whiteboard experience

## Acceptance criteria

- [ ] Investigate new release + implications / benefits for Alkemio
- [ ] Capture findings in MD

## Additional Context
https://github.com/excalidraw/excalidraw/releases/tag/v0.16.1

**Comment by ccanos** [comment]
https://hackmd.io/r548SfcgTxmWhwjrKcLiHQ

**Comment by techsmyth** [comment]
@ccanos nice analysis. It sounds like we should push on with moving to this new version, how much effort would that be?
