### ISSUE TITLE
Performance diagnostic page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4785]
## Description

As a developer I want to be able to check the performance of the browser in which the client-web is being run

## Acceptance criteria

- [ ] Simple html page hosted in the public directory of the client-web, called "client-diagnostics.html"
- [ ] Pure html / javascript page, with very basic html structure:
-  display Alkemio logo 
-  display static text stating: "Browser performance diagnostic page"
-  display meta information about the browser: client type, version, OS?, ???
- [ ]  "Test Configuration Load" button to execute the following logic: hard coded call to production end point public graphql query and retrieve the configuration (so no authentication required). After executing the query the page reports on the elapsed time to retrieve the data.  Note: focuses on latency. 
- [ ]  "Test Browser Compute" section with two items a) field to allow user to specify the number of pi digits to compute , defaulting to 30 (update as needed, ideally the compute should take 5+ seconds on a developer machine)  b) button to execute the compute test. After executing the query the page reports on the elapsed time to retrieve the data.  Note: focuses on browser compute capacity.

## Additional Context
Key customers are experiencing non-usable load times within a Citrix environment. This page is to allow us to understand the capability of the browser / IT setup that is being used.

**Comment by Comoque1** [comment]
I cannot see such field: a) field to allow user to specify the number of pi digits to compute , defaulting to 30 (update as needed, ideally the compute should take 5+ seconds on a developer machine)

**Comment by techsmyth** [comment]
@Comoque1 I had forgotten to update the acceptance criteria, this implementation is fine - the pi suggestion did not work out in the end.

**Comment by Comoque1** [comment]
Thanks, @techsmyth !
