### ISSUE TITLE
BUG: Demo spaces are not visible under 'current visibility' block 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4802]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/admin/innovation-hubs/demo-visibility - demo spaces are not displayed in the list
2. Try to add a space - request succeeds, but space is not added
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--588fe098f62c076f8c4408cf984af364f6f28356/image.png)

**Expected behavior**
Demo spaces are visible.
Demo spaces can be sorted.
User can add spaces with other visibility?

**Comment by hero101** [comment]
@valentinyanakiev 
The demo spaces were never meant to be visible in the `Current Selection` control.
That control is only meant for sorting Spaces when the Hub is of list type.
The sorting of "visibility" spaces was never possible.
Will need to address this issue with Product.

**Comment by valentinyanakiev** [comment]
@hero101 shouldn't they be visible, at least?

**Comment by hero101** [comment]
> @hero101 shouldn't they be visible, at least?

@valentinyanakiev Was not planned like that to begin with.
