### ISSUE TITLE
Custom Home Page description limit

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#4806]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

## Additional Context

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUhZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ddefaa70fab20e937a29e92381a19617e9e23608/image.png)

**Comment by techsmyth** [comment]
@larssondenise please check this once the new release is out...
