### ISSUE TITLE
Whiteboard RT: settings on who can edit it

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4818]
## Description

As a user I want to be able to control who can edit my whiteboard

## Acceptance criteria

- [ ] Defined controls regarding who can edit a whiteboard
- [ ] Authorization policy updated to reflect logic
- [ ] Client using privileges to control what actions users are offered

Design:
- [ ] Share dialog to get a second section named Settings
- [ ] Sentence to reflect whether Multiuser collaboration is enabled in the Space or not
- Spaces with RT whiteboards disabled: Based on the settings of the Space that this Whiteboard is in, real-time collaboration is not enabled. This means that only one user can edit at a time. 
- Spaces with RT whiteboards enabled: Based on the settings of the Space that this Whiteboard is in, you can edit with multiple users at once. If you do not want others to edit, change the settings below
- [ ] Left side: small user card for owner of the whiteboard (= creator for now) (50% width)
- [ ] Right side: single select for who can edit, which can only be updated by the owner (50% width)

## Additional Context

Design: https://www.figma.com/file/MzjrE0u8iwQjQ8os56AitR/Multi-user-whiteboards?type=design&node-id=246%3A244&mode=design&t=3XxyxytWiP6OcicK-1

**Comment by SimoneZaza** [comment]
@techsmyth estimation was based on the server part already being done..

**Comment by techsmyth** [comment]
@SimoneZaza  ok - moved the estimate back...

**Comment by Comoque1** [comment]
There are a couple of details that need to be covered:
- clicking on user profile redirects to wrong endpoint: 
<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd91ffc40c6212a05b46708d1f56c9a154d8a7e6/image.png" alt="image.png" />
- Missing journey type on the options:
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25TQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c17d54f9e517c00b3160f7bc14e9b693deafd8f/image.png" alt="image.png" />

- for public space and only "owner contribution allowed", space member can contribute
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81c600a0c4231d900145814fbd04780cdcee277c/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@SimoneZaza I have a question regarding from where should the Whiteboard setting appear:
1. from whiteboard dialog, share button - currently implemented
2. from callout share dialog - not implemented - is it expected?
<img width="1191" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5d67bb81d51ad050549a45eb4f21807402142d6/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
"UPDATE_CONTENT" privilege on WhiteboardRT is not applied until the Space policies are not reset:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b7c7432c853694717e30dfa034a877f451459fa/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
@Comoque1 thanks for raising this inconsistency. It was indeed only expected to be in the share dialog when opened from the whiteboard itself, but this is clearly inconsistent/confusing from a user perspective. I will raise it as a separate issue.

**Comment by Comoque1** [comment]
@me-andre , when a normal user have WB open and owner disable it for modifications from "everyone", the user cannot close the WB.
<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3pmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1998af9489cc382302843c05578419a3b46e08c8/image.png" alt="image.png" />


Moving it back to backlog.

**Comment by Comoque1** [comment]
Raised a separate bug about the last comment: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5415
