### ISSUE TITLE
Show correct message on space dashboard, when user rejects invitation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4829]
## Description

As a User I want to have correct message, when I reject an invitation. At the moment there is a label, stating "Accept invitation our Community...", but when user clicks on it, empty dialog is open

## Acceptance criteria

- [ ] If invitation is rejected, client behaves as if the invitation had not happened

## Additional Context

Screen shots / UX designs / data that are relevant.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXptIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe3bb27c376eb86f2bcb19b4dc101df53dfa2257/image.png)

**Comment by SimoneZaza** [comment]
@valentinyanakiev can you have a look at estimating this one? It seems to be a server thing?

**Comment by SimoneZaza** [comment]
Part of #5484
