### ISSUE TITLE
Clarity on why users can't be invited to a space

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4831]
## Description

As an admin or lead, trying to invite people to join a Space, I do not want to get errors. Based on our error logs, users are currently trying to add people who are either already a member or already invited to a Space, which causes an error. 

## Acceptance criteria
In the dialog for inviting Alkemio users, in the list that pops up when searching:
- [x] Sort on membership status: 
       - [ ] First the people who are not a member and not yet invited, 
       - [ ] then people who already made an application to join
       - [ ] then invitees, 
       - [ ] then members
- [x] Disable applicants invitees and members
- [x] Show a message (caption italic) for invitees and members:
       - [ ] This user already received an invitation
       - [ ] This user has already applied
       - [ ] This user is already a member
- [x] If not too much work: visually indicate that this user is disabled. Maybe a disabled icon on top of the avator, or in front? Or whatever is easy.
 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1htIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e2b6a814a2c67a6c2ed377c5370bfe0c2f38109/image.png)
 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@ccanos can you please have a look at what is needed to address this? We have gotten quite a number of error messages which this issue would address...thanks!

**Comment by Comoque1** [comment]
Looks pretty nice:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dd2cd102bf634af14a16972fb5fcbd633678088/image.png)
