### ISSUE TITLE
Search component for the new Page banner

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#4845]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Expandable on click
- [ ] Has search scope dropdown with Space selected by default (Search can only be scoped by Space at the moment)
- [ ] Search scope dropdown has 2 options: Search within Space and Search on the Platform
- [ ] No changes to how search results get opened (local search inside Space, global search on the global Search page)
- [ ] Looks as per design if takes reasonable time, but must highlight the scope of the search
- [ ] Both hitting Enter and clicking on Search icon triggers search

## To be discussed
- [ ] Conditions to collapse the Search box

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
@me-andre I suggest collapsing the search box once the user leaves the search results page.. If much easier, it can also be collapsed immediately if the search terms are transferred to the input field on the search page itself.
