### ISSUE TITLE
User menu

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#4847]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Expands both on click and hover
- [ ] If possible, use the existing user menu component
- [ ] If activated on click, don't close when the cursor goes away
- [ ] Has the items as per design
- [ ] Looks as per design

## To be discussed

- [ ] Sign in / Sign up when signed out

## Additional Context

**Click/hover open/close behavior should be implemented once for both menus, please synchronize with the team before starting**

**Comment by SimoneZaza** [comment]
@me-andre good one 😊 I'll add a design. Basically, it will come down to replacing the user avatar with a sign in/up button.

**Comment by SimoneZaza** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckR1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0beb3332296796508d868ec2f8ad0bb13e0e30c7/image.png)
