### ISSUE TITLE
Display also the  email address when adding members on challenges / spaces

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4851]
## Description

As an admin I want to be able to see the email address of the user I am adding

## Acceptance criteria

- [ ] Email address to also be shown in the table when selecting a new member to add, even if that is 'not accessible'

## Additional Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVR0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24771bafdd6f8482e9fdf526d59dc57bbabde135/image.png)

**Comment by techsmyth** [comment]
@ccanos this can also be done in a simple way e.g. just have the email address in brackets after the name. I am presuming he complexity comes from having multiple columns?

**Comment by Comoque1** [comment]
Works fine on DEV env.
<img width="1424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d9f72fa503f4e0025f6174298aad3f4eb941e18/image.png" alt="image.png" />
