### ISSUE TITLE
New banner for User, Organization and Innovation pack profile pages

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#4884]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Header: potentially uses the same component as Journey banner (with more content in it - look in Figma)
- [ ] Banner image as on global pages
- [ ] User Bio section updated (content moved from the old header - look in Figma)
- [ ] Innovation pack - no avatar

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1JQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6745b72db812a13e54df0e72f43767d5a40c05d/header_pp.png)
This is the image in png, 309kb, I can export it in a higher resolution but let's check this one first, the smaller the better I think 😊
