### ISSUE TITLE
Improve messages on closed callouts

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4895]
## Description

As a User I want to have a clear visualization and information when a callout is closed and there is / there is no data.

## Acceptance criteria

- [ ] The conditions are defined in the attached file
[callout- closed_state.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6117e88c0d2859d79ffdafe4be261dea1d9b1c4/callout-%20closed_state.xlsx)
- [ ] Message depends on callout type + whether there is data or not

## Additional Context

Screen shots / UX designs / data that are relevant.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09fde3b3a5ea129494be2b75521148b4a7031a6f/image.png)

**Comment by SimoneZaza** [comment]
@Comoque1 I'm closing this one as it's a bit outdated and we're picking up the more recent #6243. Would you to like me to update this excel file with the new AC?
