### ISSUE TITLE
Update code gen versions

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4918]
## Description

As a developer I want to get meaningful error messages
## Acceptance criteria

- [ ] Graphql codegen to be at the same level as in test-suites

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
@techsmyth tried updating all codegen related packages + updating typescript version to match the test suits and the generation error problem still persists. Needs more deeper dive into config.
