### ISSUE TITLE
Search dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4928]
## Description

As a user, I often prefer to stay where I am when I'm searching for something. Currently, depending on the search scope, I get referred to a different page

## Acceptance criteria

- [ ] Search dialog as per design (As simple as possible to implement)
- [ ] Remove search tab from space
- [ ] Remove global search page

## Additional Context

Figma: https://www.figma.com/file/6J0lfFjW0MYkMhsT3tphHR/Powered-by-Alkemio?type=design&node-id=311%3A4805&mode=design&t=u49RsuVSgDnAgpTl-1

**Comment by Comoque1** [comment]
Second point of AC is not met:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a438d4755929a2a64f8a8dbfdeec7880115c8a80/image.png)
