### ISSUE TITLE
BUG: Saving a single or realtime whiteboard triggers twice uploadVisual request

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4931]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/length-sp/knowledge-base
2. Create a single or realtime whiteboard
3. Open in edit mode the whiteboard
4. Add an image to it
5. Save the change - `uploadVisual` request is triggered twice with 2 different visualIDs
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e16cd1d94219e56bb2928519f120528226c90121/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3dbdeb8b27dca869fa842235d96118339ea4405/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dfb347bca6682ab3f031d29fba0b3e863e1b47e/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23aacd7b7376a54c71133df87c27ca5d8fa95197/image.png)

**Expected behavior**
When a whiteboard is saved upload visual is triggered only ones.

**Comment by techsmyth** [comment]
@Comoque1 not a bug, it is saving two different images
