### ISSUE TITLE
BUG: Post callout cannot be sorted on top

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4944]
**Describe the bug**
There is an issue, with 11 particular callout, that cannot be sorted on to of a challenge dashboard.
**To Reproduce**

1. Go to https://alkem.io/building-alkemio-org/challenges/teamoffsiteseptemb-9083/dashboard
2. Set 'Thank you!!!' callout on top - position on client doesn't change, but with each try, the sort order increase.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f06284718b393963c9c8122336c66ba6bea2431f/image.png)

**Expected behavior**
When callout is intended to be sorted on top, it gets correct position.

**Additional context**
The issue cannot be reproduced on ACC env or another challenge within this space.

**Comment by valentinyanakiev** [comment]
@techsmyth that's only if we want to go above the predefined in callouts in the template. Is this intended or not?

**Comment by techsmyth** [comment]
@valentinyanakiev good if we take a few minutes to talk this one through...

**Comment by techsmyth** [comment]
@valentinyanakiev there is no special ordering for callouts. There is a client bug that means it is not picking up the right set of callouts based on display location
