### ISSUE TITLE
BUG: Content of recent contributions block not truncated

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4946]
**Describe the bug**
With some contributions, the preview of the text doesn't seem to be truncated, see for example the screenshot below. Now I look at it again, isn't it just picking up the wrong part? Could it be that call for posts show the description instead of the title?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b6159e5c932478ae1c8e20d809c74865d8b6179/image.png)

**To Reproduce**

**Expected behavior**
Preview to be just one line

**Comment by alstojanovic** [comment]
@SimoneZaza Post creation activity currently displays "PostDisplayName - postDescription". We can change it to be only PostDisplay name or truncate the whole string from some point.

**Comment by SimoneZaza** [comment]
@alstojanovic, I think it's nice to also show a part of the description, so if possible, keep it this way and then truncate the entire thing to fit on one line?

**Comment by SimoneZaza** [comment]
Part of #5399
