### ISSUE TITLE
BUG: Accepted applications are shown as added members in activity log

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4947]
**Describe the bug**
When the application of a user to a private space is accepted, the activity log message doesn't make sense. It shows the name of the person accepting the application, while it should just say something like <User> joined the space. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW94QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef2900c6cb548dcc518506b0c93655850dd194cc/image.png)

**To Reproduce**

**Expected behavior**
In this screenshot: "10 seconds ago Merijn Zondag joined "Building the A-team"

**Comment by techsmyth** [comment]
@SimoneZaza this needs a deeper discussion, we currently trigger the member joined notification when accepting - we ideally need multiple new notification types. So a bigger piece of work.

**Comment by techsmyth** [comment]
@SimoneZaza a second thought on this: it would be a smaller update to get at least the activity logs updated - maybe we split it?

**Comment by SimoneZaza** [comment]
@techsmyth , I've made a second issue for the notification: #268
