### ISSUE TITLE
Add label to 'show password'- button

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4949]
## Description

As a user with a visual impairment, I need to be told what the button next to the password input field does, otherwise I might accidentally click it and show my password to everyone who can see my screen

## Acceptance criteria

- [ ] Add label "Show Password" to eye button next to password input field on sign up page
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by ccanos** [comment]
Please @SimoneZaza ,  when you have a minute, can you have a look and confirm me if this fix is enough? 
Should be in dev already

**Comment by SimoneZaza** [comment]
@ccanos Yes, works, perfect! Thanks!
