### ISSUE TITLE
Whiteboards: 2x same icon for different functionalities

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4956]
## Description

We currently use the same icon for Zoom to fit (bottom left, next to zoom percentage) and full screen (top right). I suggest using a different one for the zoom to fit. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGc1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49f3338ac8b0017a1cca8550d3e49bd8ae1d31e8/image.png)

## Acceptance criteria

- [ ] Change bottom icon (zoom to fit) to be the ControlCamera icon (mui, see below)
- [ ] …

## Additional Context

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjA3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--460ca32208f50de7fb9aedf8c7e9f764f19633c2/image.png)

**Comment by hero101** [comment]
Im closing this story because it's absolute - they have changed the UI.

<img width="310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--931aad094874cb58bd043ebdb2b834e84498f347/image.png" alt="image.png" />
