### ISSUE TITLE
Report: overview of client information on resize observer errors

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4959]
## Description

As a developer I want to know more about what is causing the resize observer errors

## Acceptance criteria

- [ ] Overview of what pages it happens on, who experienced it, browser / client OS information

Spike: 2 hours

## Additional Context
https://github.com/alkem-io/client-web/issues/4793

**Comment by hero101** [comment]
https://kibana.alkem.io/app/dashboards#/view/38606740-73de-11ee-aa45-97727dee3418?_g=()
