### ISSUE TITLE
BUG: Need to click 2 times on edit button to open whiteboard in edit mode

### ISSUE THREAD

**Issue by alstojanovic** [alkem-io/client-web#4961]
Steps to reproduce:
1. Create a Single Whiteboard Callout
2. Click to open the Whiteboard
3. Click on 'edit' button.
4. User cannot enter the edit mode (he enters only after clicking the 'edit' button two times)

Expected behaviour: User can enter edit mode after clicking 'edit' button once.

Same issue happens with whiteboards in Whiteboard collection callouts.

When a whiteboard is opened

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08b946bd6e92a080500c2dc73608dc79533209ce/image.png)

**Comment by techsmyth** [comment]
@alstojanovic can you please add a full description to this bug?
