### ISSUE TITLE
BUG: PoweredBy Menu not visible on white background

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4965]
**Describe the bug**
PoweredBy menu is not clearly visible on lighter background.

**To Reproduce**

1. Go to ['Test Innovation Hub on Sandbox'](https://sandbox-innovation-hub.alkem.io/home)
2. Try to locate the PowerBy menu
3. It is hard to see
![Image](https://github.com/alkem-io/client-web/assets/7090348/10a3acc1-ed95-4655-badb-99bf0e1ed663)

**Expected behavior**
We can locate the menus / controls on the screen easily.

**Additional details**
- [ ] Add shadow x=0 y = 0 blur =10 ? #000000 opacity 25%

**Comment by Comoque1** [comment]
Looks better
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUYwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44e53c0b3dd3d7ed7f95ac98ad3b3d26b750d1fc/image.png)
