### ISSUE TITLE
My Dashboard for Logged in User

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4967]
## Description

As a User
I would like to have meaningful / self explanatory controls
so that I don't get lost in the application

## Acceptance criteria

- [ ] Clicking on `My Dashboard` points to meaningful places for both Alkemio and Innovation Hub domains

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by SimoneZaza** [comment]
Will be picked up with the powered by epic
