### ISSUE TITLE
BUG: Anonymous access to Org leads to 401

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4969]
**Describe the bug**
Anonymous access to Org gives Unauthorized error.

**To Reproduce**

1. Open incognito window
2. Navigate to https://sandbox.alkem.io/organization/eco1host
3. You get 401

**Expected behavior**
You should be able to see an org being anonymous.

**Comment by valentinyanakiev** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90b7033c9a05d288f603ec677866c3f873cc3d21/image.png)

That's anonymous access now. Again, fixed by propagating auth properly to contribution.

**Comment by Comoque1** [comment]
fixed
