### ISSUE TITLE
BUG: unauthorized dialog opening

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4970]
Describe the bug
When I go back to the homepage and try to revisit the Space from there, I get the unauthorized dialog and can't click on apply, the button top right says I'm member. After refreshing it disappeared. This happened a couple of times, and after that not anymore.

To Reproduce

Go to sandbox.alkem.io
Click on a space that you're a member of

See error (or not)

Expected behavior
To just be able to open the space

**Comment by techsmyth** [comment]
@Comoque1 please see if you can find a way to reproduce this.

**Comment by Comoque1** [comment]
@techsmyth, cannot reproduce on DEV env.
