### ISSUE TITLE
BUG: Wrong text color in profile page header

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4971]
Describe the bug
The text color of my name is not in the right color

To Reproduce

Go to my profile

See error

Expected behavior
Text color to be darker, same as on the homepage

Screenshots

![Image](https://github.com/alkem-io/client-web/assets/38861315/8209fa1d-1c2b-4418-8f0c-3b485127db44)

**Comment by Comoque1** [comment]
fixed
