### ISSUE TITLE
BUG: sign in/up button missing

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4972]
**Describe the bug**
Anonymous user doesn't have My Dashboard and Memberships

**To Reproduce**

1. Go to [ 'Sandbox Innovation Hub'](https://sandbox-innovation-hub.alkem.io/home) as Anonymous user
2. Click on the user 
3. The Menu has My Dashboard and Pending Memberships

**Expected behavior**
When a user isn't signed in, the top right icon is a grey user icon. This should be in primary color to stand out more.

Screenshots

![Image](https://github.com/alkem-io/client-web/assets/38861315/19b210d8-a407-4863-989e-fd07a5e9638e)

**Comment by Comoque1** [comment]
fixed
