### ISSUE TITLE
BUG: Clicking on Alkemio logo navigates to a broken state

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4975]
**Describe the bug**
When clicking on the Alkemio logo element on the navigation bar, you are navigated to a broken state/page.

**To Reproduce**

1. Go to "https://sandbox.alkem.io/home"
2. Click on the"Powered by" Alkemio logo on the navigation bar 
4. You are navigated to a broken page  (see screenshot below)

**Expected behavior**
You are navigated to the proper place (TBD what is the RIGHT place)

** Screenshot **
![Image](https://github.com/alkem-io/client-web/assets/7901834/65d81ebf-d1f6-4ba1-8b23-c87bf3507cde)

![Image](https://github.com/alkem-io/client-web/assets/7901834/da03f14b-a2d2-44db-bbcc-07f4a6462420)

**Comment by valentinyanakiev** [comment]
@SimoneZaza is /landing what was desired here?

**Comment by SimoneZaza** [comment]
@valentinyanakiev  yes, this should bring the user to the landing page

**Comment by Comoque1** [comment]
fixed
