### ISSUE TITLE
BUG: Missing margings

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4977]
**Describe the bug**
Margings are missing between the navigation and page content

**To Reproduce**

1. Go to all tabs in https://sandbox.alkem.io/admin
2. Observe the missing margins between the navigation and the page content

**Expected behavior**
Some margin needs to be introduced between the navigation and the page content

**Screenshot**

![Image](https://github.com/alkem-io/client-web/assets/7901834/15cc38c2-100d-4820-a4d4-d7484a6049df)

![Image](https://github.com/alkem-io/client-web/assets/7901834/4518b71f-2588-4b4d-a541-c5aa5ca113ba)

**Comment by Comoque1** [comment]
fixed
