### ISSUE TITLE
BUG: Not able to create a new Space

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4978]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox.alkem.io/admin/spaces/new
2. See error

**Expected behavior**
The page does not crash.

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7901834/b6584ec9-1bf1-4d5a-9ae2-d963f838f77f)

**Comment by Comoque1** [comment]
fixed
