### ISSUE TITLE
BUG: Innovation flow not displayed correctly

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4979]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox.alkem.io/admin/spaces/eco1/challenges/cleanairinthewor-8894/innovation-flow
4. See how the picture is displayed

**Expected behavior**
The picture must be displayed correctly

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7901834/e7908f86-3d41-44ef-9581-02be5928b2d4)

**Comment by ccanos** [comment]
Cannot reproduce this anymore

**Comment by valentinyanakiev** [comment]
Could not reproduce locally or on sandbox with the feature branch
