### ISSUE TITLE
BUG: My profile URL is wrong

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4980]
**Describe the bug**
When I go to "My profile" the url is displaying the internal UUID.

**To Reproduce**

1. Go to "My profile" on the users menu, right top corner over the avatar
2. Click on it
3. See the url

**Expected behavior**
You should see the nameID instead of the UUID of the user

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7901834/46b2c6fd-5a8c-41bb-8018-0aa73518f20d)

**Comment by valentinyanakiev** [comment]
Might be fixed with latest @me-andre PR

**Comment by Comoque1** [comment]
fixed
