### ISSUE TITLE
BUG: Two floating buttons on smaller resolution

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4981]
**Describe the bug**
Two floating question buttons are displayed on smaller resolution

**To Reproduce**

1. Go to https://sandbox.alkem.io/eco1/dashboard
2. Click on reduce the width to less than 1200px
3. Observe the double floating buttoons on the bottom right

**Expected behavior**
One button is expected at any time

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7901834/09827c76-b5a7-45db-8715-2f175246be16)

![Image](https://github.com/alkem-io/client-web/assets/7901834/8a46a207-a9c5-49d5-b306-2cdd9c7fb3de)

**Comment by Comoque1** [comment]
fixed
