### ISSUE TITLE
BUG: Callout tags are ignored on Create

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4982]
Describe the bug
When creating a callout, adding tags into the Tags makes no effect

To Reproduce

    Go to a challenge, contribute tab for example
    Click on `Add a Collaboration Tool`
    Click on `Post` for example
    Write a name, write a description and add some tags.
    Click on `Publish`
    Scroll down to the created callout
    See the missing tags:

![Image](https://github.com/alkem-io/client-web/assets/16032487/1608f5f7-78ef-4552-b0e6-1561a2971af7)

![Image](https://github.com/alkem-io/client-web/assets/16032487/861c6c3c-e912-4c86-b078-e4884089a5ad)

Tags are not going to the server on Create:
![Image](https://github.com/alkem-io/client-web/assets/16032487/44db8afd-c62a-45a9-9f3f-d9c3909fce02)

When editing a callout I tags can be added and it works

Expected behavior
Tags are added correctly on create

**Comment by Comoque1** [comment]
fixed
