### ISSUE TITLE
BUG: User avatar doesn't load

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4984]
Describe the bug
On Share Dialog, Simone's avatar didn't load:

![Image](https://github.com/alkem-io/client-web/assets/16032487/e05c790d-f6ce-42cd-afac-55658c2d5d0f)

![Image](https://github.com/alkem-io/client-web/assets/16032487/ec15c381-e900-4382-8abc-35fecc47884e)
![Image](https://github.com/alkem-io/client-web/assets/16032487/f981ce19-aa98-49c4-a3d5-71d91b4bd32d)

![Image](https://github.com/alkem-io/client-web/assets/16032487/8dcfa162-764f-4f1b-bb28-83f0a40e0b32)

URL of the avatar: https://sandbox.alkem.io/api/private/rest/storage/document/e5411780-5cc7-41b6-80de-a87d048d6729

Response:
{
    "statusCode": 403,
    "code": "FORBIDDEN",
    "timestamp": "2023-10-17T08:48:20.842Z",
    "message": "Authorization: unable to grant 'read' privilege: Read document: newFile.jpg - 'e5411780-5cc7-41b6-80de-a87d048d6729 user: f6df5ebd-3040-4bb4-88f3-195370383615",
    "stack": "ForbiddenHttpException: Authorization: unable to grant 'read' privilege: Read document: newFile.jpg - 'e5411780-5cc7-41b6-80de-a87d048d6729 user: f6df5ebd-3040-4bb4-88f3-195370383615\n    at StorageAccessController.document (/usr/src/app/dist/services/api-rest/storage-access/storage.access.controller.js:55:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

To Reproduce

    Go to a post
    Click on Share button
    Type the name of a user who has an avatar set
    See error

Expected behavior

Screenshots

**Comment by SimoneZaza** [comment]
🙁 and it was such a nice avatar..

**Comment by valentinyanakiev** [comment]
Likely fixed with the authorization fix on contributions.

**Comment by Comoque1** [comment]
Still reproducible on DEV env.

**Comment by techsmyth** [comment]
@valentinyanakiev @Comoque1 I put a PR up for this yesterday evening
