### ISSUE TITLE
Expanding all breadcrumbs shifts the right side of navigation out of the page

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#4985]
### Acceptance criteria
- [ ] Breadcrumb max width based on percentage of screen
- [ ] min width for right side of navigation
- [ ] expanded state of search bar / breadcrumbs are mutually exclusive, if one is expanded, the other is collapsed.

![Image](https://github.com/alkem-io/client-web/assets/594548/0b8424d5-215d-4779-a9c7-7e4fa1c4d6fd)

**Comment by valentinyanakiev** [comment]
@me-andre can you please fill in the details following the bug template?

**Comment by Comoque1** [comment]
Fixed
