### ISSUE TITLE
My Dashboard elements: New memberships block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5011]
## Description
As a user, I want to be prompted about the journeys that I have been invited to
As a user, I want to have a consistent layout (the block not to disappear when there are no invitations)

## Acceptance criteria

- [ ] Badge behind the title with the amount of open invitations 
- [ ] First section: list of pending applications
- [ ] Second section if the first section holds 0, 1, or 2 items: list of journeys that were most recently joined
- [ ] More button **if second section is shown**: Show all my memberships, opens dialog
- [ ] More button **if only first section is shown**: Show all my pending memberships, opens pending memberships dialog (which is already on production)
 - [ ] Please check if it looks acceptable on mobile
 

## Additional Context
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=550%3A14704&mode=design&t=3UBbJ33IgFrWSZau-1

**Comment by Comoque1** [comment]
The following points are missing:
- [ ]  Badge behind the title with the amount of open invitations
 <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2hrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7ca3141feb26adaa87a73e8466d640ff78edefc/image.png" alt="image.png" />
- [ ] Avatars are missing
<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c847c48ae4739daedce71b3d848e3b632ab5d8ab/image.png" alt="image.png" />
- [ ] In addition, @SimoneZaza isn't it good Idea this block to be called Pending membership, as it is related to this information?

**Comment by SimoneZaza** [comment]
@Comoque1 , if you have less than 4 invitations/applications open, the most recent new memberships are added to keep a consistent list size. That's why the header is New Memberships instead of Pending.

**Comment by Comoque1** [comment]
The number of open invitations doesn't correspond to the number in the badge counter
<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47d07b9766c9ad0258fd6b92a15ac2a02c801f46/image.png" alt="image.png" />

<img width="1559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ec0744aab04945c09d7e6623dada9bdb55400d6/image.png" alt="image.png" />
