### ISSUE TITLE
My Dashboard elements: My latest contributions block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5012]
## Description
As a user, I want to be able to jump right back to the collaboration tool that I was last contributing to. 

## Acceptance criteria

- [ ] List of collaboration tools that the user last contributed to (or that he/she created) as per design
- [ ] Clicking on one of the list items opens the callout dialog in the journey page. 
- [ ] Please check if it looks acceptable on mobile
 

### List items:
- [ ] Journey avatar with callout type icon on top as per design
- [ ] Callout title
- [ ] Location

## Additional Context
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=550%3A14704&mode=design&t=3UBbJ33IgFrWSZau-1

**Comment by Comoque1** [comment]
At the moment, all activities under the same callout are displayed without the actual content. When user worked on 1 callout, show it only ones with latest timestamp activity
<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12e4abf8423186c9cc5c2b7fcd964c88aad09c04/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Added the above comment to Feedback on My Dashboard #5316 and closing this one.
