### ISSUE TITLE
My Dashboard elements: Tips & Tricks block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5013]
## Description
As a user, I want some guidance on what to do next
As the Alkemio operations team, I want to be able to update the image and text once in a while, to point people to other blog posts

## Acceptance criteria

- [ ] Static list of tips and tricks as per design, both image url as text to be in the translation file
- [ ] Clicking on one of the list items brings the user to a related blog post on the Alkemio website **in a new tab**, URLS will be provided by the operations team and need to be in the translation file.
- [ ] Link to more tips & tricks brings user to the blogs section of the website **in a new tab** 
- [ ] Please check if it looks acceptable on mobile
 

## Additional Context
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=550%3A14704&mode=design&t=3UBbJ33IgFrWSZau-1

**Comment by Comoque1** [comment]
Looks nice, but the first 3 links point to private challenge of a private space.
This results in misleading information for the user
<img width="1727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89024d21687505c2d6484a8b13a29bac823a8d4a/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b54ef14c55f35e86d224540db505b6a16b2e4dc/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
@larssondenise quick check: you are updating these links right? If not, let me know, then I will have a look 🙂

**Comment by larssondenise** [comment]
@SimoneZaza yess still on the to do..
