### ISSUE TITLE
Button labels sign in/up flow

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5025]
## Description

As a user with a visual impairment I want to know what buttons do once I activate them so I can appropriately use the platform

## Acceptance criteria

- [ ] Check all buttons on sign in/up pages
- [ ] Add missing labels 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@SimoneZaza still an issue?

**Comment by SimoneZaza** [comment]
I'll check

**Comment by KayleeS96** [comment]
@SimoneZaza Checked sign up/sign in pages with tabbing and screenreader. Everything is reachable and labeled.

**Comment by SimoneZaza** [comment]
Thanks for checking @KayleeS96 !!
