### ISSUE TITLE
Display of lists in markdown

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5038]
## Description

As a user I want my enumerations to look nice in the markdown field.

## Acceptance criteria

- [ ] Remove double line break above and below the list (should be single)
- [ ] Use same font as for the normal text

## Additional Context

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2htQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf7e83ccb8af4d91ccd130591194448d612367cc/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1863e18f43ae4ceef4a401c9f68fcd3247f8c9ee/image.png)

**Comment by SimoneZaza** [comment]
very interesting... I don't know how I did it, but I somehow managed to get it right in one list and wrong in the other..

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMksxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da05fe69d90ec2235d79cb2305774df9cef064b8/image.png)

**Comment by Comoque1** [comment]
The behavior with double line break is still experienced, when copying the list when it contains a sentence before the list. 
If a user copy only the list: OK.
If a user type type it using the MD form: OK

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c74837724c0c83ad9cd047e6f64f55b76f7d4fc9/image.png)


@SimoneZaza , @larssondenise , If you accept the above behavior feel free to close the issue. 
If not - we'll move it back to backlog.

**Comment by SimoneZaza** [comment]
I'm happy! @larssondenise ?

**Comment by Comoque1** [comment]
Add other story: `Improve copy/paste when copied text contain sentence and a list #5219` for the failing case and closing this one, based on discussion with @larssondenise
