### ISSUE TITLE
Labels on all icon/image buttons

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5042]
## Description
Currently, there are many icon buttons on the platform without a label. When using a screen reader, a label is necessary to understand what you're doing or where you're going.
An example on the sign in page:

> A user finds the input field for their ID and enters it
> Next field is password, all is fine
> Next is a button without a name. Probably to enter?
> User activates this button but isn't signed in or something, instead, his/her password is visible to everyone who might be walking by.. It was the show password button.

Note that arealabelby might be nice to use here

## Acceptance criteria
**All labels in translation file?**

### Main navigation
- [x] Search icon: Search
- [x] Tools menu icon: Tools menu
- [x] User avatar: User menu
- [x] Breadcrumb maybe use arealabelby? > Screen reader is currently reading the full filename of the avatar out loud...

### Global FABs (although I'm not sure they're actually accessible through tabbing)
- [x] Help icon: help
- [x] Arrow icon: move to the top of the page

### Dialogs
- [x] Close icon: Close
- [x] Share icon: Share
- [x] Settings icon: Settings

### Homepage
- [ ] ...

### Innovation Library
- [x] Search icon in search fields inside the blocks: Search
- [x] Expand icon on the blocks: Expand window

### Challenges page
- none

### Contributors page
- [x] Email button on user card: email

### Forum
- [x] Bin icon on discussion and comments: delete
- [x] emoji icon next to reply underneath comment: Add Emoji
- [x] Emoji icon in comment input field: Emoji
- [x] Mention icon in comment input field: Mention someone
- [x] Send icon in comment input field: Send
- [x] Question icon next to comment input field: Formatting help

### User + Organization profile
- [x] Email icon (header): Email
- [x] Settings icon (header): Settings
- [ ] Social icons

#### All
- [x] Share button top right: Share
- [x] Settings button top right: Settings
- [x] Expand button top right: Expand window

#### Collection of links
- [x] Plus button on Collection of links callout: Add
- [ ] Currently, the screen reader reads the url instead of the visible text

#### Call for posts/whiteboards
- [ ] Plus card on Call for posts/whiteboard: Add

#### Post / Comments
- [x] Bin icon on comments: delete
- [x] emoji icon next to reply underneath comment: Add Emoji
- [x] Emoji icon in comment input field: Emoji
- [x] Mention icon in comment input field: Mention someone
- [x] Send icon in comment input field: Send
- [x] Question icon next to comment input field: Formatting help

#### Menu
- [x] Share icon: Share
- [x] Settings icon: Settings

#### Dashboard
- [ ] Member icon: You're a member (or arealabelby tooltip?)
- [ ] Questionmark in space structure block: About this structure
- [x] Expand button in Events block: Expand window
- [x] Share button in Updates from the leads block: Share
- [x] Switch most recent/active in Contributions block: Switch view
- [x] Avatars in most recent Contributions bock: "Avatar of <full name>"
- [ ] About dialog: Share button: Share
- [ ] About dialog: Envelop icon on organization(/user?) cards: Email
- [ ] Info icon in Hosted by block: Information (or tooltip text if that is otherwise not reachable)

#### Community
- [x] Email icon on organization card in hosted by block: Email
- [x] Switch in who's involved block: Switch view
- [x] Search icon in search field in who's involved block: Search
- [x] Expand button in Who's involved block: Expand window

#### Challenges
- [x] Search icon in search field in All challenges block: Search

#### Knowledge base
- None

#### Menu
- [x] Share icon: Share
- [x] Settings icon: Settings

#### Dashboard
- [ ] Member icon: You're a member (or arealabelby tooltip?)
- [x] Expand button in Events block: Expand window
- [x] Share button in Updates from the leads block: Share
- [x] Switch most recent/active in Contributions block: Switch view 
- [x] About dialog: Share button: Share
- [ ] About dialog: Envelope on org cards in Leading block: Email
- [ ] About dialog: Envelope on user/org cards in Contributors block: Email

#### Contribute
- [x] Innovation flow settings icon: Innovation flow settings

#### Opportunities
- None

#### Menu
- [x] Share icon: Share
- [x] Settings icon: Settings

#### Dashboard
- [x] Expand button in Events block: Expand window
- [x] Share button in Updates from the leads block: Share
- [x] Switch most recent/active in Contributions block: Switch view 

#### Contribute
- [x] Innovation flow settings icon: Innovation flow settings

#### About
- [x] Innovation flow settings icon: Innovation flow settings
- [x] State button: Show the full innovation flow
- [x] Expand button on Description block: Expand Window
- [x] Expand button on Background block: Expand Window
- [x] Expand button on Impact block: Expand Window
- [x] Expand button on Who's involved block: Expand Window

## Additional
Timebox: 5 hours + 3 hours testing

**Comment by Comoque1** [comment]
Issues discovered while testing are listed in this post: https://alkem.io/building-alkemio-org/challenges/testingexperiment-3692/opportunities/testscenarios-8213/collaboration/testresults-7379/posts/test-labelsonall-4674

There are also to regressions, which are going to be addressed as separate bugs.
