### ISSUE TITLE
BUG: Social icons gone on user profile

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5076]
**Describe the bug**
The social icons were moved to no longer be part of the banner, but didn't get transferred to their new location inside the bio block.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9943bd415369e7c5de71b004c1973c8b9ce96e/image.png)

### Acceptance Criteria
- [ ] Add social icons (Github, X, LinkedIn) bottom right of the bio block
- [ ] Only show social icons for the fields that are filled in

Design:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--398612576c13ebeacf090030d67a9b6a5006a5c3/image.png)

**Comment by Comoque1** [comment]
Removed the bug squash at is requires enrichment of the component where it is stated it should belong.

**Comment by Comoque1** [comment]
Looks like on design
<img width="1583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnQ0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ea5cff156c370ac5e1491975f98587a0ba0e7d0/image.png" alt="image.png" />
