### ISSUE TITLE
Usability: Opportunity proposals vs new Opportuntiy

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5081]
When I go to Challenge Opportunities, I always click on Opportunity proposals when I actually want to create an Opportunity

**Comment by SimoneZaza** [comment]
@Comoque1 do you experience the same when there are opportunities already there? Or only when it looks like this:


![Image](https://github.com/alkem-io/client-web/assets/38861315/6309278d-9f1e-410f-958b-7c0540940c2c)

**Comment by Comoque1** [comment]
@SimoneZaza, no, but I am not a good example.

**Comment by SimoneZaza** [comment]
@Comoque1 I've created a new issue for this: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5115

**Comment by techsmyth** [comment]
Covered by another issue
