### ISSUE TITLE
Nav menu: link to landing takes to innovation hub subdomain

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5083]
If you're under an innovation hub, link to landing goes to `<subdomain>/landing`
thus capturing you inside innovation hub (if you click on [And there are many more...](https://acc-demo.alkem.io/home?from=landing) you go back to the innovation hub).

**Comment by SimoneZaza** [comment]
@techsmyth I think this can be closed since we don't have /landing anymore?

**Comment by techsmyth** [comment]
Agreed
