### ISSUE TITLE
BUG: User Profile throws an error for opportunityContritbutionDetails query

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5089]
**Describe the bug**
Going to another user's profile as normal user (just a member of a community) yields errors in `opportunityContributionDetails` query

**To Reproduce**

1. Go to ['Svetlio's profile'](https://acc.alkem.io/user/svetoslav-petkov-7551)
2. Open the GraphQL network tab
3. You see errors in `opportunityContributionDetails` query

**Expected behavior**
You should not see errors in `opportunityContributionDetails` query

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7090348/a47925ee-cb3d-4653-9fc4-963eed9b06ea)

**Comment by valentinyanakiev** [comment]
not reproducible any more
