### ISSUE TITLE
Control over release notifications

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5116]
## Description

As a product champion I want to be able to control when a new notification is shown

## Acceptance criteria

- [ ] Ability to control when a new release notification should be shown
- [ ] Release notifications are translatable
- [ ] User is able to check 'don't show again' box to not show this set of notes again
- [ ] Data is saved in the browsers local storage. 

## Additional Context
At the moment every release, even for a minor patch, is showing the release notification. This is very frustrating for users.

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise  we need to sort this one - we are again getting the same message shown again after a new release, even after the user has clicked it away. One idea is that we have a field "release-id" or something like that, and when that changes then the release notification is shown again. Thoughts? We could then control that id e.g. from the server?

**Comment by SimoneZaza** [comment]
@techsmyth sounds good. For me, it's important that people get the message of the last "big" release, even if there were several smaller releases without a message after it. And of course I agree that once you've clicked it away, a new release shouldn't trigger it when the message didn't change. Aside from this, I think it's also good if we have a way of showing the previous messages...

**Comment by techsmyth** [comment]
@valentinyanakiev @hero101 would be good to get ideas on how to do this. Maybe we simply have a bunch of release notification texts in the translation file, and each time we have a release where we want a new notification to be shown we add one. Then the client would need to be checking for a particular release identifier - and that would not be changing for each patch release so the click away would stay. @SimoneZaza we would then need some place to show the list of previous release notifications - where would that be?

**Comment by SimoneZaza** [comment]
@techsmyth I would prefer that list to be in the same dialog, but hidden until the user clicks on "Show previous notifications" or something like that. It would then also be nice to be able to open this dialog from the footer...
