### ISSUE TITLE
BUG: When I sign out the page turns white for a very long time

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5119]
**Describe the bug**
When I sign out, instead of showing the landing page, it turns white for a while (~1 min?). This has happened to me every time I sign out today (switching between accounts).
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2818a39800b4f7ef3c538d7279ef19845f2623e/image.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SimoneZaza** [comment]
Still happening today, it now took ~ 2 minutes

**Comment by SimoneZaza** [comment]
Still happening today

**Comment by SimoneZaza** [comment]
Deleting all cookies did the trick in the end, now this is not happening to me anymore. Maybe good to know that Stefan experienced the same issue, without having used another environment before.

**Comment by Comoque1** [comment]
The issue is not reproducible since split of the environments domains. 
It will be reopened in case someone hit it.
