### ISSUE TITLE
Change header of Spaces structure block on Space Dashboard

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5123]
## Description

As a new user or someone with a complete lack of sight, it is unclear to me what the list on the left side of the dashboard is about. Especially when there are not many items in there, or no Opportunities, it is not clear that this is actually an overview of the Space.

## Acceptance criteria

- [ ] Remove hub icon
- [ ] Change title to "Challenges and Opportunities in <Space Title>"

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
The Hub icon is still there, and @SimoneZaza could you please suggest, what t to with truncated text (of the Space title)?
Display the whole on hover or move it on a new row:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a533429ec85603b52665cc35ba5cf16718ea545/image.png)

**Comment by SimoneZaza** [comment]
@Comoque1 this is fine, the text shouldn't be wrapped over two lines. Showing the whole title on hover would be great!
