### ISSUE TITLE
BUG: sign in link is pointing to dev

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5124]
**Describe the bug**
On a local dev setup, the signin button is pointing to dev: (see bottom left in image)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30b611197d562174944391c191a9a37350be266d/image.png)

**To Reproduce**

1. Get develop on client + server
2. open up home page
3. click on the sign in link

**Expected behavior**
Sign in link to point to local signup page

NOTE: it looks like the client is picking up the wrong location / parameter from the server config?

**Comment by Comoque1** [comment]
Issue is resolved on local env.
<img width="338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1FhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82d9922300179ab7245d8b2f5755e5b9e4f6e707/image.png" alt="image.png" />
