### ISSUE TITLE
BUG: user avatars not visible in activity log

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5127]
**Describe the bug**
the user avatars do not show up on the community tab

**To Reproduce**

1. Go to https://alkem.io/mansi/community
2. See avatars, maybe cookies?

**Expected behavior**
avatars visible

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1mQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5286371ac773a50d0913453439749aa3d94a5a3/image.png)

**Comment by techsmyth** [comment]
@ccanos this looks to be a client issue as the data is coming back just fine in the query response
