### ISSUE TITLE
Innovation flow cards to include phases

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5146]
## Description

As a user scrolling through the innovation flows that I can choose for my Challenge, I want to know which steps are included in the flows right away, without having to click on a card first.
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmEwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31c59eb72d3bbe5f2773450ce77bd59c22d0c78d/image.png)

## Acceptance criteria

Update innovation flow card as per design
- [ ] Icon, title, creator
- [ ] Description truncated to 3 lines
- [ ] states separated by  ·  , truncated to 2 lines
- [ ] tags

Locations of the card:
- [x] Space library (Space templates in Space settings)
- [x] Library dialog when selecting innovation flow from Challenge/Opp creation or Ch/Opp Settings > Innovation flow
- [ ] Platform library
- [ ] Innovation pack profile pages

Other: (note from Andrew)
- [ ] Implementation wise: Flow states field is mandatory

## Additional Context

Figma link: https://www.figma.com/file/mNLjbQJ765mpce4wPZTzPo/Innovation-flow-card?type=design&node-id=0%3A1&mode=design&t=ps8KbHn35Z4nAbQR-1

**Comment by Comoque1** [comment]
The cards equal as per following groups:
1. Library dialog when selecting innovation flow from Challenge/Opp creation or Ch/Opp Settings > Innovation flow and Platform library - **don't have the creator**
2. Space library (Space templates in Space settings) and Innovation pack profile pages - **have an footer not defined in AC**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU4xQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e932a76cc4ac3898b6a8031345719ed9507ab5d/image.png" alt="image.png" />

@SimoneZaza , is this expected or they must be equal on all locations as per AC?
