### ISSUE TITLE
BUG: release notification is shown **every** time I go to home

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5153]
**Describe the bug**
The release notification is shown every time I go to home, despite clicking it away

**To Reproduce**

1. Go to https://alkem.io/home

**Expected behavior**
If the release is clicked away then it is not shown again. If not easy to do then again disable this functionality to show the release notification.

**Comment by valentinyanakiev** [comment]
@techsmyth I have tried on Chrome, Firefox and Chromium and can not reproduce this. Are you sure you are not in different context or incognito?
