### ISSUE TITLE
BUG: Loading Collaboration on spaceProvider Query throws an Authorization Error for Anonymous

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#5158]
**Describe the bug**

**To Reproduce**

1. Log of https://acc.alkem.io if you are logged in
2. Navigate to https://acc.alkem.io/release-01-03-2023-hub2/dashboard
3. `SpaceProvider` query throws an error - `"User () does not have credentials that grant 'read' access to Space.collaboration"`

**Expected behavior**
No error is thrown.

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWE3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5077b258ff2c99fdcfe942e6e6d05a47f605c2d/image.png)

**Comment by Comoque1** [comment]
Reopening, because authenticated user hit this error when navigate to private space:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM20rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7522a56640143d80bdced40f6aeabacfcb4a3eb/image.png)
