### ISSUE TITLE
BUG: Deleting a callout with whiteboard takes >15sec

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5160]
**Describe the bug**
When I delete a whiteboardRT callout, it takes 15.9sec without any feedback that it's actually doing something. I checked, other callouts are deleted fast, but also call for whiteboards callouts with a whiteboard inside are slow. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXk3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ce03992776e610144c4a5c54c66b1b261902aeb/image.png)

**To Reproduce**

1. Go to https://alkem.io/building-alkemio-org/challenges/testingexperiment-3692/contribute
2. Create a RT whiteboard
3. Delete it

**Expected behavior**
It to be fast, and if it can't be fast, to give some sort of feedback (spinner?) to show that it's in progress

**Comment by valentinyanakiev** [comment]
<img width="1832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNklTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fc4014e43ba4f20f2cd4c175a1fde7a3c8d9cf9/image.png" alt="image.png" />
No longer relevant, tested the exact flow and it took me 1 second
