### ISSUE TITLE
BUG: When open callout from templates - error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5161]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:3000/111/dashboard
2. Start the process of callout creation
3. Select the option to choose a template
4. Pick a template - error is thrown: `"message": "No Callout found with the given id: 0972c63d-8d3d-411b-95d4-0dee8c259fad",`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMys4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c155030b84a22dda0435fe127b014d23cde7586a/image.png)

**Expected behavior**
No error is thrown.

**Additional context**
The error is thrown, but the template is open, so the issue is not critical for the moment.

**Comment by alstojanovic** [comment]
I think it is important to say that this happens with callout templates of type PostCollection.
