### ISSUE TITLE
BUG: Lists appear differently

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5174]
**Describe the bug**
In the authorization settings, the list is displayed differently per Challenge. This can be confusing.

**To Reproduce**

1. Go to any Challenge
2. Check authorization
3. Go to another Challenge
4. Check authorization
5. See differences

**Expected behavior**
similar lists 

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2UrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96ea95850dec42f385158e2f3bbbe488f433d58a/image.png)

**Comment by SimoneZaza** [comment]
should be fixed when moving to subspaces, the settings pages are completely updated
