### ISSUE TITLE
BUG: look up of invalid challenges / opportunities

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5181]
**Describe the bug**
Server logs are showing a lot of failed retrievals of challenges + opportunities by nameID: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0hEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6aa6667a2d3d585d17fc8cd14c8f3b56ba59ebc/image.png)

**To Reproduce**

1. Review server error logs

**Expected behavior**
There should not be structural errors happening. 
The source of these errors needs to be investigated. It could be the client has a bug where by it is sending in a nameID instead of a UUID - this can be easiest avoided by using challenge / opportunity lookup by UUID in most places. 

Other ideas?

**Comment by alstojanovic** [comment]
We are still passing challenge/opportunity nameID for a certain number of queries that use Challenge and Opportunity resolved fields under Space entity.
The server code is handling it correctly inside `getChallengeInNameableScopeOrFail` function.
After looking at the logs in kibana, the challenge nameIDs that are mentioned in the errors are not existing anymore.

**Comment by techsmyth** [comment]
Maybe we should also extend the server log messages to include more info eg space nameid, user id etc?

**Comment by alstojanovic** [comment]
The nameIDs are not existing because the challenge/opportunity was deleted.
Someone is trying to access a deleted challenge/opportunity through a saved url and then the server cannot find that journey. This is not clear from the server logs but we have these same errors on the client and there we can see the url that the user is accessing (we can also know the space etc.).
Another curiosity is that the server errors and the client don't match so it might be that someone is trying to query data directly through graphql.

We cannot remove the use of nameIDs completely. We could remove them when we add nameID to ID mapping but it would not be easy. The mapper query would need to run before opening any url because our urls use nameIDs and page components use those nameIDs to query for data.

**Comment by hero101** [comment]
@techsmyth What @alstojanovic means is that those journeys were deleted.
We have also look in the client logs - there are a lot of instances trying to access the three journeys. 
> Maybe we should also extend the server log messages to include more info eg space nameid, user id etc?

We already have the information you are refering to (if available, see below).
IMO some server logs shows instances where someone is trying to query the information through the API without using the client.

I don't believe there is more we can do here. The client is clearly trying to access deleted entities - they might be bookmarked OR a bot is doing all there strange requests.


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b12f81e89884a095f8dea2379292f3415e0b2844/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c7e9124b8fd2681ec5ce083dc0205f4aab9c36c/image.png)

**Comment by techsmyth** [comment]
@hero101 @alstojanovic thanls for the analysis - I understand the situation I think now. I would be keen to know any context then about the request eg if user doing it is logged in or not, if so then would like the user id; if not then nice to get the ip?   Tw, which space are these journeys in?

**Comment by alstojanovic** [comment]
We have all that info in the client logs (apm-errors).

**Comment by alstojanovic** [comment]
@techsmyth 
List of client errors for "Unable to find challenge": [kibana url](https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-120d,to:now))&_a=(columns:!('@timestamp',message,url.full),filters:!(),grid:(columns:(message:(width:458))),index:f46e21bb-e115-4266-8541-3d5729dfee63,interval:auto,query:(language:kuery,query:'%22Unable%20to%20find%20challenge%22'),rowsPerPage:500,sort:!(!('@timestamp',desc))))
List of client errors for "Unable to find opportunity:" [kibana url](https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-120d,to:now))&_a=(columns:!('@timestamp',message,url.full),filters:!(),grid:(columns:(message:(width:458))),index:f46e21bb-e115-4266-8541-3d5729dfee63,interval:auto,query:(language:kuery,query:'%22Unable%20to%20find%20opportunity%22'),rowsPerPage:500,sort:!(!('@timestamp',desc))))
All errors are within Digicampus space.
