### ISSUE TITLE
BUG: unable to publish collection of links from template

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5213]
**Describe the bug**
When trying to publish a collection of links callout that was opened as a template from the space library, it fails. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1RmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a2a2e9b1fa8763050faf4dd4c0808a685481a01/image.png)

**To Reproduce**

1. Save collection of links callout (with a link inside) as a template
2. Add it somewhere in a Challenge
3. Click "Publish"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alstojanovic** [comment]
Cannot reproduce locally nor on dev env. It would be good to have more context, which space, challenge and template.

**Comment by SimoneZaza** [comment]
Me neither.. This happened in the /visimp space, but I now tried again in the building the a-team space and couldn't reproduce it. @Comoque1 I suggest closing this?
