### ISSUE TITLE
BUG: Bold / Italic not applied

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5233]
**Describe the bug**
bold or italic not applied when you select a word as well as the space after the word

**To Reproduce**

1. Create a post in a call for post 
2. Select a word to make bold or italic (notice that it also highlights the space after the word, or at least on my laptop)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUx2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3a0c89fd0e18c2df2ca82b8ccb02788cd34058f/image.png)

3. Click on make bold/italic icon 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVB2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e086b21c5f4250141f311301fab871da0a01c8c2/image.png)

4. click on create/save
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVh2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89a988e214ee7720bb290b053d472a7113765c4a/image.png)

4. See the asterixis appear instead of bold text

**Expected behavior**

also if the space is selected, the styling should be applied

**Screenshots**

**Comment by Comoque1** [comment]
Not reproducible anymore. Tested on DEV env on post of post for callout.
<img width="1849" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb69e920e567d245baf4b74cbd4cdaa85a669667/image.png" alt="image.png" />
