### ISSUE TITLE
Notification when closing callout before publishing

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5244]
## Description

When I .....
- Create a new callout and add a description or a whiteboard
- I close the create dialog, either because I want to cancel it or by accident
- There is no notification to remind me 'are you sure because you have amazing content in there possibly'. 

Especially when you create a whiteboard with a lot of content and click save, users forget that the whiteboard was saved but the callout was not published > whiteboard is also not published. 

## Acceptance criteria

- [ ] If there is content in a callout (title, whiteboard, description, tags) and you close the callout before publishing, show a dialog stating: "Are you sure you want to close this [collaboration tool type]? Unsaved changes will be lost."
- [ ] Buttons:
- CANCEL
- YES, CLOSE

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by larssondenise** [comment]
@techsmyth sure that this one can't be included? Had conversations with several users who lost their work...

**Comment by techsmyth** [comment]
@larssondenise ok, understood - @alstojanovic can you please try to look at this one near term?

**Comment by alstojanovic** [comment]
Sure, we can add a dialog like the one on publish. @SimoneZaza can we just confirm the text and the text in the buttons. Do we want a cancel button (as in cancel the close, I want to continue working on this) and something like discard or close to confirm the closing?

**Comment by Comoque1** [comment]
@larssondenise @SimoneZaza , the notification is not triggered when:
1. Whiteboard RT: only whiteboard or whiteboard template is added to the callout 
2. Call for Posts: only default description or default description template is defined

For the rest of the callout types notification is triggered on each changed field.
If you accept it like this, we can close it, but I think the main reason is not resolved.

**Comment by larssondenise** [comment]
@Comoque1 thanks for checking! I think indeed it is important that it is triggered when there is whiteboard content, such as a template. Because the user clicks on save after adding the whiteboard (assuming it is saved).
