### ISSUE TITLE
Chat mode interaction on guidance

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5258]
## Description

As a user I want my answers to take into account the conversation

## Acceptance criteria

- [ ] Allow users to clear their chat which resets it
UI: see figma file: 
- [ ] UI: 3 dots icon next to input field, acc label: "Options"
- [ ] Clicking on the icon opens a tiny menu with for now: 
- Clear conversation
- Close window

## Additional Context
**Please note: Estimate is just about clearing the conversation from the client (+ UI)**
Messages need to be deleted one by one, this may not be very straightforward

https://www.figma.com/file/olkYnTAZwWzmwJGjni8RHt/Helpcenter---clear-chat-history?type=design&node-id=0%3A1&mode=design&t=sEWCqjP3eMc7Juin-1

**Comment by techsmyth** [comment]
@SimoneZaza we talked about this a bit back but I think we still nee to action it?

**Comment by ccanos** [comment]
@ccano resetChatGuidance
