### ISSUE TITLE
BUG: Support link in footer not pointing to the correct place

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5265]
**Describe the bug**
As a user, when I click on Support, I probably really need help.. It is then quite frustrating to see the following page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ef1aba6572f97b10fe3cdbbdbf77682d1c805a/image.png)

**To Reproduce**

1. Go to https://alkem.io
3. Scroll down to the footer
4. Click on Support

**Expected behavior**
This page to be https://welcome.alkem.io/help/

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hero101** [comment]
Please verify that this is till the case.

**Comment by SimoneZaza** [comment]
👍 seems fixed!
