### ISSUE TITLE
Alkemio logo in the footer of the platform to link to meaningful place

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5266]
## Description

As a user clicking on the logo in the footer, this is what I currently see: https://alkem.io/about
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17e0ea8f48a28a57a79374b88826eff0003727a9/image.png)

https://www.figma.com/design/DTLiV3nOwWyYMNiDAq3rV5/Alkem.io%2Fabout?node-id=1-87&t=mUe4PcrAmRJNC13w-1
## Acceptance criteria

- [ ] Add the version number to the support dialog.
- [ ] Clicking on logo brings user to the welcome site

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by jeroentskui** [comment]
oh wow yeah; okay; lets design something lovely for this :)

**Comment by SimoneZaza** [comment]
@jeroentskui thanks for your comment, you're absolutely right about this empty page. I discussed it with Neil, and we'll add the version number to the support dialog. Can you make a quick sketch for this? Adding it to the footer is a bit too heavy, especially since we're talking about two sets with a couple of digits.
