### ISSUE TITLE
BUG: My Memberships footer message is wrong

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5275]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox-alkem.io/home
2. Open "My Memberships" dialog - on the bottom of the dialog there is a message stating that the user cna explore all Spaces, but he is actually redirected to `*/challenges` page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da49a55539a681620f1b27844aacf96ffd7cd0ca/image.png)

**Expected behavior**
TBD

**Comment by SimoneZaza** [comment]
@Comoque1 good point. We were going to change the Challenges page into a Spaces page, but this isn't getting much priority at the moment. I will think of a better text for now

**Comment by hero101** [comment]
@SimoneZaza what needs to be done in order for this to be closed?

**Comment by SimoneZaza** [comment]
@hero101 nothing :) I will close it now.
