### ISSUE TITLE
Better explation for readonly Whiteboard RT

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#5279]
## Description

As a user of the Whiteboard
I want a clear sign that I can't edit the Whiteboard and why
So that I have better awareness

## Acceptance criteria

- [ ] User is presented with an explation why the Whiteboard is in read only mode
- [ ] The explanation to consist of what, why and how (e.g 'you can only read but not interact')

## Additional Context
Currently the only sign that the user can only read the content and observe changes other users do, is a small message in the far corner of the Whiteboard (see screenshot below).

**We need a better explanation of the situation, why and how, and to be in an obvious, visible place.**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEFnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c854ceaea2787776a4f4d5613e536bcae6407f6f/image.png)

**Comment by hero101** [comment]
@SimoneZaza @larssondenise @techsmyth please raise this on the next product discussion concerning Whiteboards

**Comment by techsmyth** [comment]
@hero101 is this not covered by #5026

**Comment by hero101** [comment]
Closing in favor of #5026
