### ISSUE TITLE
No lead org: do not show

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5296]
## Description

<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK00zQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30d5327244c0b9493f4a9ffcb2c50d57b4136c2d/image.png" alt="image.png" />

As a user, I don't want to see "no leading organizations available" when there is no lead org.. 

## Acceptance criteria

- [ ] When there are no leading organizations, don't show these two sentences (title + note) in the about dialog
- [ ] For Challenges + Opportunities

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
The same about dialog is used for Space. The change will reflect there also if no Leading organizations are available.
<img width="849" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODk0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ac3e46d16c9aa37fb265e7972590b1ff4131e51/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
👍
