### ISSUE TITLE
BUG: "Powered by" link in the menu pointing to wrong link

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#5308]
**Describe the bug**
The "powered by alkemio" in the menu options (see screenshot) is pointing to [https:alkem.io/landing](https:alkem.io/landing)

**To Reproduce**

1. Go to [https://alkem.io](https://alkem.io)
2. Hover/Click on the menu button next to the user profile OR inside a journey, click on the "powered by" at the banner right corner
3. Click on "powered by"
4. The link is incorrect

**Expected behavior**
The link is pointing to https://welcome.alkem.io/ instead of https://alkem.io/landing

**Screenshots**
<img width="430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e841bb70f1fbd8bd87f2250639d41e9757cf4b33/image.png" alt="image.png" />

<img width="391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGRMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13df808bede5d3a60f7973ad600ba0fc17c5a010/image.png" alt="image.png" />

**Comment by hero101** [comment]
@SimoneZaza @techsmyth Is this assumption correct? Please provide the correct link.

**Comment by SimoneZaza** [comment]
@hero101 yes, correct, should point to welcome.alkem.io

**Comment by SimoneZaza** [comment]
@techsmyth @valentinyanakiev this one is pretty bad, commenting here to bring it to your attention :)

**Comment by techsmyth** [comment]
Agreed this needs to be addressed. Note that #5352 will make it less of an issue, but that should not be relied upon. Have tagged with the current sprints...
