### ISSUE TITLE
BUG: Latest contributions query is querying to much data on a single request

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5330]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/home with beta tester
2. Check `LatestContributions` query - it query 200 records, which is big load for the server
<img width="1637" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f59342dcf034acd5250aab5d55124d481f5c2b6/image.png" alt="image.png" />

**Expected behavior**
Limit the number of returned results to:??

**Comment by hero101** [comment]
This is expected due to https://github.com/alkem-io/server/issues/3514
