### ISSUE TITLE
BUG: When there is private challenge in a space, space members get error on MyMemberships query on My Dashboard page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5331]
**Describe the bug**

**To Reproduce**

1. Go to a Space with private challenge with user that is member only of the space
2. Go to "My dashboard" page of the member (must be beta tester) - MyMemberships query fails
<img width="1516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1be55c58f89e3748c93325c57a1852244a562353/image.png" alt="image.png" />
<img width="1683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4979363fabd72387425b088170ba7d9416bc5eb4/image.png" alt="image.png" />

**Expected behavior**
MyMemberships query on My Dashboard page doesn't fail

**Additional context**
This issue impacts the data displayed on MyDashboard page on multiple blocks

**Comment by Comoque1** [comment]
@techsmyth do you think we can make these 2 fields accessible to users that are member of space to challenge and opportunity community : ` myMembershipStatus` and  `myRoles`?

**Comment by techsmyth** [comment]
Yes that is the right solution, I will put up a PR near term -  need to look at what implications this has.

**Comment by techsmyth** [comment]
@Comoque1 I presume the title should read "where there is a private challenge in a space" :)

I have removed a field decorator that was checking READ privilege for community field on Community - which was a minor bug. 

However looking at the queries above, I think they are fundamentally wrong. If a Challenge is private, the Opportunities inside that Challenge **must not** be visible to space members if they do not have READ privilege on the Challenge. So there is I think a design error in how the client is using the queries - maybe needs a discussion...

**Comment by Comoque1** [comment]
@techsmyth Updated the title of the bug. 
The error is not hit on my dashboard anymore,
Regarding the opportunity issue, you are right we need a discussion.
