### ISSUE TITLE
Whiteboard RT to show (callout) title

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5340]
## Description

As a user I want to know in what whiteboard I am working.

## Acceptance criteria
**for the whiteboards that are part of the callout framing, so not for call for whiteboards-whiteboards:**
- [ ] Add title of the callout to the top left of the whiteboard
- [ ] remove the text "Whiteboard"

## Additional Context

<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aa1577c9af64b40b491550d412efc76fe20f735/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Looks much better:
<img width="1681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWw1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a98e74cdeeecfa5828d00cbfe162fd518cb34a0/image.png" alt="image.png" />
