### ISSUE TITLE
Redirect from landing to welcome site

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5352]
## Description

As a user with bookmarks for Alkemio I want those links to work

## Acceptance criteria

- [ ] If the client gets a request for "/landing" it should redirect to the configured welcome site

## Additional Context
We are getting incoming requests for alkem.io/landing - which are triggering server errors, and that mean the user does not go to the right page.

**Comment by valentinyanakiev** [comment]
@techsmyth I think this is not for the client - @renehonig can you please set up a netlify redirect for this?

**Comment by techsmyth** [comment]
@valentinyanakiev agreed not for the client. But Netlify cannot do this, as it is a path that needs redirecting. So needs to be done in Traefik?

**Comment by techsmyth** [comment]
To be clear, it is requests to https://alkem.io/landing should now go to https://welcome.alkem.io
