### ISSUE TITLE
BUG: MD list larger font when words are made bold/link

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5361]
**Describe the bug**
A list in markdown nowadays looks nice and the font size is consistent with the other text. However, when some words are made bold (edit: or hyperlinked), the entire list gets a larger font size then the rest of the text. See these screenshots below:
<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa70e77e5b20e54ba3aefc143ee79bac078742e7/image.png" alt="image.png" />

<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b151de6d7fca5e9473f50bec776d0c59e4ca003/image.png" alt="image.png" />

<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43a7b74ecc665efd2ff7b640f064b68b59bb9edf/image.png" alt="image.png" />

<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c47cc51eb0c9e80248f3ae7d6fff926db48d864d/image.png" alt="image.png" />

**To Reproduce**

1. Make a list in a MD editor
2. save
3. looks good
4. edit
5. make some words in the list bold
6. save
7. looks weird

**Expected behavior**
Font size to remain the same

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
Seems to be working fine
<img width="1178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9707727cb354cfa9ebb77db28fbbb5ae511b4f08/image.png" alt="image.png" />
