### ISSUE TITLE
Refactor PendingMembershipsUser

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#5371]
## Description

As an Alkemio User
I would like to have a responsive application
so that I can work on my flows efficiently

## Acceptance criteria

- [ ] `PendingMembershipsUser` on `myDashboard` uses `user` with single ID and not `users` with an array of IDs with one item

## Additional Context

For me, the same query with user instead of users was 4x faster.

**NB: It could be a different query needed here, if it is reaused in a different way (with more than one id) in other places!**

**Comment by alstojanovic** [comment]
PendingMembershipsUser is retrieving user data for a specific user. The query accepts a single userId as a variable so it doesn't make sense to use users query in the first place. This was probably missed in a code refactor.
This query should use the `user` query instead of `users`.
```
query PendingMembershipsUser($userId: UUID!) {
  users(IDs: [$userId]) {
    id
    profile {
      id
      displayName
    }
  }
}
```
