### ISSUE TITLE
Hide Blank Whiteboard from innovation library

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5375]
## Description

As a user scrolling through the content of the innovation library, I don't like to see a "Blank Whiteboard"

## Acceptance criteria

- [ ] Assuming that we still use the blank template for when there is no other template selected, hide it from the library
- [ ] …

## Additional Context
<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9212ce3c803144e658ba5f78ae74665b1fa62932/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
Should we maybe delete it completely from the library?

**Comment by SimoneZaza** [comment]
@alstojanovic if we don't need it to keep the ability to have a blank whiteboard (and to be able to "reset" it to a blank whiteboard when a user is creating the whiteboard callout): yes please! :)

**Comment by alstojanovic** [comment]
@SimoneZaza  I checked, we are using the empty whiteboard value that we have as a constant in our code for reseting to empty whiteboard.

**Comment by SimoneZaza** [comment]
@alstojanovic thanks and sorry for the confusion, I will then just delete it :)
