### ISSUE TITLE
BUG: When user open WhiteboardRT after a visual is uploaded, it doesn't load for him

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5387]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/building-alkemio-org/challenges/testingexperiment-3692/contribute
2. While on contribute page don't open the a Whtiboard RT
3. Using another user add a visual to a whiteboard
4. Open with the first user the whiteboard - the visual is not loaded
<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f063c3a5553d10c7e012c881fd36e83ba58c1b20/image.png" alt="image.png" />

**Expected behavior**
Visuals are loaded, no matter if the user has the whiteboard open or is openning it after visuals are added to it.

**Comment by hero101** [comment]
We have agreed on a socket-server-socket interaction shown below.

<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de2d50896cfdc872b311030d46294541976f7c13/image.png" alt="image.png" />

1. A socket(client) sends a request message to the server to request files from other sockets(clients)

2. Sockets(clients) respond with files

3. Server relays the response from (2) to the other sockets(clients)

4. Client handles the response message if needed
