### ISSUE TITLE
BUG: User details (name/location) not showing in message dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5417]
**Describe the bug**
In the message dialog that opens when you click on the envelope icon on a user card in the search dialog, the user name + location aren't visible. 

<img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlBtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d55c11034ef54f55452a019849083335ac9e039/image.png" alt="image.png" />

**To Reproduce**

1. Search for a contributor on the platform
2. Click on the envelop icon on the user card in the search dialog

**Expected behavior**
Same info to show as in other message dialogs

**Comment by Comoque1** [comment]
When the location data is available, it is displayed, yet.
<img width="1095" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0VaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--825c6c2516b1798ba3c076c197d192c06859c6d4/image.png" alt="image.png" />
