### ISSUE TITLE
BUG: fixed menu bar in all places

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5418]
**Describe the bug**
We fixed the menu bar in callouts and when adding contributions to avoid people missing the save button. But when you edit a contribution this bar is not fixed.

**To Reproduce**

1. Go to a Call for post
2. Click on one of the posts and edit
3. See the bottom menu bar is not fixed

**Expected behavior**
Fixed menu bar at the bottom

**Screenshots**
EDIT DIALOG POST IN CALL FOR POST
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2JtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dafc8a6445c9aa3db0b7b7e63f186005f6fa5a4b/msedge_HDx6ZHQtkb.png" alt="msedge_HDx6ZHQtkb.png" />

ADDING BANNER IMAGE DIALOG
<img width="1134" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1RuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbdff73c77752f6ba8bc031bb90b313394cdda3b/image.png" alt="image.png" />

How it should be:
<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ptQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62cf5ffb9eca08aaa1c20f284afc5fe8577ed29c/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
This is part of #4266, which is now in progress

**Comment by Comoque1** [comment]
This exact issue is addressed. There is some more feedback, that needs to be addressed.
