### ISSUE TITLE
Add event directly from Journey Dashboard

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5420]
## Description

As a user I want to be able to add an event directly from the dashboard, without having to open the events dialog first

## Acceptance criteria

- [ ] Plus button (40*40, neutral color) visible for people with the right credentials in the events block on the dashboard
- [ ] (& keep the current add button in the dialog)

## Additional Context
<img width="822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1efbb38f9a180549e36c0a407291724d273acf41/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Closing, as events can now be created on space level from events block.
