### ISSUE TITLE
BUG: Interaction new contribution block: user doesn't stay in journey after closing

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5443]
**Describe the bug**
When clicking on a contribution in the contribution log on My Dashboard, the user goes to the specific content, which is usually a dialog. After closing this dialog, the user should stay in that specific context (journey or post), but is now brought back to the My Dashboard.
In case of a call for posts, when the user is directed to a post and the post gets closed, the user goes back to the journey dashboard instead of the underlying post.

**Expected behavior**
Construct the parent URL/callout location through the callout tagset

**Andrew:** we trigger the "Back" action if it's available, but we should check if it is the right URL. We should only go back if the previous url is the same as the parent url

**Comment by SimoneZaza** [comment]
Testing this issue is very time consuming

**Comment by Comoque1** [comment]
The fix makes the behavior much better, but there are 2 more cases that need improvement on Contribution page:
1. User clicks on post of call for posts (the callout is positioned in NOT active tab of lifecycle) - User is redirected to the active tab, and after closing the dialog, cannot see the callout
<img width="1928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b4a356b040bf36fc5d7e95ac48c465ed3139b0e/image.png" alt="image.png" />

2. User selects a callout from list of callouts, that is not part of the active tab in lifecycle - after closing the callout dialog - user remains on active tab and cannot see the callout


@SimoneZaza if you accept the above behavior, we can close the bug. In my opinion, these should be resolved.
