### ISSUE TITLE
Reconnect on dropped WT session due to network issue

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#5444]
## Description

As a user
I want to reconnect to the whiteboard when I was disconnected
So that I can still work without interruptions if I am able to

## Acceptance criteria
- [ ] Window popup states that trying to reconnect, with 3 tries 5,10, 20 seconds apart + then closes window 
- [ ] Add button to allow reconnecting manually

**Comment by techsmyth** [comment]
@hero101 this is a good one to do, but I think the logic of when + how to reconnect needs a bit of discussion e.g. if mouse moves on the page then I should e reconnected - maybe with a back off retry length approach...
