### ISSUE TITLE
BUG: List of journeys sorted incorrectly?

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5449]
**Describe the bug**
The list of journeys at the top of my Dashboard should be sorted on my most recent activity, but I think they're actually not. 
See for example the screenshot below. My latest contribution was in the Testing & Experimenting Challenge in Building the A-team, but that Challenge is not listed above:

<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--194f40489feaed7c8808ef197e5f4739d15bce36/image.png" alt="image.png" />

**To Reproduce**

I'm not sure..

**Expected behavior**
The Journeys that are displayed are the ones I was most recent active in.

**Comment by Comoque1** [comment]
The issue is still reproducible. Seems, that only newly added Journeys are sorted.
