### ISSUE TITLE
BUG: When Visual or Object is double clicked on WB and pasted, the whole WB json is pasted

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5454]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/space-23-01-24-release/collaboration/11111-8218
2. Double click on a Visual
3. Press "Ctrl+C" combination
4. Press "Ctrl+V" - the WB freezes and notification "Connection lost" is displayed

**Expected behavior**
TBD

**Additional context**
When Visual or Object is double clicked on WB and pasted, the whole WB json is pasted

**Comment by ccanos** [comment]
fixed along with the UI refinements, please @Comoque1 take a look. call me if you need help trying to reproduce

**Comment by Comoque1** [comment]
Not reproducible.
