### ISSUE TITLE
BUG: Activities are not displayed on My Dashboard page logs 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5465]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Publish any callout on a challenge - it is not displayed on My Dashboard page logs 
<img width="1616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48c39dcb6d3b8ada09ec9310d84838e1a69cd931/image.png" alt="image.png" />

**Expected behavior**
When User publish callout, no matter if "notifications" (on Publish dialog) are on or off, activities are displayed on parent journey activity logs, on the journey itself activity logs, and on My Dashboard page logs.

**Comment by hero101** [comment]
Must be fixed with https://github.com/alkem-io/server/pull/3563

**Comment by Comoque1** [comment]
Not reproducible anymore.
