### ISSUE TITLE
BUG: Pending memberships dialog not showing journey cards/avatars

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5485]
**Describe the bug**
In the pending memberships dialog, the images aren't visible on the Journey cards and avatars

<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0c82bedddad946f84d4a5de435c693b0aa1cbe6/image.png" alt="image.png" />

**To Reproduce**

1. Make sure you have some invitations and applications
2. Open the Pending Memberships dialog
3. See error

**Expected behavior**
Images to be shown

**Comment by Comoque1** [comment]
The issue is still reproducible for invitations:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--add4e87549d16ae453a099b46c66a307f1fffe1a/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Avatars are now visible
<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c6a547da4eba3c036bd75fde828db692f06b12a/image.png" alt="image.png" />
