### ISSUE TITLE
Remove icon + label on tree navigation block on Space Dashboard

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5495]
## Description

As a user, I only want to see relevant text. Through the visual representation, I understand that the list in the Space navigation block shows the things that are inside this space. Therefore, the hub icon and the text "Challenges and Opportunities in" should be removed, thus only showing the Space title here.

<img width="515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2951d0d95466d534c2994290ba6e5d973020e133/image.png" alt="image.png" />

## Acceptance criteria
For the title of the navigation block:
- [ ] Remove hub icon
- [ ] Remove "Challenges and Opportunities in"
- [ ] (thus only show space title)
For the avatars:
- [ ] Remove blurry, colored filter
- [ ] Remove icon
- [ ] (thus only showing avatar)
## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
@me-andre , can we move the icon on title level for mobile
<img width="1149" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2078d507779bd3b78ca81f80d6d6049e30976842/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Comment is addressed.
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f56c517b284496676fbf60a47d3a08cab845c76e/image.png" alt="image.png" />
