### ISSUE TITLE
When callout is positioned on left column and title is longer, the component buttons overlap the title

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5508]
**Describe the bug**

**To Reproduce**
1. Go to https://dev-alkem.io/my-latest/challenges/111-7383/opportunities
<img width="1169" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGt5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c40ea7df480d909ddadb3fdff25fad7ec9cb8f62/image.png" alt="image.png" />

**Expected behavior**
Title and buttons don't overlap

**Comment by SimoneZaza** [comment]
No longer relevant
