### ISSUE TITLE
Visibility Sign up button on Sign in page

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5520]
## Description

As a new user visiting the sign IN page (instead of sign up), I start the wrong flow because I don't notice the sign up button at the bottom (especially on smaller screens)

<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODAvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--319f8221cced705a604a123aa8d78797ec1d608a/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Move "Don't have an account yet" sentence to be directly under the title (Sign in to Alkemio)
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Looks as per AC:
<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4db8c598895c574a2a92ea0a75bfd815fe3f8d6/image.png" alt="image.png" />
