### ISSUE TITLE
Hiding Events block when there are no events

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5522]
## Description

As a user, I get confused by empty blocks. As an admin, I want my space to only hold relevant blocks.

## Acceptance criteria

- [ ] When there are no events, only show this block to admins and leads
- [ ] Change text in list view when there are no events to be: 
 
Since there are no events, this block is **only visible for admins and leads** (so users with `CREATE` privilege for those events, we should **NOT** use roles to determine what is visible / not visible, just privileges). Once an event is added, the calendar will be visible for all users.

Font: Caption, neutral light

## Requested by
Denise

**Comment by Comoque1** [comment]
On Challenge and Opportunity "Events" block is not visible to admins, when there are no events.
<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ecb746a8197426a2769f3747c12ba92a66ba7c3/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
On Challenge and Opportunity "Events" block is not visible to admins, when there are no events.
<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ecb746a8197426a2769f3747c12ba92a66ba7c3/image.png" alt="image.png" />
