### ISSUE TITLE
BUG: tagging someone in a draft does not trigger notification

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5557]
## Description:
when I tag someone in a draft callout, there is no notification triggered. Sometimes it is a way for admins to communicate with each other, without the members seeing it. So when I tag another admin, I want to trigger the notification.

## Steps to Reproduce:
- Callout in draft modus
- Tag someone

## Expected behavior (optional):
Notification email send

## Additional context
Not entirely sure if this really is a bug, or that it was never defined as expected behavior..
This should be a server thing

**Comment by alstojanovic** [comment]
@SimoneZaza Where do we mention the user, in the post callout's comment? That is I think the only place on callouts where we have mentions.
It is doable. If it is an unpublished callout and has mentions in the comment, we can filter the mentioned users by their role. In this case the role would be Admin but we can also add Lead users.

**Comment by SimoneZaza** [comment]
@alstojanovic Thanks for looking into this. This issue is indeed about the comments to callouts that are in draft state. Since there is no visual feedback that the notification is not triggered, all notifications should be triggered to anyone, including members that are thus not able to see the callout and comment. This is a responsibility of the admin/lead who is mentioning the person... So, to conclude, I don't think you'll need filtering for this :)

**Comment by alstojanovic** [comment]
It was easier to add the fix than to write this comment. I opened a PR but I haven't tested it. It was a server side change.
