### ISSUE TITLE
Linkedin display of Alkemio links

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5583]
## Description

As a user sharing Alkemio links on LinkedIn I want that Alkemio shows up well
As a communications lead I want Alkemio to display well on LinkedIn

## Acceptance criteria
Needs to be a server side middleware application
Testing: "show source" when requesting a link

- [ ] Client to add image as per feedback from https://www.linkedin.com/post-inspector/inspect/https:%2F%2Falkem.io%2Fhome
- [ ] Start with 1 image for all links
- [ ] Add other og-tags as well (title, description)
- Later: tags/image dependent on the URL (journey specific)

## Additional Context

<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE51QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec02887ea1fbf02f26f28c9acba15fdb4d73c512/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@me-andre this can be the same of all links, so is this not the case of just adding a single static line into the "index.html" file?

**Comment by bobbykolev** [comment]
@techsmyth, yes we can set og static tags so every page from the platform has a defult og:img.
If we want dynamic metadata (idealy) we should render serverside (huge effort). 

Additionally, we can add [Helmet](https://www.npmjs.com/package/react-helmet) so at least the titles of our browser tabs are relevant.  

And you can use this tool: https://www.opengraph.xyz/url/https%3A%2F%2Falkem.io%2Fhome
for preview of the sharing display on multiple platforms (not only LiN).

**Comment by bobbykolev** [comment]
@jeroentskui to provide an asset for default og:image shortly.

**Comment by bobbykolev** [comment]
- og:image;
- og:title;
- og:description
were added (synced with the ones from the website)

- title;
- description
were updated (synced with the ones from the website)

**Comment by bobbykolev** [comment]
As this change affects how the links to the platform are displayed in the socials, @SimoneZaza please review and confirm the copy:

```
<title>Alkemio - Safe Spaces for Collaboration</title>
<meta name="description" content="Join Alkemio: the platform designed to help you achieve your goals by making progress central.">

<!-- Open Graph Meta Tags used by Facebook, LinkedIn and other social apps -->
<meta property="og:title" content="Alkemio - Safe Spaces for Collaboration">
<meta property="og:description" content="Join Alkemio: the platform designed to help you achieve your goals by making progress central.">

**Comment by SimoneZaza** [comment]
Thanks @bobbykolev, this is indeed correct
