### ISSUE TITLE
Add callout block to search results

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5587]
## Description

As a user, I also want to see the callout results when I'm searching for them

## Acceptance criteria

- [ ] Label: Collaboration tools
- [ ] Order: 2nd place; after journeys, before contributions
- [ ] Filter on callout type

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Tested only the UI component without data (as it is i missing for the moment).
Raised a bug for filter on mobile: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5736
