### ISSUE TITLE
Administration of Lifecycles on Challenges / Opportunities

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#559]
## Description

As a challenge owner I want to be able to update the lifecycle for my Challenge / Opportunity

## Acceptance criteria

- [ ] Lifecycle for Challenge exposed in the admin UI, allowing the triggering of events into the Lifecycle for the Challenge / Opportunity
- [ ] The set of events that can be triggered from the admin UI are restricted to those coming from the Lifecycle instance (i.e. nextStates) field
- [ ] Authorisation level: EcoverseAdmin

## Additional Context
It probably is useful that the lifecycle can also be displayed next to the admin action?

**Comment by Comoque1** [comment]
Tested OK on test environment:

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/24baed31-16f8-46ae-a917-e4cb3a19912e)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ef85945a-f8fc-4a53-8920-765912b182c9)

Both ecoverse admin and the particular challenge admin, can modify the lifecycle of the challenge/opportunity.
