### ISSUE TITLE
Cannot read properties of undefined (reading 'userID')

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#5606]
**Describe the bug**
Error "Cannot read properties of undefined (reading 'userID')" is thrown when a journey with provided ID cannot be found.

**To Reproduce**
1. Go to `https://alkem.io/graphql`
2. Run the following query:
```
{
  space(ID: "randomId"){
    nameID
  }
}
```
3. Observe the error

**Expected behavior**
Not finding the space should give an error about the space, not the user

I**Additional context**

Error logs on apm-errors:
https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-4d,to:now))&_a=(columns:!('@timestamp',message,url.full,user.id),filters:!(),grid:(columns:(message:(width:741))),hideChart:!f,index:f46e21bb-e115-4266-8541-3d5729dfee63,interval:auto,query:(language:kuery,query:'%22Cannot%20read%20properties%20of%20undefined%20(reading%20!'userID!')%22'),sort:!(!('@timestamp',desc)))

There is a user, `michiel.sintenie@vattenfall.com`, trying to access a space that does not exist `publiekeplatformen`. We need to understand why.

**Comment by techsmyth** [comment]
This was a problem with the exception handling, which was fixed a while back
