### ISSUE TITLE
BUG: Card not displayed correctly on the profile page

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#5613]
**Describe the bug**

**To Reproduce**

1. Go to a user profile page
2. Look at the community cards
3.The card(s) is (are) displayed incorrectly.

**Expected behavior**
The card(s) is (are) not squished

**Screenshots**
<img width="1860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68d42cedbd52009ae1932fb7252408100e0027b5/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
Duplicate: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5469
