### ISSUE TITLE
Release banner instead of dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5615]
## Description

As a user, I don't want my flow to be interrupted by dialogs that I didn't ask for. Also, I feel more welcome to respond an more part of the community when I can share my questions or feedback directly underneath the release description. 
So, instead of showing the Release notification in a dialog as we currently do, we post it on the forum. On My Dashboard **for authorized users with memberships** a banner appears when a new release is out that we want to inform our users about. The text in the banner is clickable and leads to the forum discussion. There is a close icon on the banner to remove the banner from the homepage. It will then stay hidden until a new release notification is triggered, the same way we currently do with the release dialog (don't show this message again switch)

## Acceptance criteria

- [ ] Banner with title and text, both in the translation file
- [ ] Text to link to forum discussion, link to be in the translation file
- [ ] Close button to not show banner again until the next release (current don't show this message again switch)

## Additional Context
<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32c7c6db2f617420b2724c5a6c513a188127ce04/image.png" alt="image.png" />

https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=550%3A14080&mode=design&t=bw33kF0Hz2bw736G-1

**Comment by Comoque1** [comment]
The link in the moment points to a hardcoded discussion
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d268ff04a1d332215bb3c8a3aba3b13f2d42a2b4/image.png" alt="image.png" />
