### ISSUE TITLE
BUG: When deleting a single WB, "WhiteboardContentUpdatePolicy" and "WhiteboardWithContent" queries are triggered and failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5627]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox-alkem.io/whiteboards/challenges/whiteboards-challeng-2429/contribute
2. Create a whiteboard collection callout with a whiteboard card
3. Delete the whiteboard card - "WhiteboardContentUpdatePolicy" and "WhiteboardWithContent" queries are triggered after delete request and are failing
<img width="1515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16cdfa04d95887187b644c288ceaf4041f50c0f6/image.png" alt="image.png" />

**Expected behavior**
The queries are not triggered after deletion of single WB.

**Comment by Comoque1** [comment]
These are changes from develop branch deployed on sandbox env.
Policy reset was also applied.

**Comment by hero101** [comment]
Could not reproduce when the callout is deleted from the settings menu of the callout.
The issue was caused only when deleting through the delete button of the whiteboard in the specific case of a Whiteboard callout. This button will be removed, and the ony option to delete the callout will be through the settings menu. Related issue: #5651

**Comment by Comoque1** [comment]
@hero101 , @me-andre , apologize, the issue is reproducible with removing WB card from WB collection callout
<img width="1670" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9mQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28fa8bd90c2ce5aef821add7f30e35cad13d5db2/image.png" alt="image.png" />
