### ISSUE TITLE
BUG: When create whiteboard on whiteboard collection, activity logs are failing to load the data

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5629]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox-alkem.io/whiteboards/challenges/whiteboards-challeng-2429/dashboard
2. Create collection of WB callout
3. Add a WB to it
4. Close the WB
5. Refresh the page - error is thrown; "message": "Unable to find callout where whiteboardId: 3441168c-48a9-4eb3-97b8-89b06e68fb8f",
<img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNENTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--608e90307937ec884c770efa7cc4bbc34c142e8c/image.png" alt="image.png" />

**Expected behavior**
Activity logs are returning correct data, after WB is added to WB collection callout

**Comment by alstojanovic** [comment]
Fix is in [PR #3657](https://github.com/alkem-io/server/pull/3657)
