### ISSUE TITLE
Release notification url management

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5644]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [x] URL for categories in the forum
- [x] URL for selecting first discussion under a category .../releases/latest
- [x] Server configuration extended with an additional url under 'platform' section called "releases"

<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e2c4e40b4e7bf0c9cb30a34f626907538eb2cec/image.png" alt="image.png" />

- [ ] Client uses releases url picked up from server configuration for the release notification banner

 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
@SimoneZaza We already have a releases url under platform used for https://welcome.alkem.io/releases. Do we still need this old? If yes we will just need to name this new url releasesforum or something else.

**Comment by alstojanovic** [comment]
@Comoque1 after a discussion with @SimoneZaza we agreed to NOT change the release notifications banner functionality.
The forumreleases url is added to the server and it will stay because in future we may want to use it to reference it from a translation file or add on some other page.
