### ISSUE TITLE
Allow editing a forum discussion title + description

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5645]
## Description

As a global admins of a forum discussion I want to be able to modify the title + description

## Acceptance criteria

- [ ] Allow updating of the title + description of a forum discussion if the user has UPDATE on the discussion entity
- [ ] Grant the UPDATE privilege to all global admin roles. Note: not to the creator of the discussion
UI:
- [ ] EditOutlined icon next to bin icon to start editing 
- [ ] Edit to open same dialog as create discussion dialog, but with the fields filled in

## Additional Context

This editing is only for platform admins as if we allow people to modify the description after people have commented then they may be commenting on something old. 

Main difficulty is in creating wrappers, adjusting existing views to this new purpose.

**Comment by techsmyth** [comment]
@SimoneZaza explicitly in the current sprint?

**Comment by SimoneZaza** [comment]
@techsmyth ehm, not for me? I think you've added all these release mgmt issues to this sprint last week, but maybe by mistake?

**Comment by alstojanovic** [comment]
@SimoneZaza all global admins meaning global admins and global space admin?

**Comment by SimoneZaza** [comment]
@alstojanovic  <img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUsvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50b99f32b0d95d162542def99533cc090b7be35b/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
Alright, I added global community admins as well. Thanks!
