### ISSUE TITLE
BUG: When user without update_content privileges open a WB, the user who joins the WB afterward, doesn't see edit controls

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5647]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/my-latest/collaboration/afterrefctor-spac-2963 (the WB is enabled for editing only by the owner)
2. Open the WB first with user who doesn't have rights to edit and keep the WB open
3. Using another user open the WB with the owner - "edit" controls are not visible
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb02869f6ac1c5ebb05e6b9fe78c3fa933c08cb5/image.png" alt="image.png" />

**Expected behavior**
Everyone with update_content privileges open a WB after a user who doesn't have right to update it have it open - can modify the WB.

## Additional information
The is likely on production, since we release multi-user whiteboards

**Comment by SimoneZaza** [comment]
I think we should fix this as part of the whiteboard rt epic - when users hit this it is quite severe and completely unclear to them what is going wrong.

**Comment by Comoque1** [comment]
This issue is not reproducible, after the fix for this [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5639) was applied.
