### ISSUE TITLE
BUG: Added links to "collection of links" callout are not tracked by activity logs

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5649]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/fixed-left/dashboard
2. Add link to "Getting Started" callout - link is created successfully but is not reflected on activity log 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d20befb9c92bfab1825b3fc364dea4749e294619/image.png" alt="image.png" />

**Expected behavior**
Added links to "collection of links" callout are tracked by activity logs

**Comment by techsmyth** [comment]
@alstojanovic can you please have a look at this one?
