### ISSUE TITLE
BUG: GA can't load more than 50 spaces in list

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5653]
**Describe the bug**
In the platform administration, I can only see the first 50 spaces. 

**To Reproduce**

1. Go to https://alkem.io/admin/spaces
2. Click on 'Load more' (bottom of the list)
3. Click a couple of times until you have 50 in the list
3. Scroll down to the bottom of the list
4. See error: button to load more is gone

**Expected behavior**

**Screenshots**
<img width="1920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2lmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc82eaac816294f13970aec631017ad16bf48820/image.png" alt="image.png" />

<img width="1912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2FmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40b64f9baf2ca557f691f27890f8b17001a62804/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
There's a client-side limit for the 'searchable list' - 50. 
I'll increase the limit to 1000 for now. It's used for both filtered and all results in the following components (not isolated):
<img width="328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0hIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4181234e1008930f03d0fdc48a29b3ac453de6d/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
@bobbykolev thank you!

**Comment by Comoque1** [comment]
Tested OK on ACC env.
