### ISSUE TITLE
BUG: Innovation flow "Browse through all available materials" filters are not fully visible on smaller screen or when there are terms in the search

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5662]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/innovation-library
2. Scroll down to  "Browse through all available materials"
3. Decrease browser width - the filter are not well positioned
<img width="674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--546757082b8e0054fdbe75bd24d70e8401cce02d/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME95QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05acfaf2e66c3251483f9fd080a38597dbac5eaf/image.png" alt="image.png" />

<img width="491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5ed145f312bd46a0ac3bbb9cc16d1398c3b0a12/image.png" alt="image.png" />

**Expected behavior**
Filters are visible for both view - expanded and not.

**Comment by SimoneZaza** [comment]
@ccanos @me-andre I'm not sure if we should continue wrapping these filters here, expecially on mobile we might want to use a filter dropdown instead?

**Comment by EmiliaPavlova** [comment]
Designs: https://www.figma.com/file/eqgXjZpOz5VpBBwp2rmuMj/Member-guidelines-templates?type=design&node-id=1-137&mode=design&t=m5zHTEIFWVvrBoAb-0

**Comment by EmiliaPavlova** [comment]
After some discussions the final design is: the search field stays where in  - on the first line, the filter chips go on a second line and the word "Show:" is removed.
