### ISSUE TITLE
Whiteboard preview: crop instead of fit

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5663]
## Description

As an admin, spending some time on creating a **beautiful** whiteboard... I hate that the preview looks so ugly with all the whitespace around it. 

## Acceptance criteria

- [ ] Instead of creating a preview image in which all whiteboard content "fits" inside the image, crop the content from the center to fill the preview image
- [ ] …

## Additional Context
this makes me sad...
<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0dqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf2846fce807c16b7b60c1fd1a371b7c1527f706/image.png" alt="image.png" />

This is what I want as a preview:
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2FqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28a5d9e085058e7e27b4021e5e8654f14ecee334/image.png" alt="image.png" />

**Comment by EmiliaPavlova** [comment]
@SimoneZaza, this one can't be done with CSS only.

**Comment by SimoneZaza** [comment]
@EmiliaPavlova That's ashame. Any idea on how we should approach it?
