### ISSUE TITLE
Join/Apply dialog (Member Guidelines)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5666]
## Description

As a lead I want my community to read the member guidelines when applying/joining the space

## Acceptance criteria

- [x] Application dialog instead of page (see screenshot below for the current -confusing-  situation)
Content:
- [x] Title: Join [Space Title]  or Apply to [Space title]
- [ ] Application form without title
- [x]  Member Guidelines title, H4
- [x]  Member Guidelines description
- [x]  Member Guidelines references
- [x] Fixed footer with "Apply" or "Join" button, if the content is too tall, vertical scroll (while keeping button in sight)

## Additional Context
Current application form inside Space on Dashboard?? Weird UI
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af10313477fed21f4f97575320b78e680f6bd3d2/image.png" alt="image.png" />

https://www.figma.com/file/RJ72PKZ2aGQkbB7KKpQqha/Community-Rules?type=design&node-id=0%3A1&mode=design&t=0TdSSOHJt7tfDtcS-1

**Comment by alstojanovic** [comment]
@SimoneZaza the acceptance criteria says 'Application form without title' but the design is showing the title. Do we show it or not? Is this maybe a fixed text in the design 'Hey, super nice that you're joining...?
<img width="857" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d9f3af6c40f7f396b6ed8dbb4e7ba5f2e536d65/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
@alstojanovic which title do you mean? In this screenshot it is 
- Join + space title
- Introduction text from application form
- Application form
- Description field from member guidelines (in which this amazing user indeed wrote a sort of amazing title 😉) 
Feel free to give me a call!

**Comment by alstojanovic** [comment]
Well for community guidelines we were referring to guidelines description as the title and I am not sure what is considered to be Application form title here? 🤔
