### ISSUE TITLE
Switch to disable default callouts when creating challenge / opportunity

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5690]
## Description

As an admin, I sometimes (/often) want to create a new journey without the default callouts. Currently, the first thing I'm doing when I've created a new challenge is to delete all of those callouts..

## Acceptance criteria

- [ ] In the Challenge/Opportunity create dialog, add a switch for enabling/disabling default callouts. Label: "Add default collaboration tools"
- [ ] Location: under tags, above innovation flow
- [ ] Default = on

## Additional Context
server api support for this should be in with the innovation flow to states PR, so this is only client side.

**Comment by Comoque1** [comment]
Works as defined on dev env.
