### ISSUE TITLE
New whiteboards to be editable by everyone by default

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5710]
## Description

As a user, when I create a new whiteboard in a Space with multiple members, I expect all of them to be able to work with me on this whiteboard. It is nice that I can lock it, but I expect it to be open by default, since it is posted in a shared space. 

## Acceptance criteria

- [ ] When a new whiteboard is created, settings should be open to everyone to collaborate
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by alstojanovic** [comment]
@SimoneZaza on whiteboard creation we are setting the contentUpdatePolicy to `contributors` meaning everyone can contribute. I tested within a new space for whiteboard and whiteboard collections on dev environment.

**Comment by alstojanovic** [comment]
@SimoneZaza agreed to close the issue.
