### ISSUE TITLE
BUG: SpaceChallengeCards and SpaceDashboardNavigationChallenges requests are failing, when user try to access collection that contains a private spec and he is not a member

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5717]
**Describe the bug**

**To Reproduce**

1. Go to SpaceDashboardNavigationChallenges - error is thrown: ` "message": "User (evgeni@alkem.io) does not have credentials that grant 'read' access to Challenge.collaboration",`
2. Create a public space with private and public challenge
3. Navigate to the space challenge page with space member - error is thrown and no challenges are displayed
<img width="1820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVhTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b75e5dc9b693b4298310988764b5f3e22f741485/image.png" alt="image.png" />

**Expected behavior**
Space members can see the challenges cards no matter if they are public or private.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
The solution was to remove the query of innovation flow state from challenges cards on Space level.
Regarding opportunity:
  1. if user is not member of the private challenge cannot see its opportunity
  2.  if the user is member of the challenge he sees the innovation flow state on the opportunity card, but doesn't fail, again because of the above reason

**Comment by hero101** [comment]
@ccanos please give an estimate
