### ISSUE TITLE
Changing labels

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5738]
## Description

As a user I want to be able to navigate to the subspaces in my space/subspace

## Acceptance criteria

- [x] Change "Challenges" tab into "Subspaces" tab on Space level
- [x] Change "All Challenges" as block title into "Subspaces" (without the 'All')
- [x] Change "Opportunities" tab into "Subspaces" tab on Challenge level
- [x] Change "All Opportunities" as block title into "Subspaces" (without the 'All')
- Check if text is correct when there are no Challenges/Opportunities

## Additional Context

Note: for now we'll keep the icons of the mountain and the lightbulb on the subspaces cards (on these places + the search) since these subspaces will be of type: challenge and type: opportunity. 

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by alstojanovic** [comment]
@SimoneZaza re text when no Challenges/Opportunities
Old text:
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a61dad5cf39c3327209ad59a44abb8f2db034d7/image.png" alt="image.png" />
I propose just removing 'in this Challenge' text:
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d43db9ed9cc0612c0ca1b0ac70d6fdffeafe87c1/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@SimoneZaza , what are the expectations regarding Challenge (on platform level) page, Search results and Admin sections?
