### ISSUE TITLE
Callouts to be only on the right side of pages

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5748]
## Description

As a user I want to see a structured page with a clear dedicated location for specific types of content 

## Acceptance criteria

- [ ] Only show add collaboration tool button on the right side of the page
- [ ] Remove the location Left from the edit callout-change llocation menu

## Additional Context

Figma: https://www.figma.com/file/XDWND6E1djfELwBfMa4U3u/Spaces-%26-SubSpaces?type=design&node-id=7%3A3889&mode=design&t=JuCyfWWG1LR3Bb5E-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
