### ISSUE TITLE
BUG: Opening wb activity from my latest activity on my dashboard, throws an error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5768]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io
2. Create a WB on any journey
3. Make change to the WB
3. Go to my dashboard
4. Click on the activity - it is open, but error is thrown:
<img width="1514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29a99a743591ba5c4bc4e3729c02d9c6d304b4d7/image.png" alt="image.png" />

**Expected behavior**
Activity is open without errors.

**Comment by Comoque1** [comment]
@me-andre the issue is still reproducible on Challenge and Opportunity journeys. You also need need to click on my latest contribution

![image](https://github.com/alkem-io/client-web/assets/23620658/f211b66e-4c92-4a76-9fa3-0300fd6a90eb)

**Comment by valentinyanakiev** [comment]
@Comoque1 https://github.com/alkem-io/server/pull/3751

**Comment by Comoque1** [comment]
I wasn't able to reproduce anymore as well.
