### ISSUE TITLE
BUG: Innovation flow buttons miss white background

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5808]
Although the new innovation flow is super, super, super nice, there's one little thing:

The different phases/states should have a white background

<img width="927" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32355faafdb7e472f293c3d73c96ea2f0c10f679/image.png" alt="image.png" />

Design: https://www.figma.com/file/SKe3YDHm3Rs7yzuDohHSPK/Innovation-flow-design?type=design&node-id=353%3A463&mode=design&t=ZRkiMNuoVYRyoVZB-1

**To Reproduce**

1. Go to Contribute page

**Expected behavior**
White background for all states except for selected state

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by EmiliaPavlova** [comment]
As per discussion with @SimoneZaza the borders of the buttons is also changed to #D3D3D3 according the Figma design.
