### ISSUE TITLE
Also allow global SPACES admin to use releases category 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5815]
## Description

As a Global Spaces Admin, I want to add release notes to the releases category. Currently, only Global Admins can add things to this category

## Acceptance criteria

- [ ] Unhide Releases category for global spaces admins as well
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@ccanos how is this currently done?

**Comment by alstojanovic** [comment]
@techsmyth discussion categories are saved as an array of strings in the db. The releases category is filtered out on the client for users that are not global admins. On the server when creating a new discussion with category 'releases' we have a check if the user has global admin privilege (this is to manage the case if someone tries creating a releases discussion via api directly).
