### ISSUE TITLE
In activity logs, show user that joined, not user who accepted/added

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5821]
## Description

As a member, I get confused and find it weird to see a familiar face next to a name I don't know
<img width="297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d873f492ae539e45e716188b7f6ba7ebaf80c3c/image.png" alt="image.png" />

## Acceptance criteria

- [ ] For MEMBER JOINED events, show avatar of user that joined, instead of the person inviting/adding/accepting them

## Additional Context
Neil: this used to be the case, seems to have been lost

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Fixed on dev env.
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d958886a672c69dc76dabf53e7dfb66533c30692/image.png" alt="image.png" />
