### ISSUE TITLE
My Memberships dialog: UX update

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5823]
## Description

As a user with more than 5 memberships, I want to have a quick and clear overview of all my memberships in the My Memberships dialog. Currently, each space takes a lot of space in this dialog with the large cards. 

## Acceptance criteria

- [ ] Expandable list view for dialog
- [ ] Per list item: avatar, title, tagline, and the word(s) admin, lead when relevant
- [ ] Sort spaces on activity, subspaces on displayname (as is currently the case in this dialog)
- [ ] Show everything collapsed by default
- [ ] Use spinner for loading indication
- [ ] Mobile: see design, show admin/lead label underneath title/tagline instead of next to it
- [ ] Mobile **if easy**: truncate title at 2 lines, tagline at 2 lines
- [ ] Keep current footer message

## Additional Context

https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=1491%3A9141&mode=design&t=OKMPurcBo29buoSW-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
