### ISSUE TITLE
Mobile: Text on open Invitations should be displayed under space card

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5825]
## Description

As a User I want to have nice invitation dialog

## Acceptance criteria

- [ ] When invitation dialog is open on mobile, all the text is moved below the card
<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02721648d647c17574a8d42057fd7d609148a6b2/image.png" alt="image.png" />

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
In addition to the suggested column layout on mobile, the following changes were applied:

- [x] The layout is now centered on mobile;
- [x] The title is now wrapped in multiple lines making it visible. Until now the important part (space name) was cut on lower resolutions; 

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6b307691da452f14363ca0bc5da84ba9cd01bc4/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Looks better now on DEV env.
<img width="835" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3g4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94f094df52511f025d6283991153a19b70d88b6e/image.png" alt="image.png" />
