### ISSUE TITLE
BUG: Missing validation for the size of Community guidance description

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5827]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/admin/spaces/space-mig/community
2. Enter the following text:
```
Advertisement 

pica - high quality and fast image resize in browser.

babelfish - developer friendly i18n with plurals support and easy syntax.

You will like those projects!

h1 Heading 

h2 Heading

h3 Heading

h4 Heading

h5 Heading

h6 Heading

Horizontal Rules

Typographic replacements

Enable typographer option to see result.

© © ® ® ™ ™ (p) (P) ±

test… test… test… test?.. test!..

!!! ??? , – —

“Smartypants, double quotes” and ‘single quotes’

Emphasis

This is bold text

This is bold text

This is italic text

This is italic text

Strikethrough

Blockquotes

Blockquotes can also be nested…

…by using additional greater-than signs right next to each other…

…or with spaces between arrows.

Lists

Unordered

Create a list by starting a line with +, -, or *

Sub-lists are made by indenting 2 spaces:

Marker character change forces new list start:

Ac tristique libero volutpat at

Facilisis in pretium nisl aliquet

Nulla volutpat aliquam velit

Very easy!

Ordered

Lorem ipsum dolor sit amet

Consectetur adipiscing elit

Integer molestie lorem at massa

You can use sequential numbers…

…or keep all the numbers as 1.

Start numbering with offset:

foo

bar
```
3. Press update button: request is successful, but description is empty:
<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8198c72b0f8dcaab7ba8b284d2c1bade68d02bf6/image.png" alt="image.png" />

**Expected behavior**
TBD

**Comment by alstojanovic** [comment]
@Comoque1 when I do the steps the guidelines get updated and I have the text in the description field in the request.
<img width="1624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80be05731631a9689339f99194bb6c569ef6c451/image.png" alt="image.png" />
