### ISSUE TITLE
BUG: retrieving platform updates, which are not used

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5837]
**Describe the bug**
CLient is downloading platform updates, which are not used!

<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e283637080ea53ab9cfca7a2dc4a36edf7e8e8/image.png" alt="image.png" />

**To Reproduce**

1. Go to any page on the platform + refresh

**Expected behavior**
We do not query the platform updates

**Comment by hero101** [comment]
No platform updates are downloaded - only the roomID for the platform communication updates is used in order to subscribe to top level updates, using the  `roomEvents` subscription.
@techsmyth are you saying let's not subscribe to updates anymore?

**Comment by techsmyth** [comment]
@hero101  we have never used this, and are not using it - not sure when / how it came in.
