### ISSUE TITLE
Switch the redirects from alkem.io to welcome.alkem.io

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#5840]
## Description

As a NEW user (or Search Engine), I want "alkem.io" to load faster.
This will result in better first-time user experience and higher SEO ranking of alkem.io landing.

_Note that this request is targeting only the first-time user experience, aiming to switch the logic of redirect from the platform to the welcome site. Making the entire platform faster would be higher effort part of separate Epic._

## Acceptance criteria

- [ ] Should not change the current UX - landing on alkem.io/home* in case of returning visitor and landing on welcome.alkem.io for new users (new browser session).
- [ ] Should load the welcome site faster, after accessing it through alkem.io.

## Additional Context

Currently, if a new user (search engine as well) try to hit alkem.io, the request goes to the platform, then after loading the entire bundle it redirects to welcome.alkem.io.
 
This results in huge performance (and SEO) penalty for our landing page - from 66 to 25% performance score (Google). 
 
I'd suggest reworking the flow and land ALL users directly on welkome.alkem.io. From there we could check the session (fetch 'whoami' suggested by @me-andre) and redirect to alkem.io/home if need.
 
I know it's not ideal for our existing users and we could have to change some redirect URLs (/ -> /home), but it's important for every new user and Search Engine.

## Areas that will be affected 
- client web - TopLevelRoutes, RedirectToLanding, etc.
- welcome site - script in the <head> checking for existing cookie/session - TBD.
- TBD - infrastructure configurations on the LB/treafic/nginx/kratos side where the following redirect should be configured "alkem.io -> welcome.alkem.io" and "alkem.io" -> client-web

**Comment by techsmyth** [comment]
Potentially this can be (partially) done via middleware according to @valentinyanakiev

**Comment by valentinyanakiev** [comment]
after talking to @techsmyth - the scope is just **alkem.io**, and not **alkem.io/***
