### ISSUE TITLE
Review and enhance the client errors

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#5843]
## Description
In order to better understand and prioritize the client errors we need to research and improve the Sentry Error Logs including the following:

- include additional information to handled errors;
- improve the tagging / categorization of handled issues;

## Acceptance criteria
TBD based on the research and implementation;
- [ ] Router data for handled errors available in Sentry;
- [ ] Handled errors with tags - CATEGORY (SERVER, AUTH)

## Additional Context
Sentry Issues:
https://alkemio.sentry.io/issues/?environment=production&project=5862875

**Comment by hero101** [comment]
Are we closing this since https://github.com/alkem-io/client-web/pull/5847 was addressed or there is something more to do?
