### ISSUE TITLE
BUG: [Sentry] ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#5845]
**Describe the bug**
There's a high volume bug (highest ATM) reported by Sentry - _ResizeObserver loop completed with undelivered notifications_.
I was able to see the error as part of my session (in Sentry) but there was no indication in the browser - **No user affection**.  

**To Reproduce**

There are no concrete steps, just browsing the application and the error pops in Sentry. Sometimes after navigation, other times around graphQL calls.

**Expected behavior**
Reducing its count and/or filtering it in Sentry.

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Edge]

**Additional context**
Link to the error in Sentry:
ResizeObserver loop completed with undelivered notifications.

**Areas that will be affected**
Scroll listeners should be revised.

**Comment by techsmyth** [comment]
Closing in favor of 5896
