### ISSUE TITLE
Profile page for VC

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5862]
## Description

As a user I want to see where a VC is contributing

## Acceptance criteria

- [ ] Profile page, with no memberships, social links, location, or messaging;
- [ ] Content:
- Name, Description, Tags, References, 
- Body of knowledge that is used
- Persona that is used
- What it uses from the Space it is invited into
- Host organization or user
- Info on data safety/exposure etc.

## Additional Context

Design which one of the two TBD: https://www.figma.com/file/0cSP9R1SqhlrBuucR1NYJu/Create-Virtual-Contributor?type=design&node-id=119%3A7&mode=design&t=lRJ2FQWYkLx9R3wJ-1

**Comment by bobbykolev** [comment]
The initial design* was applied. Some of the contents are hardcoded. See the linked PR for details.
