### ISSUE TITLE
BUG: Newly created personas are not visible on "Create Virtual Contributor" page without refreshing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5880]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/admin/virtual-contributors/new-virtual-contributor
2. Create new persona
3. Go to "Create Virtual Contributor" tab - the persona is not available in the list
<img width="1766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--339a36339e9e551e75c61e0775a560179f1f7c7a/image.png" alt="image.png" />

**Expected behavior**
Newly created personas are visible on "Create Virtual Contributor" page without refreshing.

**Comment by valentinyanakiev** [comment]
this is working now, validated locally
