### ISSUE TITLE
Description of innovation flow state should not be required

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5902]
## Description

As an admin, I sometimes want to make a flow without descriptions for the phases. I get frustrated when I have to.

## Acceptance criteria

- [ ] Allow for Innovation flow steps without description (currently the save button is disabled if there is no description)
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
@techsmyth I assume there was no specific reason for making these descriptions to be required fields?

**Comment by techsmyth** [comment]
@SimoneZaza  no real reason, so ok for it to be empty.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
