### ISSUE TITLE
BUG: Users cannot be mentioned on forum discussions

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5903]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/forum/discussion/tes-8718
2. Mention a user - error is thrown: `"message": "Variable \"$communityId\" got invalid value \"\"; UUID not valid: ",`
<img width="1559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXhYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e96fcfde97f1cf3ee9597df7e4f6c7a3bebe381/image.png" alt="image.png" />

**Expected behavior**
Users can be mentioned on forum discussion.

**Comment by Comoque1** [comment]
All requests are still failing with 502, when try to mention a user or send a message / reply
<img width="1209" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjl3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--259f340260bdc145a2b1a560e868489e9726b781/image.png" alt="image.png" />

<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN053QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce9a1118201be97fce0b7e7d764ac160c4affe8d/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
Sorry, the bug said the error was happening when trying to add a mention, I haven't tried sending the message. Will look at it.

**Comment by Comoque1** [comment]
No works fine, thanks!
