### ISSUE TITLE
Sticky scroll

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5905]
## Description

As a user working on a desktop, I want to keep the context I'm working in in sight when scrolling through the callouts. I want to easily navigate between innovation flows, add new callouts, check for recent updates/events/subspaces/etc etc without having to scroll to the top.

## Acceptance criteria

- [x] Keep left column fixed when scrolling down the page. When the left column is longer than the page, the user should be able to scroll to the bottom, but not move further. If there is any complexity in this, we will create a new issue for this.
- [x] Keep the innovation flow and add button fixed to the top of the browser when scrolling down the page. The user thus scrolls away the banner image and main navigation, but then the innovation flow and add button remain fixed once they reach the top of the page
- [x] Background color shadow at the cut off point/line of the InnovationFlow-Callouts

## Additional Context
Figma: https://www.figma.com/file/XDWND6E1djfELwBfMa4U3u/Spaces-%26-SubSpaces?type=design&node-id=478%3A1239&mode=design&t=351XbJX6piw6N5ik-1
Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by ccanos** [comment]
@SimoneZaza  About the shadow, I've been playing with this https://medium.com/walmartglobaltech/activatable-drop-shadow-on-sticky-elements-d0c12f1ebfdf
I have a stash locally but it doesn't look fully good. I would create another task and try again in another sprint, this has taken me too much
