### ISSUE TITLE
Space Templates section: update cards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5906]
## Description

As a admin, I want to see a nicely designed page in the settings as well. 
As an Alkemio team member, I want the Templates section to also show up nicely when I give a demonstration

## Acceptance criteria

- [ ] Use cards that are used in the global library for the Space Templates section as well
- [ ] Probably needs changing the container as well
- [ ] Remove the old cards from the codebase after both this issue and #5918 are done

## Additional Context

<img width="1154" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71e203d2a3008e0a80b6fc04271dac8303150cdb/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
All cards on space / templates are missing in the header the organization and the footer
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--925d45c15fe8b68c39b28f19b66c53d833cea8b1/image.png" alt="image.png" />
