### ISSUE TITLE
Improved editing of VC profiles

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5911]
## Description

As a sales lead I want the VCs to have rich profiles

## Acceptance criteria

- [ ] Allow editing of all content on a VC profile, using user profile editing page as a basis:
- Avatar
- Name
- Tagline
- Description
- Tags
- References
- Host (can't edit)
- Space (can't edit)
- Subspace (dropdown with list of subspaces within the related space)

## Additional Context
Figma: https://www.figma.com/design/0cSP9R1SqhlrBuucR1NYJu/Create-Virtual-Contributor?node-id=194-1879&t=9psLVx6UF7uJzYIS-1

- Who can edit? Admin or only host?
- Complexity with space relation + goign back and forth between teams

**Comment by SimoneZaza** [comment]
@techsmyth who has the privilige to edit the profile/create the vc? Only the host or also the admin?

**Comment by bobbykolev** [comment]
I'll extract two points from the inital ACs:
- references;
- Dropdown with Subspaces - MVP shows only the selected one. You can change the BoK by deleting the current VC and creating a new one.
@SimoneZaza @Comoque1 FYI

**Comment by Comoque1** [comment]
thanks @bobbykolev !
