### ISSUE TITLE
Create/edit dialog for Callout templates

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5921]
## Description

As an admin, I want to directly understand what is part of the actual template, and what is part of the framing of the template. ...and I also want something that matches the UI of the rest of the platform.

## Acceptance criteria
- [ ] Use dialog from #4632
- [ ] Title, Description, Tags
- [ ] Callout type
- [ ] If Call for posts: Add Default Post Description
- [ ] If Whiteboard/Call for whiteboards: Add Whiteboard Template
---
- [ ] In Global library (Innovation pack settings > add Callout template)
- [ ] In Space library (Space settings > templates > add Callout template)
- [ ] When user clicks "Save as template" on callout
  
## Additional Context

Figma: https://www.figma.com/file/nT1quBVBiH37zvmtdcsHVq/Templates?type=design&node-id=1%3A54&mode=design&t=yMwVo9nSzcrQQWPg-1

**Comment by Comoque1** [comment]
Save as template to be tested separately.
