### ISSUE TITLE
Member Guidelines Template cards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5924]
## Description

As a user, I want to get a small preview of the guidelines from the cards when scrolling through the library

## Acceptance criteria

- [ ] Very similar to post template card:
- [ ] Icon: HandshakeOutlined
- [ ] Template title
- [ ] Template description (not the guidelines themselves)
- [ ] Template tags
- [ ] Innovation pack

## Additional Context
Figma: https://www.figma.com/file/eqgXjZpOz5VpBBwp2rmuMj/Member-guidelines-templates?type=design&node-id=48%3A1783&mode=design&t=DLxu1YSc6kkjxVDO-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested on dev env.
One bug raised: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6360
