### ISSUE TITLE
Add innovation pack to template cards in global library

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5925]
## Description

As a user I want to see in what innovation pack a template is included, since this give me some extra context information.

## Acceptance criteria

- [ ] In the "Browse through all available materials" block in the global library and the corresponding dialog, add the Innovation pack at the bottom of the card
- [ ] In the library dialog accessed through a space, add the Innovation pack at the bottom of the cards from the platform library (cards from the space templates section don't have an innovation pack associated)
- Space settings > Templates > Library
- Whiteboard > Library
- Create Call for posts > Library

## Additional Context
This might already be included, just not made visible???

Figma (example 1 card): https://www.figma.com/file/eqgXjZpOz5VpBBwp2rmuMj/Member-guidelines-templates?type=design&node-id=48%3A1783&mode=design&t=DLxu1YSc6kkjxVDO-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Whiteboard and Post for Callouts don't have Innovation pack at the bottom of the card.
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1e95ba5f594d61e2a969c510a5db29f64d252af/image.png" alt="image.png" />


<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f0ed3c072881ad7b105652ebe509af7ec6fc4f8/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Now it works fine on DEV env.
