### ISSUE TITLE
Preview dialog for Member Guidelines and Callouts

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5931]
## Description

As a user, I want to be able to see the templates in detail before using them

## Acceptance criteria

- [ ] Use the latest preview dialog component(?), same as used for other templates in the global library
- [ ] Callouts: already exists?
- [ ] Member guidelines: left template info, right member guidelines themselves

## Additional Context
No figma design, should be consistent with other preview dialogs

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by EmiliaPavlova** [comment]
The dialog designs: https://www.figma.com/file/nT1quBVBiH37zvmtdcsHVq/Templates?type=design&node-id=0%3A1&mode=design&t=ZpmW7ZEtVRvxiCKO-1
