### ISSUE TITLE
BUG: Unable to Create Events  

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#5950]
**Describe the bug**
As a Global Admin, I'm unable to create events, the add event option is missing. 

**To Reproduce**
Reproducible on local (develop branch) and dev-alkem.io. 

1. Go to Space Dashboard;
2. Expand the Calendar Events;
3. Observe the missing 'Add event' button (bottom right); 

**Expected behavior**
The create button and all calendar and event functionalities should be available for Global admins and Space leads and admins.

**Screenshots**
<img width="1273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7f4e3d17399a1ed5f8b6315874dd6c1aa60cd93/Screenshot%202024-04-17%20171212b.png" alt="Screenshot 2024-04-17 171212b.png" />

**Additional context**
Reproducible with the latest develop branch.
The required permissions are provided by the server but there's a 'skip' logic that prevents populating the permissions in some cases:
`skip: !journeyId || journeyTypeName !== 'subsubspace',`
The ` journeyTypeName !== 'subsubspace'` is truthy on space level and this lead to skipping the initial query (useSpaceCalendarEventsQuery).

It looks like it was broken with the subspace simplifications around the 9th of April commit a4597e5812660517242f32f0bb7d40964c738b65 

@valentinyanakiev, @me-andre please advise on resolution. Are we skipping the entire `journeyTypeName !== 'subsubspace` check or do we keep it only for space, or something else?

**Areas that will be affected**

**Comment by SimoneZaza** [comment]
@valentinyanakiev We still have events in subspaces, but in a dialog instead of always visible on the page

**Comment by bobbykolev** [comment]
Fix applied - the check `journeyTypeName !== 'subsubspace'` was removed - as part of client-web [#5952](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5420)
