### ISSUE TITLE
Able to expand discussion group window to show more

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5951]
## Description

As a user, especially of VCs, I **really** want to be able to see more of the discussion

<img width="1908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1628c8729171888734c8d00844137e69037c4b8c/image.png" alt="image.png" />

## Acceptance criteria
- [ ] For all comments everywhere put time in header, next to the bin (left time, right bin)
- [ ] Max height = full available height in the browser, minus 20px (1row) on top of the page and at the bottom the page
- [ ] Min height = height needed to fit content

**Comment by techsmyth** [comment]
@SimoneZaza @me-andre this one is a real pain when working with the VCs demo - even when "going full screen".

can you think of options to show more of the discussion thread / expand the screen / other ideas? Thanks!

**Comment by SimoneZaza** [comment]
@techsmyth thanks for flagging this. I think we should at least make the dialog taller, but I'd also like to have a look at the spacing, I think we might be able to remove one row of whitespace at the bottom of each message. I'll look into it!
