### ISSUE TITLE
Update default image to match new primary color

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5958]
## Description

As a user, I want to see a default image that aligns with the color usage on the platform

## Acceptance criteria

- [x] Product team to update image with the right colours
- [ ] New images to be used on the platform

## Additional Context

https://www.figma.com/file/GBImEseeYtdz0gsAG1vcWw/Default-Images?type=design&node-id=50%3A3121&mode=design&t=VQutRRGJnV6Hi1H9-1

## Images are on sharepoint here:
https://stichtingcherrytwist.sharepoint.com/:f:/r/sites/Product/Shared%20Documents/5.%20Platform%20Content%20and%20Information/Default%20images?csf=1&web=1&e=7Ojktd
Both jpgs and svgs in this folder

**Comment by SimoneZaza** [comment]
I see this issue is still on the backlog, but I actually think it is done. On dev I see the updated images.

**Comment by Comoque1** [comment]
Tested on DEV env, without the search.
One bug is raised, related to these visuals: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6098
