### ISSUE TITLE
Callouts library button to be visible for all members

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5959]
## Description

As a member that can add callouts to a Space, I also want to be able to use the callouts in the library

## Acceptance criteria

- [ ] Show button for library (bottom of the list of the choose callout type dialog) for all users, currently it is only visible for global admins
- [ ] …

## Additional Context

<img width="477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTV5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3b3b001cf788dbb6e4050fb79bc246cfb9ce542/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK locally on all levels with Community member.
