### ISSUE TITLE
Refinement Member Guidelines block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5960]
## Description

As a user, I don't immediately see how I can continue reading since the expand button is at the top of the block, while I already started reading and my eyes moved down.
As a user, this block confuses me when there is no content inside
As an admin, I'd like to be able to directly go to the place where I can add my content when it is empty

## Acceptance criteria

- [ ] Add "Read more" button bottom right, like the ones on the blocks on My Dashboard (eg New Memberships/Tips & Tricks block)
- [ ] When there are no guidelines, only show this block to the admins and leads with the text: 
"Since there are no Member Guidelines specified, this block is only visible for admins and leads. Click here to update the Member Guidelines in the Space settings" with the second sentence being a link to the Space settings > Community tab

## Additional Context

<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49b24e2d77d1eb105f7173fc7a7c89a5626c6cbb/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
The link when there is no guidelines, points to 404 page
<img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnpnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--648054cb824f5dc639ebc742c2f58cdf9dc308d9/image.png" alt="image.png" />

<img width="1103" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62bb733e2758b5f3ead2ab07406f3ec60012f9e0/image.png" alt="image.png" />

**Comment by EmiliaPavlova** [comment]
Works as expected. Please check again.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6325bb7e806c0046e24c8081dd4e5602dd14cbc/Screen%20Recording%202024-05-16%20at%2014.43.13.mov)


<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7333c24b97fce20db58d22d2402af865695e6c4b/Screenshot%202024-05-16%20at%2014.00.27.png" alt="Screenshot 2024-05-16 at 14.00.27.png" />

**Comment by Comoque1** [comment]
On acc env with latest changes, wasn't able to reproduce the issue as well.
