### ISSUE TITLE
BUG: Space cards banners are not loaded on Spaces page

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5970]
**Describe the bug**
On the global spaces page, none of the custom card images (space banners) are visible, they're all replaced by the default image.

Please note that this does not have anything to do with the space, we still have more than enough available (Valentin checked) and the server reset did not fix it.

**To Reproduce**

1. Go to https://alkem.io/spaces

**Expected behavior**
Background space banners are visible (instead of the default ones).

**Screenshots**
<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUo1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f10fa8e6e45d936e00285239e6d3501785e8405e/image.png" alt="image.png" />

**Additional context**
The bug seems related to: https://github.com/alkem-io/client-web/issues/5739

On first look, it seems the latest implementation does not pass the `banner` property to the `JourneyCard`: 
https://github.com/alkem-io/client-web/pull/5846/files#diff-ec8843f386dc769711c4201c3c931886f629ff4843772c73658e3e66d1692532R55

...that was present in the previous implementation:
https://github.com/alkem-io/client-web/pull/5846/files#diff-cb84df968c0b0ffd0a4f06fd3f83d23c5b1810896611452b61176e1c93e8b2c8L152

...and the JoruneyCard uses it for displaying the banner and the alt text (both defaulting ATM)
https://github.com/alkem-io/client-web/pull/5846/files#diff-e9a2a0a17eff73230e84083a956396cb866f2ec171a54a085d4d65d6ed411a03L67

**Areas that will be affected**
/space page -> SpaceSubspaceCard.tsx component.

**Comment by bobbykolev** [comment]
The banner URL information was missing on the display card. After the fix, both Space and SubSpace banner images should be displayed as expected.
