### ISSUE TITLE
BUG: My Membership dialog returns code

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5975]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Click on 'Explore all your spaces' - dialog is open and part of the message is not translated

<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUorQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd16e5d2c4e4d0379cdf4e8a20368e756e52d3de/image.png" alt="image.png" />

**Expected behavior**
Shows correct text.

**Comment by bobbykolev** [comment]
Now the link points to the new /spaces page. Also, the wording was changed from subspaces to spaces:

> [Click here](https://alkem.io/spaces) to explore all spaces on the platform.

**Comment by Comoque1** [comment]
Tested OK on dev env.
<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--590b0aa2c66b86960d169e30a9733ace33c50b1e/image.png" alt="image.png" />
