### ISSUE TITLE
BUG: hierarchy block on space dashboard

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6031]
**Describe the bug**
The outline/hierarchy block on Space level looks broken when visiting a Space, see screenshot below. After clicking on the "Show full hierarchy" button it does look okay.

**To keep in mind:**

When list is very long:
- events block moves out of sight
- loading time

Two possibilities:
- Move events block above hierarchy block
- or keep original collapsed version (see block on production with button to "show all")

<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--454f01e9ad74ca572b48a35deb52bc7565fabd78/image.png" alt="image.png" />

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by ccanos** [comment]
@me-andre then, this is for you :)
<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--610d942a68d920b62781f683074a3038f477c996/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
OK on DEV env.
<img width="553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f6f26731886bfc328984516a81039ad450ccb6a/image.png" alt="image.png" />
