### ISSUE TITLE
BUG: After submitting verification code in SignUp flow and press continue button, user get a blank screen

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6034]
**Describe the bug**

**To Reproduce**

1. Go to alkem.io
2. Register new user in incognito browser
3. Copy verification link from email
4. Paste it in the browser and press submit - user is redirected to success page, but blank screen is displayed.
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9YQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04ecc5222c1dfbda0ef888d2f5b641aa9542e3a0/image.png" alt="image.png" />

**Expected behavior**
User is redirected to signin page.

**Additional context**
On acc env, the issue is not reproducible.

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by bobbykolev** [comment]
Can you share a screenshot from the console tab, please? @Comoque1

**Comment by Comoque1** [comment]
Managed to register on Prod, without hitting the issue described above.
