### ISSUE TITLE
BUG: As a subspace member I can see `manage flow state` and `settings` buttons

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6051]
**Describe the bug**
As a subspace member I can see `manage flow state` and `settings` buttons

**To Reproduce**

1. Log in as space member of the alkemio space and raisingthealkemio challenge
2. (https://sandbox-alkem.io/alkemio/challenges/raisingthealkemio-6086)
3. You can see `manage flow state` and `settings` buttons

**Expected behavior**
The buttons should be conditionally rendered based on privileges.

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/7090348/f2413084-8bf3-4d76-994b-26d10886162c)

**Comment by ccanos** [comment]
@Comoque1 please, make sure that all the cases you saw in #6096 are effectively solved by this one

**Comment by Comoque1** [comment]
Looks ok on local env.
