### ISSUE TITLE
BUG: Recent contributions block not loading

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6052]
**Describe the bug**

![Image](https://github.com/alkem-io/client-web/assets/38861315/7238cbff-cf3e-40a6-9c0c-ff498a6313fd)

![Image](https://github.com/alkem-io/client-web/assets/38861315/4952244a-871f-46ff-9dc0-2522e9df545b)

https://sandbox-alkem.io/alkemio/dashboard

**To Reproduce**

- add screenshots 
- add url on the location with problem

**Expected behavior**

**Screenshots**

**Comment by bobbykolev** [comment]
The issue is reproducible only in this Space on this environment (sandbox).
I can't reproduce it on dev, local, and on any other space on sandbox.

**Comment by Comoque1** [comment]
Closing the issue as haven't reproduce it anywhere else.
