### ISSUE TITLE
BUG: Share dialog mentioning Space instead of Subspace

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6056]
**Describe the bug**
The share dialog that is opened through the menu on the subspace uses "Space" instead of "Subspace":

<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e7a948929a13110ef601f1089d5f9dcec94e3a7/image.png" alt="image.png" />

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on ACC.
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWpKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afcf0189ea211d3c1c2e5bbfa8c0bc9568182c92/image.png" alt="image.png" />
