### ISSUE TITLE
BUG: Space avatar is missing in the breadcrumb

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6060]
**Describe the bug**
The Space avatar is not shown in the breadcrumb, even though there is a card image uploaded on the profile. Avatars for Subspaces are still working. 

<img width="439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b587351dc489786d31e7197b952597286c65ce32/image.png" alt="image.png" />

<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aeb08c6c87526c512581f53d00df9475bb435e2/image.png" alt="image.png" />

**To Reproduce**

1. Go to https://dev-alkem.io/space-mig/dashboard

**Expected behavior**
Space avatar in breadcrumb to be a crop from the banner card image, as is currently the case on production

**Comment by Comoque1** [comment]
Looks OK now on DEV env.
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27758b5ceae7e4fa4db358e8854a5ff785d48034/image.png" alt="image.png" />
