### ISSUE TITLE
Persistent Collapsed/Expanded state of the left panel in subspaces layout

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6076]
## Description
As a user I want the browser to remember my choice of whether the left page column in a subspace is collapsed or expanded.

## Acceptance criteria
- [ ] Browser to remember for the specific subspaces whether a user had collapsed the panel when last leaving the page
- [ ] If much easier, also okay if browser remembers a user collapsing a panel in a subspace without it being that particular subspace. So when the user collapses/expands the panel anywhere, this is remembered.

## Additional Context
The story was extracted from: 
https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5893

Screen shots / UX designs / data that are relevant.
https://www.figma.com/file/XDWND6E1djfELwBfMa4U3u/Spaces-%26-SubSpaces?type=design&node-id=478%3A1238&mode=design&t=351XbJX6piw6N5ik-1

**Comment by bobbykolev** [comment]
A suggestion to persist the user choice for all subspaces for consistency was commented in the related story:
https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5893

**Comment by EmiliaPavlova** [comment]
Keeping the same expanded/collapsed state for all subspaces, based on [this comment](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5893#issuecomment-2082822023)

**Comment by Comoque1** [comment]
Behaves as per last comment.
