### ISSUE TITLE
BUG: Subspaces tab fails when the user is a member of the Space, the Subspace is private and the user is not a member

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#6083]
**Describe the bug**
Subspaces tab fails when the user is a member of the Space, the Subspace is private and the user is not a member

**To Reproduce**

1. Create a public / private space (with an Admin)
2. Create a  private subspace (with an Admin)
3. Log in with normal user
4. Join the space
5. Do NOT join the subspace
6. Navigate to the `Subspaces` tab on the `Space`
7. Exceptions are thrown, and no `Subspaces` are visible

**Expected behavior**
`Subspace` cards should be visible

**Comment by Comoque1** [comment]
Errors are not triggered and all challenges are visible on DEV env with the above scenario
<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0091064ca85dcb14501fe9bedc21cf10999a5dec/image.png" alt="image.png" />
