### ISSUE TITLE
BUG: Unable to create Event on mobile

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6087]
**Describe the bug**
Users are unable to create events on mobile. The Name input is hidden and the form cannot be submitted. 

ENVs - **All**.
Screen res - mobile < 600px.

**To Reproduce**

1. Go to space (on mobile)
2. Click on Create event
3. Select event type and see there is no name input and the form cannot be submitted.

**Expected behavior**
A name input should be present and the form creation should not be blocked.

**Screenshots**
<img width="368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c859cc698e573a3903abd92dea788473b79c5adc/image.png" alt="image.png" />

**Additional context**

**Areas that will be affected**
Event creation form.

**Comment by Comoque1** [comment]
Tested OK on dev env.
<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0s4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73ade9e8fc53f25802b51df097e14880ab41267d/image.png" alt="image.png" />
