### ISSUE TITLE
BUG: Community updates open from Space activity logs are pointing to 404 page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6106]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/subs-space/dashboard
2. Open space activity logs
3. Scroll to find a community update
4. Click on it - user is redirected to 404 page
<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8a62dea5cb22198acb5dc8e2f2cdc7ee82ffbfa/image.png" alt="image.png" />
<img width="1306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1tQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcbcd8af9fa8b3f70ca8de95c5e071934a37383a/image.png" alt="image.png" />

**Expected behavior**
Community update is loaded successfully.

**Comment by Comoque1** [comment]
The issue is still reproducible.
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1703565070c5623e06bc2fb7d84cab2726d70b73/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
These Community Updates are accessible through:

- Main Dashboard - "Latest Contributions in my Spaces"
- Space Dashboard - "Updates from the leads"
- Space Activity
- Subspace Activity
- SubSubSpace Activity

**Comment by Comoque1** [comment]
Works fine on DEV env.
