### ISSUE TITLE
BUG: inheritMembershipRights collaboration option is not exposed to the client

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6107]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/admin/spaces/subs-space/challenges/subspaces-publicc-7810/settings
2. Or go to a space settings - the collaboration setting `inheritMembershipRights` is missing on the client on challenge level
3. See the screenshot
<img width="1315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekduQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a983937180c3349e77d95cd4bf4b2edc61aba4c5/image.png" alt="image.png" />

**Expected behavior**
If we consider the current PROD behavior, this setting should allow/forbid space members to contribute to a challenge.
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemluQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f66f09537bf2c236d5fd19a59fc77637eb0a14b/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
As the entire "Challenge Authorization" page is now gone and we have the same settings page for spaces and subspaces, do we have a spec what should be present on a subspace level? Is it only the one described in the bug - `inheritMembershipRights` - or we should add the other options as well (4 on PROD). Do we need to strip something that should be available only on a Space level?
