### ISSUE TITLE
BUG: SubSpace admins can't access the admin settings - Restricted 

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6109]
**Describe the bug**
As a SubSpace admin (both Sub and SubSub levels) I'm unable to access the admin settings page. 

**To Reproduce**

1. Go to any SubSpace that you are an admin of it (and not global admin).
2. Click on the settings icon in the left navigation panel.
3. See the error page - Restricted

**Expected behavior**
The subspace settings should load.

**Screenshots**
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXl0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb0037570065e95795b4e511be06bc9416a5a3f5/Recording%202024-05-02%20121944.mp4)

**Additional context**

### It's happening because of the following reasons combined:
1. Space admins get ADMIN privilege on the platform
2. There is an ADMIN privilege on the platform (while there is PLATFORM_ADMIN privilege for that use case)
3. Client is checking ADMIN privilege for admin routes and not PLATFORM_ADMIN
4. Client is checking platform admin privilege for ALL admin routes and not just top level ones

Here are the links to the subspace and the admin settings:
https://acc-alkem.io/bobtestspace101/challenges/testsubspace-9802
https://acc-alkem.io/admin/spaces/bobtestspace101/challenges/testsubspace-9802

It seems that the client checks the platform level rights which are limited:

<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZ0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a429ff19918b8d27f5d5a02fb8a14b935e2cb68/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
The bug is persistent with my account on ACC. However, @Comoque1 & @EmiliaPavlova are unable to reproduce it.

@Comoque1 , please double-check and close if you think it's an isolated issue.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
