### ISSUE TITLE
BUG: Communities in the Profile are missing subspaces

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6127]
**Describe the bug**
On any user profile, the list of **Communities** includes **only Spaces**. For every subspace (challenge/opportunity), a duplicate of the parent Space is presented. 

**To Reproduce**

1. Go to any user's profile (part of a subspace community) e.g. https://acc-alkem.io/user/bo-ko-1562
2. There are only spaces under Communities with duplicates for every subspace the user is part of.

**Expected behavior**
The communities should **include** the **Subsapces** and there should be **no duplicated Spaces**.

**Screenshots**
<img width="1108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHE5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed6272d9ff26067383ec317a7e204c8a03fc4a07/Screenshot%202024-05-07%20144915.png" alt="Screenshot 2024-05-07 144915.png" />

**Additional context**
ENV - Acceptance, Dev (Subspaces Release)

**Comment by valentinyanakiev** [comment]
@hero101 @EmiliaPavlova this broke myProfile, and quite possible other pages...

**Comment by hero101** [comment]
@valentinyanakiev There is a not merged client PR

**Comment by valentinyanakiev** [comment]
@hero101  all merged and working now, closing
