### ISSUE TITLE
BUG: Returned users in global search cards are not clickable

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6149]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/admin/spaces?search-terms=Hessel+van+Oorschot
2. Scroll down to "Contributors"
3. Click on the returned user card - it cannot be clicked
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3pFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce8c871bce19c1b4a87b4f8bde95f3ec752db6d3/image.png" alt="image.png" />

**Expected behavior**
Contributors cards are clickable.

**Comment by bobbykolev** [comment]
Already fixed
