### ISSUE TITLE
BUG: The Search in Spaces Explorer is broken

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6153]
**Describe the bug**
I'm unable to search in Space Explorer getting a server error and no results on submit.

**ENV**
PROD 

**To Reproduce**

1. Go to alkem.io/spaces.
2. Type a search phrase in the search box and hit enter.
3. See the error.

**Expected behavior**
No errors and set of spaces and subspaces should be returned.

**Screenshots**
<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d65e2522b03bcc30c4db0b3da55d8f2308b72eb9/image.png" alt="image.png" />

<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5365c04b9fc2c40b6ed6f018b6458b0531d96006/image.png" alt="image.png" />

**Additional context**

**Areas that will be affected**

**Comment by Comoque1** [comment]
Tested OK on ACC env.
