### ISSUE TITLE
[Create Space] Delete space button

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6174]
## Description

As a creator of spaces (or admin)
I want to be able to delete a space.

_e.g. So that I can create a new free one._

## Acceptance criteria

- [ ] Delete Space block should be available under Space settings > settings (see screenshot).
- In Space
- In Subspace
- In Subsubspace: add empty settings WITH ONLY THIS DELETE BUTTON! NO OTHER SETTINGS! otherwise Evgeni will be unhappy.
- [ ] Show delete button if the user has DELETE privileges on the space level.
- [ ] Confirmation dialog to be presented to the user. 
- [ ] After deletion the user should be navigated to My Dashboard.

## Additional Context
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=1689%3A4498&mode=design&t=pszRHLnNzU3s5AUg-1
Screen shots / UX designs / data that are relevant.
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--289b2babbe5caa81428944fbfe0d80a9af027190/License%20V1.png" alt="License V1.png" />

## Areas that will be affected 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
After a chat with @bobbykolev I've updated the AC with regards to who can see the delete button.

**Comment by bobbykolev** [comment]
Hey @SimoneZaza , once again the visibility of the button was discussed and I updated the ACs.

The previously described logic should be applied on the server:

> The Delete button should be available to Space Host. If host is not a user but an organization, it should be visible to the owner of the organization. If this is a huge hassle (not sure if the owner of the org even has access..) fine to continue without the second part (org owner) for now and to raise another issue to approach this later.

The client will use the DELETE privileges provided on a account + space level.
