### ISSUE TITLE
Remove Magic URL button in Space invitations block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6201]
## Description

As a space/subspace admin, I don't want to see something that is breaking the design + not available to me

## Acceptance criteria

- [ ] Remove Copy Magic URL button from Invite others block in Community Settings

## Additional Context

<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2762fb0d083676c0d7eb45a981530b2f9d2ffe58/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1121" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a468a7bb48823dbfdfe40b230894a61e22522675/image.png" alt="image.png" />
