### ISSUE TITLE
BUG: Clicking on All Memberships on my dashboard, after applying to a subspace also shows the space application as pending

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#6237]
**Describe the bug**

**To Reproduce**

1. Apply to public space
2. Accept the application (from another user)
3. Apply to public subspace
4.  Click on All pending memberships in the homepage
<img width="477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67b4fd7e6459b0a7f4abbadeaa65aa0c2acf1e51/image.png" alt="image.png" />

**Expected behavior**
The space containing the applied subspace shouldn't appear here as an open application

**Screenshots**
<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55ce6bd3890d846906876669253ba2fc04a2347e/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
The issue is still reproducible for me on acc env.

**Comment by Comoque1** [comment]
Now is better. Tested on acc env.
