### ISSUE TITLE
Send invitation for specific role

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6239]
## Description

As an admin, I want to invite people directly as admin or lead, instead of waiting for them to accept the invitation before I can promote them to be an admin or lead.

## Acceptance criteria

- [ ] In Alkemio user invitation dialog, add dropdown for role as per design (same as for email invite)
- [ ] In email invitation dialog, add dropdown for role as per design (same as for email invite)
- [ ] Roles that can be selected, in this order:
- Member
- Admin
- Lead

## Additional Context
Related server issue: #3911
https://www.figma.com/design/y7EcC4ImZuFvbckKNdE1Vt/Invitations?node-id=97-2&t=8gQTybbc5S1NAn48-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza got a strong request to enable this from Denise, server PR just went up so please move the associated client work up in priority. Basically the admin can now specify an extra role when inviting a user to join a community, so the entry role (member) plus one other.

**Comment by SimoneZaza** [comment]
@techsmyth Ok, thanks, I've updated this issue with the right design. @bobbykolev can you estimate this issue?

**Comment by bobbykolev** [comment]
Sure, I'll look into it and I'll add an estimate.

**Comment by bobbykolev** [comment]
Setting 5 as I'm not sure whether the server peice is complete or it would need testing. Also it's time-consuming for both dev and QA testing. @SimoneZaza

**Comment by bobbykolev** [comment]
Hey @SimoneZaza , @techsmyth, the client supports the role assignment during the invite with the following PR:
https://github.com/alkem-io/client-web/pull/7025

However, note that the **server** currently supports ONLY passing a specific role for existing Users. The email invite (external users) is not supported.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
Test results: https://alkem.io/myspaceevgeni/challenges/qaandtesting/collaboration/testresults
