### ISSUE TITLE
BUG: Incorrect/double message on closed callouts

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6243]
**Describe the bug**
- 'Discussion closes'-message on posts that are closed without comments
- Double message on posts that are closed with comments
See screenshot below. The bigger message mentioning the Callout is using the correct logic: when there are no comments, don't show anything. When there are comments, do show this message. 
The other message in a smaller font is incorrect and should never be there.

**Expected behavior**
- [ ] Use style of newer "this discussion is closed" message
- [ ] Use logic and text as described below:

Let's discuss what the current behavior actually is and find the best solution. I suspect the "You can't reply to this discussion" is a more generic message that is also displayed in public spaces to people who are not a member. It would be best if we can use this message (nicer look&feel) to tweak it for different scenarios:

**All of this is only about comments, not about contributions like in a call for posts/whiteboards/links**
- Closed without comments, same for everyone:
_Nothing shown_
- Closed with comments, same message for everyone:
This discussion is closed so you can no longer comment
- Open, message for people who are not a member/not signed in: 
 You can't reply to this discussion since you're not a member of this Space

<img width="1057" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3dSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ae2f95570ddbd1a1a2470d61f2e4dfa20d96c1c/image.png" alt="image.png" />

**To Reproduce**

1. Create two posts
2. Add a comment to one of them
3. Close both (using the edit dialog)

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested on DEV env.
The messages are applied only for post callout.
The rest of the scenarios: post in call for posts are not covered.
