### ISSUE TITLE
Remove/hide location field from callouts in Subspaces

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6246]
## Description

As a user I no longer understand what this Location in the Edit dialog of a callout in a Subspace means, especially since I can't select anything other than DASHBOARD
<img width="1310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67e98a6fe098aad33859dc37e094b44e164aad2f/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Remove/hide location field from callouts in Subspaces

## Areas that will be affected 
 
Please note that this should not remove the field on Space level!!!

**Comment by Comoque1** [comment]
Tested OK on DEV env.
