### ISSUE TITLE
BUG: Wrong profile link if the host of the Space is User

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6251]
**Describe the bug**
The link of the Space host (About dialog) points always to /organisation route, leading to 404 / wrong page if the host is user.

**To Reproduce**

1. Go to space with user host
2. Click on About
3. Click on the host
4. See the error

**Expected behavior**
The link should point to the corresponding profile (user, org or VC in the future).

**Screenshots**
<img width="1227" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20034df3632354d5d70ab65b24260c1849b41652/Screenshot%202024-05-27%20170330.png" alt="Screenshot 2024-05-27 170330.png" />

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Closing as duplicate to: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6262
