### ISSUE TITLE
Space account page: setup

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6257]
## Description

As a user I want to be able to manage my VC, see my space subscription, etc. 

## Acceptance criteria
Account tab on **Root** Space settings with:
- [ ] URL/Visibility/Host information block 
- [ ] Delete block (keep the delete block in subspaces on Settings tab)

## Additional Context

Figma: https://www.figma.com/design/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?node-id=496-6&t=3efJ78j0HrVGTzLI-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Looks as per AC locally.
<img width="681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e0772bc038a0e02983139c6f5b43b0cec725177/image.png" alt="image.png" />
