### ISSUE TITLE
Use T&C text from the website in the T&C dialog, + update text

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6263]
## Description

As a T&C specialist, I can't point to a specific subset of the T&C that can be extracted into the dialog. Therefore the text needs to change to summarize the responsibility and then point to the full T&C directly.

## Acceptance criteria

- [ ] Update text to be:  I understand that as a host, I am responsible for all content within the Space. Click here to read more about the Terms & Conditions.
- [ ] Dialog to show content from https://welcome.alkem.io/legal/#tc . If this is a lot of work, skip the dialog and instead, open this page in a new tab.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
I'm leaving the behavior for opening the link in a **new tab** as we can't programmatically obtain only the T&Cs block from the welcome site. We can copy the entire text into translations but this would require some effort and doubling the information - change on one of the places would not change it in the other.  An iframe is also not an option, at the moment, as the welcome site doesn't allow it.

**Comment by SimoneZaza** [comment]
@bobbykolev 👍 thanks for looking into it!
