### ISSUE TITLE
Clean up Organization cards

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#6269]
## Description

As a developer I want a clean codebase

## Acceptance criteria

- [ ] To render an organization view with an Avatar and displayName/subtitle (location) 1 component is used

## Additional Context

Components to be merged/removed:

OrganizationCardHorizontal
OrganizationCard
ContributorCardHorizontal
LeadOrganizationCard

preferred component: ContributorCardHorizontal (newer/uses BadgeCardView)

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by EmiliaPavlova** [comment]
Removed components, all replaced with `ContributorCardHorizontal` :
- `LeadUserCard`, `LeadOrganizationCard` and `LeadContributorCard` - in [space]/community
- `OrganizationCard` - in user/[user]
- `OrganizationCardHorizontal` - in [space]/challenges/[subspace]/about -> Contributors -> More Contributors; [space]/challenges/[subspace]/opportunities/[subsubspace]/about -> Contributors -> More Contributors

**Comment by Comoque1** [comment]
The cards are opening/loading, but the look and behavior is different on different locations.
Raised a separate card for this to be addressed: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6674
