### ISSUE TITLE
Remove the Virtual Contributors creation from Global Administration

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6274]
## Description

As the VCs are created per Account and BoK, we don't need the VC creation through the admin. 
Let's keep the Virtual Personas there. The list of VCs could be replaced with a list of VPs

## Acceptance criteria

- [ ] On the Global Administration VC tab only the creation of Virtual Personas should be available.
- [ ] VC tab listing Virtual Personas.
- [ ] VC tab (Admin) listing All virtual contributors with links to their profiles.

<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3N0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2311df05fff7316d9fbeeec8a5e61b52c65fd38/Screenshot%202024-06-03%20131228.png" alt="Screenshot 2024-06-03 131228.png" />

**Comment by Comoque1** [comment]
Works as defined on ACC env.
