### ISSUE TITLE
BUG: Creating space from "My Dashboard" fails on Dev env.

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6276]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/create-space with beta user
2. Create a space from My Dashboard - error is thrown on dev env.
<img width="1447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--986be2cb736d0b948031456e8b7b5d122bd84002/image.png" alt="image.png" />

**Expected behavior**
Space is created successfully.

**Comment by ccanos** [comment]
Should be fixed when we merge https://github.com/alkem-io/client-web/pull/6285
