### ISSUE TITLE
Community Guidelines section in Space Templates

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6278]
## Description

As a space admin, I want to suggest a set of Community Guidelines for admins from the subspaces to use. 

## Acceptance criteria

- [ ] Add section in Space templates for Community Guidelines
- [ ] Library + Create button, behaving just like the other blocks 
- Library button opens dialog with templates from global library, that can be imported
- Create button opens create dialog. Creating a template from here saves it to the Space library

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested on dev env.
One bug raised: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6356
