### ISSUE TITLE
Show Community Guidelines in Subspaces

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6294]
## Description

As a subspace member I want to know what the Community Guidelines in this Subspace are.
As a user, I want to be able to find the same content in the same place, whether I'm on the Space or the Subspace level.

## Acceptance criteria

- [ ] Show community guidelines in subspace about dialog on the right side, below all other blocks
- [ ] Do the same for the space about dialog (move to the right, currently on the left)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested ok on DEV env.
