### ISSUE TITLE
BUG: Plans links on account page, point to incorrect location

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6305]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/vcs-callout/settings/account
2. Click on any link from license block - all of the point to 404 page instead to https://welcome.alkem.io/pricing-own-space/
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG92QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a65d082076d8f5a364d3a9f79f9d6b1653ba2027/image.png" alt="image.png" />

**Expected behavior**
Links point to : https://welcome.alkem.io/pricing-own-space/

**Comment by bobbykolev** [comment]
The links were updated in the server repo alkemio.yml file. @valentinyanakiev is this the source of truth for all environments or they are configured elsewhere?
