### ISSUE TITLE
Edit VC profile after create in dialog instead of page 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6309]
## Description
As Alkemio I want people to enrich their VC profiles
As a user I want to skip this part and just get started, I'm so curious about how this works! 
As a UX person I want people to know about the profile and all the things that are missing, but I want people to easily continue in their flow

## Acceptance criteria

- [ ] Open the 'edit profile' in a dialog, not in a separate page.
- [ ] …

## Additional Context
Extracted from:
https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6254

Screen shots / UX designs / data that are relevant.
https://www.figma.com/design/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?node-id=496-6&t=3efJ78j0HrVGTzLI-1

**Comment by bobbykolev** [comment]
Note that the **host** and **BoK** fields are omitted in the dialog. 
They are important in the VC's profile, but in this edit dialog the context is clear and they are redundant. 
@SimoneZaza

**Comment by SimoneZaza** [comment]
👍 thanks for the info

**Comment by Comoque1** [comment]
Behaves as per requirements:
<img width="1335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5RQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53aa7fb8bee0874128cd17845f7591264eb3d018/image.png" alt="image.png" />
