### ISSUE TITLE
Filter on just Subspaces in VC create flow

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6310]
## Description
As a user, I want a clear way of creating a VC, not having too many options
As a PO, I want people to use a Subspace as a body of knowledge, not a root Space

## Acceptance criteria

- [ ] Only show subspaces as options to choose from when creating a VC
- [ ] No subspaces? Show text: Create a Subspace first, and populate it with the relevant information for your Virtual Contributor.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Note that to handle the requirements I decided to disable the button and place the text below it. I don't think that opening the form would make more sense. @techsmyth @SimoneZaza FYI
<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1EwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fb3b0ef3420cda5b8b025c6afedfc3e41f7e8f6/Screenshot%202024-06-04%20150637.png" alt="Screenshot 2024-06-04 150637.png" />

**Comment by SimoneZaza** [comment]
Perfect!
