### ISSUE TITLE
Community: Allow inviting a VC to invite to their space

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6317]
## Description

As an admin, I want to have a path to add other VCs to my space

## Acceptance criteria
On the dialog that is shown after clicking "invite VC":
Store section: 
- [ ] Display a list of VCs that are using the platform.library.virtualContributors query
- [ ] Allow the user to search within the list using the search box
- [ ] Allow the user to click the plus button to open the invite dialog where they can add a message, with a button to also go back

## Additional Context
The invite by URL functionality was extracted here: https://github.com/alkem-io/client-web/issues/6480

## Design
https://www.figma.com/design/oKRFyc7P9WwlNyIWAiiHKf/Inviting?node-id=76-284&t=FMEAi1gdenS9hEn9-1

**Comment by techsmyth** [comment]
@jeroentskui @bobbykolev  is this ready for develop or more design work needed?

**Comment by bobbykolev** [comment]
> @jeroentskui @bobbykolev is this ready for develop or more design work needed?

No design is needed as stated in **Clarifications**. We'll reuse what we can from the existing flows.

**Comment by techsmyth** [comment]
Ok, I was confused as the Product Team label was still there...and those issues often get filtered out.

**Comment by Comoque1** [comment]
Tested OK locally.
- The last point - "back button" on add dialog is missing and added it as point to the story #6480
