### ISSUE TITLE
BUG: When admin change innovation flow to one with only one state, callouts are not displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6319]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:3000/111/challenges/test-subspace/index
2. Create a space
3. Create innovation flow with 1 state only
4. Create a subspace with default innovation flow - it has callouts displayed
5. Change the subspace innovation flow  to the one with only one state - the callouts are not displayed
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzAwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5769e60df6089f238d30f1490206283c7243db65/image.png" alt="image.png" />

**Expected behavior**
Callouts are displayed.

**Comment by bobbykolev** [comment]
Note tha the bug is not related to the amount of states.
When you switch to a Workflow that doesn't have the same Preselected State, the new flow loads but you need to **explicitly select the state** in order to load its contents (even it it's just one).

**Comment by Comoque1** [comment]
Tested OK on DEV env.
