### ISSUE TITLE
BUG: Control flowing outside of panel area

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#632]
**Describe the bug**
Navigate to demo.cherrytwist.org
Search on innovation
Click on Roche Pharma

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4c8819dd-b6c6-4cc3-b7b0-82c4e8920c68)
*

**Comment by atstojanov** [comment]
Maybe full redesign of the popup and even removing the pop (bad practice nowadays, doesn't work well in mobile).
