### ISSUE TITLE
Update links to policies

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6320]
## Description

Updating the links on the platform to the correct pages (to be added)

## Acceptance criteria
- [ ] Footer: Terms, Privacy (Add button for cookies?)
- [ ] Sign up page
- [ ] Create a Space dialog
- [ ] Adding references to post (in call for post)
- [ ] Adding references to collection of links

Other places on the platform that are linking to </terms> ?

**Comment by SimoneZaza** [comment]
@larssondenise is this also something that still needs to be done? I checked the footer and adding references to collection of links but these seem correct?

**Comment by larssondenise** [comment]
@SimoneZaza yes double checked, and we kept the old links so should all be good!
