### ISSUE TITLE
Update users on updated policies

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6321]
## Description
As we have updated our terms and conditions, we need to inform our users. Tbd how to do so

## Acceptance criteria

- [x] Make small changes to T&C and Privacy Policy and adjust latest update date
- [x] Design pop-up for user

https://alkem.io/building-alkemio-org/challenges/termsconditions-4330

## Additional Context
options:
- Email notifications to all registered users.
- Announcements on the Forum
- Pop-up notifications when users log in (requiring them to review and accept the new terms)

**Comment by SimoneZaza** [comment]
@larssondenise I've created a new issue for the second AC, is the first one already done?

**Comment by larssondenise** [comment]
@SimoneZaza Will make them when we set the release date for the pop-up!

**Comment by SimoneZaza** [comment]
@larssondenise this will be included in the next release :)
