### ISSUE TITLE
BUG: wrong link to contact support

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6333]
**Describe the bug**
On the account page, the link to contact support to change the basic settings points to the wrong URL:
<img width="1485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGs3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--716956e79fe0bed3cc6fd029e2dcf1ab40bec851/image.png" alt="image.png" />

**To Reproduce**

1. Go to Space settings > account
2. Click on If you want to change any of these settings, please contact the Alkemio team here.

**Expected behavior**
- [ ] Link to be in the translation file so the product team can update it (eg when we start having more specific contact forms)
- [ ] Link to point to https://welcome.alkem.io/contact/

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by techsmyth** [comment]
Still an issue?

**Comment by bobbykolev** [comment]
fixed on PROD
