### ISSUE TITLE
BUG: Community Admin - the profile link of Member Organization is wrong if the host is User

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6342]
**Describe the bug**
If the host of a space is user, than the link to its profile is broken, pointing to /organization/:nameID.

**To Reproduce**

1. Go to any space hosted (created) by user
2. Go to Space->Settings->Community-> Host Organizations section
3. Click on the Host (user)
4. See 404 no such page

**Expected behavior**
The profile of the contributor should be presented (/user, /organization or even /vc in the future).

**Screenshots**
<img width="654" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a27d70bcec37da03fe1b81aea40b5d6e9726022f/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on DEV env.
