### ISSUE TITLE
BUG: When user is on callout template and by mistake goes through "Call for WB" to "Update" button, he cannot click it, as the tooltip doesn't disappear

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6347]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/public-space/settings/templates/callout-templates/d64ace3a-d46e-4951-b607-b9f0ac084ba4/edit Or open in edit mode callout template in edit view
2. Using the mouse move from "Call for WB" disabled button to "Update" button - tooltip doesn't hide and user cannot click update button
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--494fb03309d75f2d5e6599baa25ff3e0ed592fe3/image.png" alt="image.png" />

**Expected behavior**
Tooltip hides when user moves mouse outside of "Call for Whiteboards" button.

**Comment by bobbykolev** [comment]
Let's discuss this with @SimoneZaza It's unpleasant but not blocking.

**Comment by SimoneZaza** [comment]
I'm afraid this will happen quite often since the shortest path from editing the title/description to the update button is very close to the call for whiteboards.. Is it possible to move the tooltip on top instead of below the button? Or anything else that helps :)

**Comment by Comoque1** [comment]
Much better experience on DEV env.
