### ISSUE TITLE
BUG: Openning community guidelines card, redirect user to 404 page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6351]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/innovation-packs/inno-pack-1/settings or any inovation pack with GA
2. If there is no `Community Guidelines Template` template create one
3. Click on the card
<img width="1147" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU5GQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0ca8cb2ad6e423ed5135d294cdbc73c67952b48/image.png" alt="image.png" />

4. User is redirected on 404 page
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--796534802e1ebc2f0eb95a81e97b716cdb8bd0be/image.png" alt="image.png" />

**Expected behavior**
The card is open in preview mode

**Comment by bobbykolev** [comment]
This issue is connected to the missing Edit Community Guidelines dialog which is in progress:
https://github.com/alkem-io/client-web/issues/5923

**Comment by ccanos** [comment]
blocked until we have the edit CG template dialog fully merged to develop

**Comment by Comoque1** [comment]
Tested OK on DEV env
