### ISSUE TITLE
BUG: Opening collaboration tool template cards on innovation pack lead to 404 page 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6353]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/innovation-packs/march-22/settings
2. Create (if there are no ) any Collaboration Tool Template
3. Click on the card
<img width="1347" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f331a764628cb164d22848bf500e84bcc1daf485/image.png" alt="image.png" />

4. User is redirected to 404 page
<img width="1154" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1129cee1351bf7d16009f20a7aa502ca9c443ff4/image.png" alt="image.png" />

**Expected behavior**
Clicking on Collaboration Tool Template card opens a preview dialog.

**Comment by bobbykolev** [comment]
The issue was fixed. However the Update is not possible due to the follwing bug:
https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6349

**Comment by Comoque1** [comment]
Tested OK on DEV env.
