### ISSUE TITLE
BUG: Visual cannot be inserted in a VC description

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6355]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:3000/vc/111/settings or to a VC that you can edit
2. On the Description field click on "Add visual" icon
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aae6dd626c398a2f107bbe2e534feba3a47d7323/image.png" alt="image.png" />

3. Attach button is not displayed on the dialog
<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8611ef24246663f47da91d1309eb728aaf3f54fa/image.png" alt="image.png" />

**Expected behavior**
Attach button is displayed and user can add successfully visual to the VC.

**Comment by EmiliaPavlova** [comment]
Cannot reproduce this.
<img width="1352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEd0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bd1a79bc2b6c9dfdccf63dfa60ededfbae928c7/Screenshot%202024-07-03%20at%2010.30.00.png" alt="Screenshot 2024-07-03 at 10.30.00.png" />

<img width="1352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEt0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176e99f604dff6a297e57ab0beed44ed7a50a773/Screenshot%202024-07-03%20at%2010.32.14.png" alt="Screenshot 2024-07-03 at 10.32.14.png" />

**Comment by Comoque1** [comment]
Cannot reproduce on ACC env as well.
