### ISSUE TITLE
When lead and host are the same user, only show user card once in welcome block

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6364]
## Description

As a host who also has a lead role in my Space, I don't want my user card to show up twice in the welcome block on my Space dashboard.

<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5MQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ca8ea4c82dafc3f7120751284ac96c07f5f949d/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Check if the lead is the same user as the host, if so, don't show **this** lead (nb there may be more leads who do need to be shown)
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
