### ISSUE TITLE
BUG: Signout button is not displayed in sandwich button, when browser width is sized down

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#637]
**Describe the bug**
Signout button is not displayed in sandwich button, when browser width is sized down.

**To Reproduce**

1. Go to https://demo.cherrytwist.org/
2. Authenticate with any user
3. Decrease the browser width to 584x985
4. Click on sandwich menu button: sign out option is missing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e5f86a7b-e607-41d7-bc13-23373eae9990)

**Expected behavior**
Sign out button must be available, no matter width of the screen.

**Comment by atstojanov** [comment]
N/A anymore
