### ISSUE TITLE
Selection of visual assets for ecoverse/challenge/opportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#638]
## Description

As an admin I would like to be able to upload the visual assets that are used to display the ecoverse/challenge/opp

## Acceptance criteria

- [ ] On the admin page, the user can select a file to upload for usage as the avatar/background/banner
- [ ] Server api expanded to support the requests, verifying the dimensions / file types being uploaded

## Additional Context
TBD: 
- what are the dimensions / ratios?
- is the upload generic - we can't use uploadAvatar?
- do we create a new reference entity, e.g. VisualReference

**Comment by FloriSpoelstra** [comment]
I often have images that are bigger than the banner ratio. Most of the time the auto-crop is fairly decent but I would prefer to have the option to crop the picture myself (by dragging it around in a frame that indicates what part of the picture will be used). 

It is not a very big deal, but would help to make it all a bit prettier.
