### ISSUE TITLE
BUG: Preview of Collaboration tool from Post callout type shows: WB

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6386]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/wb-activity/settings/templates
2. Or 
3. Navigate to Space / Settings / Templates
4. Create Collaboration tool "Post" callout
5. Open the card, so that the preview is visible: WB preview is displayed
<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzlTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65803565d766e81177a1527422958f052a4d9048/image.png" alt="image.png" />

**Expected behavior**
TBD

**Additional context**
The issue is reproducible for both Space and Library templates

**Comment by bobbykolev** [comment]
The issue was caused by the bug of creating callout templates with a whiteboard object. Any newly created ones will work/display as expected. (after 6391 is merged)

**Comment by Comoque1** [comment]
Looks OK on DEV env.
