### ISSUE TITLE
BUG: Updating collaboration tools templates on Library fails

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6392]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/innovation-packs/workable/callout-templates/e970b435-84e4-4a96-97ce-a988a7189b31
2. Open any of the following collaboration tool callout template types: collection of links, post, call for whiteboards
3. All of them fail: `"message": "Variable \"$template\" got invalid value \"\" at \"template.framing.whiteboardContent.content\"; Value is not valid excalidraw content definition: Unexpected end of JSON input",`
<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce9e7f29acbd2c5e0dc0834b725a1f6026ebaf9b/image.png" alt="image.png" />

**Expected behavior**
Templates can be updated.

**Comment by Comoque1** [comment]
The issue is still reproducible on DEV env.:
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--713aed8036a11fdc059c6b1351e453f3f4db91b8/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
Ok, we're getting this error on the Whiteboards and Whiteboards collections when you didn't edit the Whiteboard.

**Comment by Comoque1** [comment]
Just tested it on DEV env and it works fine for all types
