### ISSUE TITLE
Authorization policy visualiser + evaluation for a user

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6402]
## Description

As a developer, I want to be able to visualize a particular authorization policy and the results for a user

## Acceptance criteria

- [ ] New page under platform administration which allows for a) entering an authorization policy UUID and then visualizing the contents of that policy (credential rules, privilege rules etc) b) selecting/searching a user and getting the privileges that user would receive for the specified authorization policy 

## Additional Context
The required server queries are already present: 
- lookup.authorization
- lookup.authorizationPrivilegesForUser

**Comment by Comoque1** [comment]
Tested OK on dev env.

**Comment by techsmyth** [comment]
Raised a separate issue as I am not seeing a way to select a user to evaluate + get their privileges
