### ISSUE TITLE
Temporary storage of content to allow proper Link / Reference creation

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6404]
## Description

As a user I want a clean experience
As a developer I want simple logic

## Acceptance criteria

- [ ] The creation of links, or references, should only take place when the actual Create call is made
- [ ] After the create takes place the Document should be moved to the new storage bucket 

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
The performed testing was against ACC env and was limited to creation of 1 entity from different types (i.e. Subspace, callout, template on space, etc... ).
A couple of bugs have been raised and linked to the [epic](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/alkemio/1435), where each has impact on different areas over the application.
In the attached [file](https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Contributors/Shared%20Documents/Development/Scenarios/Release%20-%20Simple%20Home/temporaryStorage.xlsx?d=w2e5276baccea4a6cb3f1a1f0871f0fe9&csf=1&web=1&e=cAWIwZ), can be found what has been tested and the related issues.
