### ISSUE TITLE
Allow to move back to contributing as opposed to viewing after inactivity on a whiteboard

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6416]
## Description
As a user I want to go back into edit mode on my whiteboard without reloading

## Acceptance criteria

- [ ] Allow going back to edit mode on a whiteboard after it is turned read only due to inactivity
- Add button: Continue Editing

## Additional Context
Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Tested OK, but the text appearing on the "view more" dialog, is misleading
<img width="1379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0da673a599bdc336f3b92794f09eb923bed2bb6/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Also continue button is shown, in the case when max users is reached - the button should not be displayed, but admins should be contacted
<img width="1503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f4938811f46a2d5b3eedc7caedf411bb964c3a2/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 the first one is a translation entry, please just ping Denise for what to put in there. The second one needs more work, please raise a separate issue for it.

**Comment by Comoque1** [comment]
@techsmyth talked to Denise and raised: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6459

In my opinion, it should be addressed with priority, as it is likely to happen to users.
