### ISSUE TITLE
Display + accepting of Virtual Contributor invitation

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6417]
## Description

As a provider of a VC, I want to be able to see on the platform when  new invitation is made for the VC

## Acceptance criteria

- [ ] Above recent contributions, add block with invitations and applications for spaces, and invitations for virtual contributors
- [ ] Opens dialog with ability to accept invitation for VC
- [ ] ...

## Areas that will be affected 
 
_To be added during the refinement_

https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=0-1&t=bc2E1yaiBETeCFZJ-1

**Comment by bobbykolev** [comment]
We should revise the copy of the invitation so it's clear that it's a VC one. @jeroentskui , please have a look. 

<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--003f970d184be6102c364016a4c2b0e0f515c9b0/Screenshot%202024-06-21%20184200.png" alt="Screenshot 2024-06-21 184200.png" />

**Comment by bobbykolev** [comment]
A question on the widget with pending invites and spaces on my dashboard - "Spaces & Subspaces _Open invitations_". 
Could we go without the VC treatment?
Currently, the logic behind this widget is heavy, displaying **pendingCommunityInvitations**, **recentPendingApplications**, **mySpaces**, **recentMemberships** etc.

The VC invites will be shown as the others and once you open a VC one, you'll be presented with the dialog relevant for this type of invite.
@jeroentskui @techsmyth
