### ISSUE TITLE
BUG: VC refers to post that doesn't exist

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6418]
**Describe the bug**
In the answer given by my VC refers back to a post that doesn't exist (has never existed?), which makes me question where it picks up information.

**To Reproduce**

1. Go to https://alkem.io/suzannedemospace/challenges/project/collaboration/example
2. And see a reference to [Post] TEst test
3. Click on it, see that it does not exist.
4. This also happens after recreating the VC, when being sure the test post is not in the subspace

**Expected behavior**
The answers should be based on actual contents of the space. TBD: information related to data freshness?
Only relevant links should be provided and this callout never had any meaningful contents.

**Comment by techsmyth** [comment]
@larssondenise which VC in particular gave this response?

**Comment by larssondenise** [comment]
@techsmyth both Marketing strategy & Marketing strategy 2!
