### ISSUE TITLE
Add user as host of a Space

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6424]
## Description

Now that it is possible to have a person as a host of a Space, I also want to be able to change the host to a person

## Acceptance criteria

- [ ] via the platform administration, I can change the host of a Space to both persons and organizations

## Additional Context
Otherwise I cannot make people host of the Space in which they will make the VC
<img width="1585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjl4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9ebd2501be24afccbbc605ae3237c6ef6c841cb/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Details from the PR:

>  All organizations are visible in the dropdown, while users are displayed on entering search value (max 10 users matching the search term), sorted ASC. There's also a visual indication - Organization/User.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
