### ISSUE TITLE
VC Profile Settings: tab for settings

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6438]
## Description

As a provider of a VC, I want to be able to control the visibility of the VC

## Acceptance criteria
- [ ] Additional tab for "settings"
- [ ] Allow selecting the type of searchability - **Public** / **Private** (ACCOUNT) / **Hidden**
- [ ] Toggle for whether the VC is displayed in the store

Additional logic added:
- [ ] disable the Toggle for store/library if the visibility is not Public

Nice to have:
The bold text to be the label of the radio button /switch. The normal text to be selectable (not clickable) if possible. (to be extracted)

## Additional Context
Mimic the settings tab from spaces.

## Design:
Use the ACs in case of differences in the design. 

https://www.figma.com/design/WFcbewbnhPqYpGBzBJaPq1/VC-Profile-Settings?node-id=3-6244&t=4ddKM2O5XZJu1jv9-1
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLytCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2eb9acaad2ff91aa1ef95e006f908f36da7bcbaf/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
Notes:

In addition to the requirements, the following change was made:
- if the visibility status is not Public, then the Listed In Store option is disabled. 

The nice-to-have label requirement will be extracted as separate story as it requires major changes in a shared component.
