### ISSUE TITLE
BUG: error message displayed to user is missing information from server

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#644]
**Describe the bug**
Invaluable error message is thrown, when user try to create project with short nameID

**To Reproduce**

1. Go to https://dev.cherrytwist.org/ecoverses/
2. Use admin user
3. Create challenge, opportunity and navigate to the opportunity
4. Create a project with short name (i.e. 'tt') 
5. The following error message is thrown: `Response not successful: Received status code 400`, but should be something like: `Project title is less then the required symbol number`

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a27ce8f0-5839-40be-a36f-5ffa66800b02)

**Expected behavior**
Meaningful error message is thrown, when creating project with short name

**Comment by techsmyth** [comment]
This is tied to error propagation from server to client. 

Ideally the server should always return http 200 and then inside the response detect the error message to give.

**Comment by techsmyth** [comment]
This error to be fixed with validation on the input on the form

**Comment by techsmyth** [comment]
Server should be http response code 200, not 400
