### ISSUE TITLE
My Account block on My Dashboard page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6447]
## Description

As a user I want to be prompted to create a Space
As a user I want to be prompted to create a new VC on my dashboard

## Acceptance criteria

On my Dashboard
- [ ] block _Spaces & Subspaces_ to become _My Account_, including your hosted spaces and VCs owned (supporting only one space and one VC for now);
- [ ] When there is no Space and/or no VC, buttons to create them.
- [ ] If there is not yet a Space, VC create button is greyed out with message that you need a Space first.
- [ ] Create new Space triggers the existing new Space flow.
- [ ] _Create new VC_ button starts the new create VC flow (see design).
- [ ] The creation of Space/VC should be available only of users with platform privilege to CREATE.
- [ ] My Dashboard rearrangements:
   - [ ]  The My Account block is always visible on the top left for authenticated users;
   - [ ]  The Spaces Subspaces block goes as 3rd on the first row;
   - [ ]  The Start a Space banner no longer exists;

## Additional Context
https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=0-1&t=Z8cNkR277uNO8ZGi-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by EmiliaPavlova** [comment]
Last two bullets (the VC flow and invitations block) will be covered in another tickets.
