### ISSUE TITLE
[Technical] Implement tabs in VC profile

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6448]
## Description

As an owner of VC I want to be able to switch between tabs in VC Profile Settings

## Acceptance criteria

- [ ] Tabs Profile, Memberships, Settings, should be available under VC Profile Settings

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by ccanos** [comment]
will be tested together with the rest
