### ISSUE TITLE
BUG: Authentication fails on dev env

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6458]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Clean cookies
3. Authenticate - new session and csrf token are generated, but page fails to load to the user
<img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd2981246efd73edd27bc9386203de72bb100bd4/image.png" alt="image.png" />

**Expected behavior**
User authenticates successfully on dev env.

**Comment by techsmyth** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21JQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1916fdbfeb957dec6e008185b42df40389c630f3/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
The question is what is the client logic that results in it trying to register the user?
