### ISSUE TITLE
BUG: VC profile, doesn't show from where BoK is retrieved

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6463]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/vc/j25-2
2. Knowledge says: Answers j25-2 gives are based on the body of knowledge coming from:
<img width="1213" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e476b19271437838d92a5dd196852badf5c35ab5/image.png" alt="image.png" />

**Expected behavior**
BoK is returned

**Comment by bobbykolev** [comment]
It's also missing from the Edit Profile settings. It's related to the latest AI arch changes.

**Comment by bobbykolev** [comment]
As things are changing and we're not going to link a VC to a "Body Of Knowledge" Sub Space, we'll need refinement on the VC profile sections related to it.
