### ISSUE TITLE
Add VC as lead in Knowledge subspace

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6474]
## Description

As a user I want to be able to quickly navigate to my VC so I can trigger a refresh

## Acceptance criteria

- [ ] After creating the VC, add the VC as a member + lead to the chosen subspace

## Additional Context
the server PR + logic should be there, with the caveat that this works if both the VC and the subspace are part of the same Account.

**Comment by bobbykolev** [comment]
Can we just list the VCs associated with the account on the About widget instead of making them leads? @techsmyth
