### ISSUE TITLE
Add button to allow refreshing ingestion for a VC

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6478]
## Description

As a VC provider I want to have control on the data freshness in my VC

## Acceptance criteria

- [ ] Add button to VC settings to allow refresh of body of knowledge

## Additional Context

Screen shots / UX designs / data that are relevant.

https://www.figma.com/design/WFcbewbnhPqYpGBzBJaPq1/VC-Profile-Settings?node-id=3-6244&t=HgoumGvQHpyZwQj4-0

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Maybe not for this phase but we should plan a limit/cooldown per reingestion for a VC (minutes/hours/days). @techsmyth

**Comment by techsmyth** [comment]
@bobbykolev for sure this will be needed...can you already add an issue so we track it?

**Comment by bobbykolev** [comment]
Done: https://github.com/alkem-io/server/issues/4164
Please assign to the correct epic, @techsmyth

**Comment by Comoque1** [comment]
Tested OK on ACC env.
