### ISSUE TITLE
Use feature flag to enabled new communications page vs existing page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#648]
## Description
As a client user I want the communications enabled / disabled as per server settings

## Acceptance criteria

- [ ] use new server api feature flag to show new page for communications if enabled

**Comment by Comoque1** [comment]
Tested OK on local env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e3a683eb-f8fb-4ff6-8372-ac5617f6e0f7)
