### ISSUE TITLE
VC community invite with URL

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6480]
## Description

As an Admin user, I want to be able to invite a VC to my community via its profile URL.

## Acceptance criteria

- [ ] Allow the user to enter the URL to the profile of a VC that they want to invite. 
- [ ] The same invite flow should be presented as the external one - invite from Platform Library.
- [ ] Allow the user to click the plus button to open the invite dialog where they can add a message.

## Additional Context
Extracted from:
https://github.com/alkem-io/client-web/issues/6317

Screen shots / UX designs / data that are relevant.
Note that insead introducing new search/result, we're reusing the current search and results table.
https://www.figma.com/design/oKRFyc7P9WwlNyIWAiiHKf/Inviting?node-id=76-284&t=FMEAi1gdenS9hEn9-1

**Comment by bobbykolev** [comment]
With this implementation it would be trevial to add URL support for adding memebers to community (user & Orgs).

**Comment by Comoque1** [comment]
Tested OK on DEV env.
@techsmyth @SimonDoherty1234 I am closing this story, as the AC is met, but with the current server/client implementation only **public and listed** vc can be invited. For hidden it is not the case.

If it should be extended, we can raise another story.
