### ISSUE TITLE
Updates in Spaces & Subspaces block on My Dashboard

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6491]
## Description
As a user I no longer need the My Spaces section in Spaces & Subspaces Block on My Dashboard.

## Acceptance criteria

- [ ] Remove the My Spaces section;
- [ ] Rename the block to My Invitations;

## Additional Context
Extracted from:
https://github.com/alkem-io/client-web/issues/6447

Screen shots / UX designs / data that are relevant.
Design part of the VC creation flow:

https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=25-8261&t=fhaQESOTo12Hxo0C-0

**Comment by Comoque1** [comment]
Tested OK on acc env.
<img width="1542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21nQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--094c22a472a1e79742208896696aaaeff3a6786e/image.png" alt="image.png" />
