### ISSUE TITLE
Display Lead VCs in About section of Space/Subspace

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6495]
## Description

Display Lead VCs in the About section of Space/Subspace

## Acceptance criteria

- [x] A newly created VC should be displayed as a lead in its BoK in the Description block (top left on the subspace page);
- [ ] There should be a distinction between User/Org and especially VC leads / associated VCs (TBD);
- [x] The lead VCs should be displayed in the leads section of the About dialog - https://github.com/alkem-io/client-web/issues/6516

## Additional Context
Note that in the following PR: https://github.com/alkem-io/client-web/pull/6498
the VC associated with the BoK Subspace was displayed only in the description block, as a quick fix for the VC Creation Flow MVP.
Also, the VC is set to be a lead of this BoK again as a workaround to quickly have its profile (link to it) on the BoK page. 
Refinements on the VCs treatment into Space/Subspace are pending.

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by valentinyanakiev** [comment]
<img width="824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11ac1ef0b1463c15a1f6de5f330b831ba4811f51/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
Linking a bug as part of this story:
https://github.com/alkem-io/client-web/issues/6516

**Comment by bobbykolev** [comment]
Closing this one as the main points are done.
It's good to have a marker for a VC lead. Also, there's no support of VC lead on a space level. And there's no way to remove / set a vc as lead.
