### ISSUE TITLE
BUG: After accepting invitation, invitation dialog stays

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#6514]
**Describe the bug**
After accepting an invitation, invitation dialog stays

**To Reproduce**

1. Invite a user to a space
2. Under that target user, accept the invitation

**Expected behavior**
Invitation dialog closes

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by EmiliaPavlova** [comment]
The dialog stays on screen after accepting the invite. 
<img width="1423" alt="Screenshot 2024-07-05 at 18 05 53" src="https://github.com/alkem-io/client-web/assets/10547231/d29f0ee1-b2fa-47f5-a0a0-71d15b059bb5">
