### ISSUE TITLE
BUG: Display lead VC in About dialog

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6516]
**Describe the bug**
If a BoK subspace has a VC lead, display its profile card into the About dialog.

**To Reproduce**

1. Go to BoK subspace
2. Click on about
3. See there's no VC listed in lead even if there is one.

**Expected behavior**

**Screenshots**
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--680cbdc998674a37944d66868653965052dc9d0e/image.png" alt="image.png" />

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by bobbykolev** [comment]
The VC leads were added to the Subspace About dialog. Latest components were reused (instead of depricated ones) so the avatar has slightly smaller border radius. Once we migrate the other profile Avatars (users, orgs) they will be consistent.

<img width="1228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8732fc06e3116c8c778350854af3c517c91a1c0c/Screenshot%202024-07-01%20175205.png" alt="Screenshot 2024-07-01 175205.png" />

**Comment by Comoque1** [comment]
Tested OK on ACC env.
