### ISSUE TITLE
Bucket: VC creation flow refinements

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6519]
## Description

As a community manager I want the flow for creating a VC to be easy to follow for newbies

## Acceptance criteria

- [ ] tbd

Note: the amount should be driven by licensing, but for the purpose of unblocking this story we start with 3.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
Replaced by #6602 and others
