### ISSUE TITLE
Threaded interactions UI adjustments 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6520]
## Description

With the new threaded interactions, it is impossible to interact with multiple VCs in one thread (see sketch below for terminology, **each thread can hold 1 vc-interaction**). As a user, I want to understand this when I'm interacting with VCs. 
<img width="566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTdEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bcc17bf1c0715ead51fca6f6dc9a6411bc28110/image.png" alt="image.png" />

## Acceptance criteria

- [ ] When there is no vc-interaction in a thread yet, any available vc can be mentioned like currently is the case
- [ ] When there is a vc-interaction in a thread and a user tries to mention another vc:
- show vc in dropdown in disabled/muted/non-clickable state
- add text: Create a new comment to interact with another VC (neutral color, darker than the VC name and label, or a different way to stand out a bit)
- add tooltip: You can only interact with one Virtual Contributor per thread (comment + 'sub’comments). If you’d like to engage with another VC, start a new thread by creating a comment in the bottom input field.
- When user clicks on this vc, nothing happens
- [ ] …

## Additional Context

<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d164bc35153fb60a719b530d48e220e8dce7e562/image.png" alt="image.png" />
Add text below the Virtual Contributor tag, tooltip when user hovers over the card

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza for clarity: one VC in the thread, at the start but also further down?

**Comment by SimoneZaza** [comment]
@techsmyth I would actually prefer not to restrict at all, but as I understood it this was a technical requirement. Just to be sure, below a sketch of how I understand the terms post/comment/thread. Or does the thread also include the first comment? 
If we restrict I would either go for '1 VC in the thread, everywhere in the thread'  or '1 VC per message (comment or inside the thread). The latter would allow for multiple VCs in 1 thread, which would be very interesting..  

<img width="551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0bb1db01a3ec3abdb3a38bf974e77dd13bcffd8/image.png" alt="image.png" />

**Comment by valeksiev** [comment]
The behaviour in the AC can not be achieved as putting a tag suggestion in _disabled_ state is impossible with the library we use for mentioning. I implemented an alternative flow, achieving the same limitations.
1. When a _root_ comment is being composed the completion list looks as-is:
<img width="1868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0h1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f51665d80deba8d9740c71afe7d5c2fd156d3d0/image.png" alt="image.png" />
2. When replying in a thread with VC already involved, a message above the list is displayed with a _help_ tooltip with further explanation:
<img width="546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2p1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4076a02129d8da62103a56a65240ccd63c5d5785/image.png" alt="image.png" />

3. When replying to a thread without a VC involved the suggestion list is as-is:
<img width="1812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3Z1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea494460f989b127fd82afaa80d785d27bc5eaad/image.png" alt="image.png" />

**Comment by valeksiev** [comment]
There is a logic which disallows tagging the same person twice, which was not working, and I fixed it as I was already touching the components. 

Unfortunately, now it's misbehaving - should we discuss and try to tidy it up as part of this or should I _break_ it again and track it separately? cc @SimoneZaza @techsmyth

**Comment by valeksiev** [comment]
After a discussion with @techsmyth it was decided to disable VCs for event comments.
