### ISSUE TITLE
Remove Open Invitations 

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6528]
## Description

As a user I do not need to see the Open invitations block in case of no invitations. 
If I joined a Space, especially when I already joined months ago, I do not need to see it in recently joined. I already see my Spaces on the top.

## Acceptance criteria

- [ ] Do not show open invitations block when there a no invitations (VC and Space)

Note: This also means not showing the recently joined spaces. Users can find their Spaces by navigating to the 'Explore all Spaces block'. For the VC they will find it on the VC profile.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Note that after the first accepted invite on the platform, a full page reload is needed in order My Memberships block to be displayed. Besides that, it seems that recent memberships is redundant in the Invitations block.

**Comment by bobbykolev** [comment]
@larssondenise, please review the screenshots in https://github.com/alkem-io/client-web/pull/6530 and let me know if we cover everything as expected.

**Comment by larssondenise** [comment]
@bobbykolev amazing! I also see My Latest Contributions block is shown when there are no contributions. Explicit choice? Otherwise I'll also add it to the board as a new issue to remove them in case of no contributions

**Comment by bobbykolev** [comment]
@larssondenise , let's extract it in a separate task 🙏
