### ISSUE TITLE
BUG: The subspaces in VC creation flow are not refreshed after creation of VC

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6532]
**Describe the bug**
When I try to create a second VC, the option for using existing SubSpace is disabled. I need to refresh the page in order to be able to select already existing SubSpace (created during the creation of the previous VC). 

**To Reproduce**

Preconditions - use account that has a space and no VCs;

1. Go to My Dashbaord and Create a VC.
2. Then try to create another one.
3. Only the option for creation of new SubSpace is available.

**Expected behavior**
Both options for BoK should be available as you already has a subspace created during the creation of the fist VC.

**Screenshots**

**Additional context**
Reproducible after the limit of 1 VC per account was bumped to 3.

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by EmiliaPavlova** [comment]
Tested on ACC. Both options on the first stap of the wizard are available without refreshing the window. 

<img width="1037" alt="Screenshot 2024-07-05 at 17 08 29" src="https://github.com/alkem-io/client-web/assets/10547231/e635371b-da4c-49eb-a83e-b0929465604e">
