### ISSUE TITLE
Update web socket transport layer

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6536]
## Description

As a user I want a reliable updates

## Acceptance criteria

- [ ] Client ws transport layer library: replace "subscriptions-transport-ws": "^0.11.0", to "graphql-ws"
- [ ] Also replace on the server

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Let's remove it from the server as well.
