### ISSUE TITLE
Sentry event when lost connection to the server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6538]
## Description

As a user I want a reliable updates

## Acceptance criteria

- [ ] When the client detects a lost connection to the server then an event should be logged to sentry.
- [ ] ~Do not display the error message to the server~
- [ ] The connection errors are now tagged with CATEGORY: "WS";
- [ ] CODE of the error was extracted to a tag CODE;

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
From the investigation of - https://github.com/alkem-io/client-web/issues/6283 - the following items came as ACs of this task:
1.  Make sure the Code errors are populated in Sentry, as of now many of the errors are under 'callback' bucket and we can't search into the Additionl Data. [link](https://alkemio.sentry.io/issues/5238208843/events/92ad4922b01f41a6b0ad34648ca23232/?environment=production&project=5862875&statsPeriod=30d&stream_index=0)
2.  On the server in case of closed connection an error should be thrown - probably app.modules.ts -> graphql-ws -> onClose callback @hero101  to  confirm.


On the point "Do not display the error message to the server" - I think we should present an error to the user if there's such. The server is throwing authenticated related error and the client is showing it. We should prevent the sending of such error if it's not relevant.

**Comment by techsmyth** [comment]
@bobbykolev agreed...and suggest to move ahead with the fixes while all fresh!

**Comment by bobbykolev** [comment]
errors tracked in Sentry:
https://alkemio.sentry.io/issues/5254400821/events/5c49c5933646419e97fec44df8eead1b/?environment=production&project=5862875&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&statsPeriod=24h&stream_index=1
