### ISSUE TITLE
BUG: Can't leave organization

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#6541]
**Describe the bug**
In https://acc-alkem.io/user/<your profile nameID>/settings/organizations
I click on Disassociate button and nothing happens

a mutation is called
```
mutation removeOrganizationRoleFromUser(
  $input: RemoveOrganizationRoleFromUserInput!
) {
  removeOrganizationRoleFromUser(membershipData: $input) {
    id
    profile {
      id
      displayName
      __typename
    }
    __typename
  }
}
{
  "input": {
    "userID": "70e6e81b-36d9-4feb-8547-fbb21b1dabc3",
    "organizationID": "20da45fe-d354-41bd-8967-1e887a33e9aa",
    "role": "ASSOCIATE"
  }
}
```
but the organization doesn't disappear.
Neither with a page refresh (that's why I have added the server label).

Organization cards don't have a consistent width maybe take the chance to fix that if it's easy

**To Reproduce**

**Expected behavior**
The membership is removed and the page is updated

**Comment by techsmyth** [comment]
@ccanos the mutation does succeed for me with a non-privileged user, and after refreshing the page the org membership is no longer shown. So this looks to me to be a client refresh issue.

**Comment by Comoque1** [comment]
@ccanos @techsmyth when the user "disassociate" from an organization, the mutation executes successfully.

But if the user is organization admin/owner, he cannot leave as such mutation is not executed.
Probably adding a label admin, could be useful.

<img width="1817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ebaed3d98a3d21332f027c172d328bad2e020f3/image.png" alt="image.png" />
<img width="1612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC9WQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08fe221f3eb625196c0f35e5c7f6c19ccc807481/image.png" alt="image.png" />

If the user is only a member, the card disappears from user's profile.

I am going to close this issue, as the case, where org admin want to leave the organization is very unlikely and if this is the case, GA or another org admin, can remove it.
