### ISSUE TITLE
BUG: client redirecting to dashboard on user route

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6545]
**Describe the bug**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ee3acfa6cf49a9a7e65ca90ab4f4d0c665eaae6/image.png" alt="image.png" />

<img width="1781" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2krQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5f94e40d521a3065f12c05732995e991c172bbb/image.png" alt="image.png" />

**To Reproduce**

1. Navigate to [domain]/user e.g. https://acc-alkem.io/user

**Expected behavior**
The top-level routes to be protected on the client. 
1. do not allow creation of a space with nameID of one of the Platform Top Level Routes;
2. in case of access to one of them like '/user' -> navigate to home or 404, not to '/user/dashboard' with broken space layout.

**Comment by techsmyth** [comment]
@me-andre for now please enforce it only the client, I will add a separate issue to reserve nameIDs on the space level

**Comment by Comoque1** [comment]
Tested OK on DEV env.
