### ISSUE TITLE
BUG: attempting to access community when not logged in

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6546]
**Describe the bug**
Server logs are full with the following messages:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnkvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25710fdfc22d2f938c37b43467e562c3496c22cf/image.png" alt="image.png" />

**To Reproduce**

1. Open the application locally
2. With GA create a space with subspace
3. Using **unauthenticated** user navigate to the subspace: the following errors are thrown:
- User () does not have credentials that grant 'read' access to Community.organizationsInRole on authorization: 3fb402e0-82cb-4187-840c-cadcc9a4a5cb
- User () does not have credentials that grant 'read' access to Community.virtualContributorsInRole on authorization: 3fb402e0-82cb-4187-840c-cadcc9a4a5cb
- User () does not have credentials that grant 'read' access to Community.memberUsers on authorization: 3fb402e0-82cb-4187-840c-cadcc9a4a5cb
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5EQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c53f71213b0fb7459625d522163642bf758ac70/image.png" alt="image.png" />

**Expected behavior**
Client should not be attempting to access community details if not logged in

**Comment by Comoque1** [comment]
Tested OK on DEV env.
