### ISSUE TITLE
My Account block (MyDash) to be role dependent

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6554]
## Description

As a new user on the platform, I have different expectations based on how I joined:
- VC campaign: I expect to be able to create a VC and don't want to get confused by other things like spaces
- Beta tester: I expect to be able to do what I discussed when I joined as a beta tester, so I expect full functionality and a bit more, and it's okay if things are a bit less directive/clear because hey, I'm a beta tester!
- Other: I expect to be guided and not get the feeling that things are disabled for me while I don't know how to enable them. E.g. I don't want to be told to 'click here' to create a space and then just get to a pricing page from which I can't continue.

## Acceptance criteria

My Account block on My Dashboard to show different content based on Global Role 
### Default
- Header: My Account
- Section 1 header (h4?): Space
- Section 1 content: depends on scenario, text caption font and/or button
- Section 2 header (h4?): Virtual Contributor
- Section 2 content: depends on scenario, text caption font and/or button

#### No Global Role (see design!!)
- [ ] No Space, No VC
- Section 1 text: 
You don’t host a Space yet. Click [here](https://welcome.alkem.io/pricing/) to learn more about the different plans.

- Section 2 text: 
Turn your knowledge into a Virtual Contributor powered by AI in your own space. Read more about Alkemio’s Virtual Contributor [here](https://welcome.alkem.io/virtual-contributors/). 
Do you want to be part of the first group of people to test our Virtual Contributor? 
- Primary button: Sign up and join the Early Access Program for free! (https://welcome.alkem.io/vc-program/)

- [ ] Space, No VCs
- Section 1 Spaces card for Space(s) hosted by the user  
- Section 2 text:
Turn your knowledge into a Virtual Contributor powered by AI in your own space. Read more about Alkemio’s Virtual Contributor here (_https://welcome.alkem.io/virtual-contributors/_). 
Do you want to be part of the first group of people to test our Virtual Contributor? 
- Primary button text: Sign up and join the Early Access Program for free! (https://welcome.alkem.io/vc-program/)

- [ ] Space, 1-2 VCs
- Section 1 content: Spaces card for Space(s) hosted by the user  
- Section 2 content: VC card for VC(s) hosted by the user  
- Secondary button text: Create another Virtual Contributor

- [ ] Space, 3 or more VCs
- Section 1 content: Spaces card for Space(s) hosted by the user  
- Section 2 content: VC card for VC(s) hosted by the user  
- Caption italic: You've reached the maximum of 3 VCs

#### Global Role: VC Campaign (see design!!)
- [ ] No Space, No VC
- Section 1 text: 
Welcome to the  Virtual Contributors - Early Access Program!
Click below to create your Virtual Contributor. Once finished, this block will give you access to both your Virtual Contributor and your Space in which you can interact with it. Enjoy!
- **No Section 2**
- Primary button: 🎉 Create your Virtual Contributor! (leading to 2in1 create flow from #xxxx)

- [ ] Space, No VCs
Same as for No Global Role

- [ ] Space, 1-2 VCs
Same as for No Global Role

- [ ] Space, 3 or more VCs
Same as for No Global Role

#### Global Role: other (see design!!)
- [ ] No Space, No VC
- Section 1 text: 
Welcome to the  Virtual Contributors - Early Access Program!
Click below to create your Virtual Contributor. Once finished, this block will give you access to both your Virtual Contributor and your Space in which you can interact with it. Enjoy!
- **No Section 2**
- Primary button: 🎉 Create your Virtual Contributor! (leading to 2in1 create flow from #xxxx)

- [ ] Space, No VCs
Same as for No Global Role

- [ ] Space, 1-2 VCs
Same as for No Global Role

- [ ] Space, 3 or more VCs
**Same as 1-2 VCs (no restriction)**

## Additional Context
High estimation because of many different scenarios which need to be checked when developing, reviewing, and testing
https://www.figma.com/design/WAUWUkYdRExqlq4kQWkA86/My-account-block-per-role?node-id=3-823&t=ahN7X5HRzi1GQ0uv-1
<img width="571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8807dc2d5b4f6ad05692a8e709c66487a01c1cb6/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
For the flows in the right column 'Global role: other', use the following roles (as other is not strictly defined):
GlobalAdmin = 'GLOBAL_ADMIN',
GlobalLicenseManager = 'GLOBAL_LICENSE_MANAGER',
GlobalSupport = 'GLOBAL_SUPPORT'

We can add to the list later if required.

**Comment by EmiliaPavlova** [comment]
There is a mismatch between the description and the design for users with no global role, space and no vc. The implementation is according the description.

**Comment by bobbykolev** [comment]
Note that if we release this Story prior to the new VC creation flow, the current VC creation will be blocked for users in the VC campaign and without a space. 

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b301d2f88b75f5ce096fb3416a926a2875d34e01/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
When hover over the button: the text disappears: Sign up and join the Early Access Program for free! 

<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a98726ab9d9db831f28685321a6de52ea406ba9/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@SimoneZaza @bobbykolev Beta tester is not mentioned in the list of global roles and at the moment it sees the same as normal registered user.

Is this expected behavior:
<img width="1593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7146b5a3aab5343e091f9a58a31a05456bafc8d/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
@Comoque1 Thanks for raising this, beta tester should be the same as Global role: other. Beta testers should be able to create spaces and create vcs.
