### ISSUE TITLE
Add markdown editor 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#656]
## Description

As a non-technical user, I want to be easily able to edit the markdown without learning the syntax

## Acceptance criteria

- [ ] Investigate what components are there to support users in editing their markdown
- [ ] …

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/157102cd-e13e-4502-9d9e-1ba24af7d4c3)

**Comment by Comoque1** [comment]
Looks OK.
The only thing missing is a tooltip on `insert code` button
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/942f4808-ca34-4951-bd0a-000ce073fabe)
