### ISSUE TITLE
BUG: Show 404 instead of empty Space dashboard if there's no space with provided nameID in the URL

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6562]
**Describe the bug**
As a user, if I try to access a non-existent page I should be presented with 404 page.

If the URL path is not defined in the TopLevelRoutes and there's no space matching the nameID provided in the URL, then show 404 instead of broken Space Dashboard.

**To Reproduce**

1. Go to URL with path - name of space that doesn't exist e.g. https://alkem.io/no-such-space
2. See a broken space dashboard.

**Expected behavior**
404 should be presented to the user. Similar to what you'll get with a non-existing user or other entity.

**Screenshots**
<img width="1542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d26d15bfda21bcc71a792d9fbc52d66a0ca8f67f/image.png" alt="image.png" />

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
