### ISSUE TITLE
BUG: Not able to select a user to see the privileges they get with an auth policy

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6567]
**Describe the bug**
The authorization policy page should allow for selecting a user after selecting an auth policy

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9QQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13ddf8009860ebb7e054e90ef79a967b64d2da8e/image.png" alt="image.png" />

**To Reproduce**

**Expected behavior**
The page should allow selecting a user to evaluate the privileges with after selecting the auth policy

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on dev env.
<img width="1525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFRpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--588f9e5374d015045fd5da2b41e4c4da7661af9a/image.png" alt="image.png" />
