### ISSUE TITLE
When uploading a document, set the name from the file name

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6569]
## Description

As a user I upload my document, but the name of the document is not shown back to me

## Acceptance criteria

- [ ] Set the name of the document in as the link name

## Additional Context

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--711a286bc34aaa8203b634f36869396a9e0b7239/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on DEV env:
<img width="1446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi96QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1987c11df9ceca883a1528da9e427ce798e2202/image.png" alt="image.png" />
