### ISSUE TITLE
BUG: Membership cards on VC profile display

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6570]
**Describe the bug**
The membership cards on VC profile page are not the same size:

<img width="1086" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--103d9c4c10f6b6695f88d29c198fe4ed9d248d82/image.png" alt="image.png" />

**To Reproduce**

**Expected behavior**
Cards are consistent in their size

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Looks better on DEV env.
<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84a26dac923cd9a9cd6d0331d5feef9fb066ac03/image.png" alt="image.png" />
