### ISSUE TITLE
BUG: challenges section on an ecoverse is being marked as not accessible when no challenges

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#659]
**Describe the bug**
Logged in as global admin. 
Challenges are marked as not accessible when no challenges

**Comment by techsmyth** [comment]
to fix:
for the current user check if the Ecoverse entity READ privilege is present

**Comment by Comoque1** [comment]
Not reproducible anymore.
Closing the issue.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a892e99d-c870-45e9-b7f4-05abf061002e)
