### ISSUE TITLE
BUG: Pasting an image fails the first time

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6597]
**Describe the bug**
When I paste an image in, the first attempt fails and just shows a gray box. Trying it again worked. I saw this behaviour twice in a row. 

**To Reproduce**

1. Go to the team whiteboard being used for the VC session
2. Paste an image

**Expected behavior**
The image should be displayed and uploaded

**Additional context**
It looks like the file upload fails to trigger for some reason, maybe when the whiteboard is heavily used.

**Comment by Comoque1** [comment]
i've tried on production and wasn't able to reproduce.
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFliQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f5748253e55df0b5b509cccb4dd639e068add2a/image.png" alt="image.png" />
