### ISSUE TITLE
VC Create flow: Written Knowledge

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6603]
## Description

As a user, I want the create flow to align with my understanding and wishes for my VC. I want to learn about the options through the create flow, without getting too much information. The way it works should teach me. 

## Acceptance criteria

- Step 1: Add profile info and choose engine #6602
---
- [ ] Loading dialog
- Spinner
- Text: A [Space] | [Subspace] for adding the knowledge for your Virtual Contributor are being built. This process may take a few moments to complete. 
Note, if the user has no spaces, we're creating a space and we use it as BoK - easier, faster, simpler.
For ever next VC, we're creating a separate subspace in the alredy existing space. 
---
- [ ] Step 2: **Add knowledge** dialog
- This is a dialog where people directly add posts and links which will be added as posts inside a single call for posts and links inside a single collection of links and documents callout (the links). 
- They can add as many as they like, and the footer of the dialog should remain visible (dialog can expand vertically to the max height if easy to implement). 
- Posts are a somewhat stripped version of the real post, only showing title and description, not showing the image upload in the editor. They are collected in a call for posts named "Initial Posts" in the Body of Knowledge flow step in the subspace
- Links/documents are collected in a single callout named "Initial Links and Documents"  in the Body of Knowledge flow step in the subspace - extracted in https://github.com/alkem-io/client-web/issues/6719

- When user clicks create:
- [ ] Create the callouts;
- [ ] Create the VC (in that order so no reingestion would be needed);
- [ ] Navigate to the Space Dashboard where the Try you VC dialog should be shown: https://github.com/alkem-io/client-web/issues/6621

- [ ] **Confirmation dialog** when users close the dialog in this flow.
- Title: Discard Changes
- Text: ~~Are you sure you want to stop creating your Virtual Contributor or adding knowledge? Your work in this window will not be saved.~~ The following text is used to better inform the users of the impact and next steps:
"Are you sure you want to stop creating your Virtual Contributor? Your work will not be saved. A space/subspace might already be created for you. Please, reload the page if you confirm the cancellation."
- Buttons: Cancel (primary), Yes, Stop (text only button) (like the confirmation dialog when closing a callout create dialog)

In case of confirmation, the created data should be deleted.

## Additional Context

User flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/vccreateflowwith3typ

UI Designs: https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=482-207&t=jCXmCypVZY8hWnEi-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
For the first phase of this flow, we are going to:
- use the Space for BoK and not a subspace (no need to wait for 1. space creation, then 2. subspace creation, then 3. VC creation);
We can alter this implementation if needed. 


Note that in case of multiple spaces owned by the user, the BoK and the VC will be created in the one shown in the MyAccount block (no option to choose from them).
