### ISSUE TITLE
VC Create flow: Subspace

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6604]
## Description

As a user, I want the creation flow to align with my understanding and wishes for my VC. I want to learn about the options through the create flow, without getting too much information. The way it works should teach me. 

## Acceptance criteria 
This button opens the following dialog:
- [ ] Choose (Sub)Space
- Dropdown with a list of Spaces and Subspaces a user has update privileges* to
- ~~when the user clicks the close button, show confirmation dialog~~ no need of confirmation as in the current flow nothing has happened, the user could safely return to the initial options.
- [ ] When user clicks "Create":
- VC is created
- VC is added to personal space
- [ ] Then they're done and the **Try it out dialog** opens: #6621
- same as in the written knowledge flow (also open personal space in the background, **not space that vc was created from**)

## Additional Context
*UPDATES: 31.07.24
For this phase, this Choose SubSpace flow will be available only for users with space/s.
Feel free to further refine the requirements with this 'update rights', but that makes the implementation too complex.
In case there are no available spaces (and subspaces) for certain users, we can either disable the option or show an informational modal. Simone was against the disabling options so we'll start with information e.g. 'You need a Space to proceed with this option. Please go back and follow the Written Knowledge flow.'

User flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/vccreateflowwith3typ

UI Designs: https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=482-207&t=jCXmCypVZY8hWnEi-1
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b1ba37f313dbac17ef3743ac76f996b017fe304/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC.
Behaves as per AC and the additional update in them.
