### ISSUE TITLE
VC Create flow: external ai

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6605]
## Description

As a user, I want the create flow to align with my understanding and wishes for my VC. I want to learn about the options through the create flow, without getting too much information. The way it works should teach me. 

## Acceptance criteria
- [ ] Coming soon dialog:
- Input field + radio. 
- When user clicks send, an email (u2u messaging) should be send to support@alkem.io with the content from the input field + radio + user email/profile/name/something to understand who the message came from
- Let's try to go for the simplest implementation, this is just temporary

## Additional Context
Denise will create the support@alkem.io account on Alkemio
User flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/vccreateflowwith3typ

UI Designs: https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=482-207&t=jCXmCypVZY8hWnEi-1
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b1ba37f313dbac17ef3743ac76f996b017fe304/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

## Agreements
We are going to send a message to an existing user using `sendMessageToUser` mutation
- We may want to look for the user by email using `user(ID:"support@alkem.io")` (We may also want to put support@alkem.io in the translation)
- OR we may just want to put the uuid of the translation.
- Product/sales team will create the user with support@alkem.io email

**Comment by bobbykolev** [comment]
The message that will be sent to support@alkem.io is in the following format:
 `AI Service: "${values.aiService.trim()}" | User: ${user?.user.email} | Contact me: ${values.sendResponse}.`
e.g _AI Service: "xAI by Elon Musk" | User: email@example.com | Contact me: Yes._

**Comment by Comoque1** [comment]
Request is not being sent when press the button, the rest of the story looks OK.
![image](https://github.com/user-attachments/assets/4eb3ec1c-6794-4722-bf19-0e31988bdb26)

**Comment by bobbykolev** [comment]
@Comoque1 as described if support@alkem.io is not available (registered) in the environment, no message is sent.
However, Sentry log is sent on this case.

**Comment by Comoque1** [comment]
@bobbykolev support@alkem.io user is registered on acc env and added to the support group, but still getting the error:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5NQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86eb694dbc7153cc96017aa51f65afee3433e8b9/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on acc env:
<img width="1596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e78a0eccad852a829a455cfe17656fbeb2bcaa2c/image.png" alt="image.png" />
