### ISSUE TITLE
BUG: "Contact" icon leads to not existing page on MyDashboard page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6606]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/home
2. Scroll down to "More about Alkemio" block
<img width="1089" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9783a1d653499acfcd9fb094e9732799c0a1dc37/image.png" alt="image.png" />

3. Click on "Contact" icon - user is redirected to non existing page
<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef90289c03078cddb6f6869b7b807871952b2533/image.png" alt="image.png" />

**Expected behavior**
User is redirected to contact form

**Comment by valentinyanakiev** [comment]
this is configured [via overlay in infra-ops](https://github.com/alkem-io/infrastructure-operations/blob/develop/orchestration/k8s/overlays/production/default/config/01-configMap-overlay.yml)

**Comment by valentinyanakiev** [comment]
fixed - tested on ACC
