### ISSUE TITLE
 Improved display of lifecycles

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#661]
## Description

As a user, I want the lifecycle to be displayed in a way to highlight the expected flow 

## Acceptance criteria

- [x] Title visible, showing the name of the template
- [x] "nicer" layout for the boxes representing the states
- [x] Stable image (not settling down on display"

**Comment by pimotte** [comment]
@techsmyth Just to check for "name of the template" for the title, you mean the name of the opportunity/challenge, or is there some relevant name for the lifecycle?

**Comment by pimotte** [comment]
With respect to "Add the name of the triggering event to each transition"

The way I would think this should be implemented is by using the `textpath` directive in an svg. This allows to layout the names of the transitions nicely without overlapping with other elements.

However, I couldn't get this to work.

https://github.com/alkem-io/client-web/tree/lifecycle-improvement%23661c has a minimal example of text disappearing when in textpath in alkemio. 

The code in that branch generates the following svg code:

`<svg id="graph-container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0,0,800,400"><text font="&quot;MONTSERRAT&quot;" font-size="14" x="50" y="50" fill="red"><textpath href="#MyPath">TEST</textpath></text><defs><marker id="end-arrow" viewBox="0 -5 10 10" refX="10" markerWidth="10.5" markerHeight="10.5" orient="auto"><path d="M0,-5L10,0L0,5"></path></marker><filter id="drop-shadow" x="0" y="0" width="200%" height="200%"><feDropShadow dx="2" dy="2" stdDeviation="1" flood-color="#000" flood-opacity="1"></feDropShadow></filter></defs><path id="MyPath" stroke="red" d="M 100 100 L 200 200"></path><text font="&quot;MONTSERRAT&quot;" font-size="14" x="50" y="50" fill="red"><textpath href="#MyPath">TEST</textpath></text><text font="&quot;MONTSERRAT&quot;" font-size="14" x="50" y="50" fill="red"><textpath href="#MyPath">TEST</textpath></text><defs><marker id="end-arrow" viewBox="0 -5 10 10" refX="10" markerWidth="10.5" markerHeight="10.5" orient="auto"><path d="M0,-5L10,0L0,5"></path></marker><filter id="drop-shadow" x="0" y="0" width="200%" height="200%"><feDropShadow dx="2" dy="2" stdDeviation="1" flood-color="#000" flood-opacity="1"></feDropShadow></filter></defs><path id="MyPath" stroke="red" d="M 100 100 L 200 200"></path><text font="&quot;MONTSERRAT&quot;" font-size="14" x="50" y="50" fill="red">TEST</text><text font="&quot;MONTSERRAT&quot;" font-size="14" x="50" y="50" fill="red"><textpath href="#MyPath">TEST</textpath></text></svg>`

In alkemio, it shows as:

![image](https://user-images.githubusercontent.com/5917458/125260364-8ec96300-e300-11eb-85b2-7556faf53a9d.png)

In this jsfiddle (https://jsfiddle.net/da6r4Lw5/) with just the svg, it shows as: 

![image](https://user-images.githubusercontent.com/5917458/125260534-b5879980-e300-11eb-9b58-ad5cb61b1a80.png)


Options if we want to build this anyway:

- Figure out how to get textpath to work and use that
- Compute midpoints and slopes of transition arrows and layout the text with that
