### ISSUE TITLE
BUG: Contributor card in Search results not clickable

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#6610]
**Describe the bug**
Contributor cards on the search results are not clickable.

**To Reproduce**

1. Go to Search
2. Search for 'Denise"
3. Scroll down to "Contributors" category
4. Click on "Denise Larsson" to go to their profile
5. Card is not clickable

**Expected behavior**
The Contributor card in the Search results to be clickable, and by clicking you are sent to the profile of that Contributor.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
