### ISSUE TITLE
VC Create flow Step 3: Try out dialog

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6621]
## Description

As a user, I want the create flow to align with my understanding and wishes for my VC. I want to learn about the options through the create flow, without getting too much information. The way it works should teach me. 

## Acceptance criteria

- [ ] This dialog has an example post in which they interact with the VC
- [ ] @<VC name> is prefilled in the input field
- [ ] In the background, the page changed to the Personal Space
- [ ] When the user closes the dialog, they remain on the Personal Space page
- [ ] The example callout is also on the space page, on the dashboard

## Additional Context

User flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/vccreateflowwith3typ

UI Designs: https://www.figma.com/design/gV8GGWh99QRKfM65lwedrE/Dashboard-Update?node-id=482-207&t=jCXmCypVZY8hWnEi-1
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVh1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f8f3c6d68ffb4cb2ff72258c23afcb880caadc5/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Tech suggestion:
Use route param or localStorage (better) to show this dialog on space landing. In the previous step of the flow save the value in LS.
