### ISSUE TITLE
Account tab (2) in users' Settings

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6623]
## Description

As a user, I want to be able to manage my account and the entities it contains

## Acceptance criteria

- [ ] Same as the Organization account tab - https://github.com/alkem-io/client-web/issues/6440:
- Spaces
- Virtual Contributors
- + Innovation packs and custom homepages as they are moved under an account and a user can be a host;
- [ ] Reuse Create a Space existing functionality;
- [ ] Create Innovation Pack functionality (extracted and implemented from https://github.com/alkem-io/client-web/issues/6624)

UPDATE: 5.8.24
As InnoPacks and Hubs are part of the account, they will be visible on the user's profile if any.
As the InnoPack section has a Create button, it's shown even if you don't have innovation packs yet. 

- [ ] Remove the create InnoPack option in the Global Administration. 

## Additional Context

Figma (disregard the designs that are not part of this issue): https://www.figma.com/design/l0hLyZCBs5cxhpp5vUPAte/Account-page?node-id=186-106&t=AhyNIs3ukaS3wWt7-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
What was altered and could be extracted for refinement or bugs:
- There's no support on the list of items for the space name (on the right for all entities but the spaces);
- The InnoPack create button is visible (the entire section) even if you 1. don't have other packs and 2. not only for organizations (as requested);

**Comment by Comoque1** [comment]
Tested OK on DEV env.
