### ISSUE TITLE
Account tab 3: create from page

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6624]
## Description

As a user, I want to be able to create new things from my account page as well

## Acceptance criteria

- [ ] Plus button
- Bottom left
- Only visible for users with the create privilege for the corresponding entity
---
- [ ] Spaces:
- Open create flow as it currently is there from the dashboard: implemented with https://github.com/alkem-io/client-web/issues/6623
- Privilege required: CREATE_SPACE on Account entity
- limit to 3 (if not a GA - inconsistent with the home's dashboard @SimoneZaza);
- [ ] Virtual Contributors:
- Open create flow as it currently is there from the dashboard
- Each user / org can only have one account
- Privilege required: CREATE_VIRTUAL_CONTRIBUTOR on Account entity
- limit to 3 (if not a GA, as in the home's dashboard);
- [ ] Innovation Packs:
- Use current create fields (from global administration, see screenshot below), but move it to a dialog: implemented with https://github.com/alkem-io/client-web/issues/6623
- Rename SAVE into CREATE
- Privilege required: CREATE_INNOVATION_PACK on Account entity
- Create button opens innovation pack profile settings page (as it currently does)
- [ ] Custom Homepages:
- Privilege required: CREATE_INNOVATION_HUB on Account entity
- Create button opens innovation pack profile settings page (as it currently does)

## Additional Context
Higher estimate because of the many flows that need to work

Figma (disregard the designs that are not part of this issue): https://www.figma.com/design/l0hLyZCBs5cxhpp5vUPAte/Account-page?node-id=186-106&t=AhyNIs3ukaS3wWt7-1

Current create fields Innovation pack:
<img width="1089" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC91QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59332cb26ea4ab11e888f51f04743dcd8d1e768a/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
Moved back to refined column as description changed slightly

**Comment by bobbykolev** [comment]
Note that **Create Space** and **Create Innovation Pack** are available on the Users' Account Tabs (implemented as part of https://github.com/alkem-io/client-web/issues/6623).

What remains:
- Creation in the Orgs' Account Tabs;
- VC creation. Reusing the new creation flow or a simplified one @SimoneZaza?
- Create Innovation Hubs;
- Refinement on the limitations (if any) e.g. no more than [N] spaces (currently there's no limit)!

**Comment by bobbykolev** [comment]
@techsmyth , can you elaborate on the new privileges - CREATE_INNOVATION_PACK, CREATE_INNOVATION_HUB?
We'll be using the CREATE_SPACE for Packs and PlatformAdmin for Hubs until we have the above. 

Currently, the create_space is part of the platform privileges. Can we move this privilege (and the others) to be part of the account privileges? That way we'll be checking only these, no matter the platform ones and roles. e.g. instead of "platform.authorization.myPrivileges.CREATE_SPACE" we'll use "user.account.authorization.myPrivileges.CREATE_SPACE".

**Comment by bobbykolev** [comment]
Updates on 20.8:
- limits added for Spaces (and VCs); 
- Privileges are defined, although they are dependent on the account changes - https://github.com/alkem-io/server/pull/4369

**Comment by bobbykolev** [comment]
The creation was implemented before the "Account entity" changes.

Note that:
1. Currently **Space Creation** and **VC creation** flows don't allow selecting a host. It's always the user that creates them. The other creation flows (Packs & Hubs) work fine for both organizations and GAs creating them in another user's account.
2. If a contributor (user/organization) has no account, then nothing can be created from the Account Tab.
3. The privilege logic will be revisited and refined after the "Account entity" changes get merged. For now the client checks are: CREATE privilege on the account (space, pack); VC Campaign for VC; and PlatformAdmin for Hubs (see the ACs for details).

**Comment by techsmyth** [comment]
Thanks @bobbykolev . Important is to get this also merged in with the account features branch to check it there. Answers:
a) the creation should always pick up the account ID from the page where it is being created, so the account tab for a user or org. For other cases (such as VC create flow), then the key decision is which account to use. 
b) all users + orgs have accounts with the new setup
c) we do indeed need to recheck the logic once the new privileges are there (again in the new setup). I will raise an issue to actively follow up on this.
