### ISSUE TITLE
BUG: Newly created VC doesn't respond on DEV env.

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6644]
**Describe the bug**

**To Reproduce**

1. Go to dev-alkem.io
2. Register new user
3. Make it beta tester
4. Create a VC
5. Ask something the VC - error is thrown in the service and 2 VCs are displayed
<img width="1255" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2I2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90cd2eabb65d5c35240fd86eba3e803adf6350ae/image.png" alt="image.png" />

<img width="995" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2o2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1af5e65bbd5b4419cfe93214f12ac8456ee966b2/image.png" alt="image.png" />

**Expected behavior**
Only one VC is displayed.
It answers.

**Comment by techsmyth** [comment]
If this is still the case then a high priority issue

**Comment by valentinyanakiev** [comment]
VCs config fixed on dev now
