### ISSUE TITLE
BUG: Public subspaces, have "lock" icon for private spaces

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6648]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/userhostspace/subspaces
2. The subspace card shows "lock" icon, when in reality it is not private
<img width="1230" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenY2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--963aec7cb60a166934d44f06733ec1a3f80ccd62/image.png" alt="image.png" />

**Expected behavior**
Public Subspace cards (part of Private space) don't have "lock" icon when:
- returned in search results
- returned on https://dev-alkem.io/spaces page
- shown on space/subspaces page

**Comment by bobbykolev** [comment]
The client is looking into the `anonymousReadAccess` prop from `sapce.authorization` and based on its value it shows the public/private treatment (lock). 
It looks like in this particular case, the value is inherited by the parentSpace. I couldn't find the place on the server where this logic resides. Note that the client is using a lookup space->subspaces->authorization->anonymousReadAccess.

**Comment by Comoque1** [comment]
Tested OK on DEV env, without the search results. To be tested when on ACC env.
