### ISSUE TITLE
BUG: When hover over the button: the text is not visible: Sign up and join the Early Access Program for free!

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6684]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home with VC member without Space and VC
2. Hover over "Sign up and join the Early Access Program for free!" button - text becomes invisible
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ba859e3c859b437ae7e1e127367cba50d42855a/image.png" alt="image.png" />

**Expected behavior**
Text is visible.

**Comment by bobbykolev** [comment]
Done in the feature branch as part of https://github.com/alkem-io/client-web/issues/6602

**Comment by Comoque1** [comment]
Tested OK on ACC env.
