### ISSUE TITLE
BUG: On MyMemberships dialog, when click on arrow to expand the children, the dialog closes

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6690]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Open "MyMemberships" dialog
3. Try to expand the children - dialog gets closed.
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e26e90c9508bae469417f190f34b048502f3adc/image.png" alt="image.png" />

**Expected behavior**
Children are displayed.

**Comment by bobbykolev** [comment]
Handling of the error was added to the client. However, the issue is caused by a server change. The `me { spaceMemberships }` query now returns only top level space memberships (level: 0) instead of all levels.

**Comment by techsmyth** [comment]
Fyi - with this released in production, the time for me for the MyMemberships query went from 17.5 seconds to 7.1, so just over 10 seconds faster :). Not a hugely scientific measure, but still nice...
