### ISSUE TITLE
BUG: When try to create innovation hub, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6692]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/admin/innovation-hubs/new
2. Fill up all required fields - account host doesn't have any value
<img width="1607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1oQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b835404d2942f6566a5ae2f2990bb14613f06436/image.png" alt="image.png" />

**Expected behavior**
Innovation hub can be created successfully.

**Comment by Comoque1** [comment]
@ccanos accountList query still fails:
Should the data be cleaned up?
<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--088818afb709f2b30b3d48273aa032bf8be798ff/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 it should no longer be possible to create an Innovation Hub in this way, it should always specify an account ID. And retrieving of the Innovation Hubs in the admin area should be via a separate api - to be added.

**Comment by bobbykolev** [comment]
Or we can remove the create button from the Admin, can't we? It would be available from every profile's Account.

**Comment by techsmyth** [comment]
yes that would be best...should be managing existing InnovationHubs from this location, not creating new ones...
