### ISSUE TITLE
BUG: When user click on "Sign in here" from home page banner

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6706]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Click on 'Sign in here' immediately after the page loads
<img width="1697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1F4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e202fa151ebdb3ade69561e95cacfc1d3541fbf/image.png" alt="image.png" />

3. User is redirected to "sign up " page
<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1V4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5325a9e6a0cec65396283cf519764a406ee99541/image.png" alt="image.png" />

4. Click on "Alkemio preview" logo on top of the page
<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3d4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b505997c0577dd43d7d5b61be0a77a93437e267/image.png" alt="image.png" />

5. New tab is open with https://dev-alkem.io/home
6. Repeat step 2
7. After a couple a times repeating the flow from step 2 to step 4, user is redirected to **sign up** page
<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0F5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--725ac58a99ba0f91a055c1aa34e75fe04cb7f3c9/image.png" alt="image.png" />

9. Press "sign in " button
10. User is redirected to `login` page
<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0l5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5ba4a8f5d84985185f258208147e11748ed2dc0/image.png" alt="image.png" />

11. Press `reset password` link
12. User is redirected to `https://dev-alkem.io/ory/kratos/public/self-service/recovery/browser`
<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1l5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--977efb63c15f90f0e78a20a5d4361fe41959fe4f/image.png" alt="image.png" />

**Expected behavior**
User is redirected to `recovery` page.

**Comment by bobbykolev** [comment]
There is no such banner anymore after the redesign of the unauthenticated dashboard, now - Explore Spaces.
