### ISSUE TITLE
Layout improvement of Home Dashboard for users without memberships

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6718]
## Description

When you don't have memberships the layout of your homepage looks odd. 

## Acceptance criteria

- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.
Currently (no Inno pack):
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUE2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f5da35b2c19e9b1cdbaaf3d522feb7c7811e651/Alkemio-Safe-Spaces-for-Collaboration.png" alt="Alkemio-Safe-Spaces-for-Collaboration.png" />

suggested:
<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUU2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--937eff4cb25a8ea850c22409d516e93348700b60/Alkemio-Safe-Spaces-for-Collaboration%20%281%29.png" alt="Alkemio-Safe-Spaces-for-Collaboration (1).png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza can you please look at this? The layout right now for new users is pretty poor.

**Comment by bobbykolev** [comment]
Closing as this is will be fixed as part of the Simple Homepage.
