### ISSUE TITLE
Use Account.CREATE_SPACE privilege to determine where the user goes 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6734]
## Description

As a user I want to create a space if I have the rights to do so

<img width="511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7713796cabc514d0ede37671d29ebe886379e971/image.png" alt="image.png" />

The button currently redirects to welcome site even if I am a global admin.

## Acceptance criteria

- [ ] The button shown above should go to the createSpace dialog / flow if the user has the CREATE_SPACE privilege on their Account

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by bobbykolev** [comment]
Also as part of this task, we're including the forgotten addition of the Beta Testers display in this block to be as for a Global role (see comments):
https://github.com/alkem-io/client-web/issues/6554

@Comoque1 FYI
