### ISSUE TITLE
BUG: Sometimes "CreateVirtualContributorOnAccount" request is executed before "createCallout" request

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6738]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home with user that is part of VC campaign flow
2. Fill up the required fields 
3. Select Written Knowledge flow 
4. Press create button
5. Press Continue button
6. On "Try it out" page, when the user mentions the VC, no response will be returned, as the VC is not updated
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52cb1438ee51ec21c15de7118584e5650be9e13b/image.png" alt="image.png" />

**Expected behavior**
"createCallout" request is always executed before "CreateVirtualContributorOnAccount" request

**Comment by EmiliaPavlova** [comment]
The last callout is coming from the Try out dialog. If there are no posts in the Add knowledge step, a callout collection with posts are not created. This flow will be changed in [6737](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6737) and there will always be a collection of posts request before the VC creation.
