### ISSUE TITLE
BUG: When innovation flow is not set to default, the callout are not displayed on subspace creation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6749]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/aug122024sspace/settings/challenges
2. Change default settings to be different from "Default innovation flow"
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2RMQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fe24b096e4da4cf3d50bcbd870078f679294230/image.png" alt="image.png" />

3. Create an L1 space - the callouts are not displayed
<img width="1542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pMQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54d98333df1762b93e6b452e623d062f3f417e7d/image.png" alt="image.png" />

**Expected behavior**
Callouts are displayed.

**Comment by SimoneZaza** [comment]
We'll pick this up with subspace templates

**Comment by SimoneZaza** [comment]
Will be fixed with #4519

**Comment by Comoque1** [comment]
Reopening this bug, as it is experienced for existing data and it is good to have it reported in the release.
https://acc-alkem.io/ea-publicspace/challenges/privatel1/index

<img width="1449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ViQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--380f740cc8236a16b65ce471951a682fa0259e1b/image.png" alt="image.png" />

**Comment by ccanos** [comment]
@Comoque1 I've tried and I think this cannot be reproduced anymore. Please, take another look and let me know.

**Comment by Comoque1** [comment]
For the moment on DEV env, cannot reproduce the issue as well.
