### ISSUE TITLE
BUG: (Sometimes) When try out VC on "Try it out" dialog VC engine crash

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6750]
**Describe the bug**

**To Reproduce**

1. Register new user
2. Make it part of VC campaign
3. Follow the process of VC creation using "Written knowledge flow"
4. On "Try it out" dialog mention the VC - there is no response
 <img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGRNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49c12c35a05d2110ef23d30e4e29d0fe04331f00/image.png" alt="image.png" />

**Expected behavior**
VC responds always.

**Comment by bobbykolev** [comment]
We're taking a shortcut until the client get a server/engine feedback.
For the first version of this flow, we're going to show the following informational dialog:
