### ISSUE TITLE
Space tab for account details

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6781]
## Description

As a space admin I would like some information about the account the space is hosted in

## Acceptance criteria
- [x] Remove VC block entirely
- [x] Remove price from current license card
- [x] Change upper upgrade/downgrade block/button to be "Change the Space license"
- Text host: You will be redirected to the account settings on your profile
- Text other admins: The Space license can only be changed by the host of this Space
- [x] Change lower upgrade/downgrade block/button to be "Delete this Space", with danger zone label bottom right
- Text host: Click here to delete this Space. Be careful, this action cannot be undone.
- Text other admins: The Space can only be deleted by the host of this Space

Current design:

<img width="1159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3R1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77aa7cf57b2e58e8d0194f0927d414c28b1b5f8f/image.png" alt="image.png" />

New design:
https://www.figma.com/design/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?node-id=674-75&t=LVd1HqdMKh3byG3n-1

For the host:
<img width="1669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFp3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aec34f63012f62a8ef4823c18a7b34791d80d37b/image.png" alt="image.png" />

For other admins:
<img width="1670" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGh3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e0eac5257e70d9d15b905ca74ce040bd6c781bb/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

## Old ACs:
- [ ] Display the functionality level for the space, without pricing details
- [ ] Display the provider of the space (host)
- [ ] Remove ability to delete a space from within the space (only when the option to delete is there on the profile > settings > account tab)
- [ ] Remove creating a VC from the space
- [ ] Add ability to go the account for any actions related to changing the functionality level

**Comment by ccanos** [comment]
@bobbykolev Don't merge it yet, I need t ask about a link `More about the Alkemio licenses can be found here` that I don't know where should it point.

**Comment by Comoque1** [comment]
For the org space, there is no Link on the block 'Change the Space license'
<img width="1070" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0b636bc397cf7eb3136f2af403d8f74a55f225f/image.png" alt="image.png" />


For user space:
1. 'Change the Space license' link points to account setting, but from there, license cannot be changed 
2. Clicking on "More about Alkemio licenses can be found here." opens the page in same tab, would be better to be a separate tab.
<img width="1203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26f542890b52db9f84f9b7e00eb036b0aeb9b827/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Feedback addressed. Tested OK on ACC env.
