### ISSUE TITLE
Subspace templates: add to innovation pack

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6789]
## Description
As an admin, I want to have subspace templates in my innovation pack
As a user, I want to see all the templates that are available

## Acceptance criteria

- [ ] Innovation pack profile
- [ ] Innovation pack profile settings
- [ ] Card from #6789
- [ ] Create button to open dialog with:
- Title: Create Subspace Template
- Text: To create a subspace template, enter the URL of a subspace where you have admin rights.
- URL input field
- Cancel + Continue button
- [ ] Client checks whether the user has the Save_as_template privilege for the URL that was entered. If the user doesn't have the privilege show the following error text: "Unfortunately, you don't have the right privileges to create a template from this Subspace."
If it's a wrong URL, not of a subspace show the following error: "This subspace doesn't exist"
- [ ] If the user has the right privilege, continue with flow as in #6800

## Additional Context

Figma: https://www.figma.com/design/eHqxhDSrUZUyTTCmY2L5c5/Subspace-Templates?node-id=1-3149&t=7J2vE5OugJtltz9D-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza when talking this through earlier with Bobby it seems to me to be more logical to *pull* in the templates area from an existing subspace, rather than *push* from a subspace to one of multiple potential locations to store the collaboration template. So code likely simpler if we pull, and also logically I am very keen to minimize the knowledge of templates from within the spaces in terms of saving as.

**Comment by SimoneZaza** [comment]
@techsmyth Just to be sure, how would this impact user flow? I think it's essential to support both scenarios:
- When in a Subspace or the Subspaces list within a Space: saving a subspace as a template.
- When in the Space Library or Innovation Pack settings: selecting a subspace to use as a template.
I'm afraid that opting for the "pull" approach instead of "push" means that the first scenario won't be possible?
