### ISSUE TITLE
Subspace templates: actions from subspaces list in settings

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6790]
## Description
As an admin, I want to create subspace templates 
As an admin, I want to duplicate subspaces

## Acceptance criteria

- [ ] In Space settings > Subspaces (and Subspace l1 settings > Subspaces), add more button in the list with menu with three options:
- Duplicate
- Save as template
- Delete (take away the bin icon that is currently there and move it to this menu)
- [ ] Save as template starts flow from #6800
- [ ] Duplicate starts flow from #6810

(use component ActionsMenu or something like that)

## Additional Context
<img width="592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e446245423e41442ae69252e7bfae347276047f/image.png" alt="image.png" />

Design: https://www.figma.com/design/eHqxhDSrUZUyTTCmY2L5c5/Subspace-Templates?node-id=91-2330&t=RqcxSnrvIY04Zszx-1
Flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/subspacetemplates
<img width="1807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c024b77b550d009b239a871d61feb28634d084fa/image.png" alt="image.png" />

## Areas that will be affected 
 In addition to this task, the following was addressed:
- [ ] The lists of subspaces in space/subspace settings were reimplemented;
- [ ] The BadgeCardView was extended (affecting many areas in the client);
- [ ] The space items on the MyAccount settings Tab is now matching the style and size of the other lists (VCs, Packs, Hubs)
- [ ] The delete confirmation dialog (in subspaces settings) is now the main one (not the legacy one);
- [ ] Global Administration - the VCs page is now with a table layout (similar to Users & Orgs, no search though);
- [ ] Global Administration - Users & Orgs now have avatars;

The above changes (most of them) were approved by @SimoneZaza

**Comment by bobbykolev** [comment]
Note that the components used to list the subspaces (and the delete action) are both shared and legacy. 
It would require a bit more time than '1' to update the components and the options so that the other places stand untouched. @SimoneZaza FYI

**Comment by SimoneZaza** [comment]
👍 Thanks for the update!

**Comment by Comoque1** [comment]
Tested OK on DEV env.
This issue has been raised out of the testing: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6946
Search results cards are not tested, as search is not enabled on DEV env.
