### ISSUE TITLE
BUG: VC flow finishes with an error

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#6793]
**Describe the bug**

**To Reproduce**

1. Follow the vc creation flow (add knowledge or existing subspace)
2. After VC creation an error is thrown and the VC is not added to the BoK community.

**Expected behavior**
No errors, successful flow.

**Screenshots**

**Additional context**
See details in the linked PR

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
The issue fails with another (authorization) error now.
Moving it back to backlog.

**Comment by bobbykolev** [comment]
Another error extracted here:
https://github.com/alkem-io/server/issues/4445
