### ISSUE TITLE
BUG: Virtual contributors are not displayed on Space / account page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6797]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/evgenidimitrovsspace/settings/account or
2. Create a space with VCs
3. VCs are not displayed on the Space / account page
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbd5c7d7e54eefcb6a2f748d359e2b3835cc2641/image.png" alt="image.png" />

**Expected behavior**
VCs are displayed on space account page.

**Comment by techsmyth** [comment]
@Comoque1 Not sure they should be either. Needs a discussion with @SimoneZaza

**Comment by SimoneZaza** [comment]
@techsmyth @Comoque1 This indeed was intended. When we created the Host Account page, the VC was removed from the Space account page.
