### ISSUE TITLE
Subspace templates: updated create subspace dialog with option to choose template

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6801]
## Description
As a user, I want to be able to use a subspace template when I create a subspace
As a user, I want the design of the create subspace dialog to be consistent with the rest of the platform

## Acceptance criteria
Change the Subspace Create dialog to the 'new' style
- [x] Title (required)
- [x] Tagline
- [x] Description
- [x] Tags
- [x] Visuals
- [x] Template
- [x] Change template button opens library, eg like clicking on the library button in the whiteboard works
- [x] Tutorials: radio on/off (default = off) 
- [x] Only title is required

## Additional Context

<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0d5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d998b6c9c8f88dfa0f2098b38d2dc5849594576d/image.png" alt="image.png" />

## Areas that will be affected 
Design: https://www.figma.com/design/eHqxhDSrUZUyTTCmY2L5c5/Subspace-Templates?node-id=125-1563&t=vfIPktD1WUXa7Or8-1
 Flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/subspacetemplates
<img width="1807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c024b77b550d009b239a871d61feb28634d084fa/image.png" alt="image.png" />

**Comment by jeroentskui** [comment]
redesign create subspace dialouge; and include the option to pick from template in redesign https://alkem.io/sandbox/subspaces

**Comment by jeroentskui** [comment]
Need to work on how the template is displayed

**Comment by Comoque1** [comment]
Tested OK on DEV env.
