### ISSUE TITLE
Subspace templates: update innovation pack card

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6802]
## Description

As a user, I want to see complete info on a card. WIth 5 different types of templates the innovation pack card is "full" and there's no room to add the amount of subspace templates inside. 
<img width="378" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGgzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4634f29fd14a1f6743ddcd7ab1ecc379a6d65f8b/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Add subspace icon on the card - the new one subpart of the space icon (two circles connected by one line)
- [ ] Remove innovation flow icon on the card
- [ ] remove all numbers (saying how many templates of a certain type are there)
 So, each card will show what type of templates are in the pack, but not how many
- [ ] Show number in tooltip before label (which is already there, eg 7 whiteboards)

## Additional Context

Design:
<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbf8bf653f6085265875a6433c272600668875a2/image.png" alt="image.png" />
https://www.figma.com/design/eHqxhDSrUZUyTTCmY2L5c5/Subspace-Templates?node-id=13-1184&t=XCiBCz4FlxWYzQqc-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by jeroentskui** [comment]
https://alkem.io/innovation-library

**Comment by Comoque1** [comment]
Tested OK on DEV env.
