### ISSUE TITLE
BUG: There is no location from where a VC could be removed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6803]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/user/admin-alkemio/settings/account - user account settings - there is no button to remove a vc
<img width="1385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnA3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6dad70d057b15b2370ebe02f0b4e8d69a99b409/image.png" alt="image.png" />

2. https://dev-alkem.io/admin/virtual-contributors - there is no button to remove a vc
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnQ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7ae6ed387ed50f3a8ae836880f2363ba8a526b7/image.png" alt="image.png" />

**Expected behavior**
"Delete" Button is available for a VC deletion on
- user account page
- organization account page
- admin/VCs page
- VC settings page?

**Comment by SimoneZaza** [comment]
This will be fixed with #6808
