### ISSUE TITLE
Deleting resources from User/org account tab

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6808]
## Description

As a user, I want to be able to delete my VCs, Innovation packs, and custom homepages
As a user, I want to be able to delete my Spaces from my account tab

### Space
- [ ] Add "more" icon button on Space card
- [ ] This button opens a little menu with -for now only- a delete option
- [ ] Clicking delete opens the same confirmation dialog as the one on the Space>Settings>Account>Delete:
- Title: Confirm [Space/Virtual Contributor/Innovation Pack/Custom Homepage] Deletion
- Text: Are you certain you want to delete this Space? Keep in mind that this action is irreversible. You can only delete a Space if there are no underlying Subspaces associated with it. If there are any Subspaces within this page, please delete them first (you can do so from the Space settings > Subspaces page).
- Checkbox + text: Please check this box if you are certain about deleting this Space
- Buttons: Cancel; Yes, Delete

### VC
- [ ] Add "more" icon button on VC card
- [ ] This button opens a little menu with -for now only- a delete option
- [ ] Clicking delete opens a confirmation dialog:
- Title: Confirm [Virtual Contributor/Innovation Pack/Custom Homepage] Deletion
- Text: Are you certain you want to delete this [Virtual Contributor/Innovation Pack/Custom Homepage]? Keep in mind that this action is irreversible.
- Checkbox + text: Please check this box if you are certain about deleting this [Virtual Contributor/Innovation Pack/Custom Homepage]
- Buttons: Cancel; Yes, Delete

### Innovation Pack
- [ ] Add "more" icon button on Innovation pack card
- [ ] This button opens a little menu with -for now only- a delete option
- [ ] Clicking delete opens the same confirmation dialog as above (VC)

### Custom Homepage
- [ ] Add "more" icon button on Custom Homepage card
- [ ] This button opens a little menu with -for now only- a delete option
- [ ] Clicking delete opens the same confirmation dialog as above (VC)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
@bobbykolev Sorry, I've missed your last comment. Probably too late, but:
- Error when deleting space with subspaces is sort of fine, we're warning for this in the confirmation dialog
- I assume there will be no error for innovation packs of which the templates are used, since these are not (yet) linked to each other. As I understand it, when a template is selected it is just copied, losing all ties with the original. @techsmyth right?
- Regarding the custom homepage, in the end the host should be able to remove this. Fine to be picked up later when we unwrap this entire thing, allowing people to create them as well etc :)

**Comment by techsmyth** [comment]
@SimoneZaza yes indeed - templates are copied, not linked

**Comment by Comoque1** [comment]
Tested OK on DEV env.
One minor issue is raised: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6857
