### ISSUE TITLE
Finalizing + testing subspace templates flow

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6809]
## Description
Placeholder for time needed to finalize and test the subspace templates flows when it's complete

## Acceptance criteria

- [ ] Scenarios from this [file](https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Contributors/Shared%20Documents/Development/Scenarios/templates_scenarios.xlsx?d=w6a319f5ed31747978aef2e2e4f6c6dc2&csf=1&web=1&e=yq9ezF) are performed
- [ ] Findings are reported and prioritized

## Additional Context
Flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/subspacetemplates
<img width="1807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c024b77b550d009b239a871d61feb28634d084fa/image.png" alt="image.png" />

## Areas that will be affected 
 ~ 1 day of testing + AHT

**Comment by Comoque1** [comment]
Results of testing are reported on the release report:
### QA Notes
 - Testing activities
 - Automation: All API tests passing locally against master branch
 - Manual:
   - Exploratory testing
   - Feature testing
   - Risk based testing
 - [Resources](https://alkem.io/myspaceevgeni/challenges/qaandtesting/collaboration/xstatetestdesign)
