### ISSUE TITLE
Users to be able to see pending applications on their profile page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#683]
## Description

As a user I want to be able to see and cancel pending applications on my profile

## Acceptance criteria

- [ ] User Profile page expanded to also show open applications for membership
- [ ] User able to delete a pending application

**Comment by Comoque1** [comment]
Looks OK.
The only issue comes, when user has an application to an ecoverse and it is deleted - than all applications of that user are not returned due to issue in `membershipUser` query.

Logging bug about it,
