### ISSUE TITLE
BUG: Wrong link when clicking on user card in Subspace > Contributors

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6836]
**Describe the bug**
When clicking on a user card in the contributors section of a Subspace, I get a page not found. Something is wrong with the URL, it is pasted after the URL I'm at, see below:
<img width="665" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9lQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97439b0c17ecb2c563231788aa546a1efbd5f541/image.png" alt="image.png" />
URL: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/contributors/https://alkem.io/user/evgeni-dimitrov

**To Reproduce**

1. Go into a subspace
2. Click on the community
3. Click on one of the profiles
4. See error page

**Expected behavior**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by larssondenise** [comment]
can we include in this issue/with this issue that the preview of the user card is shown? @SimoneZaza @Comoque1

**Comment by hero101** [comment]
@larssondenise We will include it.

**Comment by Comoque1** [comment]
Tested OK on ACC and PROD env.
