### ISSUE TITLE
authorization policy information page to show additional information

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6843]
## Description

As a ops manager I want to be able to track down issues 

## Acceptance criteria

- [ ] Authorization policy page on admin pages of client to show a) type b) the criterias for each rule

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
```
  lookup {
    authorizationPolicy(ID:"927ac37f-cfca-49c5-8fa7-ee3e2fdccf34") {
      type
      credentialRules {
        grantedPrivileges
        criterias {
          type
          resourceID
        }
      }
    }
  }
```

**Comment by Comoque1** [comment]
Tested OK on DEV env:
<img width="1170" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1400ece17d447e9d488000c99e8ab289cf3230dd/image.png" alt="image.png" />
