### ISSUE TITLE
Only show amount of comments when there are comments, thus no (0) + only show flow state if there is one

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6860]
- As a user, I don't like seeing (0) everywhere, as an admin posting closed posts, I don't want to show (0).
- As a user, I don't like seeing - not used in the knowledge base (where the same component is used as in the subspaces, but the innovation flow isn't used)

**So:**
- Don't show (0) when there are no comments/contributions
- Don't show - not used when there is no innovation flow state

Locations:
- [ ] Knowledge base (Space)
- [ ] Subspace > Index
- [ ] Innovation flow settings/manage innovation flow drag and drop thing
- [ ] Sort contributions dialog

**To Reproduce**

1. Go to https://dev-alkem.io/testcalloutsorder/knowledge-base
2. Click on "menu"
3. Click on "sort contributions" - all posts have (0) as postfix and there is - not used in the list on the left
<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20d5750e9c5bee4f74ee85f24a7bd2645a347b7d/image.png" alt="image.png" />

**Expected behavior**
Only posts with comments get a postfix with the amount of omments

**Comment by bobbykolev** [comment]
This is the count of the comments. 

<img width="184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb78fb1aa4ce1c50edc2909eec396ae59f199dd/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
I think it would be nice if it's only visible when there are comments? So:
first (0) --> first
second (1) --> second (1)
third (43) --> third (43)
fourth (0) --> fourth

**Comment by bobbykolev** [comment]
I'm sorry for the delay but as discussed on the question - another task, please.

**Comment by reactoholic** [comment]
Locations where the zero count was removed as part of the UI:
- Space > Subspaces > Journey cards
- Space > Knowledge base [callouts list in the left]
- Space > Knowledge base [callouts cards]
- Subspace > Index
- Subspace >Innovation flow settings/manage innovation flow drag and drop thing
- Sort contributions dialog
