### ISSUE TITLE
Resources on profile page

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6873]
**NB This is part of the original issue #6856** this part is taken out to do first, since this has highest priority
## Description

As a user, I want to see what resources people are hosting
As a user, I want a quick way to access my hosted resources

## Acceptance criteria
Right column of the user profile:
- [ ] First block
- Title: Resources I host
- Show space cards as per design for each hosted space. 
- > Wrap if more than three
- Underneath, show three columns for
- > Virtual Contributors
- > Innovation packs
- > Custom homepages
- If the user doesn't have the resources of a specific type, don't show the header
- Use the horizontal cards also used on the Account page (profile > settings > account) (sorry, not in the design)
- **If the user doesn't have any resources, don't show this block**

Right column of the **organization** profile:
- [ ] Move Associates block to the left, underneath the bio
- [ ] First block
- Title: Resources we host
- Show space cards as per design for each hosted space (spaces that the org is facilitating). 
- > Wrap if more than three
- Underneath, show three columns for
- > Virtual Contributors
- > Innovation packs
- > Custom homepages
- If the org doesn't have the resources of a specific type, don't show the header
- Use the horizontal cards also used on the Account page (profile > settings > account) (sorry, not in the design)
- **If the org doesn't have any resources, don't show this block**

## Additional Context
Design: https://www.figma.com/design/TmD1pfsd50DDxEoV1ykJDl/Profile-Update?node-id=16-3&t=0GAfYWABCJ8ry5TP-1
Scroll around for various scenarios (all for a user profile, but org profile should be the same)

- new queries
- lot of details
- visibility things
--> Lot of work to get it right

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
