### ISSUE TITLE
Show subspace events in Space

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6876]
## Description
As a subspace admin, I want to be able to promote some events on the Space level as well.
As a space admin, I want to be able to prevent subspace events from being promoted on the space dashboard

### Space settings to (dis)allow subspace events to be shown in space calendar
- [x] In the Allowed Actions on Space/Subspace l1 > Settings > Settings, add
- **Subspace events**: Allow events from Subspaces to be published on this calendar as well
- as per design
- [x] Should be on by default

### Switch on event create/update dialog to show subspace event in space
- [x] At the bottom of the screen (above the footer with the buttons), add switch
- Text: Also visible on <title parent (sub)space> Calendar
- Default off

### Updated show event dialog with space/subspace title
- [x] In the dialog with the list of events, show Space/Subspace title of the event in the header of the event, on the right of the time
- [ ] In the dialog per event, show Space/Subspace title of the event in the header of the event, below the time (See design, difficult to explain)

## Design
https://www.figma.com/design/rddyv3LBg0sbm1b7Yny9ze/Calendar-V3?node-id=158-530&t=kMt4Dx0dO30ikqke-1

Comments on related server issue (old, replaced by this issue):
- In which of the 3 blocks would this setting be found? - I believe Allowed Actions fits best
- a new field for this setting needs to be added
- a new column is required to indicate the visibility of the event
- how deep do we want to display events - level 1 or further? **Let's keep it at one level up for simplicity for now**
- if I assume the subspace event will be visible when the root Space events are queried, a new field should be added to indicate this event is not part of the Space events
- Can a non-member still see the events if the subspace is private and both settings are enabled? **Preferably yes, but if this is adding complexity then please leave it as is for now, but inform product team**

**Comment by Comoque1** [comment]
Tested on ACC env.
Findings are as follows:
1. Events from private subspaces are not visible on Space level (above is written, that if there is complexity it is acceptable)
2. Unauthenticated user can see comments and users on events of Public space / Subspace: [Bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/7176)
3. Only Subspace L1 events are visible on Space level - as per AC
4. "Also visible on the parent Space calendar" button is visible on Subspace Level2: [Bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/7177)
5. The point:  In the dialog per event, show Space/Subspace title of the event in the header of the event, below the time (See design, difficult to explain) - not implemented: <img width="1414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeml4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80cd47b0de265278913374782671cab7b33ec3cc/image.png" alt="image.png" />

[Test results](https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Contributors/Shared%20Documents/Development/Scenarios/Release%20-%20Simple%20Home/eventsOnParentSpace.xlsx?d=wb1c25ebfd27d45fc85340bdcf4cfc048&csf=1&web=1&e=K1aCGn) in document related to auth.

**Comment by Comoque1** [comment]
@SimoneZaza if you accept the above feedback, we can close the issue.
