### ISSUE TITLE
Default Subspace template selection/display for Space

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6879]
## Description

As a Space admin, I want to be able to set a default template for new Subspaces

## Acceptance criteria

- [x] Change Default Settings block to:
- [x] Title: Default Subspace Template
- [x] Show preview from Subspace preview window. with everything, innovation flow and callouts, like in the library preview
- [x] Button "Change Default Template", which follows the same behavior as the change default flow button does now
- Dialog header: Change Default Subspace Template
- Dialog text: Customize the default template for newly created Subspaces. 
Below you can choose between the templates collected in the Space Templates library. If you’re looking to create new templates or explore additional templates, click here to access this library. (with link to the library)

## Additional Context

Screen shots / UX designs / data that are relevant.
https://www.figma.com/design/eHqxhDSrUZUyTTCmY2L5c5/Subspace-Templates?node-id=3-5585&node-type=canvas&t=QjiRD8pD6FpH8biD-0
## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Callouts are not displayed:
<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThrQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ee57f829ca54db4fb42a1d8b6b212e21181f47b/image.png" alt="image.png" />
