### ISSUE TITLE
"Save" button removed

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#6884]
## Description
Since the master snapshot is resolved on the server, and the save is performed server-side we need to remove the save button and its related code and actions.

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] The "Save" button from the dialog is removed
- [ ] The code related to this functionality is removed

**Comment by Comoque1** [comment]
Tested OK on sandbox.
