### ISSUE TITLE
Usage of temporary storage

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#6886]
## Description
As a developer I want to know that the temp storage is supported by the client so I can start using it

## Acceptance criteria

- [ ] Temporary storage working for upload during creation flow

## Additional context
- There is a [PR for making all uploads using temp storage.](https://github.com/alkem-io/client-web/pull/6862/files)
- There should be parameter in **FileUploadProps** that is used when uploading new files.

**Comment by reactoholic** [comment]
**[Link](https://github.com/alkem-io/client-web/pull/7114)** to the closed PR for reference to the proposal for new syntax rules, etc.

**Comment by Comoque1** [comment]
The performed testing was against ACC env and was limited to creation of 1 entity from different types (i.e. Subspace, callout, template on space, etc... ).
A couple of bugs have been raised and linked to the [epic](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/alkemio/1435), where each has impact on different areas over the application.
In the attached [file](https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Contributors/Shared%20Documents/Development/Scenarios/Release%20-%20Simple%20Home/temporaryStorage.xlsx?d=w2e5276baccea4a6cb3f1a1f0871f0fe9&csf=1&web=1&e=cAWIwZ), can be found what has been tested and the related issues.
