### ISSUE TITLE
Check if client is passing enableComments flag into createCalloutInput when creating a callout and not a calloutTemplate.

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#6898]
## Acceptance criteria

- [ ] Client should be passing `enableComments` to any CreateCallout call that creates a Post callout

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
