### ISSUE TITLE
BUG: Some parts of the Template View are not updated after template update

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#6910]
**Describe the bug**

**To Reproduce**
space templates,
- editing a space template, user changes the right part of the form, 
- click save and it saves correctly, but the form gets resetted to the previous values,
- if user closes the dialog and reopen it again, it still has the old values
- but if refresh the page, the new values are there
- the left part of the form (template title, desc, and tags) was working alright, was only the template content on the right of the form
 

Update a callout template in a space.
The right part is not updated

**Fix**
It's missing a refetch

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on ACC on space with 1 collaboration tool of type link.
