### ISSUE TITLE
BUG: Importing templates Dialog keeps state on 2nd usage

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#6911]
**Describe the bug**
Importing templates Dialog keeps state on 2nd usage

**To Reproduce**

1. https://acc-alkem.io/space-templates/challenges/subspacetemplates
2. Add collaboration tool
3. Select the template library
4. Select a template and import it
5. Try to add another collaboration tool
6. You will go to the library dialog directly

**Expected behavior**
2nd time the dialog is opened, the user should open the `Add collaboration tool` dialog

**Comment by Comoque1** [comment]
Tested OK on ACC env.
