### ISSUE TITLE
BUG: Ability to edit link when not allowed

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6932]
**Describe the bug**
When an admin closes a collection of links for further contributions, members

**To Reproduce**

1. Disable the option to add new responses for collection of links as admin
2. Visit the collection of links as member
3. See the icon with ability to edit a link 
4. Try to edit the title, description or link and click save
5. See error with forbidden policy

**Expected behavior**
If I am not allowed to edit a link, I don't want to see the icon

**Screenshots**
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1gwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d501b526485bb27a6e8d89f325d521a4144af62/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested on DEV env. Icon is still visible, but not active. @SimoneZaza do you accept the new behavior?
<img width="1133" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d0e90eb5997132114223bb939dda16e8fbfb05f/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
Thanks @Comoque1. This is better than it was, but I prefer users not to see the icon at all.. This is still a bit confusing I'm afraid.

**Comment by Comoque1** [comment]
We had a brief discussion with @bobbykolev and he mentioned, that the behavior was like that before (inactive button) and a regression was introduced recently. 
Making the button hidden, might result in a bigger effort.
Closing for now and raised another story: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6987
