### ISSUE TITLE
Update Space VC block (add invite button)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6941]
## Description
As an admin, I want to be able to invite vc's directly from my Space Community page

## Acceptance criteria

- [ ] "+ Invite Virtual Contributor" button at the top of the list of Virtual Contributors, like we do with the Subspaces hierarchy block in a Subspace (see screenshot below)
- [ ] This button should only be visible to people with the invite privilege (COMMUNITY_INVITE ?)
- [ ] The button opens the Invite VC dialog, same as it is now from Space > Settings> Community - https://github.com/alkem-io/client-web/issues/7256
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEQ1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c906b780a6ea339c770bc6ee6832da2120c29400/image.png" alt="image.png" />

- [ ] Remove margin between the VC cards in this block (see screenshot, the margin between title and vcs is fine, but there <img width="517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy81Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a983496f8d55273fbb673f89e42a8ee2982fb060/image.png" alt="image.png" />

## Additional Context
Screen shots / UX designs / data that are relevant.

**Comment by bobbykolev** [comment]
To reduce double work, let's use this ticket only for the changes in the VC block - Add button depending on the privileges. The actual functionality is better to be covered with this one:
https://github.com/alkem-io/client-web/issues/7256 

@SimoneZaza

**Comment by Comoque1** [comment]
Tested OK on ACC env.
Tests performed: https://alkem.io/myspaceevgeni/challenges/qaandtesting/collaboration/releasenotificationsscope/posts/vcstore
