### ISSUE TITLE
New homepage for unauthorized users

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6943]
## Description

As a potential user/partner/investor exploring the platform as guest, I want to see an engaging and non-confusing homepage

## Acceptance criteria

- [ ] "Explore spaces block" with:
  - [ ] Rocket icon
  - [ ] Title: Explore Spaces of Your Interest
  - [ ] Filter bar with preset tags, same as we currently have on the dashboard explore spaces block
  - [ ] 3 rows of spaces cards
    - Using the hover state of the current card for the horizontal my memberships cards on my dashboard
    - Removing the space icon
  - [ ] start with Welcome @ Alkemio space, followed by other Spaces ordered on:
  - Most Activity
  - With public spaces first
- [ ] Sign up button, centered, not stretched

## Additional Context
Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=157-258&t=Gza73MHah8E70Hxx-1
<img width="1133" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0w2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8732bd248a6bb2cdf91ae72d88b4f24148291451/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
QA notes:

The task is completed with some design deviations (discussed with Simone). 

The sorting requirements are not implemented. The options will be discussed separately.

**Comment by bobbykolev** [comment]
The sorting criteria will be met with the completion of the following story: https://github.com/alkem-io/server/issues/4517

**Comment by Comoque1** [comment]
Tested OK on local env.
The case when a user is authenticated, the sorting is not applied based on latest activity:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dcb7cb63d87f9588b9b010e01f87ad6b9156705/image.png" alt="image.png" />
