### ISSUE TITLE
BUG: L2 subspace avatar not displayed under L1 subspaces (Subspace settings)

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6946]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/78877/challenges/222z0/settings/opportunities
2. Or
3. Create sub-sub space avatar
4. Navigate to its parent subspace
5. Navigate to subspaces - avatar of l2 subspace is not displayed
<img width="1647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDcvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adc457f2d06b5687565aafc336c5ea2d39249918/image.png" alt="image.png" />

**Expected behavior**
Avatar is displayed.

**Comment by SimoneZaza** [comment]
@bobbykolev is this related to the avatar changes?

**Comment by bobbykolev** [comment]
Yes, by now there were no avatars on this level.

**Comment by Comoque1** [comment]
Tested OK on dev env:
<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEFxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fc90b43298d93c3ae5af1f1dd2fef82a9133dcf/image.png" alt="image.png" />
