### ISSUE TITLE
BUG: Explore Spaces - custom subspace visuals are not displayed (PROD)

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#6948]
**Describe the bug**
The default avatars and banners are shown for subspaces instead of the custom ones.

**To Reproduce**

1. Go to  https://dev-alkem.io/spaces - avatars & banners with custom visuals are presented with the default ones (for the subspaces).

<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEgvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6326aff84bc26e03b4a6e10b8c5fd40e21483c7/image.png" alt="image.png" />

**Expected behavior**
Custom avatars and banners are displayed.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
