### ISSUE TITLE
BUG: Support admin doesn't have rights to create templates on innovation packs

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6960]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/innovation-packs/subspaces-pack/settings
2. Assign yourself as Support admin
3. Try to create WB template - auth error is thrown: ` "message": "Authorization: unable to grant 'create' privilege: templates set create template: aec7f267-4163-4854-9022-11c28560d1ab user: c12b6a26-445e-4a4a-8718-e339b3e7ab14 on authorization of type 'templates-set'",`
<img width="1071" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9QQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75d9216e78a722844c17782e388ad150bf6592e1/image.png" alt="image.png" />

**Expected behavior**
Innovation pack to have a setting to allow support admin to manage innovation pack (like on space)

**Comment by SimoneZaza** [comment]
This is expected behavior, but of course not desired behavior.. So added a new issue to approach this more structurally, also for the other resources: #4623
