### ISSUE TITLE
Settings image upload: click on preview to start

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6963]
## Description

As a user, I keep clicking on the image to change it, this comes more naturally to me than clicking on the word 'EDIT' below it

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f71a5a8949b0c707a8f20b30a637fb5a6592453/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Make avatar preview clickable, with the same behavior as the edit button
- [ ] Space settings profile
- [ ] Subspace settings profile
- [ ] Org/user/VC profile settings
- [ ] Custom Homepages (innovation hub)
- [ ] Post card of call for post callout

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env for all points from AC and works fine.
