### ISSUE TITLE
BUG: When template is imported into WB the changes are not save

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6964]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/evgeniadminsspace/challenges/defaultsub1/collaboration/memberwbfrom1
2. Open the WB with at least 2 users
3. With user 1 import template with Visual - template it loaded on the WB
4. User 2 doesn't see the changes from the imported template
5. User 1 make a change on the WB - save event is not triggered until User 2 don't make a change

**Expected behavior**
When a template is imported, the changes are saved and visible to all active to the WB user and are saved

**Comment by hero101** [comment]
When you "use" a template or you import an excalidraw file the client "freezes", meaning it stops sending further messages that the scene has updated.
The only way to "unfreeze" it is another client to send a message and the frozen client can starting sending the messages again.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
