### ISSUE TITLE
BUG: Only showing 1 tag on call for post cards

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6968]
**Describe the bug**
Although there is enough space, only 1 tag is shown on the call for post cards:
<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08dade8bf97ae2e82a2ceeffed8af9a0c070ef22/image.png" alt="image.png" />

**To Reproduce**

1. Create call for posts
2. Add post, add two tags in it, save

**Expected behavior**
1 row of tags to be shown

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
The issue is not reproducible on PROD anymore.
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzA4Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1b4bec001be976bd7160887e93318dd4a7c453d/image.png" alt="image.png" />
