### ISSUE TITLE
Sentry: Use the environment field to categorize issues

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6989]
## Description

As a product service manager, I want to clearly see production issues - without acceptance mixed in

## Acceptance criteria

- [ ] Sentry data to properly set the environment that the error is coming from

Later: can explore how to get alerts / reports to use the environment properly.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b3ac98dfa48c302b35d073953c29eec4067312d/image.png" alt="image.png" />

## Additional Context
This is the weekly email I receive:

<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e1b0a8a4421c8a49c3a758825ed3ca2472545e0/image.png" alt="image.png" />

Could be super useful, but value is seriously undermined by having acceptance in there.

**Comment by bobbykolev** [comment]
After brief research, I can see that we're using the environment based on our build e.g. production, not the env name.
The Sentry docs suggest using this environment filed for filtering. There's nothing for separate instances per env (as Valio suggested).

A quick way to filter only the prod issues is adding a filter `url is https://alkem.io/*`.
For the alerting, @techsmyth can you double-check your "Neil - alert for prod issues" settings? Can you add the URL filtering so we're receiving only such?
