### ISSUE TITLE
BUG: Send message to user mutation fails

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6992]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/evgeniadminsspace/challenges/defaultsub1/about
2. Hover over Lead of an entity
3. Click on "mail" icon
4. Fill up the form and send a message - error is thrown
<img width="1437" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f71b881fa4331efea587655b92da3e5e18a8f4ae/image.png" alt="image.png" />

**Expected behavior**
Message is sent successfully.

**Comment by SimoneZaza** [comment]
@Comoque1 I can't reproduce this on production?

**Comment by Comoque1** [comment]
Agree, not reproducible and against the leads from the repro stes.
