### ISSUE TITLE
Community block for unauthenticated users

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6995]
## Description

As product team, I want an engaging page for unauthenticated users that enter an open Space

When a user is not logged in, they can't see user profiles. However, this community (screenshot) now seems empty even though there are several members. This creates the wrong impression.

https://www.figma.com/design/okn4NIeReIY6GT78tzn2DX/Virtual-Contributors-on-Contributors-Page?node-id=0-1&t=oq34RTx6RY6HfYGj-1

## Acceptance criteria

- [ ] Update placeholder image - ensure it is aligned with our values
- [ ] Community block in Space for unauthenticated users to show placeholder image (see if we need different grid compared to platform contributors page)

## Additional Context
![Image](https://github.com/user-attachments/assets/59621049-d9f4-4b24-a76f-427baa595327)
![Image](https://github.com/user-attachments/assets/83236198-9928-4757-b13a-e462baab5cd7)

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
Part of #7129
