### ISSUE TITLE
BUG: VC Host is not clickable

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6996]
**Describe the bug**
On the VC profile, I can't click on the host + I don't see the avatar

**To Reproduce**

1. Go to a VC profile
2. Try to click on the host 
3. 

**Expected behavior**
- [ ] I want to click on the host to for example read more about them or contact them
- [ ] I want to see the avatar
- [ ] I want it to expand when I hover

**Screenshots**
<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--104a24fe844ac4b07b1068dfedc8480613e083df/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested ok on dev env for both
- VC hosted by ORG
- VC hosted by USER
