### ISSUE TITLE
Notify option in create dialog

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7001]
## Description

As a user I want consistency in whether or not/how I can notify my community when I create a collaboration tool

## Acceptance criteria

- [ ] notify option for collaboration tools in create dialog (similar to when creating space)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by jeroentskui** [comment]
check all create dialogs

**Comment by SimoneZaza** [comment]
Part of new create flow
