### ISSUE TITLE
Space > Subspaces tab > "List view" block

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7012]
## Description

As a user I want to easily navigate my subspaces
As a PO I want consistency in the lay-out of the platform

## Acceptance criteria

- [ ] Add search and remove 'list view' (a block similar to the Knowledge Base)
- [ ] Placeholder text should be 'Find Subspaces...'
- [ ] Only show this block when there are more than 3 Subspaces
- [ ] Use avatars instead of icons

## Additional Context
Current design:
<img width="1135" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21oQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e3f943e15703b65d948752fdeaac7b80c7b57a/image.png" alt="image.png" />

Knowledge base index:
<img width="318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmc2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ae9d6ab147d25922eb029e1fd3225ce1add9958/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by larssondenise** [comment]
@SimoneZaza I don't think we need to rename to index, but simply take the same block as knowledge base (which doesn't have a 'title'). what do you think?

**Comment by SimoneZaza** [comment]
@larssondenise agreed!

**Comment by bobbykolev** [comment]
Hello, for consistency, why don't we reuse the block that we have on the dashboard?
<img width="357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e48c004a464bbc30da6775004a3dc9656ba5d2e0/image.png" alt="image.png" />
@SimoneZaza

**Comment by SimoneZaza** [comment]
@bobbykolev Because there's no filter/search option there... Or we should implement it there as well? E.g. search icon where the ? is now..

**Comment by bobbykolev** [comment]
> @bobbykolev Because there's no filter/search option there... Or we should implement it there as well? E.g. search icon where the ? is now..

Nope, as we have a huge section with a search on the right where the main content is, I suggested having something similar to a resources/spaces/subspaces list. Nevermind, it's already implemented.

**Comment by Comoque1** [comment]
Looks OK on Prod Env.
