### ISSUE TITLE
BUG: When unauthenticated user open public space, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7023]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home
2. With unauthenticated user search for the term "roles" - only 1 result is returned
3. Click on the space - it is loaded successfully, but error is thrown: `"message": "No Agent found with the given id: ",`
<img width="1494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2923635d1517ccea3e3eab4cfaa8e1f0f1547bb/image.png" alt="image.png" />

**Expected behavior**
Errors are not thrown.

**Comment by techsmyth** [comment]
It is to do with the myRoles field on roleSet on subspaces: 
query SpaceDashboardNavigationChallenges($spaceId: UUID!) {
  lookup {
    space(ID: $spaceId) {
      id
      subspaces {
        id
        community {
          id
          roleSet {
            id
            myRoles
          }
        }
      }
    }
  }
}

gives the same error
