### ISSUE TITLE
Allow invitation to subspace of private space

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#7026]
## Description

As an admin, I want to invite people directly as admin or lead to a subspace within a private space

## Acceptance criteria

- [ ] Allow access to sufficient information about the Space that is being invited to without needing READ access to the parent space
- [ ] Client updated to use the information from the me query to display the Space information

**Comment by Comoque1** [comment]
Tested OK on ACC env.
Test results: https://alkem.io/myspaceevgeni/challenges/qaandtesting/collaboration/testresults
