### ISSUE TITLE
BUG: All is not all on dashboard unauthenticated user

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7029]
**Describe the bug**
On the dashboard for unauthenticated users, they see a block with All spaces. However it does not show all Spaces 

**To Reproduce**

1. Go to alkem.io/home without logging in 
2. See tab with all Spaces 
3. 15 Spaces are shown

**Expected behavior**
- "All" in filter should be "Most Active Spaces"
- "Show all spaces on the platform" should be "Show more"

**Screenshots**
<img width="1018" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20acdd0ceb50d3204ef68e91dab95b8b0b6f7aab/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
The request for the load more items copy - Show more, could collide with fix from: https://github.com/alkem-io/client-web/issues/7031
However, I think '**Show more**' is correct in both instances (initial results and on search with a predefined tag).

**Comment by Comoque1** [comment]
Tested ok on dev env.
