### ISSUE TITLE
BUG: Show all Spaces should be Show all

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7031]
**Describe the bug**
On the dashboard for unauthenticated users, there is a tag for example for innovation. When I expand, it shows me more Spaces with the tag innovation. However, the text says show all spaces on the platform

**To Reproduce**

1. Go to Dashboard without logging in
2. Click on the tag innovation
3. See all spaces on the platform text

**Expected behavior**
Adjust the translation?

**Screenshots**
<img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b7aa15820d0200ed54b5179b84af78b30f602e9/image.png" alt="image.png" />

**Comment by DonnaDuiker** [comment]
30 min total untill sending to review
