### ISSUE TITLE
BUG: Calendar events bucket - must fix

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7032]
**Describe the bugs**

<details>
<summary>- [x] Remove "True" label from "Title" box</summary>
Align the top 2 boxes
<img width="1425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fc7ad3e476020370a5c247fc9f8db5593fd0465/image.png" alt="image.png" />
</details>

<details>
<summary>- [x] Location is not returned when it is added on create/update of event:</summary>
<img width="1621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ed1f7aea8ea2a653229938fa5ef3d8a20383cfd/image.png" alt="image.png" />
<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dca044b6201617c87f4b715de6b552b539e11866/image.png" alt="image.png" />
</details>

<details>
<summary>- [x] When set start date and try to set end date to be the same as start date, the date is not clickable (_3rd party calendar limitation_)</summary>
<img width="1221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eebb318170c7bf4b7d80d43b1aa24f39c1a2a8cd/image.png" alt="image.png" />
</details>
<br />

**Expected behavior**
The above issues to be addressed.

**Comment by bobbykolev** [comment]
As a fix for the third one, logic was added to set the end date as the start date every time the user selects the start date after the end date.
