### ISSUE TITLE
Simple homepage: activity dialogs

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7034]
## Description

As a normal user, working in just 1 or 2 Spaces or none at all, I want a clean and simple homepage that brings me right back to the Space. At the same time, I want to have the option to show recent activity, invitations, etc. 

## Acceptance criteria
Recent Activity in my Spaces dialog
- [ ] Same as the block that's currently on the right side of the dashboard, but then in a dialog
- [ ] (maybe a bit broader if we have a standard width for dialogs?)

My Recent Activity dialog
- [ ] Combination of the dialog above and the current "My recent activity" block
- [ ] Filter on Space (like in the Recent Activity in my spaces)
- [ ] Cards like they are in the current "My recent activity" block
- [ ] Paginated, like in the Recent Activity in my spaces

### dev notes
Activity is tricky and if we stick to what we have it could be less ~3 but with the new filtering on My Activity is unclear and it would be higher.

<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenROQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--121179b86c8d0d0041c69e1f99856fdc10b1ca03/image.png" alt="image.png" />

Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=310-2&t=grlSUn8WuhYieTBr-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Notes on **My Latest Activity**:

- the component now loads 20 items (similar to the other);
- The logic behind it creates complex groupings, and paginating is not trivial. If possible, let's leave it for future refinement.
- The Loading component was added to both. Now, on initial load and filtering, the loaders spin under the filters. 

@SimoneZaza FYI
