### ISSUE TITLE
Simple homepage: switch in menu

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7036]
## Description

As a normal user, working in just 1 or 2 Spaces or none at all, I want a clean and simple homepage that brings me right back to the Space. As a power user, I want my rich dashboard back!

## Acceptance criteria
- [ ] Add switch to user menu where users can toggle the "simple homepage" on or off

## Additional Context
Design follows
Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=310-2&t=grlSUn8WuhYieTBr-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
The component is available and functional.
Its called "Activity" view
<img width="1679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJ4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bee1ed803c3da5547e3c12f6bb6e8b9f1b6f156d/image.png" alt="image.png" />
