### ISSUE TITLE
Simple homepage: mobile version

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7041]
## Description

As a user, I want the content of my homepage to looks good and to be accesible on mobile. 

## Acceptance criteria
- [ ] Make sure all components are visible/accessible on smaller resolutions.
- [ ] The Dashboard Menu should transform into an expandable component on tablet/mobile resolution.
Collapsed by default. The visible part should state 'Menu' with an ExpandMoreOutlinedIcon on the right.
- [ ] Invites badge to be present next to the Menu copy.

Addional ACs:
- [ ] the Activity blocks switch their positions on mobile (avtivity view).
- [ ] the resources menu is hidden on mobile. 

## Additional Context
<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d4b0a98bd04408913ff9c460bef63f04aadee88/image.png" alt="image.png" />

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb022ec2e72845a7d91b16a59d4e291667300e15/image.png" alt="image.png" />

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1rQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c2703e6a54e425a0acfd2d77227aece7dfd75ad/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
