### ISSUE TITLE
Move Spaces from Alkemio BV account to appropriate accounts

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7087]
## Description

As PO and Engineer I want to have Alkemio BV account clean from spaces that are not directly related  to it. There are 2 reasons for this:
1. the account is large and policy reset struggles to perform
2. spaces related to particular cause are transferred to appropriate account

## Acceptance criteria

- [ ] Analyze the spaces under the account  
- [ ] Make a list with spaces to be moved to the appropriate accounts
   - [ ] If there is no account that fit, create
- [ ] Transfer all listed spaces

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@Comoque1 this has already been done as far as I am aware, right @larssondenise ?
