### ISSUE TITLE
When new client changes are deployed, the user gets them without the need of hard refreshing the browser

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7088]
## Description

As a User I want all changes to be displayed, without the need of triggering commands (ctr+shift+r) to do a hard refresh on the browser

## Acceptance criteria

- [ ] All latest changes are visible to end user without the need of refreshing with keyboard key combination and cache cleanup

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@Comoque1 I thought that this was in place already? There used to be a hash added to each generated build...

**Comment by Comoque1** [comment]
The issue wasn't reproduced with the latest deployment to production.
For now we'll close it and if it happens again, we'll dig deeper.
