### ISSUE TITLE
BUG: Missing user name in the Dashboard page, welcoming section in the top left corner.

### ISSUE THREAD

**Issue by reactoholic** [alkem-io/client-web#7089]
**Describe the bug**
Missing User name in the top left welcoming block.

**To Reproduce**

1. Go to 'alkem.io log in page'
2. Enter login credentials
3. Wait to be redirected to the dashboard page
4. See missing user first name in the welcoming block

**Expected behavior**
User must see their first name in the dashboard's welcoming block after successful login.

**Screenshots**
<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a24e1f0fb66a83832af4d3cdb5c9752e41cf4b93/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on DEV env.
