### ISSUE TITLE
[Simple Homepage] Testing

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7103]
## Description

This is the task to cover the testing of the entire Simple Homepage epic.

## Acceptance criteria

- [ ] All ACs from the other stories from the epic should pass;

## Additional Context

Screen shots / UX designs / data that are relevant.
https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=344-833&node-type=frame&t=oCWL1EYyFmgzSuHY-0

## Areas that will be affected 
All user landing dashboards/home.

**Comment by Comoque1** [comment]
Tested on ACC env.

[Test design + results](https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Contributors/Shared%20Documents/Development/Scenarios/Release%20-%20Simple%20Home/simpleHomePage.xlsx?d=wb8bddf89b24047c7b3e8b2b3a50e2ec8&csf=1&web=1&e=lc2amu)
The main testing was performed on Chrome and Chromium based browser
Additional exploration has been performed against the following configurations
Mobile:
Samsung Galaxy S23: Chrome
iPhone 15: Safari

Desktop:
OS: Ubuntu 22.04
 - Chrome 130
 - Brave: chromiunm 130
 - Firefox: 132
