### ISSUE TITLE
Address errors in JS console

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#711]
## Description

As a user / developer, it does not look good to see errors in the browser console

## Acceptance criteria

- [ ] Errors being reported in the JS console are addressed
- [ ] Remove console.log messages

## Additional Context

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3f5713c4-2537-4093-8cba-ca1a2a5f77fb)

**Comment by Comoque1** [comment]
Still getting the errors on dev environment.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/596c9c8b-bcd9-4f39-8eec-05f618757370)
