### ISSUE TITLE
Updated Contributors page with VCs

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7126]
## Description

As a user. I want to browse through all available VCs on the platform

## Acceptance criteria

- [ ] Reduce the height of the blocks on the contributors page, to show only 1,5 rows of cards per block
- [ ] Add Virtual Contributors block between Users and Organizations
- [ ] Show all VCs that are allowed to be shown in public selection lists(?) (see screenshot below)
- [ ] When a user hovers over a VC, show the VC card
- [ ] Titles: (tbd)
- Top users
- Public Virtual Contributors
- Verified Organizations

## Additional Context

Only show VCs of which the visibility is set to public + added to lists:
<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGVPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a4ff776556acdc5df9796f05701c6e0d1668eea/image.png" alt="image.png" />

Figma: https://www.figma.com/design/okn4NIeReIY6GT78tzn2DX/Contributors-Page?node-id=0-1&t=qgXV2wr0QR17F5x1-1
<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--598a41e17edcf9bee57074edd013243d97ed25cb/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza yes that is fine - closes the gap for now...

**Comment by Comoque1** [comment]
Tested OK on DEV env.
Only 1 comment raised in a [story](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/7285).
