### ISSUE TITLE
BUG: Images in a whiteboard are not loading in the Edge browser

### ISSUE THREAD

**Issue by DonnaDuiker** [alkem-io/client-web#7141]
**Describe the bug**
Images in a whiteboard are not loading in the Edge browser, while they are loading in the Chrome Browser. 

This is occuring in the whiteboard to collect feedback from partners: Alkemio - Safe Spaces for Collaboration 

Sentry Issue: Error downloading file: https://alkem.io/api/private/rest/storage/document/498113d1-7626-4b31-9b8...: https://alkem.io/building-alkemio/challenges/productfeedback/collaboration/productfeedback-collabora/whiteboards/whiteboard — alkemio — alkemio 

**To Reproduce**
It is not happening with Alkemio accounts with elevated priviliges (Global Admin, GS). 

It is happening with accounts that are part of the Space "Building Alkemio" but not of the subspace "Alkemio Product Feedback", in which the whiteboard is located. 

After becoming a member of the Subpace I still don't see the images in the Edge browser. 

(I used my personal gmail account)

**Expected behavior**
Images to load also in the Edge browser

**Screenshots**
<img width="1032" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2360f09f154638c3875e6dee22124af0d8b513a5/image.png" alt="image.png" />

**Desktop (please complete the following information):**

- OS: Windows >=10
- Browser Edge
- Version 130.0.0

**Additional context**
Spotted in Sentry, also received an e-mail from a partner that had this issue.

**Comment by SimoneZaza** [comment]
@Comoque1 can you have a look whether this is easily reproducible or not?

**Comment by Comoque1** [comment]
@SimoneZaza , the document from the description is removed.
The exact same scenario tried to reproduce on ACC env and I the visuals were available for windows/edge configuration.
<img width="1570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFhCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7655754da090374eb0eebec0153316e678956098/image.png" alt="image.png" />
On production I have tried with my alkemio account (not GA and not member of the subspace) to see the visuals on the particular WBs - they were accessible from Windows10/ Edge 130...
