### ISSUE TITLE
Simple Homepage: On joining an invite, redirect to the (Sub)Space

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7155]
## Description

As a user, I want to be directed to the corresponding community, right after I click on 'Join' of an invite.

## Acceptance criteria

- [ ] On click on 'Join' button in the Invite Dialog or on the Dashboard (no memberships), redirect the user to the corresponding space/subspace.
- [ ] Make sure that dashboard is refreshed after you get back. e.g. from no memberships to the Spaces Dashboard.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env
