### ISSUE TITLE
Privacy icon on the Space/subspace cards

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7156]
## Description

As a user, I want a visual indication for public/private communities.

## Acceptance criteria

- [ ] The Space/Subspace tiles (Explore Spaces, no memberships, not authenticated, etc) to have visual distinction between public and private - a lock icon 
- [ ] For private spaces: 
- Primary color lock icon in white circle, 
- top right of the image, 
- size tbd, the size in the screenshot (15px) may be too small 
- little bit of elevation/shadow?
- [ ] No indication for public spaces

## Additional Context

<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c635b26c8f4decb3407d634b37d1e7ad896bbb4/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
On Explore spaces page is not used the new icon, but the old label:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW04Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5c5659c5c66eb3684330a8e245629773604923f/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@SimoneZaza is it expected search results dialog to be added as well?
<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTI4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11c025ca02d5406cf9462389b5deb6d472834855/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Thanks @SimoneZaza . Closing the issue.
