### ISSUE TITLE
BUG: Opening "My Membership" dialog, doesn't load subspaces data

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7166]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home
2. Set "activity view" to "true"
3. Click on "Explore all your spaces" block - "My Membership" dialog opens and doesn't load subspaces data
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94705e4e493940765e7d6cfdfb8ed6aff757379e/image.png" alt="image.png" />

**Expected behavior**
Subspaces data is loaded.

**Additional information**
The query executed loads the part in 
```gql
        childMemberships {
          id
          space {
            ...SpaceMembership
            __typename
          }
```
 but the client doesn't show it:

```gql
query MyMemberships {
  me {
    spaceMembershipsHierarchical {
      id
      space {
        ...SpaceMembership
        __typename
      }
      childMemberships {
        id
        space {
          ...SpaceMembership
          __typename
        }
        childMemberships {
          id
          space {
            ...SpaceMembership
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment SpaceMembership on Space {
  id
  level
  authorization {
    id
    myPrivileges
    __typename
  }
  community {
    roleSet {
      id
      ...MyMembershipsRoleSet
      __typename
    }
    __typename
  }
  profile {
    id
    url
    displayName
    tagline
    cardBanner: visual(type: CARD) {
      ...VisualUri
      __typename
    }
    __typename
  }
  __typename
}

fragment MyMembershipsRoleSet on RoleSet {
  id
  myMembershipStatus
  myRoles
  __typename
}

fragment VisualUri on Visual {
  id
  uri
  name
  __typename
}
```

**Comment by reactoholic** [comment]
@bobbykolev I am not able to reproduce this bug. I tried in incognito as well, I added myself to new spaces and subspaces and everything was displayed as expected. Do you still have this issue on your side?

**Comment by Comoque1** [comment]
Tested OK on ACC env.
