### ISSUE TITLE
BUG: Scrolling down on "Latest Activity in my Spaces" scrolls down the whole page instead to be in a block

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7167]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home with user with bigger membership or in the membership to have many activities
2. Scrolling down on "Latest Activity in my Spaces"  - the whole page scrolls down
<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d42240b44ecda7848410902dc0f1a45603a5047/image.png" alt="image.png" />
<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--720b75189aff9a5085093df93a7e41fdd6d8ce6e/image.png" alt="image.png" />

**Expected behavior**
TBD

**Comment by valentinyanakiev** [comment]
@SimoneZaza can you please provide expected behavior & priority for this, is this in / out of the release?

**Comment by bobbykolev** [comment]
I'd say it's not blocking, there's nothing below this widget and if you scroll - you're getting more items. Let's refine it later if @SimoneZaza agrees.

**Comment by SimoneZaza** [comment]
@valentinyanakiev @bobbykolev Fully agree, we'll refine later!

**Comment by SimoneZaza** [comment]
This issue is addressed in #7267
