### ISSUE TITLE
Loading indicator missing for Innovation Library

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7174]
## Description

As user on the platform, I think the innovation library is empty since I don't see any content in the first few seconds
As Alkemio, I want to give engaging demo's that show the potential of the platform and our filled innovation library

## Acceptance criteria

- [ ] Add loading indicators to the innovation packs & template section (skeleton, spinner is also fine if much easier)

## Additional Context

<img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW11Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc2e9327df5dfdf20e14623e8af6e6b50ab50dc0/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on DEV env.
