### ISSUE TITLE
BUG: Alkemio "About" page fails to load

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7183]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/about in incognito browser - the page fails to load
<img width="1301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHkzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b154f3692b50547d434acfe9857c025fd47d54f3/image.png" alt="image.png" />

**Expected behavior**
About page loads as before.
<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDYzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfe693c1e54a1ca6c4d4780e5c86a8ea2618b0f1/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
Actually the about page will be gone soon, we'll add the version numbers to the support dialog. So instead of fixing this, the version numbers should be added to the support dialog and the logo in the footer should point to the welcome site

**Comment by keyboardguy25** [comment]
@SimoneZaza I cannot see the images, but I see that this should not be fixed? It is unclear to me what you mean by version numbers and support dialog? you mean the support button in the footer? I cannot see the version numbers on this page https://acc-alkem.io/about

**Comment by SimoneZaza** [comment]
you're fast! Wanted to discuss this one during the planning session today. Basically, we removed the /About page from the platform. My question to you is if you can look into whether that's okay in terms of SEO or if we should do something else with it.

**Comment by keyboardguy25** [comment]
SEO could be improved but nothing to do with the About page, so this is okay: https://freetools.seobility.net/en/seocheck/check?url=https%3A%2F%2Falkem.io%2Fhome&crawltype=1
