### ISSUE TITLE
BUG: Translations don't have a fallback on MyMembership card and dialog

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7190]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home
2. Switch to Bulgarian language: Translations don't have a fallback on MyMembership card and dialog
<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnk0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61473066caa71a2310936f0ee44b839eb89f157a/image.png" alt="image.png" />

**Expected behavior**
There is a fallback to English.

**Comment by SimoneZaza** [comment]
Same holds for Dutch!

**Comment by Comoque1** [comment]
On DEV env. Explore all spaces card is fixed. "My membership" dialog - not.

**Comment by bobbykolev** [comment]
As part of this task, we're updating all translations from Crowdin (exported and provided by @hero101).
This update fixes the issues.
