### ISSUE TITLE
UI treatment of Beta Testers

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7204]
## Description

As a user,
I want to know when I'm seeing the platform's **beta** version.

## Acceptance criteria

- [ ] A badge on the profile picture in the Platform Navigation (top right on every page banner) if the user is in a Beta Tester role.
- [ ] …

## Additional Context
<img width="589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--255d1086d253906d3501a0f48cceb62a45bdb219/image.png" alt="image.png" />

## Areas that will be affected 
Platform navigation. 

**Dev notes:**
Use Platform Privileges (TBD) instead of agent credentials to detect the Beta Tester role.

**Comment by Comoque1** [comment]
Tested OK on ACC env,
<img width="1293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2f3c2399d8aa37d5bd0e6d6b9a9ea5f75094fbe/image.png" alt="image.png" />
