### ISSUE TITLE
BUG: License Plans set for space from admin section are not taking effect

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7205]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/admin/spaces
2. Set a space the feature: "SPACE_FEATURE_SAVE_AS_TEMPLATE":true
3. Go to the space and try to save a callout as template - the option is not available.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86308f2a4705da9c29d80f8df2fc48144f2f4cc0/image.png" alt="image.png" />

**Expected behavior**
GAs can set features to spaces.

**Comment by valentinyanakiev** [comment]
Client is checking the obsolete `AuthorizationPrivilege.SaveAsTemplate`, whereas it should check the entitlements.

**Comment by Comoque1** [comment]
Tested OK on dev env.
