### ISSUE TITLE
Beta tester/vc campaign indicators

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7208]
## Description

As a user in a campaign, I need to be prompted with the right text on the homepage
As a beta tester, I need to be aware that I'm seeing the platform in beta mode
As both users, I need to be able to see somewhere what my status is

## Acceptance criteria

- [ ] Add VC Campaign or Beta tester to the user menu, where "Global admin" is also displayed. ~~If there are multiple roles, show all (display priority: 1. GlobalAdmin, then the 2. VC campaign, and lastly 3. Beta Tester.)~~ (see update below)
- [ ] Remove the campaign block from the homepage for beta testers

UPDATE 25.11.24
- [ ] the Platform role displayed in the Menu should be only one, following the order and copy as follows: 
```
"roles": {
      "GLOBAL_ADMIN": "Global Admin",
      "SUPPORT": "Support Admin",
      "LICENSE_MANAGER": "License Manager",
      "BETA_TESTER": "Beta Tester",
      "VC_CAMPAIGN": "VC Early Access"
    }
```
e.g. if you have both Beta Tester and VC Campaign roles, you'll see only Beta Tester

## Additional Context
Tech - **platform.myRoles query should be very useful for this functionality.**

<img width="289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9EQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88d732b24f89ad105006551bf2f66d5759ac0921/image.png" alt="image.png" />

## Areas that will be affected 
Platform Menu
Campaign block

**Comment by techsmyth** [comment]
@SimoneZaza note also here that the platform.myRoles query should be very useful for this functionality.

**Comment by SimoneZaza** [comment]
@techsmyth check, thanks!
