### ISSUE TITLE
BUG: After redeployment the client throws an error on DEV env.

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7214]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Make redeployment
3. Click on any link - age fails to load
<img width="1375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1418adb023eb1510451a0c467c475e2658f86dd/image.png" alt="image.png" />

**Expected behavior**
Page loads without errors.

**Comment by bobbykolev** [comment]
**Explanation** of the issue:
After redeployment, the names of the dynamic chunks are changed (different hash).
Then your outdated index.js is trying to load a no longer existing file.  

To solve the issue we need to:
1. catch the error (with a local catch or preferably on a global level);
2. apply logic to either
  2.1. notify the user that there's a new version and a reload is required;
  2.2. or reload the page;
(I'm suggesting #2.1)

**Comment by Comoque1** [comment]
The issue was reproduced on PROD env, after latest deployment.

**Comment by bobbykolev** [comment]
@Comoque1, please double-check after the next release, we've introduced changes that were not part of the old version - resulting in this erro. 
However, if a user has an older client version of the client, and there are partials (chunks) that are not yet loaded, a full page reload will be required, always.

Currently, we're notifying the user and an action is needed - click on reload. Another option would be to reload the page automatically but this could have a negative impact. The same scenario is valid in case of a lost connection for example.
@Comoque1

**Comment by Comoque1** [comment]
The issue has not been experienced, with latest 2 releases.
