### ISSUE TITLE
Support dialog: Update + Link to new documentation

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7243]
## Description

As a user in need, I want a pleasant experience leading me to the documentation or to contacting Alkemio

## Acceptance criteria

- [ ] Make the dialog smaller and change the text as per design
- [ ] Text/icons smaller as per design
- [ ] Add version numbers to the footer as per design
- [ ] Explore documentation --> open alkem.io/docs (new tab)
- [ ] Contact the team --> Open dialog with embedded hubspot contact form (will be available soon!)
- [ ] Join the Welcome Space --> open https://alkem.io/welcome-space (new tab)

## Additional Context
Figma: https://www.figma.com/design/IcZgJtuguDeodanyH0Xy08/Help-dialog?node-id=602-8&t=qGRGyXcdRAmGHYjE-1
<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63f0a1ed4b148f8498dd5008120acbc6a09f5b3e/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUgwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c743d033364156acc18cad13171a187cb6e5229/image.png" alt="image.png" />
