### ISSUE TITLE
Ability to edit the link for Subspace template

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7255]
## Description

As a user, I want to easily edit or update my Subspace template. However, the current flow is deleting the Subspace template and creating a new one since I can't re-enter the link. This results in a lot of unnecessary extra steps.

## Acceptance criteria
In edit subspace template dialog, 
- [ ] Show (filled) URL input field top right and allow the user to change this link (or trigger an update)
- [ ] If easy: change button text from "Use this subspace"  to "Update" for the edit dialog (keep Use this Subspace in create dialog)

## Additional Context

<img width="1240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8810debaaef1627b0ce604e7c54dd9e048758c23/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
