### ISSUE TITLE
VC 'store' 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7256]
## Description

As a lead, I want to be impressed by the VC demo. I want to see a visually appealing list of Virtual Contributors to choose from when inviting them to my Space

## Acceptance criteria

- [ ] Visually resembling the library dialog (see screenshots below)
- [ ] Dialog 1 (overview)
  - [ ] Change the sections, open both sections from the start
  - Section 1: "Virtual Contributors from my account"
  - Section 2: "Other Virtual Contributors"
  - [ ] Hide section 1 + **both titles** when there are no vcs in the account
  - [ ] Use VC cards - same as user hover cards (see screenshot) **without mail icon**
- [ ] Clicking on a card opens the preview dialog:
  - [ ] Show profile information on the right (reuse the profile details component, as there will be changes to the vc profile in the future)
  - [ ] Change "Use" button to "Add" (for vcs from the account) or "Invite" (for other vcs) (check corresponding privileges?)
  - [ ] Invite opens invite dialog as it currently works with the invite vc list from space settings > community > invite external vc
- [ ] To be implemented in the 
- space > community > VC block invite (#6941) 
To be reused in the settings as part of https://github.com/alkem-io/client-web/issues/7334

## Additional Context
**Note that we will start using this for other types of contributors in the future as well. Probably ;)**

Similar to dialogs from the library:
<img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16e2cb73dfbab518a7895e9c13782692618682b2/image.png" alt="image.png" />

<img width="1599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9tQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da923dc9a213cfb01b4e784928a849671f3b9ccc/image.png" alt="image.png" />

Cards similar to user contributor cards:

<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--803bdba9c88b8eea4b689402efc4f7b33b467426/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
Tests performed: https://alkem.io/myspaceevgeni/challenges/qaandtesting/collaboration/releasenotificationsscope/posts/vcstore
