### ISSUE TITLE
Directly show whiteboard preview when importing Subspace template

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#7273]
## Description

As a user, I want to see the templates that I imported
As a template provider, I want to show the beautiful templates I created

## Acceptance criteria

- [ ] Directly show preview of the whiteboard

## Additional Context

<img width="1329" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTc5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e51f2fe6c50f75a928dc96fc63c9c1191c3671e/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
Added to #4649
