### ISSUE TITLE
BUG: VC section in settings/community is not available for some spaces

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7297]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/j25/settings/community or https://acc-alkem.io/evgenil-space2/settings/community
2. The spaces have the VC flag enabled and the Accounts has gone successfully through VC flow
3. Navigating to the spaces / settings / community - doesn't display the VC block(from where a VC could be added / removed / invited)
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBUQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90202781c2bf9199a0b63d9545dadea20824c301/image.png" alt="image.png" />

**Expected behavior**
Virtual Contributors section is available, for space with enabled feature and account with license plus

**Comment by bobbykolev** [comment]
I'm experiencing it locally. For some reason the entitlements are with `isAvailable: false`
