### ISSUE TITLE
BUG: Callout name/type is not displayed in the notification header

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7305]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/challengeadminsspace/challenges/subspacefortestingnotific
2. Or navigate to a space / subspace
3. Create a post callout
4. Mention a member in the callout
5. The header of the received notification is missing the callout name/type
<img width="891" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd29jQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d461c9aceadde3431b003a16c3bc3d0f5c9a2975/image.png" alt="image.png" />

**Expected behavior**
The header of the received notification  the callout name/ype

**Comment by hero101** [comment]
Closing in favor of https://github.com/alkem-io/client-web/issues/7317
