### ISSUE TITLE
BUG: [In App] Handle broken notifications - don't show them 

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7313]
**Describe the bug**
If critical information is missing, don't show the notification.

**To Reproduce**
1. Create a callout
2. Delete the callout
3. Check the notifications
4. A notification is shown with partial information (in the receiver's inbox)

**Expected behavior**
Notifications related to the deleted callout should not be included in the inbox.

**Additional context**
The client builds the notifications info, so the server can't exclude notifications with missing callout, space or actor/contributor etc. So this should be handled on the client.

**Comment by hero101** [comment]
Closing in favor of https://github.com/alkem-io/client-web/issues/7317
