### ISSUE TITLE
BUG: Admin navigation is not working

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#732]
**Describe the bug**
Admin navigation is not working.

**To Reproduce**

1. Authenticate with GlobalAdmin
2. Navigate to i.e. https://dev.cherrytwist.org/admin/ecoverses/testecoeid81a395/challenges/chalnaid1625233803809.9521/opportunities
3. Using the admin navigation, get back (i.e. to ecoverse level)
4. The buttons aren't active
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d7a335bc-533e-4535-9cda-ad1d5b43cb98)

**Expected behavior**
Navigation is working.

**Comment by techsmyth** [comment]
Working in v0.11.6 version again.
