### ISSUE TITLE
BUG: 2 users on dev env are getting error from inAppNotifications request

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7321]
**Describe the bug**

**To Reproduce**

1. Go to https://dev-alkem.io/home
2. Authenticate with user: challenge.admin@alkem.io
3. Error is thrown for inAppNotifications request: `"message": "Cannot return null for non-nullable field InAppNotificationUserMentioned.commentOriginName.",`
<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2trQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18c1ed1b8300911dca8fde356948ef279b09625b/image.png" alt="image.png" />

**Expected behavior**
No error is thrown.

**Comment by hero101** [comment]
The error was caused due to missing `commentOriginName` field in the older notifications.
The data was migrated and it is not reproducible anymore.
