### ISSUE TITLE
BUG: After finalizing the VC flow InAppNotifications request starts failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7329]
**Describe the bug**

**To Reproduce**

1. Go to start the VC flow (written knowledge ) on dev env
2. Finalize the flow
3. The request: InAppNotifications starts failing: 
<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBrQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d2661463c6a355f09e3b99766bb5d3176201e2f/image.png" alt="image.png" />

**Expected behavior**
Finalizing the flow does not break the existing notifications. (Not a VC flow problem)

**Comment by hero101** [comment]
The problem was that the getter function for Contributors was expecting only Users when the contributor in question was a VC.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
