### ISSUE TITLE
Reuse the Invite VC functionality in (Sub)Space community settings

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7334]
## Description

As a lead, I want to be impressed by the VC demo. I want to see a visually appealing list of Virtual Contributors to choose from when inviting them to my Space

## Acceptance criteria

- [ ] The new invite flow available in (sub)space settings > community > + invite vc

## Areas that will be affected 
Space/Subspace settings, InviteVCsDialog

**Comment by bobbykolev** [comment]
The functionality of adding/removing/inviting works as expected.

However, there are a couple of **drawbacks**:

1. In the new flow there's **no search** ⚠️
2. The _On Account_ list shows all VCs under the account. On SubSpace level this could cause an error on attempt to add a VC not part of the parent community.
3. There's one button **Add** similar to the other tables in the Layout. The invite button was removed as both are doing the same thing.

@SimoneZaza, I'd suggest to merge/release this one once we have search functionality implemented. It would be nice to have a limit/pagination on the 'Other Virtual Contributors', as well.

**Comment by SimoneZaza** [comment]
Dropping this for now because of the drawbacks, creating a new issue to continue
