### ISSUE TITLE
BUG: When invitation is accepted from user's dashboard, the data is not redirected to the space/subspace

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7346]
**Describe the bug**

**To Reproduce**

1. Go to acc env
2. Make invitation to a user or a vc of a user
3. Using the invited account, navigate to its dashboard
4. Click on invitations 
5. On the dialog accept the invitation - the user is not redirected to the subspace and the invitation doesn't disappear
<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVVzQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58e293b17490241ea9456b007e0dc2826615bc81/image.png" alt="image.png" />

**Expected behavior**
User is redirected to the invited space/subspace.
OR
The invitation is removed from the list.

**Comment by bobbykolev** [comment]
The **issue** is that there's no redirect (intentionally) on the VC invite. Because of this, we need to refresh the invitations (not required on redirect).

**Fix** - we're refreshing the invites list on every accept/reject. 
There's no redirect in case of a VC invite.
