### ISSUE TITLE
Use all fields from the Context entity on Challenge / Ecoverse

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#782]
## Description

As a Challenge / Ecoverse owner I do not see some of the context fields that I filled out visible, nor are they used consistently.

## Acceptance criteria

- [x] Ecoverse: Use the context.who field in the community section 
- [x] ChallengePage: Use the context.background + context.impact field in the Opportunities section 
- [x] ChallengePage: Use the context.vision field in the top level section
- [x] ChallengePage: Use the context.who field in the community page
- [x] ChallengePage: Put the Community section below the Opportunities section

## Additional Context

Ecoverse page:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e52afd27-ff5a-4d3d-b52f-a466f9b0e31d)

Challenge page:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e1c6ae0e-a7b7-47df-93dc-5ea76acd9c6f)

**Comment by Comoque1** [comment]
With respect to the requirements, all looks good.

Ecoverse:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5be1b4d9-580b-4025-bb5b-f0b9878f947e)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9bc63b68-480d-462a-b4e1-2884a743dbfa)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8575db9a-648b-4bc2-b840-8562ff28ae5b)

Challenge:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/205c12d3-2734-4fe9-be81-fef3f1efd3f9)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d5ec5a93-064d-4755-87f9-c47202d01176)
