### ISSUE TITLE
BUG: User can make a registration, without providing first/last name and without accepting TaC

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#802]
**Describe the bug**
User can make a registration, without providing first/last name and without accepting TaC.

**To Reproduce**

1. Go to https://acc.alkem.io/auth/registration?flow=285d20f2-0776-4951-b9e7-f1de76fe5ef0
2. Fill up email and valid password only
3. Press "Sign Up" button, user is successfully registered, even the first/last name and  TaC check is not flagged
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/843b3866-d376-408b-95db-bdf2cd2abebe)

**Expected behavior**
User must not be allowed to register, without accepting TaC.
First/Last name not required??

**Comment by techsmyth** [comment]
The first name / last name fields should be marked as required

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/692464a6-d9a0-44e9-a9df-5dd1362eefec)
