### ISSUE TITLE
BUG: Unable to submit application for ecoverse

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#805]
**Describe the bug**
Application is missing parent ID.

**To Reproduce**

0. Authenticate with newly created user
1. Go to https://hub.alkem.io/alkemio/apply
2. Fill up only the required questions (the first one)
3. Press "Apply" button: `Response not successful: Received status code 400` error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a02a6f90-8361-49d8-9199-26d63dcb6c8f)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d4c2ff8b-45d8-49ec-b54a-d63accef707b)

**Expected behavior**
Newly created user must be able to apply for an Ecoverse.

**Comment by techsmyth** [comment]
That is correct, as per the configuration:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/5321976c-f382-42e2-814f-f8799c9096d7)

**Comment by Comoque1** [comment]
I see. 
Still, there is an issue with application creation.

**Comment by Comoque1** [comment]
After some investigation the following behavior was identified on PROD application creation:
 - createApplication mutation running from graphql - OK
 - **createApplication from client-web, when user is not part of the community - throws error that parentID is empty**
 - if user is added to the community and after that tries to createApplication, the application is successfully performed, but there is no point of doing it, as it is already part of the community 

Assigning @atstojanov, as it seems like client-web issue

**Comment by atstojanov** [comment]
It is not web issue. it is Authorization issue.

```
 "message": "User (pesho3@angelstoyanov.info) does not have credentials that grant 'read' access to Ecoverse.community",
```

**Comment by Comoque1** [comment]
The issue described above is against public ecoverse.

**Comment by techsmyth** [comment]
Yes but the community always required read permission, regardless of public / private. I have now removed that so that the community.id is accessible. There may be another issue, but there are certainly two fixes that are in the PR on the server that are needed.
