### ISSUE TITLE
BUG: Invalid form feedback from Kratos

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#810]
When submitting the signup form without all the required information the message that is returned is not properly displayed:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/acf2988c-8e4b-477a-95e0-a9bfb59de69f)

**Comment by atstojanov** [comment]
Closing this issue because it is based on wrong configuration with combination of unclear Kratos configuration.
For more information ory/kratos#400
