### ISSUE TITLE
BUG: User membership details not being fully displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#826]
**Describe the bug**
"Member of" on user profile, is not populated with all entities, it is part of.

**To Reproduce**

1. Authenticate with any user to https://hub.alkem.io/profile
2. Add the user to Organisation group and Ecoverse community (i.e. using global admin)
3. Refresh the user profile page - "Member Of" field is not displaying all entities, to which the user assigned.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/63335117-ecf9-4382-a943-fb3df6419430)

**Expected behavior**
User profile must display all entities, which the user is part of.

Note: ensure that all the information returned from the membership query is displayed.

To applications also.

**Comment by hero101** [comment]
RETEST
@Comoque1 issue seems to be resolved by [#644](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/644)

**Comment by Comoque1** [comment]
User member of opportunity community is not displayed on user profile page.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/53ba61b2-437c-422a-a9d2-ebfa3259c77c)

**Comment by Comoque1** [comment]
Please also add "Ecoverse" displayName on client, when user is memebr of its community.

**Comment by Comoque1** [comment]
Tested OK on test env with this branch of client and dev server - looks better now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/df2a4e73-e07b-43b7-8d32-6a3af776aea1)

Probably it would make sense to differentiate the  colors of groups and communities. In addition, it would be nice if we have the ecoverse community / groups, challenge community / groups, opportunity community/groups boxes align, so that the relation among is clear.
