### ISSUE TITLE
BUG: User profile page - alignment issues

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#827]
**Describe the bug**
User profile page - alignment issues.

**To Reproduce**

1. Go to your user profile page: https://hub.alkem.io/profile - the data is misaligned or not displayed at all
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1b8881c2-3325-48b4-997e-5997f06a4dfa)

**Comment by hero101** [comment]
RETEST
@Comoque1 issue seems to be resolved by [#644](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/644)
- Used the core Tag components instead of what was already there.
