### ISSUE TITLE
Update client package manager from npm to yarn v2

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#843]
## Description
As a developer I want to be on the reasonably dev versions

## Acceptance criteria

- [ ] Switch to using Yarn v2 instead of NPM
- [ ] Documentation updated

## Additional Context

Our package-lock.json is version 1 and we are stuck with npm v6 (distributed with node v12). npm v7 (available in node 14 and newer) is using package-lock.json v2 which is much easier to maintain and merge when there are merge conflicts. Both are compatible.

**Comment by atstojanov** [comment]
Yarn v2 introduce nice features like:
- PnP modules,
- workspaces
- speed

Most of which we can't  benefit from.
- The PnP modules have to resolve the npm modules hell and get rid of node_modules folder, but requires packages that are supporting it.
- Workspaces are not usable for us currently. They can help us if we decide to switch to monorepo.
- speed - nice to have.
