### ISSUE TITLE
Spike: GraphQL Error Handling

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/client-web#858]
## Description
Because of bug in the apollo-client the GraphQL Errors are not available in the ApolloError object. However the NetworkError property is populated and contains the whole error object, even the part that should be available in the GraphQLErrors array. The typescript prevents accessing this data so we are casting the ApolloError object to any so we can check and use the actual error. 
The issue is tracked here: apollographql/apollo-client#8503
After this issue is resolved we can improve our ErrorHandling to use properly the ApolloError object.

## Acceptance criteria

- [ ] We know whether we can use GraphQL Errors to ApolloError objects in the client

Spike to a couple of hours

## Additional Context
To be re-evaluated in light of graphq; refresh

**Comment by hero101** [comment]
The error is still not available in the graphql errors. Only in the network error object as seen below.

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/bcce2baa-18b6-4748-83e2-1d1c3b958143
)
