### ISSUE TITLE
Spike: Prototype using Kratos v0.7.0 and AJAX flows

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#867]
## Description

As a developer I would like to not have page redirects on the client to make debugging easier + improve user experience

## Acceptance criteria

- [ ] Try out switching to AJAX interaction for authentication flows on the client
- [ ] Recommendation of effort / key changes needed, also including impact on server

## Additional Context

Capture what is needed infrastructure-wise to make this work in production.

**Comment by atstojanov** [comment]
The new AJAX flows are making the the authentication processes much smoother with almost no redirects. Unfortunately in our case the logout is causing issues:
- After logout the `ory_kratos_session` cookie is not invalidate/removed from the browser and the next request to the graphql leads to error `401 Unauthorized`. In the previouse version (0.6) the session was removed and everything worked perfect.

I've ask a question about this in this discussion:
https://github.com/ory/kratos/discussions/1582

**Comment by techsmyth** [comment]
Possible to migrate all except logout?

**Comment by valentinyanakiev** [comment]
As of 28.08.2021 this should no longer be blocked - https://hub.docker.com/layers/oryd/kratos/v0.7.3-alpha.1/images/sha256-08a9facce9501b7174c865260ab4eb12352a44d5c5b93b330e839bdf3b7b407e?context=explore

**Comment by atstojanov** [comment]
Will require infrastructure update. @valentinyanakiev

**Comment by valentinyanakiev** [comment]
Helm charts for Kratos are still not updated. The [values.yml](https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml) file clearly indicates the chart from the master branch uses Kratos 0.6.3-alpha1.

**Comment by valentinyanakiev** [comment]
So there are two options from here:
- We wait for the helm chart to be updated in line with the latest release - slower, but more stable
- We test overriding the image version in the kratos.yml - the approach is fairly simple but given the update is from 0.6 to 0.7 if there is schema incompatibility there is a high likelihood of failure. We can time box a Spike to test out this approach.

**Comment by valentinyanakiev** [comment]
I am putting the story on Blocked until we make a decision.

**Comment by valentinyanakiev** [comment]
I have captured [the issue](https://github.com/ory/k8s/issues/336) on the kratos k8s backlog:
