### ISSUE TITLE
Spike: Development guideines + restructuring

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#890]
## Description

As a developer I want to be able to easily navigate the client web code base so that I can be effective

## Acceptance criteria

- [ ] Define a convention for the directory structure
- [ ] Define a convention for components (what and when)
    - [ ] Usage of codegen for working with graphql queries (per component?)
- [ ] Carry out initial directory restructuring / renaming
- [ ] Detail both conventions in a top level "development-setup.md" file
- [ ] Gap analysis + high level estimate on the migration -> output is placed in an epic (TBD) - https://hackmd.io/@alkemio/SJeEp6CR_

## Additional Context
- Directory structure food for thought: https://www.taniarascia.com/react-architecture-directory-structure/) 
- Components food for thought: https://medium.com/wesionary-team/types-of-react-components-you-should-know-251cceacd8ac

### Keep in mind 
    - impact of using states (via XState)
    - ability to reuse data / logic components (vs display components)

**Comment by atstojanov** [comment]
Research: 
- Graphql codegen to put each hook in separate file ???
- polish the concept of using graphql + hooks + container components (raise separate issue)
