### ISSUE TITLE
BUG: User cannot create application to challenge

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#903]
**Describe the bug**
User cannot create application to challenge.

**To Reproduce**

1. Authenticate with user Alkemio and navigate to https://acc.alkem.io/value-tracks/challenges/medicine/apply
2. Fill the required fields and press "apply" button - error message is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/94cec3aa-1522-4fa1-857f-acf4b805f507)

**Expected behavior**
User can create application on challenge.

**Comment by Comoque1** [comment]
The user is able to apply for a challenge, once its application to the challenge ecoverse is approved.

**Comment by atstojanov** [comment]
This issue is related to incorrect user rights. 
![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/14d901bd-8145-4027-8153-2016d6e682df)

**Comment by Comoque1** [comment]
Correct, insufficient user rights.
Probably it would make sense to hide the button if the user is not member of the parent community.

**Comment by techsmyth** [comment]
Not clear what the right behaviour should be - to be refined.

**Comment by techsmyth** [comment]
Not sure why the user needs to read the above fields to create an application. 

The membership information for the user should be what is used to determine if the user already has an application pending for this community, not the information on the community itself. 

To discuss...

**Comment by atstojanov** [comment]
The query is using predefined fragments, which are querying too much data. The query should be optimized to get the minimum set of data required for displaying the application and the creation of a new one. Also we have to be sure that this information is publicly available.

Currently an application needs this information:
- communityId
- community Name = challenge.displayName/ecovers.displayName
- entity avatar ( *.context.visual.avatar)
- tagline (*.context.tagline)

**Comment by techsmyth** [comment]
To be further refined / designed

**Comment by Comoque1** [comment]
User can make an application to challenge directly
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/43ba38f1-4e8c-4fb4-a183-4ffba77cb4c7)

Apply button, remains active - should be fixed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5380d81e-9f72-420e-b085-21ef2639b55f)

**Comment by Comoque1** [comment]
After discussion with @atstojanov, created [new bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1028) for the issue with "apply" button.

Closing this one.
