### ISSUE TITLE
BUG: Saving user profile after removing reference is throwing an error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#909]
**Describe the bug**
Saving user profile after removing reference is throwing an error.

**To Reproduce**

1. Go to https://test.alkem.io/profile/edit
2. Authenticate with any user
3. Add reference to the profile
4. Open browser dev tool and from "network" section set the throttling to "slow3G"
5. Remove the reference and very fat press save button
6. Error is thrown: `Unable to update reference with supplied ID: 7a27ac19-499d-49f7-b474-ca11c7f26b0d - no reference in parent entity.`

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e840481c-3878-4323-b6a5-b2d438104889)

**Expected behavior**
None exception is thrown, when removing reference and saving the changes

Test to be performed: `npm run-script test:e2e ./test/functional-e2e/user-management/user-profile` with "community.admin@alkem.io" user

**Comment by valentinyanakiev** [comment]
To be discussed an approach where to solve the issue - server vs client-side.
Proposed approach is to define two distinct update strategies - merge vs replace
