### ISSUE TITLE
BUG: Changes applied to "./identity/settings" are not preserved and displayed to the user

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#913]
**Describe the bug**
Changes applied to "./identity/settings" are not preserved and displayed to the user.

**To Reproduce**

1. Go to https://test.alkem.io/identity/recovery using FF browser
2. Set email, to which you have access
3. Submit the form
4. From the email **copy** the provided link
5. Using Chrome browser open the copied link
6. Change user profile details (i.e. first/last name) and an save the changes
7. Go to the user profile page - changes applied to the user are not preserved.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d3e95e74-0f83-407f-ba8f-527ad93a082e)

**Expected behavior**
Changes applied to the user settings are preserved and returned to the user when requested.

## Note
Changing password is reflected correctly.

**Comment by Comoque1** [comment]
## Note2
Changing the email will result in inability to authentication with neither of the emails.

**Comment by techsmyth** [comment]
To be addressed via https://github.com/alkem-io/client-web/issues/915
