### ISSUE TITLE
CommunityPage with ability to filter Users

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#916]
## Description

As a user I want to be able to see more information about a community

## Acceptance criteria

- [x] Community page available at ```/<ecoverseNameID>/community```, ```/ecoverseNameID>/<challengeNameID>/community``` + also for Opportunity
- [x] Settings button available
- [x] Section at the top for name of containing entity (ecoverse / challenge / opportunity) plus tagline
- [ ] Section for Users, including the ability to browse / filter on the Users  - firstname, lastname, country, city, email (partial match after @) ?, tagsets, description

Section for Organisations, that varies depending on the context: 
- [x] Ecoverse show label "Ecoverse host" + the ecoverse host,
- [x] Challenge show label "Leading organizations" + Challenge Leads.
- [x]  Opportunity this section is not shown currently.
//
- [x] Section for UserGroups in the community, with a default msg for when there are no groups
- [x] Section for Updates
- [x] Community not accessible without registration (direct link).
- [x] Page has the same visibility as the current Community Members field i.e. private ecoverses not visible, public ecoverse visible to registered users.

## Additional Context
Full UX design is pending for this page; this issue is about getting the page + underlying data ready / setup with initial implementation.

Discussed in https://github.com/alkem-io/alkemio/discussions/384

<div type='discussions-op-text'>

<sup>Originally posted by **FloriSpoelstra** July 28, 2021</sup>
Is it possible to let people just browse through the list of community members? So when you click "explore and connect" you automatically get the full list and then you can filter out specific people by using search words. </div>

**Comment by Comoque1** [comment]
Looks OK on Dev as per the requirements.

One concern I have is regarding the displayed groups - we may need to make a group page, similar to ecoverse, challenge,organisation, so that when a user clicks on it (even if he/she is part of it) is redirected to that page, instead of - restricted page.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a092f3f6-24fd-4443-872e-72840cc5b0b2)

@techsmyth, could you please share if we need to raise another issue regarding this?

**Comment by techsmyth** [comment]
@Comoque1 please raise this as a separate bug, it should not block this release as there is only very limited usage of groups at the moment.

**Comment by Comoque1** [comment]
Thanks for the feedback, @techsmyth! 
Added [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1178) related to the comment.
