### ISSUE TITLE
BUG(PROD): Ecoverse/Challenge admin doesn't see functional buttons on opportunity page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#917]
**Describe the bug**
Ecoverse/Challenge admin doesn't see functional buttons on opportunity page.

**To Reproduce**

1. Go to https://dev.alkem.io/testeco/challenges/testecocha/opportunities/testecoopp
2. Authenticate with Ecoverse/Challenge admin
3. User must be able to see and act on the following areas: actorGroups/Acors, Aspects and Projects
4. Only Global admin, can see the above buttons
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ebb0cb0f-e677-46cf-b62d-b5d8462ac563)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ca59accd-0550-4790-9b58-5f06f1a6ffc8)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/357fc9af-ac39-4b43-8647-da69afa9babf)

**Expected behavior**
Ecoverse/Challenge admin must be able to see and act on the following areas: actorGroups/Acors, Aspects and Projects

## Note
Graphql calls are working correct.

**Comment by atstojanov** [comment]
How we are going to check for user permissions on different pages?

**Comment by Comoque1** [comment]
Missing implementation as follows:
 - Ecoverse Admin on Opportunity page:
   - Actors - Edit/Delete
   - Remove relation
   - Aspects - Edit/Delete

 - Challenge Admin on Opportunity page:
   - Actors - Edit/Delete
   - Remove relation
   - Aspects - Create/Edit/Delete

**Comment by Comoque1** [comment]
Missing implementation as follows:
 - Ecoverse Admin on Opportunity page:
   - Actors - Edit/Delete - **OK**
   - Remove relation - **OK**
   - Aspects - Edit/Delete - **OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ad050963-6c25-439d-895e-9e8a638879e0)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0cefd686-7526-43c6-91fd-599927a76a2c)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/21f27bc8-b380-489c-9ca5-fa4a9e2a8ddd)

 - Challenge Admin on Opportunity page:
   - Actors - Edit/Delete - **OK**
   - Remove relation - **OK**
   - Aspects - Create/Edit/Delete - **OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7dae83f3-6df3-4dd0-b680-519b582e4039)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/670f0a26-86fc-4d2e-88ef-165deb1e9ff3)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cc3a9ea6-83f1-4ce7-b8c0-c25b2d1ce107)
