### ISSUE TITLE
BUG: Error is thrown after creating application on dev environment

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#926]
**Describe the bug**
Error is thrown after creating application on dev environment.

**To Reproduce**

1. Go to https://dev.alkem.io/ecofromserver/apply
2. Open browser dev tools on network
3. Create application (Global admin was used)
4. The application is created successfully, but the request, which follows after the "create" request fails
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4a0bb59-8a20-4d6e-bfb7-1251b03e9f40)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/19fa52fb-b761-4f9d-a82e-66256e5d2d76)

**Expected behavior**
All requests are returning data successfully

**Comment by Comoque1** [comment]
Note:
Not reproducible on acceptance environment.

**Comment by techsmyth** [comment]
This looks like the the problem with the orphaned credentials again.

After creating the application the client gets memberships to check for pending applications to decide how to display the button. This is causing an issue. 

You can verify if this is the case by running the memberhip query for the user via graphql api.

**Comment by Comoque1** [comment]
So, for **global admin**, the ecoverse cannot be returned:
![image](https://user-images.githubusercontent.com/23620658/128342364-94b0d32f-964a-402f-9790-9af440008a97.png)

for **community admin**, the things look good:
![image](https://user-images.githubusercontent.com/23620658/128342569-f4e37ab7-e9a7-401e-b70b-640c7b64e0d9.png)
