### ISSUE TITLE
BUG: Group name and avatar are not displayed on search results

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#929]
**Describe the bug**
Group name and avatar are not displayed on search results.
**To Reproduce**

## Acceptance critieria for display
- [ ] Label to show either "Org" or "Comm"
- [ ] Show the group name
- [ ] Show group avatar if available
- [ ] Show activity with just a members field, like on challenge card

1. Go to https://test.alkem.io/
2. Create a group
3. Assign user to the group
4. Search for the group on "Search" page
5. The group is displayed without its name and avatar. When opening the model the assigned users are not displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c71cf58d-8083-4042-a176-d159e0b18ddd)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1d326297-743f-4fe3-916f-c0337e2a892f)

**Expected behavior**
When Search for a group, the name and avatar is displayed in the results and the users assign to it are displayed.

**Comment by atstojanov** [comment]
Is this still valid after removing 'Group' card from the search result? (#953)

**Comment by Comoque1** [comment]
Not valid anymore!
Closing
