### ISSUE TITLE
BUG: Challenge card on search page, cropping issue with some data not being displayed when matching multiple terms

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#930]
**Describe the bug**
Challenge card on search page, doesn't display all data, when matched by more terms.

**To Reproduce**

1. Go to https://test.alkem.io/
2. Create challenge with multiple tags
3. Navigate to "Search" page
4. Search by all the tags associated with the challenge - not all information is displayed on challenge search card
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/988d80ec-1242-45a4-89d6-99dddc00f2cb)

**Expected behavior**
All data is displayed on search card.

**Comment by atstojanov** [comment]
Should be fixed after latest changes for search page/cards.
