### ISSUE TITLE
BUG: Error messages are inconsistent

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#943]
**Describe the bug**
Error messages are inconsistent.

**To Reproduce**

1. Go to https://test.alkem.io/admin/ecoverses/new
2. Click "Save" button, without filling up the required fields
3. Error messages are inconsistent
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/24200066-c39e-49ee-9823-053fcc6879ec)

**Expected behavior**
Messages are consistent.

**Comment by atstojanov** [comment]
Has already been fixed.
