### ISSUE TITLE
core/Button component should hold a ref

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#952]
**Describe the bug**
Our button component, using material UI button as base, must be made correctly in other to benefit from [Caveat with refs](https://material-ui.com/guides/composition/#caveat-with-refs)

**Expected behavior**

**Screenshots**
Below screenshots are when a component, like the Tooltip, is using core/Button as child.
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/ccec0fb5-cba4-4afb-88c6-fe69f409e775)![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/02fd78bb-f678-4155-a9e2-fad6622b4078)

**Comment by atstojanov** [comment]
Already fixed

**Comment by Comoque1** [comment]
Cannot reproduce the issue, but there is missing tooltip for "remove reference" button.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ccbb0b96-3082-4f11-9391-4bdec5fc773b)

**Comment by hero101** [comment]
> Already fixed
> Cannot reproduce the issue, but there is missing tooltip for "remove reference" button.

@atstojanov  @Comoque1 
When and where was it fixed?
I am using the latest develop branch and haven't seen any code changes related to that since the theme migration.
Reproducible on my local env.
