### ISSUE TITLE
BUG: User other than GlobalAdmin or Opportunity member, cannot create relation and window cannot be closed, without refresh

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#978]
**Describe the bug**
If a user User other than GlobalAdmin or Opportunity member, cannot create relation and window cannot be closed, without refresh.

**To Reproduce**

1. Go to https://dev.alkem.io/eco1/challenges/default-challenge/opportunities/default-opp
2. Authenticate with user, that is not member of the Opportunity, nor Global admin
3. Click on  `interested in collaborating` button
4. Popup is open
5. Fill the required fields and press "Submit" button - authorization error is thrown 
User cannot close the popup - page refresh is required
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/81a0440c-c711-49b3-9252-e2466ea5d437)

**Expected behavior**
Add 'x' button
 

**Additional context**
TBD the credentials required to perform the mutation.

**Comment by Comoque1** [comment]
In addition, when user successfully add relation, the resulted popup is not correct: 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f0070eaf-f89b-454c-bd85-3e8ca84fc5a2)

**Comment by techsmyth** [comment]
To be tested after server fix for ability to create relations

**Comment by Comoque1** [comment]
The issue is not reproducible, after the fix applied to [this](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1319) item.
