### ISSUE TITLE
BUG: Opportunity page - UI alignment issues

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#996]
**Describe the bug**
Opportunity page - UI alignment issues

**To Reproduce**

1. Go to https://dev.alkem.io/test/challenges/test/opportunities/testop
2. See the screenshot below
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a366af73-021f-418d-bf3f-44a6bdf78acf)

**Expected behavior**
Add button should have the same height as the rest of the cards.

**Comment by techsmyth** [comment]
Only about the actor cards screenshot as above for now; question regarding trash can etc for part of style guide
